import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('filtration-dist'),out=path.resolve('.qa-results/biofilm');fs.mkdirSync(out,{recursive:true});
const remote=process.env.FILTRATION_TEST_BASE;
const server=remote?null:http.createServer((req,res)=>{try{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});if(server)await new Promise(r=>server.listen(5259,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],report={checks:{},errors};
try{for(const [label,width,height] of [['desktop',1440,1120],['phone',390,844],['narrow-phone',320,740]]){const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce',isMobile:width<500,hasTouch:width<500}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto((remote||'http://127.0.0.1:5259/')+'#biology');await page.waitForFunction(()=>window.filtrationQA?.snapshot().ready);const snap=()=>page.evaluate(()=>window.filtrationQA.snapshot());
 await page.locator('#bio-focus').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'bio-play');assert.equal((await snap()).parts,40);assert.equal(await page.locator('#parts option').count(),4);assert.ok(await page.locator('#biology-key').isVisible());assert.ok(await page.locator('.legend').isHidden());
 const diagram=await page.locator('#biology-key').boundingBox(),viewport=await page.locator('#viewport').boundingBox();assert.ok(diagram.y>=viewport.y+viewport.height,'diagram separate from rock');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.stage').screenshot({path:path.join(out,label+'-assembled.png')});
 assert.equal((await snap()).biology.elapsed,0);await page.waitForTimeout(300);assert.equal((await snap()).biology.elapsed,0,'no autoplay');
 for(let i=0;i<3;i++){await page.locator(`[data-bio-step="${i}"]`).click();assert.equal((await snap()).biology.active,i);assert.equal((await snap()).biology.running,false);await page.locator('#biology-key').screenshot({path:path.join(out,label+'-step-'+i+'.png')});}
 if(label==='desktop'){
  await page.locator('#bio-play').click();await page.waitForTimeout(1000);await page.locator('#biology-key').screenshot({path:path.join(out,'motion-0.png')});await page.waitForTimeout(4200);await page.locator('#biology-key').screenshot({path:path.join(out,'motion-1.png')});assert.equal((await snap()).biology.active,1);const before=(await snap()).biology.elapsed;assert.ok(before>4);
  await page.locator('#bio-play').click();const stopped=(await snap()).biology.elapsed;await page.waitForTimeout(500);assert.equal((await snap()).biology.elapsed,stopped,'local pause freezes diagram');await page.locator('#bio-play').click();await page.waitForTimeout(500);assert.ok((await snap()).biology.elapsed>stopped);
  await page.locator('#pause').click();const global=(await snap()).biology.elapsed;await page.waitForTimeout(500);assert.equal((await snap()).biology.elapsed,global,'scene pause freezes diagram');await page.locator('#pause').click();await page.locator('#biology-key').scrollIntoViewIfNeeded();await page.waitForFunction(()=>window.filtrationQA.snapshot().biology.elapsed>=9);await page.locator('#biology-key').screenshot({path:path.join(out,'motion-2.png')});
  await page.waitForFunction(()=>!window.filtrationQA.snapshot().biology.running);assert.equal((await snap()).biology.elapsed,12,'finite story stops');await page.locator('#biology-key').screenshot({path:path.join(out,'motion-complete.png')});
  await page.locator('#bio-play').click();await page.waitForTimeout(350);await page.setViewportSize({width,height:600});await page.evaluate(()=>document.querySelector('footer').scrollIntoView());await page.waitForFunction(()=>!window.filtrationQA.snapshot().biology.visible);const off=(await snap()).biology.elapsed;await page.waitForTimeout(500);assert.equal((await snap()).biology.elapsed,off,'offscreen stops');
  await page.setViewportSize({width,height});await page.locator('#biology-key').scrollIntoViewIfNeeded();await page.waitForTimeout(300);assert.ok((await snap()).biology.elapsed>off);report.checks.finiteAnimationPauseAndVisibility=true;
 }
 await page.locator('#flow').click();assert.equal((await snap()).biology.shown,false);assert.equal(await page.locator('#bio-tracer').getAttribute('opacity'),'0');await page.locator('#reset').click();assert.equal((await snap()).biology.elapsed,0);assert.equal((await snap()).biology.shown,true);
 await page.locator('#experiment').click();await page.waitForTimeout(350);assert.ok((await snap()).biology.running);assert.equal((await snap()).selected,null,'no detached microbe selection');
 await page.locator('#explode-button').click();await page.waitForFunction(()=>window.filtrationQA.snapshot().explode>.995);await page.locator('.stage').screenshot({path:path.join(out,label+'-exploded.png')});assert.ok(await page.locator('#biology-key').isVisible());
 await page.locator('[data-system="skimmer"]').click();assert.ok(await page.locator('#biology-key').isHidden());assert.equal((await snap()).biology.running,false);assert.ok(await page.locator('.legend').isVisible());assert.equal(await page.locator('#flow').innerText(),'Flow on');await context.close();report.checks[label]=true;
}
 assert.deepEqual(errors,[]);report.checkedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();server?.close();}
