import {execFileSync} from 'node:child_process';import {chromium} from 'playwright';import fs from 'node:fs';import {createServer} from 'node:http';import {resolve,extname} from 'node:path';
const root=resolve(import.meta.dirname,'../../../..'),source=resolve(root,'scripts/rotatable-aquascape'),out=resolve(source,'.qa-results/filtration'),baseline=process.env.REEF_BASELINE||'9923eca5e';
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.glb':'model/gltf-binary'};
const server=createServer((req,res)=>{try{let file=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(fs.statSync(file).isDirectory())file+='/index.html';res.setHeader('content-type',mime[extname(file)]??'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(5242,'127.0.0.1',r));
const results=[];try{for(const mode of ['prior-reef','current-reef','filtration']){const b=await chromium.launch({headless:true,channel:'chrome'});try{
 const p=await b.newPage({viewport:{width:1440,height:1080}}),cdp=await p.context().newCDPSession(p);await cdp.send('Performance.enable');await p.addInitScript(()=>{let s=239;Math.random=()=>{s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};});
 if(mode==='prior-reef')await p.route('**/demos/reef-aquarium/',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:execFileSync('git',['show',baseline+':demos/reef-aquarium/index.html'],{cwd:root,encoding:'utf8'})});});
 const start=Date.now();await p.goto('http://127.0.0.1:5242/demos/'+(mode==='filtration'?'reef-filtration/':'reef-aquarium/'));await p.waitForFunction(m=>m==='filtration'?window.filtrationQA?.snapshot().ready:window.reefQA?.snapshot().ready,mode,{timeout:120000});const readyMs=Date.now()-start;if(mode!=='filtration')await p.locator('#effects').selectOption('full');await p.waitForTimeout(2500);const before=(await cdp.send('Performance.getMetrics')).metrics;const fps=await p.evaluate(()=>new Promise(r=>{const start=performance.now();let frames=0;function next(t){frames++;if(t-start<6000)requestAnimationFrame(next);else r(frames*1000/(t-start));}requestAnimationFrame(next);}));const after=(await cdp.send('Performance.getMetrics')).metrics,s=await p.evaluate(m=>m==='filtration'?window.filtrationQA.snapshot():window.reefQA.snapshot(),mode);
 const entry={mode,readyMs,taskSeconds:after.find(m=>m.name==='TaskDuration').value-before.find(m=>m.name==='TaskDuration').value,fps,triangles:s.triangles,fish:s.fish,parts:s.parts};results.push(entry);console.log(entry);
 if(mode==='current-reef'){await p.screenshot({path:resolve(out,'reef-desktop-link.png')});await p.locator('[data-reef-tool="learn"]').click();await p.locator('.reef-filter-lesson').waitFor();await p.screenshot({path:resolve(out,'reef-lesson-link.png')});await p.locator('.reef-filter-lesson').click();await p.waitForFunction(()=>window.filtrationQA?.snapshot().ready);}
 }finally{await b.close();}}fs.writeFileSync(resolve(out,'performance.json'),JSON.stringify({baseline,method:'Serial local Chrome, full reef detail, 1440x1080, seeded scene. 2.5 s warmup, 6 s sample. Not a low-end hardware claim.',results},null,2));}finally{server.close();}
