import {chromium} from 'playwright';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('filtration-dist'),out=path.resolve('.qa-results/process-guides');fs.mkdirSync(out,{recursive:true});const remote=process.env.FILTRATION_TEST_BASE;
const server=remote?null:http.createServer((req,res)=>{try{let file=path.join(root,new URL(req.url,'http://localhost').pathname);if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});if(server)await new Promise(r=>server.listen(5259,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],report={checks:{},errors};
try{for(const [device,width,height] of [['desktop',1440,1120],['phone',390,844],['narrow-phone',320,740]]){const context=await browser.newContext({viewport:{width,height},reducedMotion:'reduce',isMobile:width<500,hasTouch:width<500}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(remote||'http://127.0.0.1:5259/');await page.waitForFunction(()=>window.filtrationQA?.snapshot().ready);const snap=()=>page.evaluate(()=>window.filtrationQA.snapshot());
 for(const system of ['system','roller','skimmer','return']){
  await page.locator(`[data-system="${system}"]`).click();await page.waitForFunction(()=>window.filtrationQA?.snapshot().ready);await page.locator('#process-focus').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'process-play');assert.ok(await page.locator('#process-guide').isVisible());assert.ok(await page.locator('#biology-key').isHidden());assert.equal((await snap()).process.running,false);const idle=(await snap()).process.elapsed;await page.waitForTimeout(150);assert.equal((await snap()).process.elapsed,idle);assert.equal(await page.locator('[data-process-step]').count(),4);
  for(let i=0;i<4;i++){await page.locator(`[data-process-step="${i}"]`).click();assert.equal((await snap()).process.active,i);assert.equal((await snap()).process.running,false);await page.locator('#process-guide').screenshot({path:path.join(out,`${device}-${system}-step-${i}.png`)});}
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#process-part').click();assert.ok((await snap()).selected);assert.equal(await page.evaluate(()=>document.activeElement.id),'viewport');await page.locator('#reset').click();assert.equal((await snap()).process.elapsed,0);assert.equal((await snap()).selected,null);
  if(device==='desktop'){
   await page.locator('#process-focus').click();await page.locator('#process-play').click();await page.waitForFunction(()=>window.filtrationQA.snapshot().process.elapsed>1);await page.locator('#process-guide').screenshot({path:path.join(out,system+'-motion-0.png')});
   await page.locator('#process-play').click();const pause=(await snap()).process.elapsed;await page.waitForTimeout(300);assert.equal((await snap()).process.elapsed,pause);await page.locator('#process-play').click();
   await page.waitForFunction(()=>window.filtrationQA.snapshot().process.elapsed>5);await page.locator('#process-guide').screenshot({path:path.join(out,system+'-motion-1.png')});
   await page.locator('#pause').click();const global=(await snap()).process.elapsed;await page.waitForTimeout(300);assert.equal((await snap()).process.elapsed,global);await page.locator('#pause').click();await page.locator('#process-guide').scrollIntoViewIfNeeded();
   await page.waitForFunction(()=>window.filtrationQA.snapshot().process.elapsed>9);await page.locator('#process-guide').screenshot({path:path.join(out,system+'-motion-2.png')});
   await page.waitForFunction(()=>window.filtrationQA.snapshot().process.elapsed>=16);assert.equal((await snap()).process.running,false);await page.locator('#process-guide').screenshot({path:path.join(out,system+'-complete.png')});
   await page.locator('#process-play').click();await page.waitForTimeout(200);await page.setViewportSize({width,height:500});await page.evaluate(()=>document.querySelector('footer').scrollIntoView());await page.waitForFunction(()=>!window.filtrationQA.snapshot().process.visible);const off=(await snap()).process.elapsed;await page.waitForTimeout(350);assert.equal((await snap()).process.elapsed,off);await page.setViewportSize({width,height});await page.locator('#process-guide').scrollIntoViewIfNeeded();await page.waitForTimeout(300);assert.ok((await snap()).process.elapsed>off);report.checks[system+'MotionPauseVisibility']=true;
  }
 }
 await page.locator('[data-system="biology"]').click();await page.waitForFunction(()=>window.filtrationQA?.snapshot().ready);assert.ok(await page.locator('#process-guide').isHidden());assert.ok(await page.locator('#biology-key').isVisible());assert.equal((await snap()).process.running,false);assert.ok(await page.locator('#process-focus').isHidden());await context.close();report.checks[device]=true;
}
assert.deepEqual(errors,[]);report.checkedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();server?.close();}
