import {chromium} from 'playwright';
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';
const before=process.argv.includes('--before'),remote=process.env.FILTRATION_TEST_BASE,mode=process.env.RETURN_QA_NAME||(before?'before':'after');
const root=path.resolve(import.meta.dirname,'../../../..'),out=path.resolve(import.meta.dirname,'../../.qa-results/return-pump');fs.mkdirSync(out,{recursive:true});
const server=remote?null:http.createServer((req,res)=>{try{let f=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(root+path.sep))throw Error('Path');if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.gz':'application/octet-stream'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});if(server)await new Promise(r=>server.listen(5262,'127.0.0.1',r));
const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[],report={mode,base:remote||'local',method:'Serial Chrome 1440x1120 DPR1, actual rendered frame count over 3 seconds after warmup. No older-hardware claim.',performance:[],checks:{},errors};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1120}});page.on('pageerror',e=>errors.push(e.message));
 const base=remote||'http://127.0.0.1:5262/prototypes/hidden-reef/showroom/filtration/';await page.goto(base+'#return');await page.waitForFunction(()=>window.filtrationQA?.snapshot().ready);
 const snap=()=>page.evaluate(()=>window.filtrationQA.snapshot()),shot=n=>page.locator('#viewport').screenshot({path:path.join(out,mode+'-'+n+'.png')});
 for(const system of ['system','return']){await page.locator(`[data-system="${system}"]`).click();await page.locator('#viewport').scrollIntoViewIfNeeded();await page.waitForTimeout(1300);const a=await snap(),start=Date.now();await page.waitForTimeout(3000);const b=await snap();report.performance.push({system,fps:(b.frames-a.frames)*1000/(Date.now()-start),calls:b.calls,triangles:b.triangles});await shot(system+'-assembled');}
 await page.locator('#pause').click();await page.waitForTimeout(500);await page.locator('[data-view="front"]').click();await shot('front');await page.locator('[data-view="top"]').click();await shot('top');await page.locator('[data-view="perspective"]').click();await shot('perspective');
 await page.locator('#explode-button').click();await page.waitForFunction(()=>window.filtrationQA.snapshot().explode>.999);await shot('exploded');
 for(const id of ['pump-motor','pump-rotor','shaft','volute','strainer']){await page.locator('#parts').selectOption(id);await page.locator('#isolate').click();await page.locator('#viewport').scrollIntoViewIfNeeded();await shot(id+'-detail');await page.locator('#clear').click();}
 await page.locator('#reset').click();
 if(!before){
  await page.locator('#pump-cutaway').click();await page.locator('#viewport').scrollIntoViewIfNeeded();assert.equal((await snap()).pump.cutaway,true);await shot('cutaway');
  if((await snap()).paused)await page.locator('#pause').click();await page.locator('#viewport').scrollIntoViewIfNeeded();for(let i=0;i<3;i++){await page.waitForTimeout(250);await shot('rotor-motion-'+i);}let a=await snap();await page.waitForTimeout(600);let b=await snap();assert.notEqual(b.rotorAngle,a.rotorAngle);const fast=Math.abs(b.rotorAngle-a.rotorAngle)/(b.time-a.time);
  await page.locator('#pump-speed').evaluate(el=>{el.value='25';el.dispatchEvent(new Event('input',{bubbles:true}));});await page.locator('#viewport').scrollIntoViewIfNeeded();a=await snap();await page.waitForTimeout(600);b=await snap();const slow=Math.abs(b.rotorAngle-a.rotorAngle)/(b.time-a.time);assert.ok(slow<fast*.4&&slow>fast*.15,'inspection speed changes smoothly');report.checks.inspectionSpeed=true;
  await page.locator('#pause').click();a=await snap();await page.waitForTimeout(400);assert.equal((await snap()).rotorAngle,a.rotorAngle);await page.waitForTimeout(900);const frame=(await snap()).frames;await page.waitForTimeout(400);assert.ok((await snap()).frames-frame<3,'paused cutaway idles');report.checks.pauseIdle=true;
  await page.locator('#explode-button').click();await page.waitForFunction(()=>window.filtrationQA.snapshot().explode>.999);await shot('cutaway-exploded');await page.locator('#parts').selectOption('volute');await page.locator('#isolate').click();await page.locator('#viewport').scrollIntoViewIfNeeded();await shot('cutaway-isolated-volute');await page.locator('#clear').click();
  await page.locator('#reset').click();assert.equal((await snap()).pump.cutaway,false);assert.equal((await snap()).pump.speed,1);report.checks.reset=true;
  for(const scenario of ['open','height','restriction']){await page.locator(`[data-pump-load="${scenario}"]`).click();await page.locator('#pump-learning').screenshot({path:path.join(out,mode+'-head-'+scenario+'.png')});}report.checks.headExamples=true;
  await page.locator('#process-focus').click();await page.locator('#process-play').click();await page.waitForFunction(()=>window.filtrationQA.snapshot().process.elapsed>1);await page.locator('#process-guide').screenshot({path:path.join(out,mode+'-guide.png')});await page.locator('#process-play').click();
 }
 for(const width of [390,320]){const phone=await browser.newPage({viewport:{width,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});phone.on('pageerror',e=>errors.push(e.message));await phone.goto(base+'#return');await phone.waitForFunction(()=>window.filtrationQA?.snapshot().ready);assert.equal(await phone.evaluate(()=>window.filtrationQA.snapshot().paused),true);await phone.locator('#viewport').scrollIntoViewIfNeeded();await phone.screenshot({path:path.join(out,mode+'-phone-'+width+'.png')});if(!before){await phone.locator('#pump-cutaway').click();await phone.locator('#viewport').scrollIntoViewIfNeeded();await phone.screenshot({path:path.join(out,mode+'-phone-cutaway-'+width+'.png')});await phone.locator('[data-pump-load="restriction"]').click();await phone.locator('#pump-learning').screenshot({path:path.join(out,mode+'-phone-learning-'+width+'.png')});}assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await phone.close();}report.checks.mobile=true;
 assert.deepEqual(errors,[]);report.checkedAt=new Date().toISOString();fs.writeFileSync(path.join(out,mode+'-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
}finally{await browser.close();server?.close();}
