/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c928c76a5fe3e30b210411e1662e2a6f)
interface __BaseEnv_Env {
	ALLOWED_ORIGIN: "https://jz237.github.io";
	ROOMS: DurableObjectNamespace<import("./src/index").FinalBlowRoom>;
	CREATE_LIMITS: DurableObjectNamespace<import("./src/index").CreateLimiter>;
	BOARDS: DurableObjectNamespace<import("./src/index").ChallengeBoard>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FinalBlowRoom" | "CreateLimiter" | "ChallengeBoard";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGIN">> {}
}
