import {cupStandings,nextCupMode,type CupState} from '../multiplayer/cup';
import type {Snapshot} from './network';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const CUP_MODE_NAMES={race:'Quarry circuit',derby:'Demolition derby'};
export function cupResultsMarkup(cup:CupState,members:Snapshot['members'],self:number){
 const connected=new Set(members.filter(m=>m.connected).map(m=>m.id)),rows=cupStandings(cup),complete=cup.completed===cup.rounds;
 let place=0;
 return `<div class="eyebrow">${complete?'CUP COMPLETE':`ROUND ${cup.completed} / ${cup.rounds} COMPLETE`}</div><h3>CUP STANDINGS</h3><div class="cup-table"><table><thead><tr><th>Place / driver</th><th>Round</th><th>Total</th><th>Wins</th></tr></thead><tbody>${rows.map((entry,i)=>{if(i===0||rows[i-1].points!==entry.points||rows[i-1].wins!==entry.wins)place=i+1;return `<tr class="${members.find(m=>m.id===self)?.cupId===entry.id?'player':''}"><td>${place}. ${escape(entry.name)}${entry.bot?' · AI':''}</td><td>+${entry.lastPoints}</td><td>${entry.points}</td><td>${entry.wins}</td></tr>`;}).join('')}</tbody></table></div><p>${cup.participants.length===24?'25 points for first, one fewer per place down to 2 for twenty-fourth.':'25 / 18 / 15 / 12 / 10 / 8 / 6 / 4 points by event position.'} Equal totals use wins; otherwise places are shared. Disconnected drivers at the finish score zero. New drivers enter the cup next round.</p>${complete?'':`<h3>VOTE FOR ROUND ${cup.round+1}</h3><div class="cup-votes">${(['race','derby'] as const).map(mode=>`<button class="small-button" type="button" data-cup-vote="${mode}" aria-pressed="${cup.votes[self]===mode}">${CUP_MODE_NAMES[mode]} · ${Object.entries(cup.votes).filter(([id,vote])=>connected.has(+id)&&vote===mode).length}</button>`).join('')}</div><p role="status">Next: ${CUP_MODE_NAMES[nextCupMode(cup,connected)]}. Tied or empty votes switch event type. The host starts the next round when everyone is ready.</p>`}`;
}
