import {COURSE_NAMES,isCourseId,resolveCourseId,type CourseId} from './course-id';
import {normalizeSetup,type Garage,type Setup} from './garage';
import {DEFINITIONS,type CarKind,type Mode} from './rules';import {DEMO_CAMERAS,type DemoCamera} from './demo-director';
export type DemoOptions={version:1;course?:CourseId;field:number;lineup:'mixed'|'selected';setups:'stock'|'garage';loop:'repeat'|'alternate'|'stop';camera:DemoCamera;laps:number;duration:number};
export const DEMO_KEY='quarry-impact-demo-v1';
export const DEFAULT_DEMO:DemoOptions={version:1,field:8,lineup:'mixed',setups:'stock',loop:'alternate',camera:'director',laps:2,duration:120};
export function readDemoOptions(text?:string|null):DemoOptions{
 try{const v=JSON.parse(text??'{}');if(!v||v.version!==1)return {...DEFAULT_DEMO};const int=(n:unknown,d:number,min:number,max:number)=>typeof n==='number'&&Number.isFinite(n)?Math.max(min,Math.min(max,Math.round(n))):d;
 return{version:1,...(isCourseId(v.course)?{course:v.course}:{}),field:int(v.field,8,2,24),lineup:v.lineup==='selected'?'selected':'mixed',setups:v.setups==='garage'?'garage':'stock',loop:['repeat','stop'].includes(v.loop)?v.loop:'alternate',camera:Object.hasOwn(DEMO_CAMERAS,v.camera)?v.camera:'director',laps:int(v.laps,2,1,20),duration:int(v.duration,120,30,1200)};}catch{return {...DEFAULT_DEMO};}
}
export function nextDemoMode(mode:Mode,loop:DemoOptions['loop']):'race'|'derby'|null{return loop==='stop'?null:loop==='alternate'?(mode==='race'?'derby':'race'):mode==='race'?'race':'derby';}
export function demoCarKind(index:number,selected:CarKind,lineup:DemoOptions['lineup']):CarKind{const kinds=Object.keys(DEFINITIONS)as CarKind[];return lineup==='selected'?selected:kinds[(kinds.indexOf(selected)+index)%kinds.length];}
/** Return a fresh setup per entrant so demo use never mutates the garage. */
export function demoVehicleSetup(kind:CarKind,options:Pick<DemoOptions,'setups'>,garage:Garage):Setup|undefined{return options.setups==='garage'?normalizeSetup(garage.cars[kind]?.setup,kind):undefined;}
export function showDemoSetup(ui:HTMLElement,options:DemoOptions,selected:CarKind,save:(v:DemoOptions)=>boolean,close:()=>void,start:()=>void){
 const modal=document.createElement('div');modal.className='overlay';modal.id='demo-setup';
 modal.innerHTML=`<div class="dialog"><div class="eyebrow">AI DRIVERS / LIVE PHYSICS</div><h2>DEMO SETUP</h2><p>Watch the cars race and wreck. Demo events do not earn driver progress.</p><label for="demo-course">Race course <select id="demo-course">${Object.entries(COURSE_NAMES).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><p class="garage-help">The selected course is used for demo races. Alternating demolition events take place at Blackridge Quarry.</p><label for="demo-field">Cars <input id="demo-field" type="number" min="2" max="24" value="${options.field}"></label><label for="demo-lineup">Lineup <select id="demo-lineup"><option value="mixed">Mixed vehicle field</option><option value="selected">${DEFINITIONS[selected].name} only</option></select></label><label for="demo-setups">Vehicle builds <select id="demo-setups"><option value="stock">Factory stock</option><option value="garage">My garage setups</option></select></label><p class="garage-help">Garage builds use your saved paint, reinforcement and tuning for each vehicle.</p><label for="demo-loop">After each event <select id="demo-loop"><option value="alternate">Alternate racing and derby</option><option value="repeat">Repeat this event</option><option value="stop">Stay on the result</option></select></label><label for="demo-opening">Opening camera <select id="demo-opening">${Object.entries(DEMO_CAMERAS).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><label for="demo-laps">Race laps <input id="demo-laps" type="number" min="1" max="20" value="${options.laps}"></label><label for="demo-duration">Derby seconds <input id="demo-duration" type="number" min="30" max="1200" value="${options.duration}"></label><p id="demo-setup-message" role="status"></p><button class="primary" id="demo-begin">WATCH DEMO ▷</button><button class="small-button" id="demo-save">SAVE & CLOSE</button><button class="small-button" id="demo-cancel">CANCEL</button></div>`;ui.append(modal);
 const select=(id:string)=>modal.querySelector<HTMLSelectElement>('#'+id)!;select('demo-course').value=resolveCourseId(options.course);select('demo-lineup').value=options.lineup;select('demo-setups').value=options.setups;select('demo-loop').value=options.loop;select('demo-opening').value=options.camera;
 const commit=(watch:boolean)=>{const field=+modal.querySelector<HTMLInputElement>('#demo-field')!.value,laps=+modal.querySelector<HTMLInputElement>('#demo-laps')!.value,duration=+modal.querySelector<HTMLInputElement>('#demo-duration')!.value;
 if(!Number.isInteger(field)||field<2||field>24||!Number.isInteger(laps)||laps<1||laps>20||!Number.isInteger(duration)||duration<30||duration>1200){modal.querySelector('#demo-setup-message')!.textContent='Use 2–24 cars, 1–20 laps and 30–1200 seconds.';return;}
 const value=readDemoOptions(JSON.stringify({version:1,course:select('demo-course').value,field,laps,duration,lineup:select('demo-lineup').value,setups:select('demo-setups').value,loop:select('demo-loop').value,camera:select('demo-opening').value}));Object.assign(options,value);const persisted=save(value);modal.remove();close();if(watch)start();if(!persisted){const note=document.createElement('p');note.className='toast';note.textContent='Demo options apply this session; browser storage is unavailable.';ui.append(note);}};
 modal.querySelector<HTMLButtonElement>('#demo-begin')!.onclick=()=>commit(true);modal.querySelector<HTMLButtonElement>('#demo-save')!.onclick=()=>commit(false);modal.querySelector<HTMLButtonElement>('#demo-cancel')!.onclick=()=>{modal.remove();close();};
}
