import {ACTIONS,ACTION_LABELS,bindKey,defaultControls,keyLabel,selectedPad,steeringAxis,type DrivingControls} from './driving-controls';
export function mountDrivingControls(parent:HTMLElement,config:DrivingControls,save:()=>boolean){
 const panel=document.createElement('details');panel.className='driving-settings';panel.innerHTML='<summary>Driving controls & steering assist</summary><p>Two keys per action. Select a key to rebind; Escape cancels and Backspace clears the alternate key. Camera, recovery and menu shortcuts stay fixed.</p><div class="driving-bindings"></div><div class="driving-calibration"></div><p class="driving-live" aria-live="off"></p><p class="driving-message" role="status"></p><button type="button" class="small-button driving-reset">RESET DRIVING CONTROLS</button>';parent.append(panel);
 const bindings=panel.querySelector<HTMLElement>('.driving-bindings')!,calibration=panel.querySelector<HTMLElement>('.driving-calibration')!,message=panel.querySelector<HTMLElement>('.driving-message')!;
 let pending:HTMLButtonElement|null=null;
 const persist=()=>{message.textContent=save()?'Controls saved.':'Controls work for this session, but browser storage is unavailable.';};
 const cancel=()=>{if(pending){pending.textContent=pending.dataset.label!;pending=null;}};
 function draw(){bindings.replaceChildren();calibration.replaceChildren();
  for(const action of ACTIONS){const row=document.createElement('div');row.className='driving-binding';const label=document.createElement('span');label.textContent=ACTION_LABELS[action];row.append(label);
   for(let slot=0;slot<2;slot++){const button=document.createElement('button');button.type='button';button.className='small-button';button.textContent=keyLabel(config.keys[action][slot]??'Add key');button.dataset.label=button.textContent;button.setAttribute('aria-label',`${ACTION_LABELS[action]} ${slot?'alternate':'primary'} key: ${button.textContent}`);
    button.onclick=()=>{cancel();pending=button;button.textContent='Press a key…';message.textContent='Waiting for a driving key.';};button.onblur=cancel;
    button.onkeydown=e=>{if(pending!==button)return;e.preventDefault();e.stopPropagation();if(e.code==='Escape'){cancel();message.textContent='Binding cancelled.';return;}if(e.code==='Backspace'&&slot===1){config.keys[action].splice(1);cancel();draw();persist();return;}const error=e.ctrlKey||e.altKey||e.metaKey?'Modifier combinations are unavailable.':bindKey(config,action,slot,e.code);if(error){message.textContent=error;return;}cancel();draw();persist();};row.append(button);
   }bindings.append(row);
  }
  const select=(label:string,key:'pad'|'axis'|'throttleButton'|'brakeButton'|'handbrakeButton',options:[number,string][])=>{const row=document.createElement('label');row.className='settings-row';row.textContent=label;const el=document.createElement('select');el.setAttribute('aria-label',label);for(const [value,text]of options)el.add(new Option(text,String(value)));el.value=String(config[key]);el.onchange=()=>{const value=+el.value;if(key.endsWith('Button')&&(['throttleButton','brakeButton','handbrakeButton'] as const).some(k=>k!==key&&config[k]===value)){message.textContent='Each gamepad action needs a different button.';el.value=String(config[key]);return;}config[key]=value;persist();};row.append(el);calibration.append(row);};
  select('Gamepad','pad',[[-1,'First connected'],...[0,1,2,3].map(n=>[n,`Slot ${n+1}`] as [number,string])]);select('Steering axis','axis',Array.from({length:8},(_,n)=>[n,`Axis ${n}`]));
  for(const [key,label]of [['throttleButton','Accelerate button'],['brakeButton','Brake / reverse button'],['handbrakeButton','Handbrake button']] as const)select(label,key,Array.from({length:32},(_,n)=>[n,`Button ${n}`]));
  const ranges=[['center','Steering center',-.5,.5,.01],['deadzone','Steering deadzone',0,.45,.01],['saturation','Full-lock input',.5,1,.01],['curve','Steering response curve',.5,3,.05],['triggerDeadzone','Button / trigger deadzone',0,.4,.01],['speedAssist','Steering limit at speed',0,1,.05]] as const;
  for(const [key,label,min,max,step]of ranges){const row=document.createElement('label');row.className='settings-row';const title=document.createElement('span');title.textContent=label;const output=document.createElement('output');output.textContent=config[key].toFixed(2);const el=document.createElement('input');el.type='range';el.min=String(min);el.max=String(max);el.step=String(step);el.value=String(config[key]);el.setAttribute('aria-label',label);el.oninput=()=>{config[key]=+el.value;output.textContent=config[key].toFixed(2);persist();};row.append(title,el,output);calibration.append(row);}
  const invert=document.createElement('label');invert.className='settings-row';invert.textContent='Invert steering axis';const check=document.createElement('input');check.type='checkbox';check.checked=config.invert;check.onchange=()=>{config.invert=check.checked;persist();};invert.append(check);calibration.append(invert);
  const help=document.createElement('p');help.textContent='Default standard pad: left stick steers, RT accelerates, LT brakes/reverses, A applies handbrake. Curve above 1 softens input near center. Speed limit assist reduces full steering as speed increases (0 = off).';calibration.append(help);
 }
 panel.querySelector<HTMLButtonElement>('.driving-reset')!.onclick=()=>{cancel();Object.assign(config,defaultControls());draw();persist();};panel.ontoggle=()=>{cancel();if(panel.open)update();};draw();
 let frame=0;
 function update(){cancelAnimationFrame(frame);if(!panel.isConnected||!panel.open)return;const pads=navigator.getGamepads?.()??[],pad=selectedPad(config,pads),live=panel.querySelector<HTMLElement>('.driving-live')!;live.textContent=pad?`${pad.id.slice(0,100)} · Slot ${pad.index+1} · Raw ${Number(pad.axes[config.axis]??0).toFixed(2)} → Steering ${steeringAxis(pad.axes[config.axis]??NaN,config).toFixed(2)}`:'No selected gamepad detected. Connect it and press a button.';frame=requestAnimationFrame(update);}
}
