import {type EventOptions,DEFAULT_EVENT,RACE_NAMES} from './event-rules';
export function showEventSetup(ui:HTMLElement,options:EventOptions,close:()=>void,save:()=>boolean){
  ui.innerHTML=`<section class="event-setup" aria-label="Custom event setup"><div class="event-panel"><div class="eyebrow">BLACKRIDGE MOTOR CLUB / SOLO EVENTS</div><h1>SET THE TERMS.</h1><p>Build your race or derby. Challenges use their own fixed rules.</p><label>Field size <output id="field-value">${options.field} cars</output><input id="event-field" type="range" min="2" max="24" step="1" value="${options.field}"></label><p class="event-help">Includes you. Larger fields demand more CPU and GPU power.</p><div class="event-options"><fieldset><legend>RACING</legend><label>Format<select id="event-race">${Object.entries(RACE_NAMES).map(([key,name])=>`<option value="${key}">${name}</option>`).join('')}</select></label><label>Laps / waypoint rounds<input id="event-laps" type="number" min="1" max="20" step="1" value="${options.laps}"></label><label>Direction<select id="event-direction"><option value="forward">Forward</option><option value="reverse">Reverse</option><option value="opposing">Opposing directions</option></select></label></fieldset><fieldset><legend>DEMOLITION</legend><label>Rules<select id="event-derby"><option value="survival">Last car standing</option><option value="score">Score derby · respawns</option></select></label><label>Time limit<select id="event-duration">${[60,120,180,300,600,1200].map(s=>`<option value="${s}">${s/60} ${s===60?'minute':'minutes'}</option>`).join('')}</select></label></fieldset></div><p id="race-help"></p><p>Score derby: one point per damage dealt, 100 per knockout. Wrecked cars return after four seconds when a clear spawn is available. Highest score wins.</p><p>Survival: no respawns. Last survivor wins; at the time limit, condition breaks the tie.</p><p id="event-save" role="status"></p><div class="event-actions"><button id="event-defaults">RESET RULES</button><button id="event-close" class="primary">BACK TO QUARRY ↗</button></div></div></section>`;
  for(const [id,value]of [['race',options.race],['direction',options.direction],['derby',options.derby],['duration',String(options.duration)]])ui.querySelector<HTMLSelectElement>('#event-'+id)!.value=value;
  const raceHelp=()=>{ui.querySelector('#race-help')!.textContent=options.race==='laps'?'Opposing directions splits the grid into two groups racing head-on around the same circuit.':'Collect five numbered stations, then return to FINISH for each round. Free order lets you choose; random reveals one station at a time. Direction applies only to circuit laps.';ui.querySelector<HTMLSelectElement>('#event-direction')!.disabled=options.race!=='laps';};raceHelp();
  const persist=()=>{ui.querySelector('#event-save')!.textContent=save()?'Rules saved for your next solo event.':'Rules apply this session; browser storage could not save them.';};
  ui.querySelector<HTMLSelectElement>('#event-race')!.onchange=e=>{options.race=(e.target as HTMLSelectElement).value as EventOptions['race'];raceHelp();persist();};
  ui.querySelector<HTMLInputElement>('#event-field')!.oninput=e=>{options.field=+(e.target as HTMLInputElement).value;ui.querySelector('#field-value')!.textContent=options.field+' cars';persist();};
  ui.querySelector<HTMLInputElement>('#event-laps')!.onchange=e=>{const input=e.target as HTMLInputElement;options.laps=Math.max(1,Math.min(20,Math.round(+input.value)||3));input.value=String(options.laps);persist();};
  ui.querySelector<HTMLSelectElement>('#event-direction')!.onchange=e=>{options.direction=(e.target as HTMLSelectElement).value as EventOptions['direction'];persist();};
  ui.querySelector<HTMLSelectElement>('#event-derby')!.onchange=e=>{options.derby=(e.target as HTMLSelectElement).value as EventOptions['derby'];persist();};
  ui.querySelector<HTMLSelectElement>('#event-duration')!.onchange=e=>{options.duration=+(e.target as HTMLSelectElement).value;persist();};
  ui.querySelector<HTMLButtonElement>('#event-defaults')!.onclick=()=>{Object.assign(options,DEFAULT_EVENT);save();showEventSetup(ui,options,close,save);};
  ui.querySelector<HTMLButtonElement>('#event-close')!.onclick=()=>{const value=+ui.querySelector<HTMLInputElement>('#event-laps')!.value;options.laps=Math.max(1,Math.min(20,Math.round(value)||3));save();close();};
}
