import {BACKUP_LIMIT,backupSummary,exportSave,readSave,restoreSave,type SaveBackup} from './save-backup';
export function downloadSave(text:string){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`quarry-save-${new Date().toISOString().slice(0,10)}.qis`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function mountSaveBackup(root:HTMLElement,storage?:Storage,reload=()=>location.reload()){
 const panel=document.createElement('details');panel.className='save-backup';panel.innerHTML=`<summary>SAVE BACKUP & RESTORE</summary><p>Move your saved game to another browser or keep a backup: career, challenge medals, XP, garage builds and liveries, championships, event records, personal bests and ghosts, controls and settings.</p><p>Replay recordings are separate. Export them from the Replay Library as .qir files. Backups contain local progress, not online accounts.</p><button id="save-export">EXPORT SAVE · .QIS</button><button id="save-import">CHOOSE BACKUP TO RESTORE</button><input id="save-file" type="file" accept=".qis,application/json" hidden><p id="save-message" role="status"></p><section id="save-confirm" hidden><h3>Replace this browser’s saved game?</h3><p id="save-summary"></p><p>Close other Quarry tabs first. This replaces local progress, builds, records and settings with the backup. Replay Library recordings stay here. Export your current save first if you want to keep it. The game reloads after restoration; interrupted races restart.</p><button id="save-cancel">CANCEL</button><button id="save-restore">RESTORE & RELOAD</button></section>`;root.append(panel);
 const get=<T extends HTMLElement>(s:string)=>panel.querySelector<T>(s)!,message=get('#save-message'),confirm=get('#save-confirm'),file=get<HTMLInputElement>('#save-file');let candidate:SaveBackup|null=null,busy=false,selection=0;const store=()=>storage??localStorage;
 const cancel=()=>{if(busy)return;candidate=null;confirm.hidden=true;get('#save-import').focus();};get('#save-cancel').onclick=cancel;
 const error=(e:unknown)=>{message.textContent=e instanceof Error?e.message:'Save storage is unavailable.';};
 get('#save-export').onclick=async()=>{if(busy)return;try{downloadSave(await exportSave(store()));message.textContent='Save backup downloaded. Keep the .qis file somewhere safe.';}catch(e){error(e);}};
 get('#save-import').onclick=()=>{if(!busy){file.value='';file.click();}};
 file.onchange=async()=>{const picked=file.files?.[0];if(!picked||busy)return;const selected=++selection;candidate=null;confirm.hidden=true;try{if(picked.size>BACKUP_LIMIT)throw Error('This backup exceeds the 6 MB limit.');const value=await readSave(await picked.text());if(!panel.isConnected||selected!==selection)return;candidate=value;const s=backupSummary(value.entries);get('#save-summary').textContent=`Backup from ${new Date(value.created).toLocaleString()} · ${s.events} events · ${s.medals} challenge medals · ${s.unlocks} career groups purchased · ${s.presets} garage presets · ${s.bests} lap records · ${s.ghosts} ghosts · ${s.cup}.`;confirm.hidden=false;message.textContent='Backup checked. Review it before restoring.';get('#save-cancel').focus();}catch(e){error(e);}};
 get('#save-restore').onclick=async()=>{if(!candidate||busy)return;busy=true;panel.setAttribute('aria-busy','true');get<HTMLButtonElement>('#save-restore').disabled=true;try{await restoreSave(store(),candidate);reload();}catch(e){if(e instanceof Error&&e.message==='RESTORE_RECOVERY_REQUIRED'){reload();return;}error(e);busy=false;panel.removeAttribute('aria-busy');get<HTMLButtonElement>('#save-restore').disabled=false;}};
 panel.addEventListener('keydown',e=>{if(e.code==='Escape'&&!confirm.hidden){e.preventDefault();e.stopPropagation();cancel();}});
}
