"""Browser integration checks. Serve repo root; APX9_URL may point at a live release."""
import asyncio, os
from playwright.async_api import async_playwright

async def main():
 async with async_playwright() as p:
  browser = await p.chromium.launch(executable_path=os.environ.get('CHROME','/usr/bin/google-chrome'), headless=True, args=['--no-sandbox','--use-gl=angle','--use-angle=vulkan','--enable-features=Vulkan','--ignore-gpu-blocklist'])
  errors=[]; checks=0
  page=await browser.new_page(viewport={'width':1400,'height':900})
  page.on('pageerror',lambda e:errors.append(str(e)))
  url=os.environ.get('APX9_URL','http://127.0.0.1:8768/demos/apx9-bee/')
  async def check(name, good):
   nonlocal checks
   assert good,name
   checks+=1;print('PASS',name,flush=True)
  await page.goto(url+'?qa&acc=0&q=low')
  await page.wait_for_function('window.__apx?.operations',timeout=120000)
  await page.get_by_role('button',name='◉  Power on / Operate',exact=True).click()
  await check('power opens from visible control',await page.locator('.operate-panel').is_visible())
  await page.evaluate('__apx.operations.state.boot=8')
  await page.wait_for_timeout(300)
  await check('startup reaches hover',await page.evaluate('__apx.bee.root.position.y>2'))
  await page.get_by_role('button',name='Pause motion',exact=True).click()
  clock=await page.evaluate('__apx.operations.state.clock');await page.wait_for_timeout(250)
  await check('pause holds animation clock',clock==await page.evaluate('__apx.operations.state.clock'))
  await page.get_by_role('button',name='Systems',exact=True).click()
  await page.get_by_role('button',name='Sensor signals',exact=True).click()
  await page.locator('input[aria-label="Explode"]').fill('950')
  await page.wait_for_timeout(200)
  await check('system view preserves explode controls',await page.evaluate('__apx.getExplode()>.94 && __apx.operations.state.mode==="systems"'))
  await check('system paths contain finite coordinates',await page.evaluate('''()=>{const a=__apx.stage.scene.getObjectByName('operating-exhibit');let lines=[];a.traverse(n=>{if(n.isLine)lines.push(n)});return lines.length===3&&lines.every(n=>Array.from(n.geometry.attributes.position.array).every(Number.isFinite))}'''))
  await page.get_by_role('button',name='Mission',exact=True).click()
  await page.get_by_role('button',name='Collect pollen',exact=True).click()
  await check('mission stage can be selected', 'Collect pollen' in await page.locator('.op-status').inner_text())
  await page.locator('input[aria-label="Pollination mission progress"]').fill('1000');await page.wait_for_timeout(200)
  await check('mission scrub reaches departure', 'Depart' in await page.locator('.op-status').inner_text())
  await check('scrub pauses playback',not await page.evaluate('__apx.operations.state.playing'))
  await page.get_by_role('button',name='Vision',exact=True).click()
  await page.get_by_role('button',name='UV',exact=True).click()
  await check('UV explicitly labelled as simulation','Simulated UV' in await page.locator('.op-status').inner_text())
  await check('sensor flower falls inside clipping planes',await page.evaluate('''()=>{const c=__apx.stage.camera;const v=new __apx.THREE.Vector3(32,-10,0).project(c);return Math.abs(v.x)<1&&Math.abs(v.y)<1&&Math.abs(v.z)<1}'''))
  await page.get_by_role('button',name='Thermal',exact=True).click()
  await check('thermal control changes mode',await page.evaluate('__apx.operations.state.sensor==="thermal"'))
  await page.screenshot(path='/tmp/apx9-verified-thermal.png')
  await page.get_by_role('button',name='Repair',exact=True).click()
  await page.get_by_role('button',name='Run diagnostic',exact=True).click()
  await page.get_by_role('button',name='Remove thorax cover',exact=True).click()
  await page.get_by_role('button',name='Open parts directory',exact=True).click()
  await page.get_by_role('searchbox',name='Search parts').fill('wing-mount-r')
  await page.locator('.dir-results .row').first.click()
  await check('real directory selection identifies failed part','Correct assembly' in await page.locator('.op-status').inner_text())
  await page.get_by_role('button',name='Fit spare actuator',exact=True).click()
  await page.get_by_role('button',name='Reassemble & test',exact=True).click()
  await check('repair completes','PASS' in await page.locator('.op-status').inner_text())
  await page.get_by_role('button',name='Scale',exact=True).click()
  await check('scale dimension is explicit','24.26' in await page.locator('.op-status').inner_text())
  await page.get_by_role('button',name='Back to inspection',exact=True).click()
  await check('inspection restored',await page.evaluate('__apx.bee.root.visible && __apx.bee.root.position.length()===0 && !__apx.stage.camera.view?.enabled'))
  await check('operating panel closes',not await page.locator('.operate-panel').is_visible())
  await page.set_viewport_size({'width':390,'height':844})
  await page.emulate_media(reduced_motion='reduce')
  await page.get_by_role('button',name='◉  Power on / Operate',exact=True).click()
  await check('reduced motion starts paused',await page.evaluate('__apx.operations.state.paused'))
  await page.get_by_role('button',name='Mission',exact=True).click()
  await check('reduced motion does not autoplay mission',not await page.evaluate('__apx.operations.state.playing'))
  await page.get_by_role('button',name='Scan',exact=True).click()
  await check('reduced motion supports manual mission stages','Scan' in await page.locator('.op-status').inner_text())
  await page.screenshot(path='/tmp/apx9-verified-mobile.png')
  await check('mobile panel fits viewport',await page.locator('.operate-panel').evaluate('(e)=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight}'))
  await check('mobile panel leaves original dock accessible',await page.evaluate('document.querySelector(".operate-panel").getBoundingClientRect().bottom <= document.querySelector(".dock").getBoundingClientRect().top'))
  await page.get_by_role('button',name='Vision',exact=True).click()
  await page.get_by_role('button',name='UV',exact=True).click()
  await page.wait_for_timeout(200)
  await page.screenshot(path='/tmp/apx9-verified-mobile-vision.png')
  await page.get_by_role('button',name='Close operating panel',exact=True).click()
  await check('mobile exit restores bee',await page.evaluate('__apx.bee.root.visible'))
  await check('no JavaScript errors',not errors)
  print(f'{checks} checks passed',flush=True)
  await browser.close()
asyncio.run(main())
