import {useEffect,useRef,useState} from 'react';
import {FilterScene,filterParts,waterStages} from '../lib/aquarium/FilterScene';
import '../app/filter.css';
export default function FilterBreakdown({onClose,reduced}:{onClose:()=>void;reduced:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),host=useRef<HTMLDivElement>(null),engine=useRef<FilterScene|null>(null);
 const [trace,setTrace]=useState(false),[traceStage,setTraceStage]=useState(0),[tracePlay,setTracePlay]=useState(false);
 const [part,setPart]=useState(3),[explosion,setExplosion]=useState(0),[housing,setHousing]=useState(true),[flow,setFlow]=useState(true),[isolated,setIsolated]=useState(false),[rotate,setRotate]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const d=dialog.current!;d.showModal();try{engine.current=new FilterScene(host.current!,setPart,reduced,setTraceStage);}catch(e){setError('The 3D view could not start. The component guide is still available below.');}return()=>{engine.current?.dispose();engine.current=null;d.close();};},[reduced]);
 useEffect(()=>{engine.current?.select(part);},[part]);
 const stopTrace=()=>{setTrace(false);setTracePlay(false);engine.current?.setTrace(false);};
 const split=(v:number)=>{stopTrace();setExplosion(v);engine.current?.setExplode(v);};
 return <dialog ref={dialog} className="filter-dialog" aria-labelledby="filter-title" onCancel={e=>{e.preventDefault();onClose();}}>
 <header><div><p className="filter-kicker">THE LIVING AQUASCAPE / ENGINEERING STUDY</p><h1 id="filter-title">Inside the canister</h1></div><button className="filter-close" onClick={onClose} aria-label="Close filter breakdown">Back to aquarium ×</button></header>
 <div className="filter-layout"><section className="filter-stage" aria-label="Filter model viewer"><div className="filter-canvas" ref={host}/>{error&&<p className="filter-error">{error}</p>}<div className="filter-view-label"><span>01—10 / SELECT A COMPONENT</span><strong>{explosion>.08?'Exploded assembly':'Working cutaway'}</strong><small>Drag to orbit · Pinch or scroll to zoom</small></div><div className="filter-legend"><span>● Inlet / untreated water</span><span>● Return / filtered water</span></div><div className="filter-toolbar"><button aria-pressed={trace} onClick={()=>{if(trace){stopTrace();return;}setTrace(true);setTracePlay(!reduced);setExplosion(0);setIsolated(false);setFlow(true);engine.current?.setFlow(true);engine.current?.setTrace(true);}}>{trace?'Exit water trace':'Trace the water'}</button><button onClick={()=>split(explosion>.5?0:1)}>{explosion>.5?'Reassemble filter':'Explode filter'}</button><button onClick={()=>engine.current?.focusSelected()}>Inspect material detail</button><button onClick={()=>engine.current?.reset()}>Reset filter view</button><label>Separation<input aria-label="Filter separation" type="range" min="0" max="100" value={Math.round(explosion*100)} onChange={e=>split(+e.target.value/100)}/></label><label><input type="checkbox" checked={isolated} onChange={e=>{stopTrace();setIsolated(e.target.checked);engine.current?.setIsolate(e.target.checked);if(e.target.checked)engine.current?.focusSelected();}}/> Isolate selected part</label><label><input type="checkbox" checked={housing} onChange={e=>{setHousing(e.target.checked);engine.current?.setCutaway(e.target.checked);}}/> Show cutaway housing</label><label><input type="checkbox" checked={flow} onChange={e=>{setFlow(e.target.checked);engine.current?.setFlow(e.target.checked);}}/> Pump & water flow</label><label><input type="checkbox" checked={rotate} disabled={reduced} onChange={e=>{setRotate(e.target.checked);engine.current?.setRotate(e.target.checked);}}/> Auto orbit</label></div></section>
 <aside className="filter-guide">{trace&&<section className="filter-trace" aria-label="Water path guide"><p className="filter-kicker">FOLLOW THE WATER / {traceStage+1} OF 8</p><h2>{waterStages[traceStage].name}</h2><p>{waterStages[traceStage].text}</p><div className="trace-steps">{waterStages.map((s,i)=><button key={s.name} aria-label={`Trace stage ${i+1}: ${s.name}`} aria-pressed={traceStage===i} onClick={()=>{setTracePlay(false);engine.current?.playTrace(false);engine.current?.stepTrace(i);}}>{i+1}</button>)}</div><div className="trace-actions"><button onClick={()=>{setTracePlay(false);engine.current?.playTrace(false);engine.current?.stepTrace(traceStage-1);}}>Previous</button><button disabled={reduced} onClick={()=>{setTracePlay(!tracePlay);engine.current?.playTrace(!tracePlay);}}>{tracePlay?'Pause trace':'Play trace'}</button><button onClick={()=>{setTracePlay(false);engine.current?.playTrace(false);engine.current?.stepTrace(traceStage+1);}}>Next</button></div><small>Highlighted route is shown through the housing and media for clarity. Colors identify stages; this is an explanatory water path, not a fluid simulation.{!flow?' Pump paused.':''}{reduced?' Use the numbered stages to explore without motion.':''}</small></section>}<p className="filter-kicker">COMPONENT DIRECTORY</p><nav aria-label="Filter components">{filterParts.map((p,i)=><button key={p.name} aria-pressed={part===i} onClick={()=>setPart(i)}><span>{String(i+1).padStart(2,'0')}</span>{p.name}<b aria-hidden="true">↗</b></button>)}</nav><article aria-live="polite"><p className="filter-kicker">{String(part+1).padStart(2,'0')} / {filterParts[part].role}</p><h2>{filterParts[part].name}</h2><p>{filterParts[part].text}</p></article><div className="filter-note"><strong>Water path</strong><p>Intake → side channel → coarse foam → fine foam → ceramic media → polishing pad → impeller → return.</p><small>{explosion>.08?'Reassemble to trace the continuous water circuit. ':''}{reduced?'Motion is paused to respect Reduced motion. ':''}Representative canister design, not a manufacturer service diagram. Media order and hardware vary by model.</small></div></aside></div>
 </dialog>;
}
