"use client";
import {frameDelta} from '../lib/aquarium/frame';
import {useEffect,useRef,useState} from 'react';
import {PhotographicScene,type FishInfo as SelectedFishInfo} from '../lib/aquarium/PhotographicScene';
import {advance,balance,defaults,factors,illumination,initial,preset,scenarios,waterChange,type Environment} from '../lib/aquarium/Ecosystem';
const modes=['Living','Flow','Roots','Biology','Time-lapse','Equipment'];
const stories:Record<string,[string,string,string]>={
 Living:['A small world. A living balance.','Plants, fish and microbes share the same water. Look closely; each quiet movement belongs to a larger system.','Drag to look around · Scroll to look closer · Click a fish'],
 Flow:['The water connects everything.','The outlet carries dissolved gases and nutrients through the planting. Cyan paths show the upper current; gold paths return below. These are illustrative streamlines, not a fluid solver.','Change filter flow to compare circulation'],
 Roots:['Life beneath the surface.','Roots take up nutrients and exchange gases with the substrate. Deeper layers generally contain less oxygen. This front-plane teaching cutaway shows representative roots, rather than scanned anatomy.','Increase time speed to see the root zone expand'],
 Biology:['A world within the water.','A leaf becomes a landscape. Inspect a grazing shrimp, delicate veins and oxygen pearls in this photographic macro study.','Choose a process to trace its role'],
 'Time-lapse':['Some changes take time.','Gases respond over hours. Waste and nutrients shift over days. Plant mass, roots and algae respond over weeks. Accelerate the ecosystem to reveal those differences.','Playback accelerates chemistry; fish stay at a comfortable viewing speed'],
 Equipment:['Follow the water through.','Mechanical foam traps solids. Biological media supports nitrifiers. The impeller returns water to the aquarium; a separate regulator meters carbon dioxide.','Inspect the canister, media and carbon supply']};
const lessons:Record<string,[string,string]>={
 'Nitrogen cycle':['Food → waste → ammonia → nitrite → nitrate → plants','Microbes mineralize organic material. Ammonia-oxidizing organisms and nitrite oxidizers then convert dissolved nitrogen in two oxygen-consuming steps. Plants assimilate nitrogen; water changes export it. Readings use mg nitrogen/L.'],
 'Photosynthesis':['Light + CO₂ + water → sugars + O₂','Photosynthesis stores light energy in organic carbon. Visible pearling depends on local gas saturation and nucleation; bubbles alone cannot measure plant health.'],
 'Respiration':['Sugars + O₂ → CO₂ + water','Fish, plants and microbes respire during both day and night. When the light goes out, photosynthetic oxygen production stops but respiration continues.'],
 'Root uptake':['Water column ↔ substrate ↔ roots','Substrate retains nutrients and supports roots and biofilms. Aquatic plants can also absorb nutrients through submerged leaves, with gas exchange across their surfaces.'],
 'Gill exchange':['Water → gill surfaces → blood','Oxygen diffuses across thin gill surfaces while carbon dioxide moves out. Gas exchange depends on concentration gradients and ventilation; low oxygen can change activity.'],
 'Algae diagnosis':['Observe the system before changing it','This model shows generic algae pressure. Real green spot algae, diatoms, hair algae and cyanobacteria have different causes. Assess plant health, carbon delivery, organic waste and maintenance rather than diagnosing from nitrate alone.']};
const equipment:Record<string,string>={'Intake':'Water enters through the intake strainer. Keep its openings clear so circulation can carry waste into the filter.','Mechanical foam':'Coarse and fine foam trap particles. Rinsing removes trapped solids; the foam also carries some biological growth.','Biological media':'Porous media provides wetted surfaces for biofilm. Nitrifying organisms consume oxygen while converting ammonia to nitrite and nitrate.','Impeller and outlet':'The impeller drives circulation. The lily pipe distributes returned water and shapes surface agitation.','CO₂ regulator':'The regulator reduces cylinder pressure; the metering valve and solenoid control delivery. The diffuser creates fine bubbles that dissolve into circulating water.'};
const ranges:[keyof Environment,string,number,number,number,string][]=[['light','Light intensity',0,100,1,'%'],['photoperiod','Photoperiod',2,16,1,'h'],['co2','CO₂ supply setting',0,45,1,'mg/L eq.'],['flow','Filter flow',0,100,1,'%'],['agitation','Surface agitation',0,100,1,'%'],['temperature','Heater target',18,30,.5,'°C'],['feed','Daily feeding',0,4,.25,'×'],['fertilizer','Nutrient dosing',0,3,.25,'×'],['kh','Carbonate hardness',1,10,.5,'dKH']];
export default function LivingAquascape(){
 const host=useRef<HTMLDivElement>(null),engine=useRef<PhotographicScene|null>(null);
 const eco=useRef(initial()),env=useRef(defaults()),speedRef=useRef(1),pauseRef=useRef(false),reducedRef=useRef(false),audio=useRef<AudioContext|null>(null),audioGain=useRef<GainNode|null>(null),volumeRef=useRef(20);
 const [mode,setMode]=useState('Living'),[error,setError]=useState(''),[controls,setControls]=useState(false),[readings,setReadings]=useState(false),[snapshot,setSnapshot]=useState(initial()),[environment,setEnvironment]=useState(defaults()),[scenario,setScenario]=useState<string>(scenarios[0]),[explanation,setExplanation]=useState(preset(scenarios[0]).explanation),[speed,setSpeed]=useState(1),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false),[clean,setClean]=useState(false),[sound,setSound]=useState(false),[volume,setVolume]=useState(20),[quality,setQuality]=useState('High'),[recommended,setRecommended]=useState('High'),[frame,setFrame]=useState(0),[selected,setSelected]=useState<SelectedFishInfo|null>(null),[lesson,setLesson]=useState('Nitrogen cycle'),[part,setPart]=useState('Biological media'),[notice,setNotice]=useState(''),[camera,setCamera]=useState('Gallery'),[loading,setLoading]=useState(true);
 const changeCamera=(name:string)=>{setCamera(name);if(name==='Leaf macro'){changeMode('Biology');}else {if(mode==='Biology')changeMode('Living');engine.current?.cameraPreset(name);}};
 const changeMode=(m:string)=>{setMode(m);engine.current?.setMode(m);setSelected(null);setCamera(m==='Equipment'?'Equipment':m==='Roots'?'Root zone':m==='Biology'?'Leaf macro':'Gallery');};
 const changeSpeed=(s:number)=>{speedRef.current=s;setSpeed(s);};
 const changeEnv=(key:keyof Environment,value:number)=>{env.current={...env.current,[key]:value};setEnvironment({...env.current});};
 const loadScenario=(name:string)=>{const p=preset(name);eco.current=p.state;env.current=p.environment;setSnapshot({...p.state});setEnvironment({...p.environment});setScenario(name);setExplanation(p.explanation);changeSpeed(name===scenarios[0]?1:3600);};
 const notify=(text:string)=>setNotice(text);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(id);},[notice]);
 useEffect(()=>{
 const preference=matchMedia('(prefers-reduced-motion: reduce)').matches;reducedRef.current=preference;setReduced(preference);
 const tier=navigator.hardwareConcurrency<=4||innerWidth<700?'Performance':'High';setRecommended(tier);
 let saved=tier;try{saved=localStorage.getItem('living-aquascape-quality')||tier;}catch{}
 if(!['Performance','High','Ultra','Photography'].includes(saved))saved=tier;setQuality(saved);
 let active=true,e:PhotographicScene|null=null;
 try{if(host.current){e=new PhotographicScene(host.current);engine.current=e;e.setQuality(saved);e.onSelectedFish=setSelected;e.onInspect=name=>changeMode(name==='equipment'?'Equipment':name==='roots'?'Roots':'Biology');
 e.ready.then(()=>{if(active)setLoading(false);}).catch(()=>{if(active){setLoading(false);setError('Some visual assets could not load. Reload to try again; the educational controls remain available.');}});
 }}catch{setLoading(false);setError('This browser cannot start WebGL. The static gallery and ecosystem controls remain available.');}
 if(saved==='Photography'){pauseRef.current=true;setPaused(true);}
 let request=0,last=performance.now(),report=0,frames=0,elapsed=0,gamepadPress=false;
 const loop=(now:number)=>{const raw=(now-last)/1000,dt=frameDelta(now,last);last=now;
 if(!pauseRef.current)advance(eco.current,env.current,dt*speedRef.current/3600);
 const gamepad=navigator.getGamepads?.()[0];if(gamepad&&e){const x=Math.abs(gamepad.axes[0]||0)>.15?gamepad.axes[0]:0,y=Math.abs(gamepad.axes[1]||0)>.15?gamepad.axes[1]:0;e.nudge(x*dt*200,-y*dt*200);if(gamepad.buttons[0]?.pressed&&!gamepadPress){pauseRef.current=!pauseRef.current;setPaused(pauseRef.current);}gamepadPress=!!gamepad.buttons[0]?.pressed;}
 e?.update(dt,eco.current,env.current,reducedRef.current,pauseRef.current);
 if(audioGain.current&&audio.current)audioGain.current.gain.setTargetAtTime(env.current.flow/100*.035*(volumeRef.current/20),audio.current.currentTime,.3);
 frames++;elapsed+=raw;if(now-report>500){setSnapshot({...eco.current});setFrame(elapsed/frames*1000);frames=0;elapsed=0;report=now;}
 request=requestAnimationFrame(loop);};request=requestAnimationFrame(loop);
 const keyboard=(event:KeyboardEvent)=>{if((event.target as HTMLElement).matches('input,select,button,textarea'))return;
 if(event.key==='Escape')setClean(false);if(event.key.toLowerCase()==='h')setClean(v=>!v);
 if(event.code==='Space'){event.preventDefault();pauseRef.current=!pauseRef.current;setPaused(pauseRef.current);}
 if(/^[1-6]$/.test(event.key))changeMode(modes[Number(event.key)-1]);
 const arrows:Record<string,number[]>={ArrowLeft:[-35,0],ArrowRight:[35,0],ArrowUp:[0,35],ArrowDown:[0,-35]};
 if(arrows[event.key]){event.preventDefault();e?.nudge(arrows[event.key][0],arrows[event.key][1]);}
 if(event.key==='+'||event.key==='=')e?.zoom(e.camera.zoom*1.15);if(event.key==='-')e?.zoom(e.camera.zoom/1.15);
 };
 window.addEventListener('keydown',keyboard);return()=>{active=false;cancelAnimationFrame(request);window.removeEventListener('keydown',keyboard);e?.dispose();engine.current=null;void audio.current?.close();audio.current=null;};
 },[]);

 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'load_aquascape_scenario',description:'Reset the visible educational ecosystem to a named reproducible scenario.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:[...scenarios]}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const name=(input as {scenario?:unknown})?.scenario;if(typeof name!=='string'||!scenarios.some(s=>s===name))throw Error('Choose a listed aquarium scenario.');loadScenario(name);return {scenario:name,state:{...eco.current}};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
 const changeQuality=(q:string)=>{setQuality(q);try{localStorage.setItem('living-aquascape-quality',q);}catch{}engine.current?.setQuality(q);if(q==='Photography'){pauseRef.current=true;setPaused(true);}notify(q==='Photography'?'Simulation paused. Frame your shot and save a PNG.':q+' rendering selected.');};
 const toggleAudio=async()=>{try{if(sound){await audio.current?.suspend();setSound(false);return;}if(!audio.current){const ctx=new AudioContext();audio.current=ctx;const source=ctx.createOscillator(),gain=ctx.createGain(),low=ctx.createBiquadFilter();source.type='sine';source.frequency.value=60;gain.gain.value=.012;low.type='lowpass';low.frequency.value=140;const pan=ctx.createStereoPanner();pan.pan.value=.5;source.connect(low).connect(gain).connect(pan).connect(ctx.destination);source.start();const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate),data=buffer.getChannelData(0);let seed=237;for(let i=0;i<data.length;i++){seed=(seed*1664525+1013904223)>>>0;data[i]=(seed/4294967296-.5)*.11;}const water=ctx.createBufferSource(),filter=ctx.createBiquadFilter();water.buffer=buffer;water.loop=true;filter.type='lowpass';filter.frequency.value=450;water.connect(filter).connect(gain);water.start();audioGain.current=gain;}await audio.current.resume();setSound(true);}catch{notify('Audio could not start in this browser.');}};
 const togglePause=()=>{pauseRef.current=!pauseRef.current;setPaused(pauseRef.current);};
 const f=factors(snapshot,environment),score=balance(snapshot,environment),story=stories[mode];
 return <main className={'exhibit '+(clean?'clean':'')}><div className="tank" ref={host}/>{loading&&<div className="loading-poster"><img src="./aquascape.png" alt="A planted aquarium in a dark gallery"/><p role="status">Bringing the aquascape to life…</p></div>}{error&&<div className="fallback"><img src="./aquascape.png" alt="Concept artwork of a planted aquarium in a dark gallery"/><p>{error} Image: original photographic artwork.</p></div>}
 <header className="chrome"><a href="../">← Demos</a><h1>THE LIVING AQUASCAPE</h1><p><i/> {paused?'TIME SUSPENDED':score>=80?'A SMALL WORLD, IN BALANCE':'A LIVING SYSTEM, IN TRANSITION'}</p></header>
 <div className="left-tools chrome"><button aria-expanded={controls} onClick={()=>setControls(!controls)}>☷ Environment</button><button aria-expanded={readings} onClick={()=>setReadings(!readings)}>◉ Chemistry</button></div>
 {controls&&<aside className="drawer chrome" aria-label="Environmental controls"><div className="drawer-heading"><h2>Environment</h2><button aria-label="Close environmental controls" onClick={()=>setControls(false)}>×</button></div><label className="field">Guided scenario<select value={scenario} onChange={e=>loadScenario(e.target.value)}>{scenarios.map(s=><option key={s}>{s}</option>)}</select></label><p>{explanation}</p>{ranges.map(([key,label,min,max,step,unit])=><label className="range" key={key}><span>{label}<output>{environment[key]} {unit}</output></span><input type="range" min={min} max={max} step={step} value={environment[key]} onChange={e=>changeEnv(key,+e.target.value)}/></label>)}<div className="pair"><button onClick={()=>{engine.current?.feedAt();eco.current.waste+=.5;notify('Food added. Waste mineralizes gradually.');}}>Feed once</button><button onClick={()=>{waterChange(eco.current);setSnapshot({...eco.current});notify('30% of dissolved waste removed. Established algae remains.');}}>30% water change</button><button onClick={()=>{eco.current.biomass*=.7;notify('Plants trimmed by 30%. Observe new growth over days.');}}>Trim plants</button><button onClick={()=>{eco.current.algae*=.4;notify('Visible algae reduced by manual cleaning.');}}>Clean algae</button></div><label className="field">Rendering <small>Suggested: {recommended}</small><select value={quality} onChange={e=>changeQuality(e.target.value)}>{['Performance','High','Ultra','Photography'].map(q=><option key={q}>{q}</option>)}</select></label><label className="check"><input type="checkbox" checked={reduced} onChange={e=>{setReduced(e.target.checked);reducedRef.current=e.target.checked;}}/> Reduced motion</label><button onClick={()=>loadScenario(scenarios[0])}>Restore balanced aquarium</button></aside>}
 <aside className="chemistry chrome" aria-label="Live modeled readings"><span>♨ <b>{snapshot.temperature.toFixed(1)}</b> <small>°C</small></span><span>pH <b>{snapshot.ph.toFixed(2)}</b><small> estimate</small></span><span>CO₂ <b>{snapshot.co2.toFixed(1)}</b> <small>mg/L</small></span><span>O₂ <b>{snapshot.oxygen.toFixed(1)}</b> <small>mg/L</small></span><button className="balance" onClick={()=>setReadings(!readings)} aria-expanded={readings}>BALANCE <strong>{score}</strong><small>/ 100</small></button></aside>
 {readings&&<aside className="chemistry-detail chrome"><div className="drawer-heading"><h2>Under the surface</h2><button aria-label="Close chemistry details" onClick={()=>setReadings(false)}>×</button></div><p>Modeled water chemistry · 180 L<br/>Dissolved nitrogen in mg N/L</p><dl>{[['Ammonia-N',snapshot.ammonia.toFixed(3)],['Nitrite-N',snapshot.nitrite.toFixed(3)],['Nitrate-N',snapshot.nitrate.toFixed(2)],['Plant biomass',snapshot.biomass.toFixed(2)+'×'],['Algae cover',(snapshot.algae*100).toFixed(0)+'%'],['Biofilter maturity',(snapshot.bacteria*100).toFixed(0)+'%']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>Balance factors</p>{Object.entries(f).map(([k,v])=><label className="factor" key={k}>{k}<meter min="0" max="1" value={v}/></label>)}<small>Carbonate-only pH estimate. Aquasoil, organic acids and non-carbonate buffers can invalidate this relationship in a real aquarium.</small></aside>}
 {!controls&&mode!=='Equipment'&&<section className="story chrome"><p className="eyebrow">{String(modes.indexOf(mode)+1).padStart(2,'0')} / {mode.toUpperCase()}</p><h2>{story[0]}</h2><p>{story[1]}</p><small>{story[2]}</small>{(mode==='Living'||mode==='Flow')&&<div className="range current-control" role="group" aria-label="Water movement"><span>Water current<output>{environment.flow}%</output></span><input aria-label="Water current" type="range" min="0" max="100" step="1" value={environment.flow} onChange={e=>changeEnv('flow',+e.target.value)}/><span>Surface ripples<output>{environment.agitation}%</output></span><input aria-label="Surface ripples" type="range" min="0" max="100" step="1" value={environment.agitation} onChange={e=>changeEnv('agitation',+e.target.value)}/><small>{paused?'Resume playback to see the plants sway.':reduced?'Turn off Reduced motion in Environment to see the plants sway.':'Watch the tall leaves bend; rooted bases stay still.'}</small></div>}</section>}
 {mode==='Equipment'&&<section className="equipment-card chrome"><p className="eyebrow">WATER, THROUGH THE SYSTEM</p><h2>Inside the filter</h2><div className="equipment-steps">{Object.keys(equipment).map((name,i)=><button key={name} aria-pressed={part===name} onClick={()=>setPart(name)}><small>{String(i+1).padStart(2,"0")}</small>{name}<span aria-hidden="true">→</span></button>)}</div><p>{equipment[part]}</p><small>Representative photographic equipment · functional inspection guide</small></section>}
 {mode==='Biology'&&<section className="lesson chrome"><label className="field">Look closer<select value={lesson} onChange={e=>setLesson(e.target.value)}>{Object.keys(lessons).map(l=><option key={l}>{l}</option>)}</select></label><h2>{lessons[lesson][0]}</h2><p>{lessons[lesson][1]}</p></section>}
 {selected&&mode==='Living'&&<section className="inspector chrome"><button aria-label="Close fish inspection" onClick={()=>{engine.current?.selectFish(null);setSelected(null);}}>×</button><p className="eyebrow">LIVING COLLECTION</p><h2>{selected.species}</h2><p>{selected.mood} · {selected.preferredDepth}<br/>Fish seek food, maintain distance and respond to their school.</p></section>}
 <div className="view-tools chrome"><label>Look closer<select aria-label="Camera framing" value={camera} onChange={e=>changeCamera(e.target.value)}>{['Gallery','Aquascape','Open water','Root zone','Equipment','Leaf macro'].map(c=><option key={c}>{c}</option>)}</select></label><button aria-label="Zoom out" onClick={()=>engine.current?.zoom((engine.current?.camera.zoom||1)/1.2)}>−</button><button aria-label="Zoom in" onClick={()=>engine.current?.zoom((engine.current?.camera.zoom||1)*1.2)}>+</button><button onClick={()=>{changeMode('Living');setControls(false);setReadings(false);setSelected(null);}}>Reset view</button><button onClick={()=>{engine.current?.feedAt();eco.current.waste+=.5;pauseRef.current=false;setPaused(false);notify(reduced?'Food added. Turn off Reduced motion to watch feeding.':'Food added — watch the school gather near the surface.');}}>Feed fish</button></div>
 <div className="transport chrome">
<button onClick={togglePause} aria-label={paused?'Resume simulation':'Pause simulation'}>{paused?'▶':'Ⅱ'}</button><span>DAY {Math.floor(snapshot.hours/24)+1} <b>{String(Math.floor((12+snapshot.hours)%24)).padStart(2,'0')}:{String(Math.floor(snapshot.hours*60)%60).padStart(2,'0')}</b></span><select aria-label="Ecosystem time speed" value={speed} onChange={e=>changeSpeed(+e.target.value)}><option value={1}>Real time</option><option value={3600}>1 hour / sec</option><option value={86400}>1 day / sec</option></select>{mode==='Time-lapse'&&<button onClick={()=>{advance(eco.current,env.current,24);setSnapshot({...eco.current});}}>+1 day</button>}</div>
 <nav className="modes chrome" aria-label="Exploration modes">{modes.map(m=><button key={m} aria-pressed={mode===m} onClick={()=>changeMode(m)}>{m}</button>)}</nav>
 <div className="photo-tools chrome"><button onClick={()=>setClean(true)} title="Hide interface (H)">◉ <span>Photo mode</span></button><button onClick={()=>{if(engine.current){engine.current.capture();notify('Aquarium PNG saved.');}else notify('PNG capture requires the animated view.');}}>Save PNG</button></div><div className="audio-tools chrome"><button aria-pressed={sound} onClick={toggleAudio}>{sound?'Sound on':'Sound off'}</button>{sound&&<label>Volume<input aria-label="Environment volume" type="range" min="0" max="100" value={volume} onChange={e=>{const value=+e.target.value;setVolume(value);volumeRef.current=value;}}/></label>}<small>{frame.toFixed(1)} ms / frame</small></div>
 {clean&&<button className="restore" onClick={()=>setClean(false)}>Show controls · H / Esc</button>}{notice&&<div role="status" className="toast">{notice}</div>}<a className="model-note chrome" href="./about.html" target="_blank" rel="noopener">Educational model · Methods &amp; limits ↗</a>
 </main>;
}
