import test from 'node:test';import assert from 'node:assert/strict';
import {createHydro,stepHydro} from '../hydrodynamics.js';import {landingResponse} from '../landing-response.js';import {createSprayField,stepSprayField,sprayAt} from '../rival-spray.js';import {rideSoundMix} from '../ride-sound.js';import {breakerProfile} from '../curling-breakers.js';import {refractionSize,shadowDue} from '../render-budget.js';import {boundaryHeight,setBoundaryWaves,boundaryCount} from '../boundary-waves.js';
const craft={id:0,x:0,z:0,heading:0,vx:0,vz:20,speed:20,turn:0,throttle:1};
test('airborne weight shifts change pitch without adding lift or horizontal momentum',()=>{const states=[-1,0,1].map(lean=>{const h=createHydro();h.initialized=true;h.y=8;h.airborne=h.launched=true;for(let i=0;i<45;i++)stepHydro(h,craft,i/60,1/60,()=>0,{lean});return h;});assert.ok(states[0].pitch>states[1].pitch+.1);assert.ok(states[2].pitch<states[1].pitch-.1);assert.ok(Math.abs(states[0].y-states[2].y)<1e-9);});
test('directional entries produce different measured landing losses and bounded kicks',()=>{const h={impact:9,pitch:0,roll:0},level=landingResponse(h,craft),bow=landingResponse({...h,pitch:.45},craft),stern=landingResponse({...h,pitch:-.45},craft),side=landingResponse({...h,roll:.7},{...craft,vx:8});assert.equal(bow.style,'bow-first');assert.equal(stern.style,'stern-first');assert.equal(side.style,'sideways');assert.ok(side.loss>bow.loss&&bow.loss>stern.loss&&stern.loss>level.loss);assert.ok(bow.kick<0&&stern.kick>0);assert.ok(landingResponse({...h,pitch:.45},craft,{dampen:true}).loss<bow.loss);});
test('real drop records its entry, then pressure settles the hull',()=>{const h=createHydro();h.initialized=true;h.y=2;h.pitch=.4;h.airborne=h.launched=true;let entry;for(let i=0;i<200;i++){const event=stepHydro(h,{...craft,vz:0,speed:0},i/60,1/60,()=>0);if(event.landing)entry=h.entry;}assert.ok(entry&&entry.loss>0);assert.ok(Math.abs(h.y-.025)<.04);});
test('spray has a moving footprint, excludes its owner, expires and freezes when paused',()=>{const f=createSprayField(),r={...craft,hydro:{y:0,wet:1,sternWet:1,pitch:0,roll:0,vy:0,waterVelocity:0}},other={...r,id:1,z:-6,hydro:{...r.hydro}};stepSprayField(f,[r,other],.06);const p=f.packets.find(p=>p.owner===0);assert.ok(sprayAt(f,p,1)>0);assert.equal(sprayAt(f,p,0),0);const held=structuredClone(f);stepSprayField(f,[r],0);assert.deepEqual(f,held);for(let i=0;i<90;i++)stepSprayField(f,[],1/60);assert.equal(sprayAt(f,p),0);});
test('spray exposure rises when a following rider crosses the jet plume',()=>{const f=createSprayField(),r={...craft,hydro:{y:0,wet:1,sternWet:1,pitch:0,roll:0,vy:0,waterVelocity:0}};stepSprayField(f,[r],.06);const p=f.packets[0],follower={...r,id:2,speed:0,x:p.x,z:p.z,hydro:{...r.hydro,y:p.y-.9}};for(let i=0;i<5;i++){follower.x=p.x;follower.z=p.z;follower.hydro.y=p.y-.9;stepSprayField(f,[follower],1/60);}assert.ok(follower.sprayExposure>.1);});
test('curled profile overturns past its uppermost point and collapses to whitewater',()=>{const face=breakerProfile(.55,.6,1),lip=breakerProfile(1,.6,1),collapsed=breakerProfile(1,.98,1);assert.ok(lip.forward>face.forward&&lip.y<face.y);assert.ok(collapsed.foam>.9&&collapsed.y<.1);});
test('wall rebound is localized and course switching clears it',()=>{setBoundaryWaves({dockOutline:[[0,0],[0,40],[20,40],[20,0]],ground:()=>-2});assert.ok(boundaryCount.value>0);assert.ok(Math.abs(boundaryHeight(1,20,.3,.5))>.001);assert.ok(Math.abs(boundaryHeight(150,150,.3,.5))<.0001);setBoundaryWaves(null);assert.equal(boundaryHeight(1,20,.3),0);});
test('sound responds to hull pressure, landing drainage and actual submersion',()=>{const m={},r={...craft,hydro:{wet:1,load:1,impact:0,landingId:0,rollVelocity:0,pitchVelocity:0}};rideSoundMix(m,r,0,0);r.hydro.load=4;r.hydro.impact=8;r.hydro.landingId=1;const hit=rideSoundMix(m,r,.6,.1);assert.ok(hit.slap>0&&hit.drain>0&&hit.rattle>0);assert.equal(hit.cutoff,620);r.hydro.load=1;let dry;for(let i=2;i<80;i++)dry=rideSoundMix(m,r,-1,i*.1);assert.ok(dry.drain<hit.drain*.01);assert.equal(dry.cutoff,18000);});
test('refraction saves pixels without changing aspect and shadow cadence is bounded',()=>{for(const q of ['high','medium','low']){const s=refractionSize(1600,900,q);assert.ok(s.width*s.height<=1600*900*.65);assert.ok(Math.abs(s.width/s.height-16/9)<.005);}assert.equal(refractionSize(1600,900,'high',2).height,360);assert.ok(shadowDue(0,'high')&&!shadowDue(1,'high'));assert.ok(!shadowDue(0,'low'));});

import * as T from '../vendor/three.module.js';import {makeWaterlineScenery} from '../waterline-detail.js';import {getCourse} from '../courses.js';
test('coastal shelves exist below water and marine shells attach only to real piling extents',()=>{const root=new T.Group(),o=new T.Mesh(new T.CylinderGeometry(.2,.2,4),new T.MeshStandardMaterial());o.position.set(2,0,3);root.add(o);const detail=makeWaterlineScenery(root,getCourse('greyhaven'),[{o,r:.2,h:4}]);assert.ok(root.userData.waterlineDetail.shelves>0);assert.ok(root.userData.waterlineDetail.barnacles>0);const shells=root.children.find(o=>o.isInstancedMesh),m=new T.Matrix4();for(let i=0;i<shells.count;i++){shells.getMatrixAt(i,m);const p=new T.Vector3().setFromMatrixPosition(m);assert.ok(p.y>=-2&&p.y<=2);assert.ok(Math.abs(Math.hypot(p.x-2,p.z-3)-.216)<1e-5);}detail.dispose();o.geometry.dispose();o.material.dispose();});

import {makeFinishingEffects} from '../finishing-effects.js';
test('landing and rival spray both create lens drops, freeze on pause, and drain away',()=>{class Element{constructor(){this.style={};this.children=[];}setAttribute(){}append(e){this.children.push(e);e.parent=this;}replaceChildren(){this.children=[];}remove(){if(this.parent)this.parent.children=this.parent.children.filter(e=>e!==this);}}const prior=globalThis.document;globalThis.document={body:new Element(),createElement:()=>new Element()};try{const fx=makeFinishingEffects(new T.Scene()),camera={x:0,y:2,z:0};fx.reset({rocks:[]});fx.sprayHit(.8);const lens=document.body.children[0];assert.ok(lens.children.length>0);fx.landing({...craft,hydro:{impact:8}},camera);fx.update(0,0,camera,'low');fx.update(.1,0,camera,'low');const held=lens.children.map(e=>({...e.style}));fx.update(.1,0,camera,'low');assert.deepEqual(lens.children.map(e=>({...e.style})),held);for(let i=2;i<25;i++)fx.update(i*.1,0,camera,'low');assert.equal(lens.children.length,0);fx.dispose();}finally{globalThis.document=prior;}});
