import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';
import {SampleSound,engineMix,SOUND_FILES} from '../sample-sound.js';
class Param{constructor(){this.value=0;}setTargetAtTime(v){this.value=v;}}
class Node{constructor(){for(const k of ['gain','frequency','pan','playbackRate'])this[k]=new Param();}connect(n){return n;}disconnect(){}start(){}stop(){this.onended?.();}}
const ctx=()=>({currentTime:0,createGain:()=>new Node(),createBufferSource:()=>new Node(),createBiquadFilter:()=>new Node(),createStereoPanner:()=>new Node(),decodeAudioData:async()=>({duration:8})});
test('shipped audio hashes match eight real ElevenLabs exports',()=>{const base=new URL('../assets/audio/',import.meta.url),m=JSON.parse(readFileSync(new URL('PROVENANCE.json',base)));assert.equal(m.provider,'ElevenLabs');assert.equal(m.exports.length,8);for(const row of m.exports){const bytes=readFileSync(new URL(row.file,base));assert.ok(bytes.length>15000);assert.equal(createHash('sha256').update(bytes).digest('hex'),row.sha256);}assert.equal(m.purchases,0);});
test('throttle raises engine pitch at a standstill, loss of intake unloads it and silences water contact',()=>{const idle=engineMix(0,1,0),rev=engineMix(0,1,1),run=engineMix(13,1,1),air=engineMix(13,0,1);assert.ok(rev.fastRate>idle.fastRate);assert.ok(run.water>.4);assert.equal(air.water,0);assert.ok(air.fastRate>=run.fastRate);});
test('sample loops load from local assets and support independent stereo engines and mono',async()=>{const bank=new SampleSound(ctx(),new Node(),new Node()),urls=[];assert.equal(await bank.load(async url=>{urls.push(url);return new ArrayBuffer(4);}),true);assert.equal(urls.length,Object.keys(SOUND_FILES).length);assert.ok(urls.every(u=>u.pathname.includes('/assets/audio/')));bank.update(3,.5,1,{speed:12,wet:1,throttle:1},.2,false,'stereo');const first=bank.loops.find(l=>l.player===0&&l.id==='fast'),second=bank.loops.find(l=>l.player===1&&l.id==='fast');assert.ok(second.source.playbackRate.value>first.source.playbackRate.value);assert.ok(first.pan.pan.value<0&&second.pan.pan.value>0);bank.update(3,.5,1,null,0,false,'mono',true);assert.equal(first.gain.gain.value,0);assert.equal(second.gain.gain.value,0);assert.ok(bank.loops.every(l=>l.pan.pan.value===0));bank.dispose();assert.equal(bank.loops.length,0);});
test('missing audio assets keep fallback usable and one shots are bounded',async()=>{const bank=new SampleSound(ctx(),new Node(),new Node());assert.equal(await bank.load(async()=>{throw Error('offline');}),false);assert.equal(bank.play('splash'),false);bank.buffers.splash={duration:3};for(let i=0;i<30;i++)bank.play('splash');assert.equal(bank.shots.size,12);bank.dispose();assert.equal(bank.shots.size,0);});
