import test from 'node:test';import assert from 'node:assert/strict';
import {initialSave,addRecord,addScore,validateSave,exportSave,importSave,replaceSave,eraseRecords,restoreRecords,readSave,cleanName} from '../race-records.js';
function populated(){const s=initialSave();s.names=['Mara Current'];s.unlocked=2;s.reached.push('amber','neon');s.settings[2]={engine:.5,grip:-.25,handling:.75};s.versus={rider:2,tune:{engine:-1},handicap:true};s.audio={mode:'headphones',music:true,volume:.6,enabled:true};s.preferences={graphics:'medium',laps:5,seaState:'storm'};addRecord(s,{course:'amber',time:120,bestLap:35,rider:2,initials:'JRB',custom:true});addScore(s,{course:'neon',score:6500,rider:1,initials:'JET'});return s;}
test('portable saves round-trip names, tuning, both record types, unlocks and preferences',()=>{const original=populated(),candidate=importSave(exportSave(original));assert.deepEqual(candidate,original);let data;const storage={setItem:(k,v)=>data=v,getItem:()=>data};const target=initialSave();replaceSave(target,candidate,storage);assert.deepEqual(readSave(storage),original);assert.deepEqual(target,original);});
test('invalid imports cannot partially overwrite progress, including nested records and prototype keys',()=>{const original=populated();for(const mutate of [s=>s.unlocked=99,s=>s.settings[0]={engine:Infinity},s=>s.records['amber/0/3'].times[0].rider=8,s=>s.records['amber/0/3'].times[0].bestLap=999,s=>s.scores['neon/0'][0].score=-2,s=>s.audio.volume=-1,s=>s.reached=['imaginary'],s=>s.settings=JSON.parse('{"__proto__":{"polluted":true}}')]){const bad=structuredClone(original);mutate(bad);const target=structuredClone(original);assert.throws(()=>replaceSave(target,bad,{setItem(){throw Error('should not write invalid data');}}));assert.deepEqual(target,original);}assert.equal({}.polluted,undefined);assert.throws(()=>importSave('{broken'));assert.throws(()=>importSave('x'.repeat(300001)));assert.throws(()=>importSave('{"version":1,"data":{}}'));});
test('storage failure keeps the live save, and legacy version-one data gains defaults',()=>{const target=populated(),before=structuredClone(target);assert.throws(()=>replaceSave(target,initialSave(),{setItem(){throw Error('quota');}}),/Existing progress was kept/);assert.deepEqual(target,before);const old={version:1,records:{},settings:{0:{engine:0}},unlocked:1};const migrated=validateSave(old);assert.equal(migrated.audio.music,false);assert.equal(migrated.unlocked,1);assert.deepEqual(migrated.settings,old.settings);});
test('erasing a selected record scope preserves other records and can be undone',()=>{const s=populated(),before=structuredClone(s),undo=eraseRecords(s,{course:'amber',kind:'time'});assert.equal(s.records['amber/0/3'],undefined);assert.deepEqual(s.scores,before.scores);assert.deepEqual(s.settings,before.settings);restoreRecords(s,undo);assert.deepEqual(s,before);const scores=eraseRecords(s,{course:'neon',kind:'score'});assert.deepEqual(s.records,before.records);restoreRecords(s,scores);assert.deepEqual(s,before);});
test('rider names remain readable, bounded plain text',()=>{assert.equal(cleanName('  Skipper <Jet>\n '),'Skipper Jet');assert.equal(cleanName('A'.repeat(60)).length,20);});
test('undoing an erase retains new records earned afterward',()=>{const s=populated(),undo=eraseRecords(s,{course:'amber'});addRecord(s,{course:'amber',rider:0,initials:'NEW',time:110,bestLap:33});restoreRecords(s,undo);assert.deepEqual(s.records['amber/0/3'].times.map(r=>r.time),[110,120]);assert.equal(s.records['amber/0/3'].lap.bestLap,33);const scoreUndo=eraseRecords(s,{course:'neon',kind:'score'});addScore(s,{course:'neon',score:7000,rider:2,initials:'NEW'});restoreRecords(s,scoreUndo);assert.deepEqual(s.scores['neon/0'].map(r=>r.score),[7000,6500]);});
