import test from 'node:test';import assert from 'node:assert/strict';
import {createState,step,context,loadWeight,finish,wave,ground,JOBS} from '../simulation.js';
import {pilot,voyage} from '../verification.js';
const running=()=>({...createState(),mode:'playing'});
function run(s,input,seconds){for(let t=0;t<seconds;t+=1/60)step(s,input,1/60);}
test('complete voyage uses ordinary controls for departure, three recoveries, two deliveries',()=>{const s=running();let index=0;for(let n=0;n<480*60&&s.mode==='playing';n++){const p=pilot(s,voyage,index);index=p.index;step(s,p.input,1/60);}console.log('Voyage result',JSON.stringify({mode:s.mode,time:s.time,hull:s.hull,delivered:s.delivered,index,x:s.x,z:s.z}));assert.equal(s.mode,'success');assert.equal(s.delivered.length,3);assert.ok(s.time>300&&s.time<480);assert.ok(s.hull>30);});
test('loaded hull is slower and cargo capacity blocks a fourth unit',()=>{const light=running(),heavy=running();light.z=heavy.z=90;heavy.load=[0,1];heavy.jobs[0].status=heavy.jobs[1].status='aboard';run(light,{throttle:1},10);run(heavy,{throttle:1},10);assert.ok(heavy.speed<light.speed*.8);heavy.x=JOBS[2].x;heavy.z=JOBS[2].z;heavy.speed=0;assert.equal(context(heavy).type,'full');assert.equal(loadWeight(heavy),3);});
test('salvage requires proximity, low speed and sustained interaction',()=>{const s=running();run(s,{interact:true},24);assert.equal(s.load.length,0);s.x=JOBS[0].x;s.z=JOBS[0].z;s.speed=3;assert.equal(context(s).type,'slow');s.speed=0;run(s,{interact:true},10);assert.equal(s.load.length,0);run(s,{interact:true},13);assert.deepEqual(s.load,[0]);});
test('partial haul can finish only after successful delivery',()=>{const s=running();s.load=[0];s.jobs[0].status='aboard';finish(s);assert.equal(s.mode,'playing');run(s,{interact:true},3.2);assert.deepEqual(s.delivered,[0]);finish(s);assert.equal(s.mode,'success');});
test('collision destroys hull, deadline fails, restart resets every mission field',()=>{const s=running();s.x=-72;s.z=28;s.heading=-Math.PI/2;s.hull=8;s.speed=4;run(s,{throttle:1},3);assert.equal(s.mode,'failure');const timed=running();timed.z=60;timed.time=479.9;run(timed,{},1);assert.equal(timed.mode,'failure');const reset=createState();assert.equal(reset.hull,100);assert.equal(reset.time,0);assert.equal(reset.load.length,0);assert.ok(reset.jobs.every(j=>j.progress===0&&j.status==='waiting'));});
test('pause freezes simulation and shared waves remain finite through storm',()=>{const s=running();s.mode='paused';run(s,{throttle:1},10);assert.equal(s.time,0);assert.equal(s.z,139);for(const storm of[0,.5,1])for(let t=0;t<100;t++)assert.ok(Number.isFinite(wave(32,-59,t,storm)));for(const j of JOBS)assert.ok(ground(j.x,j.z)<-.85);});
