import test from 'node:test';
import assert from 'node:assert/strict';
import {frameElapsed} from '../frame-clock.js';
import {surfHeight,surfStrength} from '../surf-waves.js';
import {displacedSurface,sampleSwell} from '../wave-model.js';
import {createDemoScene,demoInput,demoSceneDone} from '../demo-driver.js';
import {stepRace,createRace} from '../race-core.js';
import {stepRaceFlip} from '../race-flips.js';
import {createState} from '../simulation.js';
import {initialSave,validateSave} from '../race-records.js';
test('10 fps and 2 fps advance real race seconds instead of slow motion',()=>{for(const fps of [60,30,10,2,1]){let elapsed=0;for(let i=0;i<fps*5;i++)elapsed+=frameElapsed(1/fps);assert.ok(Math.abs(elapsed-5)<1e-8);}assert.equal(frameElapsed(60),1);assert.equal(frameElapsed(NaN),0);});
test('Big Surf adds metre-scale waves using identical render and hull heights',()=>{surfStrength.value=1;let min=Infinity,max=-Infinity;for(let x=-80;x<80;x+=3)for(let z=-80;z<80;z+=5){const h=surfHeight(x,z,4),p=displacedSurface(x,z,4,.3);min=Math.min(min,h);max=Math.max(max,h);assert.ok(Math.abs(sampleSwell(p.x,p.z,4,.3)-p.y)<.01);}assert.ok(max-min>4);createRace();assert.equal(surfStrength.value,0);createRace({seaState:'surf'});createState();assert.equal(surfStrength.value,0);});
test('all four demo riders really jump and finish clean wave flips',()=>{const s=createDemoScene(),peaks=s.racers.map(()=>0);while(!demoSceneDone(s)){stepRace(s,demoInput(s),1/60);s.racers.forEach((r,i)=>peaks[i]=Math.max(peaks[i],r.hydro.y-r.hydro.waterHeight));}assert.ok(s.racers[0].lap>1);for(let i=0;i<4;i++){assert.ok(peaks[i]>2);assert.ok(s.racers[i].stunt.tricks>0);assert.equal(s.racers[i].stunt.crashes,0);}});
test('flips require a request and a short failed flip penalizes landing',()=>{const r=createRace().racers[0];r.hydro.airborne=true;r.hydro.landingId=0;for(let i=0;i<40;i++)stepRaceFlip(r,{},1/60);assert.equal(r.stunt.trick,null);stepRaceFlip(r,{trick:'flip'},1/60);r.hydro.airborne=false;r.hydro.landingId=1;r.vx=20;stepRaceFlip(r,{},1/60);assert.equal(r.stunt.crashes,1);assert.ok(r.vx<20);assert.equal(r.stunt.trick,null);});
test('Big Surf is the new default and survives saved preferences',()=>{const s=initialSave();assert.equal(s.preferences.seaState,'surf');assert.equal(validateSave(s).preferences.seaState,'surf');});
