import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
const context=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});globalThis.document={createElement:()=>({width:0,height:0,setAttribute(){},getContext:()=>context})};globalThis.localStorage={getItem:()=>null,setItem(){}};
const source=readFileSync(new URL('../src/DefenderShow.ts',import.meta.url),'utf8').replace("'./game'",JSON.stringify(new URL('../src/game.ts',import.meta.url).href)).replaceAll("'./DefenderSound'",JSON.stringify(new URL('../src/DefenderSound.ts',import.meta.url).href));const {DefenderShow}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const make=()=>{const g=new DefenderShow();g.draw=()=>{};return g};
test('autonomous display fights, rescues and loops with bounded entities without player input',()=>{const g=make();for(let i=0;i<120*60;i++)g.update(1/60);assert(g.kills>20);assert(g.rescued>=4);assert(g.wave>1);assert(g.foes.length<=38);assert(g.sparks.length<300);assert(g.lasers.length<10);assert(g.x>=0&&g.x<g.world)});
test('pause and cabinet power freeze autonomous state and resume cleanly',()=>{const g=make();g.update(.03);const x=g.x,t=g.time;g.demoPaused=true;g.update(.03);assert.equal(g.x,x);assert.equal(g.time,t);g.demoPaused=false;g.power=false;g.update(.03);assert.equal(g.x,x);g.power=true;g.update(.03);assert.notEqual(g.x,x)});

test('lander pickup, laser release, falling catch and delivery happen in order on screen',()=>{const g=make(),phases=[];let humanIndex=-1,pickupPosition=0;for(let i=0;i<30*60;i++){g.update(1/60);const r=g.mission;if(r){if(phases.at(-1)!==r.phase)phases.push(r.phase);if(humanIndex<0){humanIndex=r.humanIndex;pickupPosition=g.demoHumans[humanIndex]}const screenX=g.wrap(r.x-g.cameraX);assert(screenX>=0&&screenX<=960,'human stays inside CRT viewport');if(r.phase==='fall')assert.equal(r.lander.alive,false,'fall begins only after lander is shot');if(r.phase==='return')assert.equal(g.carrying,true);}if(g.rescueEvents.delivered)break;}assert.deepEqual(phases,['descend','lift','intercept','fall','return']);assert.deepEqual(g.rescueEvents,{pickedUp:1,dropped:1,caught:1,delivered:1});assert.equal(g.demoHumans.length,24);assert.equal(g.carrying,false);assert.notEqual(g.demoHumans[humanIndex],pickupPosition,'same human is set down at the landing location');});
test('power pauses a falling humanoid and resumes the rescue without losing it',()=>{const g=make();for(let i=0;i<1200&&g.mission?.phase!=='fall';i++)g.update(1/60);assert.equal(g.mission?.phase,'fall');const y=g.mission.y;g.power=false;for(let i=0;i<100;i++)g.update(.03);assert.equal(g.mission.y,y);g.power=true;for(let i=0;i<600&&!g.rescueEvents.delivered;i++)g.update(1/60);assert.equal(g.rescueEvents.caught,1);assert.equal(g.rescueEvents.delivered,1)});

test('pods release swarmers on a laser hit and bombers leave persistent mines',()=>{const g=make();g.nextRescue=Infinity;g.foes=[{x:g.x+110,y:g.y,kind:3,phase:0,alive:true}];g.lasers=[{x:g.x+110,y:g.y,dir:1,life:.5}];g.update(.001);assert.equal(g.foes.filter(e=>e.kind===4).length,4);assert.equal(g.score,1000);g.foes=[{x:g.x+500,y:200,kind:2,phase:0,alive:true,cooldown:0}];g.update(.02);assert.equal(g.mines.length,1);const mine=g.mines[0];g.update(.02);assert.equal(g.mines[0].x,mine.x);});
test('a wave advances only after enemies clear, and prolonged patrol stays bounded',()=>{const g=make();g.nextRescue=Infinity;const wave=g.wave;g.kills=100;g.update(.01);assert.equal(g.wave,wave);g.foes=[];g.update(.01);assert.equal(g.wave,wave+1);for(let i=0;i<600*60;i++){g.update(1/60);assert(g.foes.length<=38);assert(g.mines.length<=45);assert(g.charges.length<=40);}assert.equal(g.canvas.width,294);assert.equal(g.canvas.height,240);});

test('ship cannot collect a grounded human, including a fall that has reached terrain',()=>{const g=make();g.nextRescue=Infinity;const hx=g.demoHumans[0];g.x=hx;g.y=g.groundY(hx)-30;g.update(.01);assert.equal(g.carrying,false);assert.equal(g.rescueEvents.caught,0);g.mission={lander:{x:hx,y:200,kind:0,phase:0,alive:false},humanIndex:0,x:hx,y:g.groundY(hx)-15,vy:100,phase:'fall',age:1,dir:1};g.x=hx;g.y=g.groundY(hx)-33;g.updateRescue(.016);assert.equal(g.carrying,false);assert.equal(g.rescueEvents.caught,0);assert.equal(g.mission,undefined);});
