import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';
const context=new Proxy({createRadialGradient:()=>({addColorStop(){}}),createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});globalThis.document={createElement:()=>({width:0,height:0,setAttribute(){},getContext:()=>context})};globalThis.localStorage={getItem:()=>null,setItem(){}};
const source=readFileSync(new URL('../src/DefenderShow.ts',import.meta.url),'utf8').replace("'./game'",JSON.stringify(new URL('../src/game.ts',import.meta.url).href)).replaceAll("'./DefenderSprites'",JSON.stringify(new URL('../src/DefenderSprites.ts',import.meta.url).href)).replaceAll("'./DefenderPilot'",JSON.stringify(new URL('../src/DefenderPilot.ts',import.meta.url).href)).replaceAll("'./DefenderFont'",JSON.stringify(new URL('../src/DefenderFont.ts',import.meta.url).href)).replaceAll("'./DefenderSound'",JSON.stringify(new URL('../src/DefenderSound.ts',import.meta.url).href));const {DefenderShow}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));
const make=()=>{const g=new DefenderShow();g.draw=()=>{};return g};
const foe=(x,y,kind=0,extra={})=>({x,y,kind,alive:true,phase:0,spawn:0,cooldown:100,...extra});
test('unattended pilot fights, rescues, progresses and preserves unique human states',()=>{
 const g=make();let maxWave=1;
 for(let i=0;i<600*60;i++){g.update(1/60);maxWave=Math.max(maxWave,g.wave);assert(g.foes.length<=64);assert(g.sparks.length<=640);assert(g.mines.length<=45);assert(g.charges.length<=40);assert(g.lasers.length<10);assert(Number.isFinite(g.x)&&Number.isFinite(g.y));
  const humans=[...g.deadHumans,...g.carriedHumans,...g.looseHumans.map(h=>h.index),...g.foes.filter(e=>e.alive&&e.captive!==undefined).map(e=>e.captive)];assert.equal(new Set(humans).size,humans.length,'human cannot occupy two states');}
 assert(g.kills>100);assert(g.rescued>10);assert(maxWave>4);assert(g.bombsUsed>0);assert(g.deaths>0);assert.equal(g.canvas.width,294);
});
test('pause and power freeze flight, falling humans and spawn clocks',()=>{const g=make();g.looseHumans=[{x:g.x,y:400,vy:80,index:1}];g.demoPaused=true;const snapshot=JSON.stringify([g.x,g.time,g.squadClock,g.looseHumans]);g.update(.04);assert.equal(JSON.stringify([g.x,g.time,g.squadClock,g.looseHumans]),snapshot);g.demoPaused=false;g.power=false;g.update(.04);assert.equal(JSON.stringify([g.x,g.time,g.squadClock,g.looseHumans]),snapshot);g.power=true;g.update(.04);assert(g.time>0);});
test('squads spawn five at a time and reserves prevent premature wave completion',()=>{const g=make();assert.equal(g.foes.length,5);assert.equal(g.landerReserve,10);g.foes=[];g.updateSpawns(.01);assert.equal(g.foes.length,5);assert.equal(g.landerReserve,5);assert.equal(g.stage,'battle');});
test('ordinary lander grabs an available human and mutates at the ceiling',()=>{const g=make();g.foes=[foe(g.demoHumans[0],g.groundY(g.demoHumans[0])-39)];g.updateEnemies(.01);assert.equal(g.foes[0].captive,0);g.foes[0].y=121;g.updateEnemies(.04);assert.equal(g.foes[0].kind,1);assert(g.deadHumans.has(0));});
test('destroying a carrier releases its human and destroying an empty lander does not',()=>{const g=make(),e=foe(1000,300,0,{captive:2});g.foes=[e];g.killFoe(e);assert.equal(g.looseHumans[0].index,2);assert.equal(g.looseHumans[0].y,324);g.killFoe(foe(1200,300));assert.equal(g.looseHumans.length,1);});
test('multiple falling humans can be caught and delivered with separate scoring',()=>{const g=make();g.foes=[];g.x=1000;g.y=400;g.looseHumans=[{x:995,y:420,vy:50,index:0},{x:1005,y:420,vy:50,index:1}];g.updateHumans(.01);assert.deepEqual(g.carriedHumans,[0,1]);assert.equal(g.score,1000);assert.equal(g.maxCarried,2);assert.equal(g.looseHumans.length,0);g.y=g.groundY(g.x)-30;g.updateHumans(.01);assert.equal(g.rescued,2);assert.equal(g.score,2000);assert.equal(g.carriedHumans.length,0);assert.notEqual(g.demoHumans[0],g.demoHumans[1]);});
test('ground contacts resolve before catches; gentle falls land and hard falls die',()=>{const g=make();g.foes=[];g.x=1000;g.y=g.groundY(g.x)-30;g.looseHumans=[{x:1000,y:g.groundY(1000)-15,vy:150,index:0},{x:1004,y:g.groundY(1004)-15,vy:20,index:1}];g.updateHumans(.01);assert.equal(g.carriedHumans.length,0);assert(g.deadHumans.has(0));assert(!g.deadHumans.has(1));assert.equal(g.score,250);assert.equal(g.demoHumans[1],1004);g.updateHumans(.01);assert.equal(g.carriedHumans.length,0);});
test('ship death drops passengers without deleting unrelated humans',()=>{const g=make();g.carriedHumans=[2,3];g.carrying=true;g.loseShip();assert.equal(g.lives,2);assert.equal(g.stage,'death');assert.deepEqual(g.looseHumans.map(h=>h.index),[2,3]);assert.equal(g.deadHumans.size,0);g.advanceStage(2);assert.equal(g.stage,'battle');assert.equal(g.looseHumans.length,2);});
test('pods split into four red swarmers; bombers leave stationary mines',()=>{const g=make();g.foes=[foe(800,250,3)];g.killFoe(g.foes[0]);assert.equal(g.foes.filter(e=>e.kind===4).length,4);assert.equal(g.score,1000);g.foes=[foe(2000,200,2,{cooldown:0})];g.updateEnemies(.02);assert.equal(g.mines.length,1);const x=g.mines[0].x;g.updateEnemies(.02);assert.equal(g.mines[0].x,x);});
test('smart bombs have finite stock and a visible-area blast including pod children',()=>{const g=make();g.cameraX=0;g.foes=[foe(400,200,3),foe(2000,200)];g.smartBomb();assert.equal(g.bombs,2);assert(g.foes.filter(e=>e.x<900).every(e=>!e.alive));assert(g.foes.find(e=>e.x===2000).alive);const score=g.score;g.smartBomb();assert.equal(g.score,score);g.bombs=0;g.bombClock=0;g.smartBomb();assert.equal(g.bombs,0);});
test('extra ship/bomb thresholds award once and game over restarts without user input',()=>{const g=make();g.score=25000;g.awardExtra();assert.equal(g.lives,5);assert.equal(g.bombs,5);g.awardExtra();assert.equal(g.lives,5);g.lives=1;g.loseShip();g.advanceStage(5);assert.equal(g.score,0);assert.equal(g.lives,3);assert.equal(g.wave,1);});
test('survivor bonus scales and the fifth wave restores the planet',()=>{const g=make();g.wave=4;g.deadHumans=new Set([0,1]);g.completeWave();assert.equal(g.waveBonus,3200);g.advanceStage(4);assert.equal(g.wave,5);assert.equal(g.deadHumans.size,0);assert(g.planet);g.deadHumans=new Set(Array.from({length:10},(_,i)=>i));g.checkPlanet();assert(!g.planet);assert(g.foes.every(e=>e.kind!==0));assert(g.foes.some(e=>e.kind===1));});
test('momentum brakes through reversal and swept lasers select the closest wrapped target',()=>{const g=make();g.velocityX=245;g.fly(-245,.04);assert(g.velocityX>0);for(let i=0;i<30;i++)g.fly(-245,.04);assert(g.velocityX<0);const near=foe(8,250),far=foe(30,250);g.foes=[far,near];g.fireLaser({x:4780,y:250,dir:1,life:.8},.04);assert(!near.alive);assert(far.alive);});
test('scanner follows multiple carried humans and excludes lost humans',()=>{const g=make();g.carriedHumans=[0,1];g.x=1000;g.y=400;assert.equal(g.humanPosition(0).y,420);assert.notEqual(g.humanPosition(0).x,g.humanPosition(1).x);g.deadHumans.add(2);assert.equal(g.humanPosition(2),undefined);});
test('reactive pilot can collect two nearby falls and deliver both without scripted phases',()=>{const g=make();g.foes=[foe(3500,200,2)];g.landerReserve=0;g.invincible=100;g.x=1000;g.y=380;g.looseHumans=[{x:1100,y:410,vy:40,index:0},{x:1120,y:410,vy:40,index:1}];for(let i=0;i<600&&g.rescued<2;i++)g.update(1/60);assert.equal(g.maxCarried,2);assert.equal(g.rescued,2);});
