import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {stripTypeScriptTypes} from 'node:module';import {createHash} from 'node:crypto';import {buildDetailedCabinet} from '../model-detail.mjs';import {robotronLayouts} from '../robotron-layout.mjs';
const ctx=new Proxy({},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});globalThis.document={createElement:()=>({width:0,height:0,setAttribute(){},getContext:()=>ctx})};globalThis.localStorage={getItem:()=>null,setItem(){}};
let source=readFileSync(new URL('../src/RobotronShow.ts',import.meta.url),'utf8');for(const module of ['game','RobotronSprites','DefenderFont','RobotronSound'])source=source.replaceAll(`'./${module}'`,JSON.stringify(new URL(`../src/${module}.ts`,import.meta.url).href));const {RobotronShow}=await import('data:text/javascript;base64,'+Buffer.from(stripTypeScriptTypes(source)).toString('base64'));const make=()=>{const g=new RobotronShow();g.draw=()=>{};return g;};
test('Robotron pilot rescues, shoots independently, progresses and remains bounded',()=>{const g=make();let maxWave=1,independent=false;for(let i=0;i<360*60;i++){g.update(1/60);maxWave=Math.max(maxWave,g.wave);independent||=g.aim[0]!==g.move[0]||g.aim[1]!==g.move[1];assert(g.actors.length<=92);assert(g.shots.length<100);assert(Number.isFinite(g.x)&&g.x>=9&&g.x<=283);assert(g.y>=34&&g.y<=230);}console.log({kills:g.kills,rescues:g.rescued,maxWave});assert(g.kills>30);assert(g.rescued>0);assert(maxWave>=2);assert(independent);});
test('Robotron pause and power freeze simulation',()=>{const g=make();g.demoPaused=true;const state=JSON.stringify([g.time,g.actors,g.x,g.y]);g.update(.04);assert.equal(JSON.stringify([g.time,g.actors,g.x,g.y]),state);g.demoPaused=false;g.power=false;g.update(.04);assert.equal(JSON.stringify([g.time,g.actors,g.x,g.y]),state);});
test('Robotron hulk survives shots, brain converts humans, generators spawn enemies',()=>{const g=make();g.phase='battle';g.invincible=100;g.actors=[];g.people=[];g.add('hulk',70,70);g.add('grunt',270,200);g.shots=[{x:70,y:70,vx:0,vy:0,hostile:false,life:1}];g.update(.01);assert(g.actors.some(a=>a.kind==='hulk'));g.add('brain',100,100);g.people=[{x:100,y:100,kind:0,alive:true}];g.update(.01);assert.equal(g.people[0].alive,false);assert(g.actors.some(a=>a.kind==='prog'));g.add('spheroid',40,50);g.actors.at(-1).timer=0;g.update(.01);assert(g.actors.some(a=>a.kind==='enforcer'));});
test('Robotron model has independent sticks, exactly two start caps and twelve ROM sockets',()=>{const root=buildDetailedCabinet(true);assert(root.getObjectByName('joystick'));assert(root.getObjectByName('joystick_fire'));const buttons=[];root.traverse(o=>{if(/^button_/.test(o.name))buttons.push(o.name);});assert.deepEqual(buttons.sort(),['button_5','button_6']);assert.equal(robotronLayouts.rom.chips.filter(c=>c.family.startsWith('ROM ')&&!c.empty).length,12);assert.equal(robotronLayouts.cpu.chips.filter(c=>c.family==='SC1 BLITTER').length,2);});
test('all sixteen original Robotron effects match manifests and contain PCM sound',()=>{const dir=new URL('../public/robotron/audio/',import.meta.url),manifest=JSON.parse(readFileSync(new URL('manifest.json',dir),'utf8'));assert.equal(manifest.sha1,'15afefef11bfc3ab78f61ab046701db78d160ec3');assert.equal(Object.keys(manifest.effects).length,16);for(const [name,e]of Object.entries(manifest.effects)){const b=readFileSync(new URL(name+'.wav',dir));assert.equal(createHash('sha256').update(b).digest('hex'),e.sha256);let pcm;for(let i=12;i+8<b.length;){const size=b.readUInt32LE(i+4);if(b.toString('ascii',i,i+4)==='data')pcm=b.subarray(i+8,i+8+size);i+=8+size+(size%2);}assert(pcm);let sum=0;for(let i=0;i<pcm.length;i+=2)sum+=(pcm.readInt16LE(i)/32768)**2;assert(Math.sqrt(sum/(pcm.length/2))>.005,name+' must contain audio');}});


test('Robotron slow-frame substeps preserve speed and reject invalid deltas',()=>{const g=make();const before=g.time;g.update(.5);assert(Math.abs(g.time-before-.5)<1e-8);const t=g.time;g.update(NaN);g.update(-1);assert.equal(g.time,t);});
