import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
const $=id=>document.getElementById(id), parts=[], pickables=[];let seed=937;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});}catch(e){$('loading').remove();$('error').hidden=false;throw e}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.78;$('scene').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#111b21');scene.fog=new T.Fog('#111b21',24,65);
const camera=new T.PerspectiveCamera(37,innerWidth/innerHeight,.05,100);const mobile=()=>innerWidth<900;camera.position.set(9,5.7,10.5);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=4;controls.maxDistance=32;controls.target.set(0,.3,0);controls.autoRotateSpeed=.65;
const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(new RoomEnvironment(),.04);scene.environment=env.texture;scene.environmentIntensity=.65;pmrem.dispose();
scene.add(new T.HemisphereLight(0xe9f4ff,0x373327,.65));function light(color,intensity,pos,size){const l=new T.DirectionalLight(color,intensity);l.position.set(...pos);scene.add(l);if(size){l.castShadow=true;l.shadow.mapSize.set(2048,2048);Object.assign(l.shadow.camera,{left:-14,right:14,top:14,bottom:-14});l.shadow.bias=-.0004;}return l;}light(0xffe4ad,2,[5,9,7],true);light(0x88cfff,1.25,[-7,4,-5]);light(0xffffff,1.4,[1,3,-8]);
const mat={gold:new T.MeshPhysicalMaterial({color:0xe4a615,metalness:.82,roughness:.27,clearcoat:.7,clearcoatRoughness:.21}),edge:new T.MeshStandardMaterial({color:0xeed38b,metalness:.95,roughness:.22}),steel:new T.MeshStandardMaterial({color:0xa2b4c0,metalness:1,roughness:.24}),dark:new T.MeshStandardMaterial({color:0x172025,metalness:.86,roughness:.34}),rubber:new T.MeshStandardMaterial({color:0x070b0d,roughness:.8}),copper:new T.MeshStandardMaterial({color:0xaa6036,metalness:.9,roughness:.25}),cyan:new T.MeshStandardMaterial({color:0x20caff,emissive:0x009fff,emissiveIntensity:3,metalness:.35,roughness:.18}),glass:new T.MeshPhysicalMaterial({color:0x9dced9,metalness:.2,roughness:.12,transparent:true,opacity:.2,side:T.DoubleSide,depthWrite:false,clearcoat:1}),optic:new T.MeshPhysicalMaterial({color:0x07151e,metalness:.75,roughness:.13,clearcoat:1}),fur:new T.MeshStandardMaterial({color:0x875807,roughness:.94,side:T.DoubleSide}),blackfur:new T.MeshStandardMaterial({color:0x0a0d0e,roughness:.9,side:T.DoubleSide})};
const v=(x,y,z)=>new T.Vector3(x,y,z);const geo={sphere:new T.SphereGeometry(1,40,28),small:new T.SphereGeometry(1,16,10),cyl:new T.CylinderGeometry(1,1,1,24),bolt:new T.CylinderGeometry(1,1,1,6),box:new T.BoxGeometry(1,1,1)};
const model=new T.Group();model.position.y=.35;scene.add(model);
function part(name,system,pos,offset,desc){const g=new T.Group();g.position.set(...pos);model.add(g);const p={id:parts.length,name,system,desc:desc||`${name}. Individually modeled ${system.toLowerCase()} component in the APX-9 robotic pollination system.`,group:g,base:g.position.clone(),offset:v(...offset),meshes:[]};g.userData.part=p;parts.push(p);return p;}
function mesh(p,geometry,material,pos=[0,0,0],scale=[1,1,1],rotation=[0,0,0]){const m=new T.Mesh(geometry,material);m.position.set(...pos);m.scale.set(...scale);m.rotation.set(...rotation);m.castShadow=true;m.receiveShadow=true;m.userData.part=p;p.group.add(m);p.meshes.push(m);pickables.push(m);return m;}
function ball(p,pos,scale,material=mat.steel){return mesh(p,geo.sphere,material,pos,scale)}
function rod(p,a,b,r,material=mat.steel){a=v(...a);b=v(...b);const m=mesh(p,geo.cyl,material,a.clone().add(b).multiplyScalar(.5).toArray(),[r,a.distanceTo(b),r]);m.quaternion.setFromUnitVectors(v(0,1,0),b.sub(a).normalize());return m;}
function torus(p,pos,r,t,material=mat.steel,rotation=[0,0,Math.PI/2]){return mesh(p,new T.TorusGeometry(r,t,10,48),material,pos,[1,1,1],rotation)}
function bolt(p,pos,r=.047){mesh(p,geo.bolt,mat.steel,pos,[r,.055,r]);mesh(p,geo.box,mat.dark,[pos[0],pos[1]+.031,pos[2]],[r*1.05,.008,.012]);}
function ring(name,x,r,material,offset=[-2,0,0]){const p=part(name,'Power system',[x,0,0],offset);torus(p,[0,0,0],r,.07,material);for(let j=0;j<12;j++){const a=j*Math.PI/6;ball(p,[0,Math.sin(a)*r,Math.cos(a)*r],[.04,.04,.04]);}return p;}
function shell(name,pos,scale,offset,material=mat.gold,rotation=[0,0,0],phi=0,len=Math.PI*2,theta=0,tlen=Math.PI){const p=part(name,'Body armor',pos,offset,'Impact-resistant composite armor with titanium edge reinforcement, maintenance fasteners and a biomimetic surface.');mesh(p,new T.SphereGeometry(1,48,32,phi,len,theta,tlen),material,[0,0,0],scale,rotation);return p;}
function fur(p,center,scale,n,black=false){const points=[],normals=[];for(let i=0;i<n;i++){const u=random()*Math.PI*2,z=random()*2-1,s=Math.sqrt(1-z*z),normal=v(s*Math.cos(u),z,s*Math.sin(u));const b=v(normal.x*scale[0],normal.y*scale[1],normal.z*scale[2]).add(v(...center));const len=.04+random()*.12;const tip=b.clone().add(normal.multiplyScalar(len));const tangent=v(-Math.sin(u),0,Math.cos(u)).multiplyScalar(.005);points.push(...b.clone().sub(tangent).toArray(),...b.clone().add(tangent).toArray(),...tip.toArray());}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(points,3));g.computeVertexNormals();mesh(p,g,black?mat.blackfur:mat.fur);}
// Longitudinal segmented abdomen; each casing and internal collar separates independently.
for(let i=0;i<5;i++){const x=-1.1-i*.37,r=.9-Math.pow(i/5,2)*.45;const p=shell(`Abdomen armor band ${i+1}`,[x,-.1,0],[.32,r,r*.85],[-1.7-i*.24,(i%2?-.5:.4),0],i%2?mat.dark:mat.gold);if(i%2===0)fur(p,[0,0,0],[.325,r+.01,r*.85+.01],1600);torus(p,[.23,0,0],r*.78,.035,mat.steel);for(let j=0;j<8;j++){const a=j*Math.PI/4;ball(p,[.21,Math.sin(a)*r*.9,Math.cos(a)*r*.75],[.035,.035,.035]);}}
const tail=part('Rear stabilizer / probe','Sensors',[-2.96,-.13,0],[-3,-.5,0]);rod(tail,[0,0,0],[-.6,-.12,0],.07,mat.dark);rod(tail,[-.6,-.12,0],[-.86,-.18,0],.025);for(let i=0;i<3;i++)torus(tail,[-i*.13,0,0],.17,.025,mat.gold);
const core=part('Solid-state micro-battery','Power system',[-1.55,0,0],[-.7,0,2.1],'Cylindrical energy cartridge with illuminated charge channels, copper conductors and a thermally isolated central stack.');rod(core,[-.75,0,0],[.75,0,0],.43,mat.dark);for(let j=0;j<10;j++){const a=j*Math.PI/5;rod(core,[-.6,Math.sin(a)*.45,Math.cos(a)*.45],[.6,Math.sin(a)*.45,Math.cos(a)*.45],.035,mat.cyan);}for(let i=0;i<5;i++)ring(`Battery thermal collar ${i+1}`,-2.2+i*.3,.48,i%2?mat.copper:mat.steel,[-1,0,2.5]);
const chassis=part('Thoracic titanium chassis','Internal mechanisms',[0,0,0],[0,-.5,0]);ball(chassis,[0,0,0],[.95,.73,.72],mat.dark);for(let x=-.6;x<=.6;x+=.3){torus(chassis,[x,0,0],.68,.045);for(let s of [-1,1])rod(chassis,[x,-.35,s*.5],[x,.5,s*.47],.035);}for(let s of [-1,1]){for(let i=0;i<4;i++)rod(chassis,[-.7+i*.35,-.15,s*.6],[-.6+i*.35,.35,s*.6],.04,mat.copper);}
const thorax=shell('Biomimetic thorax mantle',[0,.18,0],[1.03,.98,.89],[0,2.1,0],mat.gold,[0,0,0],0,Math.PI*2,0,Math.PI*.61);fur(thorax,[0,0,0],[1.04,.99,.9],12000);const crown=shell('Thorax dorsal service hatch',[0,.95,0],[.7,.15,.58],[0,3.1,0],mat.gold);for(let x of [-.42,0,.42])for(let s of [-1,1])bolt(crown,[x,.11,s*.34]);for(let i=0;i<6;i++)mesh(crown,geo.box,mat.dark,[-.35+i*.14,.14,0],[.065,.035,.36]);
const brain=part('Navigation neural processor','Sensors',[.45,.25,0],[.6,1.4,0]);mesh(brain,geo.box,mat.dark,[0,0,0],[.58,.2,.5]);for(let i=0;i<10;i++)for(let s of [-1,1])mesh(brain,geo.box,mat.edge,[-.24+i*.052,.02,s*.3],[.025,.06,.11]);mesh(brain,geo.box,mat.steel,[0,.13,0],[.4,.04,.34]);
const neck=part('Head gimbal / yaw bearing','Actuators',[.97,.08,0],[1.2,0,0]);rod(neck,[-.2,0,0],[.3,0,0],.34,mat.dark);for(let x of [-.1,.12,.25])torus(neck,[x,0,0],.37,.065,mat.steel);
const head=shell('Head shell / sensor housing',[1.5,.05,0],[.65,.68,.64],[2.2,.2,0],mat.gold);for(let s of [-1,1]){const p=part(`${s>0?'Right':'Left'} compound optical array`,'Optics',[1.71,.13,s*.51],[2.4,.3,s*1.4],'Convex hexagonal compound-eye array with individual dark optical facets, a machined gold bezel and perimeter fasteners.');ball(p,[0,0,0],[.46,.57,.19],mat.dark);const rim=torus(p,[0,0,0],.49,.055,mat.gold,[0,0,0]);rim.scale.set(.85,1.12,1);for(let j=0;j<17;j++)for(let k=0;k<15;k++){const yy=(j-8)*.061,xx=(k-7)*.064+(j%2)*.032;const q=xx*xx/.16+yy*yy/.28;if(q>.91)continue;const zz=s*(.09+.12*Math.sqrt(1-q));const m=mesh(p,new T.CylinderGeometry(.032,.03,.024,6),mat.optic,[xx,yy,zz],[1,1,1],[Math.PI/2,0,0]);}for(let j=0;j<10;j++){const a=j*Math.PI/5;ball(p,[Math.cos(a)*.42,Math.sin(a)*.55,s*.04],[.023,.023,.023]);}}
for(let s of [-1,1]){const name=s>0?'Right':'Left';const a=part(`${name} antenna socket`,'Sensors',[1.84,.45,s*.29],[2.4,1,s*.7]);ball(a,[0,0,0],[.12,.12,.12],mat.dark);torus(a,[0,0,0],.105,.025,mat.steel,[Math.PI/2,0,0]);const pts=[[1.85,.45,s*.29],[2.25,.69,s*.45],[2.71,.42,s*.62],[3.03,.1,s*.76]];for(let i=0;i<3;i++){const p=part(`${name} antenna segment ${i+1}`,'Sensors',pts[i],[2.8+i*.15,.8,s*(.8+i*.2)]);const d=v(...pts[i+1]).sub(v(...pts[i])).toArray();rod(p,[0,0,0],d,.027,mat.dark);ball(p,d,[.045,.045,.045]);if(i===2)ball(p,d,[.036,.06,.036],mat.gold);}}
const probe=part('Nectar sampling micro-probe','Pollination',[1.84,-.42,0],[2.3,-1.2,0]);rod(probe,[0,0,0],[.18,-.68,0],.06,mat.dark);rod(probe,[.18,-.68,0],[.24,-.9,0],.024);for(let s of [-1,1])rod(probe,[0,0,s*.14],[.15,-.6,s*.1],.028,mat.gold);
const pollen=part('Pollen collection cartridge','Pollination',[.35,-.68,0],[.3,-2.2,1.4],'Replaceable collection drum with a soft radial brush, pollen reservoir and precision dispersal apertures.');rod(pollen,[-.25,0,0],[.25,0,0],.3,mat.gold);for(let i=0;i<4;i++)torus(pollen,[-.2+i*.13,0,0],.3,.035,mat.dark);fur(pollen,[.29,0,0],[.06,.31,.31],1400);
// Four membrane wings, hand-shaped outlines and a hexagonal nano-vein network.
for(let s of [-1,1])for(let w=0;w<2;w++){const label=`${s>0?'Right':'Left'} ${w?'hind':'fore'}`;const root=[-.2-w*.4,.58,s*.63];const actuator=part(`${label} wing oscillation motor`,'Actuators',root,[w?-.7:.4,1,s*1.2]);rod(actuator,[0,0,0],[0,0,s*.25],.18,mat.dark);torus(actuator,[0,0,s*.2],.18,.045,mat.steel,[0,0,0]);for(let i=0;i<6;i++){const a=i*Math.PI/3;ball(actuator,[Math.cos(a)*.14,Math.sin(a)*.14,s*.25],[.027,.027,.027]);}
const p=part(`${label} smart membrane`,'Wings',root,[-.4-w*.5,2+w*.6,s*(2.3+w*.5)],'Transparent self-healing membrane with carbon leading spar, a gold nano-vein lattice and individually articulated mounting hardware.');p.group.rotation.x=s*-.22;p.group.rotation.y=s*(w?.48:-.18);const L=w?2.55:3.55,shape=new T.Shape();shape.moveTo(0,0);shape.bezierCurveTo(-.55,.45,-.87,L*.67,-.46,L);shape.bezierCurveTo(-.1,L+.5,.45,L+.24,.63,L*.85);shape.bezierCurveTo(.95,L*.45,.38,.12,0,0);const g=new T.ShapeGeometry(shape,40);g.rotateX(Math.PI/2);g.scale(1,1,s);mesh(p,g,mat.glass);const outline=shape.getPoints(90).map(a=>v(a.x,0,s*a.y));const curve=new T.CatmullRomCurve3(outline,true);mesh(p,new T.TubeGeometry(curve,110,.024,6,true),mat.edge);rod(p,[0,0,0],[-.42,0,s*L],.038,mat.dark);const verts=[];const radius=.18;for(let row=0;row<13;row++)for(let col=-2;col<3;col++){const cx=col*radius*1.72+(row%2)*radius*.86,cz=.3+row*radius*1.5;if(cz>L||Math.abs(cx)>(.21+.4*Math.sin(cz/L*Math.PI)))continue;for(let k=0;k<6;k++){const a=k*Math.PI/3,b=(k+1)*Math.PI/3;verts.push(cx+Math.cos(a)*radius,.006,s*(cz+Math.sin(a)*radius),cx+Math.cos(b)*radius,.006,s*(cz+Math.sin(b)*radius));}}const lines=new T.BufferGeometry();lines.setAttribute('position',new T.Float32BufferAttribute(verts,3));p.group.add(new T.LineSegments(lines,new T.LineBasicMaterial({color:0xd1ad61,transparent:true,opacity:.8})));for(let i=1;i<5;i++)rod(p,[0,0,0],[(i-2.5)*.18,0,s*(L*.78)],.009,mat.edge);}
// Six articulated legs with separate servos, armor, pistons, hoses, tibia and claws.
for(let s of [-1,1])for(let l=0;l<3;l++){const label=`${s>0?'Right':'Left'} ${['front','middle','rear'][l]}`,x=.55-l*.67;const points=[[x,-.34,s*.58],[x+.12,-.85,s*1.07],[x+.35-(l*.25),-1.55,s*1.45],[x+.62-l*.3,-2.23,s*1.62]];for(let j=0;j<3;j++){const p=part(`${label} ${['coxa rotary servo','femur knee bearing','tibia ankle joint'][j]}`,'Legs',points[j],[ (x)*.85,-.7-j*.35,s*(1+l*.28)],'Precision rotary bearing with a titanium axle, composite housing and recessed fasteners.');ball(p,[0,0,0],[.17,.17,.17],mat.dark);torus(p,[0,0,s*.12],.145,.04,mat.steel,[0,0,0]);ball(p,[0,0,s*.15],[.08,.08,.03],mat.gold);const a=v(...points[j]),b=v(...points[j+1]),d=b.clone().sub(a);const arm=part(`${label} ${['coxa link','femur armor','tibia armor'][j]}`,'Legs',a.clone().add(b).multiplyScalar(.5).toArray(),[x*.8,-1-j*.35,s*(1.45+l*.28)]);arm.group.quaternion.setFromUnitVectors(v(0,1,0),d.clone().normalize());const length=d.length();rod(arm,[0,-length*.47,0],[0,length*.47,0],.075,mat.dark);const sh=ball(arm,[0,0,0],[.12,length*.37,.12],mat.gold);for(let z of [-.07,.07])rod(arm,[z,-length*.3,.095],[z,length*.3,.095],.016,mat.steel);for(let y of [-length*.25,length*.25])bolt(arm,[0,y,.12],.027);const piston=part(`${label} hydraulic piston ${j+1}`,'Actuators',a.toArray(),[x*.9,-1-j*.4,s*(1.8+l*.28)]);const da=d.clone().multiplyScalar(.8).add(v(.12,0,0));rod(piston,[.12,-.06,0],da.toArray(),.035,mat.steel);rod(piston,[.12,-.06,0],d.clone().multiplyScalar(.48).add(v(.12,0,0)).toArray(),.06,mat.dark);}
const foot=part(`${label} adaptive foot / claws`,'Legs',points[3],[x*.9,-2,s*(1.65+l*.3)]);ball(foot,[0,0,0],[.095,.1,.095],mat.dark);for(let k of [-1,1]){rod(foot,[0,0,0],[.12,-.12,k*.12],.023);rod(foot,[.12,-.12,k*.12],[.19,-.08,k*.13],.016,mat.dark);}if(l===2){const brush=part(`${label} pollen brush`,'Pollination',points[2],[x*.8,-1.5,s*2.2]);ball(brush,[0,-.1,0],[.12,.24,.12],mat.gold);fur(brush,[0,-.1,0],[.13,.25,.13],900);}}
// Internal flight-controller harness, radiators and chemical/UV sensor packages.
for(let s of [-1,1]){for(let i=0;i<3;i++){const p=part(`${s>0?'Right':'Left'} environmental sensor ${i+1}`,'Sensors',[.3-i*.3,.25,s*.73],[0,1,s*1.5]);ball(p,[0,0,0],[.11,.1,.07],mat.dark);ball(p,[0,0,s*.06],[.055,.055,.03],i===1?mat.cyan:mat.steel);}const p=part(`${s>0?'Right':'Left'} thermal exchange fins`,'Power system',[-.75,-.1,s*.52],[-1,-.6,s*1.8]);for(let i=0;i<9;i++)mesh(p,geo.box,mat.steel,[-.24+i*.06,0,0],[.025,.4,.2]);const h=part(`${s>0?'Right':'Left'} signal harness`,'Internal mechanisms',[0,0,0],[0,-.6,s*1.2]);for(let i=0;i<5;i++){const c=new T.CatmullRomCurve3([v(-1.1,-.15,s*.4+i*.018),v(-.5,-.5,s*.6+i*.018),v(.1,-.25,s*.6+i*.018),v(.8,0,s*.4+i*.018)]);mesh(h,new T.TubeGeometry(c,36,.018,6,false),i%2?mat.copper:mat.dark);}}
// Layered service plates, exposed transmission gears and precision hardware.
function decal(text){const c=document.createElement('canvas');c.width=512;c.height=256;const cx=c.getContext('2d');cx.fillStyle='#dba520';cx.fillRect(0,0,512,256);cx.fillStyle='#202823';cx.font='bold 54px monospace';cx.fillText(text,28,76);cx.font='20px monospace';cx.fillText('AUTONOMOUS POLLINATION',28,116);cx.fillText('UNIT 09 / FIELD SYSTEMS',28,146);for(let i=0;i<24;i++)cx.fillRect(28+i*15,180,5+(i%3)*2,36);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;return new T.MeshStandardMaterial({map:tex,metalness:.65,roughness:.38});}
for(let s of [-1,1]){
 const plate=part(`${s>0?'Right':'Left'} abdomen identification plate`,'Body armor',[-1.55,.12,s*.84],[-2,.1,s*.8]);const m=mesh(plate,new T.PlaneGeometry(.85,.43),decal('APX—9'));m.rotation.y=s>0?0:Math.PI;for(let x of [-.38,.38])for(let y of [-.16,.16])ball(plate,[x,y,s*.018],[.026,.026,.02]);
 for(let i=0;i<3;i++){const p=part(`${s>0?'Right':'Left'} thoracic flank plate ${i+1}`,'Body armor',[-.5+i*.36,.01,s*.7],[-.15+i*.15,.6,s*1.1]);mesh(p,geo.box,mat.gold,[0,0,0],[.28,.4,.06],[0,0,.12*(i-1)]);for(let y of [-.15,.15])ball(p,[0,y,s*.05],[.024,.024,.018]);for(let j=0;j<3;j++)mesh(p,geo.box,mat.dark,[-.07+j*.07,0,s*.04],[.027,.18,.01]);}
 for(let i=0;i<3;i++){const p=part(`${s>0?'Right':'Left'} flight transmission gear ${i+1}`,'Internal mechanisms',[-.45+i*.35,.3,s*.55],[0,.75,s*1.5]);torus(p,[0,0,0],.15,.055,mat.steel,[0,0,0]);for(let j=0;j<14;j++){const a=j*Math.PI/7;mesh(p,geo.box,mat.steel,[Math.cos(a)*.2,Math.sin(a)*.2,0],[.055,.055,.055],[0,0,a]);}ball(p,[0,0,s*.03],[.085,.085,.045],mat.dark);}
}
const belt=part('Black thoracic tactile belt','Body armor',[-.32,.21,0],[0,2.15,0]);mesh(belt,new T.SphereGeometry(1,40,28),mat.blackfur,[0,0,0],[.28,1.01,.92]);fur(belt,[0,0,0],[.28,1.025,.93],5200,true);
for(let i=0;i<4;i++){const p=part(`Ventral structural crossmember ${i+1}`,'Internal mechanisms',[-.65+i*.38,-.5,0],[0,-1-i*.1,0]);rod(p,[0,0,-.52],[0,0,.52],.055,mat.steel);for(let s of [-1,1])ball(p,[0,0,s*.52],[.09,.09,.07],mat.dark);}
// Batch same-material surfaces inside each named assembly to reduce draw calls.
pickables.length=0;
for(const p of parts){const batches=new Map();for(const m of p.meshes){m.updateMatrix();const g=m.geometry.clone().applyMatrix4(m.matrix);const arr=batches.get(m.material)||[];arr.push(g);batches.set(m.material,arr);p.group.remove(m);}p.meshes=[];for(const [material,geometries] of batches){const merged=mergeGeometries(geometries,false);if(!merged)continue;const m=new T.Mesh(merged,material);m.castShadow=true;m.receiveShadow=true;m.userData.part=p;p.group.add(m);p.meshes.push(m);pickables.push(m);for(const g of geometries)g.dispose();}}
const pedestal=new T.Mesh(new T.CylinderGeometry(6.4,6.55,.22,128),new T.MeshStandardMaterial({color:0x172329,metalness:.2,roughness:.75}));pedestal.position.y=-2.65;pedestal.receiveShadow=true;scene.add(pedestal);const rim=new T.Mesh(new T.TorusGeometry(6.3,.013,6,160),mat.edge);rim.rotation.x=Math.PI/2;rim.position.y=-2.53;scene.add(rim);const grid=new T.GridHelper(12,32,0x41515a,0x26363e);grid.position.y=-2.53;scene.add(grid);const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.MeshStandardMaterial({color:0x10191e,roughness:.9,metalness:0}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.79;floor.receiveShadow=true;scene.add(floor);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.09,.35,2.8);composer.addPass(bloom);composer.addPass(new OutputPass());
let target=0,explosion=0,sequence=false,selected=null,elapsed=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const highlight=new T.BoxHelper(new T.Object3D(),0xf6c342);highlight.visible=false;scene.add(highlight);
function select(p){selected=p;$('part-title').textContent=p?p.name:'Engineered to bloom.';$('part-desc').textContent=p?p.desc:'Select a component on the model or browse the assembly directory. Every shell, bearing, sensor and actuator has a place.';highlight.visible=!!p;if(p)highlight.setFromObject(p.group);document.querySelectorAll('#directory button').forEach(b=>b.classList.toggle('selected',Number(b.dataset.id)===p?.id));}
function list(){const term=$('search').value.toLowerCase();$('directory').replaceChildren();parts.filter(p=>(p.name+' '+p.system).toLowerCase().includes(term)).forEach(p=>{const b=document.createElement('button');b.textContent=p.name;b.dataset.id=p.id;b.onclick=()=>select(p);$('directory').appendChild(b);});}list();$('search').oninput=list;$('count').textContent=`/ ${parts.length}`;$('stats').textContent=`${parts.length} NAMED COMPONENTS · 1,100 MODELED SURFACES`;
const ray=new T.Raycaster(),pointer=new T.Vector2();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(pickables,false)[0];select(hit?.object.userData.part||null);});
function setExplosion(n){target=n;sequence=false;$('sequence').textContent='▶ Sequence';$('explode').value=Math.round(n*100);}$('explode').oninput=e=>setExplosion(e.target.value/100);$('disassemble').onclick=()=>setExplosion(1);$('assemble').onclick=()=>setExplosion(0);$('sequence').onclick=()=>{sequence=!sequence;elapsed=0;$('sequence').textContent=sequence?'Ⅱ Pause':'▶ Sequence';};$('rotate').onclick=()=>{controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',controls.autoRotate);};$('reset').onclick=()=>{select(null);setExplosion(0);controls.target.set(0,.3,0);camera.position.set(9,5.7,10.5);controls.autoRotate=false;};$('clear').onclick=()=>select(null);$('focus').onclick=()=>{if(!selected)return;const box=new T.Box3().setFromObject(selected.group),center=box.getCenter(new T.Vector3());const dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(center);camera.position.copy(center).add(dir.multiplyScalar(Math.max(4,box.getSize(new T.Vector3()).length()*2.4)));};$('inspector-toggle').onclick=()=>{document.body.classList.toggle('inspector-open');$('inspector-toggle').setAttribute('aria-expanded',document.body.classList.contains('inspector-open'));};$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);camera.setViewOffset(innerWidth,innerHeight,mobile()?0:innerWidth*.06,0,innerWidth,innerHeight);}addEventListener('resize',resize);resize();const clock=new T.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.2);elapsed+=dt;if(sequence){target=(1-Math.cos(elapsed*.52))*.5;$('explode').value=Math.round(target*100);}explosion=reduced?target:T.MathUtils.damp(explosion,target,4,dt);for(const p of parts)p.group.position.copy(p.base).addScaledVector(p.offset,explosion);$('amount').value=String(Math.round(explosion*100)).padStart(3,'0')+'%';if(selected)highlight.setFromObject(selected.group);camera.fov=(mobile()?64:37)+explosion*17;camera.updateProjectionMatrix();controls.update();composer.render();}window.apx9={parts,renderer,scene,camera,controls,setExplosion,select,get explosion(){return explosion}};$('loading').remove();animate();
