// (generated by tools/scans.py: the scanned maps, stamped with their content
// hashes, and how each set is laid out. Do not edit by hand.)
export const SCANS = {
  "files": {
    "path.col": {
      "1k": "path_col.1k.webp?v=65f473214e",
      "512": "path_col.512.webp?v=660d215543"
    },
    "path.nrm": {
      "1k": "path_nrm.1k.webp?v=3d6653dcca",
      "512": "path_nrm.512.webp?v=0c927aa5fc"
    },
    "path.orm": {
      "1k": "path_orm.1k.webp?v=c75d47997f",
      "512": "path_orm.512.webp?v=0c9139eb6b"
    },
    "soil.col": {
      "1k": "soil_col.1k.webp?v=5b3ad482d4",
      "512": "soil_col.512.webp?v=a489e5e6e8"
    },
    "soil.nrm": {
      "512": "soil_nrm.512.webp?v=c9de6f67b9"
    },
    "soil.orm": {
      "512": "soil_orm.512.webp?v=52d47facaf"
    },
    "moss.col": {
      "1k": "moss_col.1k.webp?v=802e91555f",
      "512": "moss_col.512.webp?v=d2c48c348b"
    },
    "moss.nrm": {
      "512": "moss_nrm.512.webp?v=d7bdc7a808"
    },
    "moss.orm": {
      "512": "moss_orm.512.webp?v=0982f3b1ad"
    },
    "iron.dcol": {
      "512": "iron_dcol.512.webp?v=76e16e0b9a"
    },
    "iron.nr": {
      "512": "iron_nr.512.webp?v=aa99cafaf0"
    },
    "brass.rough": {
      "512": "brass_rough.512.webp?v=a4e43f2131"
    },
    "sky": {
      "1k": "sky.webp?v=b764996a86"
    }
  },
  "tile": {
    "path": 90,
    "soil": 70,
    "moss": 45,
    "iron": 45
  },
  "aspect": {
    "path": 2.0
  },
  "sky": {
    "k": 1.0,
    "chroma": 0.3,
    "rot": 0.9913
  }
};
