"""Slice the generated bystander sheets (art-archive/crowd-v47/raw-*.png) into
keyed RGBA sprite sheets under assets/crowd/ plus MANIFEST.json.

Each raw sheet is a 1024x1024 4x4 grid on a flat chroma key (magenta or pure
blue). Row = one character, columns = stand / shift / cheer / stride.
Usage: python3 tools/build_crowd_sheets.py <archive-dir>
"""
import json, os, sys
import numpy as np
from PIL import Image

ARCHIVE = sys.argv[1] if len(sys.argv) > 1 else "/home/jez237/.openclaw/agents/gamemaster/workspace/final-blow-art-archive/crowd-v47"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "crowd")
KEYS = {"magenta": (255, 0, 255), "blue": (0, 0, 255)}
SHEETS = {
    "tailgate": [("raw-tailgate-g1.png", "magenta"), ("raw-tailgate-g2.png", "magenta")],
    "boardwalk": [("raw-boardwalk-g1.png", "blue"), ("raw-boardwalk-g2.png", "blue")],
    "buffet": [("raw-buffet-g1.png", "magenta"), ("raw-buffet-g2.png", "magenta")],
    "poolside": [("raw-poolside-g1.png", "blue"), ("raw-poolside-g2.png", "blue")],
}
COLUMNS = ["stand", "shift", "cheer", "stride"]
CELL = 256
T0, T1 = 70.0, 150.0  # key distance ramp: fully transparent below T0, opaque above T1


def key_sheet(img, key):
    rgb = np.asarray(img.convert("RGB")).astype(np.float32)
    kr, kg, kb = key
    dist = np.sqrt((rgb[..., 0] - kr) ** 2 + (rgb[..., 1] - kg) ** 2 + (rgb[..., 2] - kb) ** 2)
    alpha = np.clip((dist - T0) / (T1 - T0), 0.0, 1.0)
    # Despill ONLY the soft edge pixels: pull the key channels down toward the
    # non-key channel so fringes lose the tint. Fully opaque pixels are never
    # touched (the 4.1 despill lesson: clamping everything destroys real colour).
    edge = (alpha > 0.0) & (alpha < 0.98)
    out = rgb.copy()
    if key == KEYS["magenta"]:
        limit = out[..., 1] + 40
        out[..., 0] = np.where(edge, np.minimum(out[..., 0], limit), out[..., 0])
        out[..., 2] = np.where(edge, np.minimum(out[..., 2], limit), out[..., 2])
    else:
        limit = np.maximum(out[..., 0], out[..., 1]) + 40
        out[..., 2] = np.where(edge, np.minimum(out[..., 2], limit), out[..., 2])
    out = np.clip(out, 0, 255)
    rgba = np.dstack([out, alpha * 255]).astype(np.uint8)
    rgba[alpha == 0] = 0
    return Image.fromarray(rgba, "RGBA")


def cell_box(sheet, col, row):
    x0, y0 = col * CELL, row * CELL
    a = np.asarray(sheet.crop((x0, y0, x0 + CELL, y0 + CELL)).split()[3])
    ys, xs = np.where(a > 128)
    if len(xs) == 0:
        return None
    return {"frame": row * 4 + col, "x": int(x0 + xs.min()), "y": int(y0 + ys.min()),
            "w": int(xs.max() - xs.min() + 1), "h": int(ys.max() - ys.min() + 1),
            "baseline": int(y0 + ys.max() + 1), "cx": int(x0 + round(xs.mean()))}


manifest = {"version": "4.7", "cell": CELL, "columns": COLUMNS, "variants": {}}
for variant, raws in SHEETS.items():
    entry = {"sheets": [], "characters": []}
    for index, (raw, keyname) in enumerate(raws):
        img = Image.open(os.path.join(ARCHIVE, raw))
        assert img.size == (1024, 1024), (raw, img.size)
        sheet = key_sheet(img, KEYS[keyname])
        name = f"{variant}-{index + 1}.webp"
        sheet.save(os.path.join(OUT, name), "WEBP", quality=92, method=6)
        entry["sheets"].append(name)
        for row in range(4):
            cells = [cell_box(sheet, col, row) for col in range(4)]
            assert all(cells), (raw, row)
            entry["characters"].append({"sheet": index, "row": row, "cells": cells})
    manifest["variants"][variant] = entry
    print(variant, "characters", len(entry["characters"]),
          "heights", [c["cells"][0]["h"] for c in entry["characters"]])
with open(os.path.join(OUT, "MANIFEST.json"), "w") as fh:
    json.dump(manifest, fh, indent=1)
print("sizes:", {f: os.path.getsize(os.path.join(OUT, f)) for f in sorted(os.listdir(OUT))})
