import * as T from 'three';
import R from '@dimforge/rapier3d-compat';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {loadCars} from '../src/assets';import {Vehicle} from '../src/vehicle';import {enginePowerFactor,engineStatus} from '../src/engine-condition';import {DEFINITIONS,type CarKind} from '../src/rules';import type {Effects} from '../src/effects';
await R.init();await loadCars(s=>document.getElementById('progress')!.textContent=s);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;document.body.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color(0x253a3e);const camera=new T.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(5,6,14);camera.lookAt(0,1.5,0);
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();
const floor=new T.Mesh(new T.PlaneGeometry(120,120),new T.MeshStandardMaterial({color:0x46514c,roughness:.8}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);scene.add(new T.HemisphereLight(0xd2e8ef,0x41402d,1.8));const light=new T.DirectionalLight(0xffe6bb,3.6);light.position.set(-6,10,7);light.castShadow=true;light.shadow.mapSize.set(2048,2048);light.shadow.normalBias=.025;Object.assign(light.shadow.camera,{left:-12,right:12,top:12,bottom:-12});scene.add(light);
const world=new R.World({x:0,y:-9.81,z:0});world.createCollider(R.ColliderDesc.cuboid(60,.1,60).setTranslation(0,-.1,0).setFriction(.85));const fx={emit(){},mark(){},detach(m:T.Mesh){m.visible=false;}} as unknown as Effects;
let cars:Vehicle[]=[],kind:CarKind='marten',running=false,elapsed=0,last=performance.now(),accumulator=0;
const titles=['Front impact','Rear impact','Cabin impact'];
function draw(){document.getElementById('result')!.innerHTML=cars.map((c,i)=>`<article class="card"><small>${titles[i].toUpperCase()}</small><strong>${engineStatus(c.health,c.engineDamage)}</strong><div>Body condition ${c.health.toFixed(0)}% · Engine damage ${((c.engineDamage??0)*100).toFixed(0)}%</div><div>Available engine force ${(enginePowerFactor(c.health,c.engineDamage)*100).toFixed(0)}% · Speed ${(Math.abs(c.speed)*3.6).toFixed(1)} km/h</div></article>`).join('');}
function setup(next=kind){running=false;elapsed=0;accumulator=0;kind=next;cars.forEach(c=>c.dispose());cars=titles.map((_,i)=>{const c=new Vehicle(i,kind,[0x6e929a,0x9e6041,0x748272][i],scene,world,fx);const p=new T.Vector3((i-1)*4.2,.89,0);c.body.setTranslation(p,true);c.current.copy(p);c.previous.copy(p);c.render(1);return c;});for(let n=0;n<90;n++){cars.forEach(c=>c.preStep(1/60));world.step();cars.forEach(c=>c.postStep(1/60,n/60));}cars.forEach((c,i)=>{c.render(1);c.root.updateMatrixWorld(true);const point=i===2?new T.Vector3(.65,.03,-.08):new T.Vector3(0,0,(i===0?1:-1)*(DEFINITIONS[kind].halfLength-.20));const direction=new T.Vector3(i===2?-1:0,0,i===0?-1:i===1?1:0);c.hit(point.applyQuaternion(c.currentQ).add(c.current),direction.applyQuaternion(c.currentQ),35,2,true);});document.getElementById('caption')!.textContent=`${DEFINITIONS[kind].name}: three identical stock cars, each receives a 35-point impact. Engine condition follows the actual engine bay. Artwork remains beta.`;document.getElementById('progress')!.textContent='Ready · component damage is independent of total body condition';draw();}
document.getElementById('marten')!.onclick=()=>setup('marten');document.getElementById('tern')!.onclick=()=>setup('tern');document.getElementById('reset')!.onclick=()=>setup();document.getElementById('launch')!.onclick=()=>{if(running)return;setup();running=true;cars.forEach(c=>c.input={throttle:1,steer:0,brake:0,handbrake:false});};
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}addEventListener('resize',resize);resize();setup();
function frame(now:number){const dt=Math.min(.1,(now-last)/1000);last=now;if(running){accumulator+=dt;while(accumulator>=1/60&&elapsed<3){cars.forEach(c=>c.preStep(1/60));world.step();elapsed+=1/60;cars.forEach(c=>c.postStep(1/60,elapsed+2));accumulator-=1/60;}if(elapsed>=3){running=false;cars.forEach(c=>c.input.throttle=0);}document.getElementById('progress')!.textContent=`${running?'Accelerating':'Run complete'} · ${Math.min(3,elapsed).toFixed(1)} / 3.0 seconds`;draw();}cars.forEach(c=>c.render(1));const x=cars.reduce((sum,c)=>sum+c.current.x,0)/cars.length,z=cars.reduce((sum,c)=>sum+c.current.z,0)/cars.length;const radius=Math.max(...cars.map(c=>Math.hypot(c.current.x-x,c.current.z-z)));const fit=Math.max(1,(radius+3)/8);camera.position.set(x+5*fit,6*fit,z+14*fit);camera.lookAt(x,1.5,z);renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
