export const parts=[
 {id:'left_panel',title:'Cabinet & artwork',code:'01 / ENCLOSURE',text:'Painted wood, rubber T-molding, and bold screenprinted graphics turn an electronics rack into an unmistakable arcade silhouette.',repair:'Inspect joints, protect original paint, and replace damaged edge trim. This exhibit uses newly commissioned homage art.',signal:'The cabinet supports and protects the assemblies.'},
 {id:'controls',title:'Control panel',code:'02 / PLAYER INPUT',text:'A joystick and a bank of momentary buttons put every action under a separate finger. Leaf-switch contacts translate movement into electrical input.',repair:'Clean contacts gently and check spring tension. Worn contacts can miss a press or repeat it.',signal:'Amber pulses follow button input to the logic boards.'},
 {id:'coin',title:'Coin mechanism',code:'03 / CREDIT SYSTEM',text:'A mechanical acceptor sorts a coin before a momentary switch reports one credit to the game logic.',repair:'Keep the coin path clean and dry. Confirm the credit switch closes once per accepted coin.',signal:'An accepted coin sends a credit pulse to the board.'},
 {id:'power',title:'Power supply',code:'04 / POWER DISTRIBUTION',text:'The power assembly converts the incoming supply into the voltages required by the game electronics, display, and lamps.',repair:'Historical overview only. CRT cabinets can retain dangerous charge after unplugging; internal service belongs to trained technicians.',signal:'Red paths illustrate supply distribution, not a wiring schematic.'},
 {id:'logic',title:'Logic boards',code:'05 / GAME COMPUTER',text:'Rows of integrated circuits manage input, game state, sprites, and display timing. Ribbon connections link the assemblies into one machine.',repair:'Document board revisions and connector orientation before service. Replacement components must match the actual hardware.',signal:'Cyan pulses carry the illustrative video path toward the CRT.'},
 {id:'crt',title:'CRT & chassis',code:'06 / VIDEO DISPLAY',text:'An electron beam scans a phosphor-coated screen. Persistence, scanlines, and a curved glass face give arcade imagery its characteristic glow.',repair:'A cathode-ray tube is a high-voltage device, even with power removed. This model is educational, not a discharge or repair guide.',signal:'Video timing and color information become a scanned image.'},
 {id:'speaker',title:'Speaker',code:'07 / SOUND',text:'A paper cone moves air in response to the audio signal. A simple cabinet speaker can turn a few synthesized tones into an unforgettable atmosphere.',repair:'Check the cone for tears and mounting points for vibration. Sound in this exhibit is generated in the browser.',signal:'Violet pulses connect the logic assembly to the speaker.'},
 {id:'ventilation',title:'Ventilation',code:'08 / AIRFLOW',text:'Openings and a modeled fan illustrate how warm air leaves the enclosure. Actual cabinet cooling arrangements vary by revision.',repair:'Keep ventilation openings clear of dust and obstructions.',signal:'Blue particles illustrate rising cooling airflow.'},
] as const;
export type Mode='Hero'|'Exploded'|'X-Ray'|'Watch';
export type Signal='all'|'input'|'video'|'audio'|'credit'|'power'|'airflow';
export const offsets:Record<string,[number,number,number]>={left_panel:[-1.22,0,0],right_panel:[1.65,0,0],back_panel:[0,0,-1.05],marquee:[0,.32,0],crt:[0,0,.52],controls:[0,-.04,.87],coin:[0,-.04,.81],logic:[1.3,.1,-.06],power:[1.18,-.02,.15],speaker:[1.28,.52,.12],ventilation:[1.88,.02,.14],chassis:[0,0,0],details:[0,0,0]};
