export const parts=[
 {id:'left_panel',title:'Cabinet & artwork',code:'01 / ENCLOSURE',text:'Painted plywood, rubber T-molding and screenprinted graphics form the original upright silhouette. The 70-inch side profile follows measured cabinet plans; newly created artwork remains an approximation.',repair:'The reference target is a later-series US upright. Side outline: jbrew / William Stillwell measured plans. The source notes donor-cabinet variations; internal joinery is approximate.',signal:'The cabinet supports and protects the assemblies.'},
 {id:'controls',title:'Control panel',code:'02 / PLAYER INPUT',text:'An up/down-only lever controls altitude. Reverse sits beside it; Hyperspace is central. The right hand operates green Smart Bomb, white Thrust and Fire buttons. Two red buttons start one- or two-player games. Leaf-switch contacts translate movement into electrical input.',repair:'Control layout is referenced to a surviving panel photograph. Recreated artwork is not an original scan.',signal:'Amber pulses illustrate switch input; they are not measured electrical waveforms.'},
 {id:'coin',title:'Coin mechanism',code:'03 / CREDIT SYSTEM',text:'A mechanical acceptor sorts a coin before a momentary switch reports a credit to the game. The coin-door mechanism is a geometric approximation.',repair:'Keep the coin path clean and dry. Confirm the credit switch closes once per accepted coin.',signal:'An accepted coin sends a credit input to the game computer.'},
 {id:'power',title:'Linear power supply',code:'04 / D8359',text:'The open linear supply uses large heatsinks, rectifiers and five board fuses. Its +5 V, +12 V and -5 V rails serve the electronics. A laminated transformer and line filter occupy the lower power panel.',repair:'Williams sheets 10 and 13 establish the component arrangement. Mounting dimensions remain approximate. This exhibit is not a servicing guide.',signal:'Red paths illustrate supply distribution, not a wiring schematic.'},
 {id:'logic',title:'CPU & video board',code:'05 / R8570',text:'The 6809E at 2I executes the game. Twenty-four 4116 DRAMs provide 48 KiB; the 5101 at 1E retains settings with three AA cells. Decoder PROMs at 3E and 3K support video addressing. Family markings follow the Williams parts list.',repair:'Source: Williams April 1981 drawing set, sheet 4. Positions are traced from its assembly drawing. Vendor logos, date codes and unverified copper traces are omitted.',signal:'The CPU, RAM and video logic create the scanned RGB image. Moving pulses are illustrative.'},
 {id:'crt',title:'CRT & chassis',code:'06 / VIDEO DISPLAY',text:'An electron beam scans a phosphor-coated screen. The K4600-family model includes the main board, upright signal cards, neck-board socket and adjustments, deflection yoke, purity/convergence rings and high-voltage lead.',repair:'CRT construction is educational, not a discharge or repair guide. Wells-Gardner K4600 manual, figures 13-18. This family appears in a surviving Defender; fitment to every factory cabinet is not claimed. Minor parts and mounting dimensions are approximate.',signal:'Video timing and color information become a scanned image.'},
 {id:'speaker',title:'Speaker',code:'07 / SOUND OUTPUT',text:'A paper cone and magnetic motor convert the sound amplifier output to air movement. The D8224 drawing specifies an 8-ohm speaker load.',repair:'Williams sound schematic, sheet 17. Distinct event sounds are newly synthesized in the browser, not original ROM playback.',signal:'Violet pulses illustrate sound-board output to the speaker.'},
 {id:'ventilation',title:'Passive ventilation',code:'08 / AIRFLOW',text:'Rear openings allow warm air to leave the enclosure. The prototype fan has been removed because the selected Williams drawings did not establish a powered fan. Vent geometry remains approximate.',repair:'Keep ventilation openings clear of dust and obstructions.',signal:'Blue motion illustrates convection, not simulated fluid dynamics.'},
 {id:'rom',title:'Program ROM board',code:'09 / D8572',text:'Eleven program ROMs occupy the red-label configuration. IC5 remains empty, as specified in the assembly chart. The 6821 PIA at IC22 provides peripheral I/O. Labels identify ROM positions without reproducing ROM contents.',repair:'Source: Williams April 1981 drawing set, sheet 8. Socket positions are traced; dimensions are not manufacturing data.',signal:'The 40-conductor ribbon joins the CPU/video board. Animation is a functional illustration.'},
 {id:'interface',title:'Input interface',code:'10 / C8573',text:'The 6821 PIA at IC1 reads controls through 4049 inverters and 74LS257 multiplexers. Two ten-pin headers connect the switch harness. W1 is installed for the upright configuration.',repair:'Source: Williams April 1981 drawing set, sheet 7. Family markings use documented alternatives without invented production codes.',signal:'Switch closures reach the interface PIA and then the CPU; amber motion is illustrative.'},
 {id:'sound',title:'Sound computer',code:'11 / D8224',text:'A separate 6808/6802-family processor runs the sound program. Its 6821 PIA drives the 1408 digital-to-analog converter; the TDA2002 amplifier drives the speaker. The board includes 6810 RAM, a ROM socket, a 3.58 MHz crystal and two slow-blow fuses.',repair:'Source: Williams April 1981 drawing set, sheets 16-17. Browser audio remains synthesized, not emulation of the original sound ROM.',signal:'Game command → sound CPU → PIA → 1408 DAC → amplifier → speaker. Pulses illustrate this sequence.'},
] as const;
export type Mode='Hero'|'Exploded'|'X-Ray'|'Watch';
export type Signal='all'|'input'|'video'|'audio'|'credit'|'power'|'airflow';
export const offsets:Record<string,[number,number,number]>={left_panel:[-1.22,0,0],right_panel:[3.10,0,0],back_panel:[0,0,-1.05],marquee:[0,.32,0],crt:[0,0,.52],controls:[0,-.04,.87],coin:[0,-.04,.81],logic:[2.10,.22,.05],power:[1.18,-.02,.15],speaker:[1.28,.65,.12],ventilation:[1.88,.02,.14],chassis:[0,0,0],details:[0,0,0]};
