export class ArcadeGame {
 canvas=document.createElement('canvas');ctx:CanvasRenderingContext2D;keys=new Set<string>();
 lastAudio=-10000;credits=0;running=false;active=false;power=true;score=0;best=0;lives=3;wave=1;rescued=0;carrying=false;time=0;cooldown=0;invincible=0;x=600;y=230;dir=1;volume=.25;muted=true;audio?:AudioContext;
 bullets:{x:number,y:number,d:number}[]=[];enemies:{x:number,y:number,phase:number}[]=[];humans:number[]=[];stars=Array.from({length:100},(_,i)=>({x:(i*337)%3200,y:(i*97)%430}));onChange=()=>{};
 constructor(){this.canvas.width=960;this.canvas.height=600;this.canvas.setAttribute('aria-label','Starward: original space rescue arcade game');this.ctx=this.canvas.getContext('2d')!;try{this.best=Number(localStorage.getItem('starward-best')||0)}catch{}this.populate();}
 populate(){this.enemies=Array.from({length:8+this.wave*2},(_,i)=>({x:100+i*283%3200,y:90+i*63%300,phase:i*1.7}));this.humans=[350,780,1150,1600,2090,2500,2910];}
 unlock(){this.audio??=new AudioContext();void this.audio.resume();}
 tone(f=180,d=.07,type:OscillatorType='square'){this.lastAudio=performance.now();if(this.muted||!this.audio)return;const o=this.audio.createOscillator(),g=this.audio.createGain();o.type=type;o.frequency.setValueAtTime(f,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.35,this.audio.currentTime+d);g.gain.setValueAtTime(this.volume*.09,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+d);o.connect(g).connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+d);}
 start(){this.credits++;this.running=true;this.score=0;this.lives=3;this.wave=1;this.rescued=0;this.carrying=false;this.x=600;this.y=230;this.bullets=[];this.invincible=2;this.populate();this.tone(480,.15);this.onChange();}
 update(dt:number){dt=Math.min(dt,.04);if(!this.power){this.draw();return}this.time+=dt;
 if(this.active&&this.running){const pad=navigator.getGamepads?.()[0];const axisX=pad?.axes[0]||0,axisY=pad?.axes[1]||0;const dx=(this.keys.has('ArrowRight')||this.keys.has('KeyD')?1:0)-(this.keys.has('ArrowLeft')||this.keys.has('KeyA')?1:0)+(Math.abs(axisX)>.15?axisX:0),dy=(this.keys.has('ArrowDown')||this.keys.has('KeyS')?1:0)-(this.keys.has('ArrowUp')||this.keys.has('KeyW')?1:0)+(Math.abs(axisY)>.15?axisY:0);this.x=(this.x+dx*360*dt+3200)%3200;this.y=Math.max(65,Math.min(482,this.y+dy*270*dt));if(dx)this.dir=Math.sign(dx);
 this.cooldown-=dt;this.invincible-=dt;if((this.keys.has('Space')||pad?.buttons[0]?.pressed)&&this.cooldown<=0){this.bullets.push({x:this.x+this.dir*20,y:this.y,d:this.dir});this.cooldown=.14;this.tone(780,.045);}
 this.bullets=this.bullets.filter(b=>{b.x+=b.d*850*dt;return b.x>-500&&b.x<3700});
 for(const e of [...this.enemies]){e.x=(e.x+(Math.sin(e.phase)*40-45)*dt+3200)%3200;e.y+=Math.sin(this.time*1.8+e.phase)*24*dt;const hit=this.bullets.find(b=>Math.abs(b.x-e.x)<28&&Math.abs(b.y-e.y)<23);if(hit){this.bullets.splice(this.bullets.indexOf(hit),1);this.enemies.splice(this.enemies.indexOf(e),1);this.score+=150;this.tone(130,.11,'sawtooth');this.onChange();}else if(Math.abs(e.x-this.x)<26&&Math.abs(e.y-this.y)<22&&this.invincible<=0){this.lives--;if(this.carrying)this.humans.push(this.x);this.carrying=false;this.invincible=2.5;this.tone(90,.4,'sawtooth');if(this.lives<=0){this.running=false;this.best=Math.max(this.best,this.score);try{localStorage.setItem('starward-best',String(this.best))}catch{}}this.onChange();}}
 if(!this.carrying&&this.y>450){const i=this.humans.findIndex(x=>Math.abs(x-this.x)<35);if(i>=0){this.humans.splice(i,1);this.carrying=true;this.tone(510,.2,'sine');this.onChange();}}
 if(this.carrying&&Math.abs(this.x-100)<55&&this.y>400){this.carrying=false;this.rescued++;this.score+=500;this.tone(920,.25,'sine');this.onChange();}
 if(this.enemies.length===0){this.wave++;this.populate();this.score+=1000;this.onChange();}
 }else if(!this.active&&!this.running){this.x=(this.time*65+600)%3200;this.y=250+Math.sin(this.time)*90;this.dir=1;}
 this.draw();}
 draw(){const c=this.ctx,w=960,h=600;c.fillStyle='#080d12';c.fillRect(0,0,w,h);if(!this.power)return;const off=this.x-w*.4;const sx=(x:number)=>((x-off+3200)%3200);c.save();c.shadowBlur=7;c.shadowColor='#8fcadd';
 for(const s of this.stars){c.fillStyle='#91a8b9';c.fillRect(sx(s.x),s.y+70,1.5,1.5)}
 c.strokeStyle='#b17b48';c.lineWidth=2;c.beginPath();for(let px=0;px<=w;px+=8){const world=off+px;const y=530+Math.sin(world*.022)*15+Math.sin(world*.063)*8;c.lineTo(px,y)}c.stroke();
 const base=sx(100);c.strokeStyle='#7bd4d1';c.strokeRect(base-35,487,70,28);c.fillStyle='#7bd4d1';c.font='13px monospace';c.fillText('BASE',base-16,480);
 for(const x of this.humans){const a=sx(x);c.fillStyle='#e8dbac';c.fillRect(a-3,494,6,6);c.fillRect(a-1,500,2,9);c.fillRect(a-5,504,10,2)}
 c.fillStyle='#e37d7d';c.shadowColor='#f05050';for(const e of this.enemies){const x=sx(e.x);c.beginPath();c.moveTo(x,e.y-10);c.lineTo(x+16,e.y+7);c.lineTo(x-16,e.y+7);c.closePath();c.strokeStyle='#e87695';c.stroke();c.fillRect(x-4,e.y,8,4)}
 for(const b of this.bullets){c.fillStyle='#ffeeaf';c.fillRect(sx(b.x),b.y,27*b.d,2)}
 const ship=384;if(this.invincible<=0||Math.floor(this.time*12)%2===0){c.save();c.translate(ship,this.y);c.scale(this.dir,1);c.shadowColor='#a3eaff';c.fillStyle='#d2f1ef';c.beginPath();c.moveTo(22,0);c.lineTo(-15,-9);c.lineTo(-8,0);c.lineTo(-15,9);c.closePath();c.fill();c.fillStyle='#e1a653';c.fillRect(-25-Math.sin(this.time*45)*5,-2,12,4);c.restore();}
 if(this.carrying){c.fillStyle='#ffe1a4';c.fillRect(ship-2,this.y+14,4,10)}
 c.shadowBlur=0;c.strokeStyle='#354752';c.strokeRect(220,12,520,36);for(const e of this.enemies){c.fillStyle='#e57d89';c.fillRect(220+e.x/3200*520,20+e.y/600*22,3,3)}c.fillStyle='#dcf0e2';c.fillRect(220+this.x/3200*520,32,5,3);c.font='17px monospace';c.fillText(String(this.score).padStart(6,'0'),22,33);c.fillStyle='#c7a569';c.fillText('WAVE '+String(this.wave).padStart(2,'0'),790,33);c.font='13px monospace';c.fillStyle='#9ba9aa';c.fillText('LIVES '+this.lives+'   RESCUED '+this.rescued,22,574);c.fillText('HI '+String(Math.max(this.best,this.score)).padStart(6,'0'),790,574);
 if(!this.running&&this.active){c.fillStyle='#070b11bb';c.fillRect(170,182,620,216);c.textAlign='center';c.fillStyle='#f4c970';c.font='bold 64px monospace';c.fillText('STARWARD',480,263);c.fillStyle='#becbcd';c.font='16px monospace';c.fillText(this.lives===0?'GAME OVER · INSERT COIN TO RETRY':'ORIGINAL SPACE RESCUE · 1981 INSPIRED',480,306);c.fillStyle='#f4c970';c.fillText('INSERT COIN / PRESS ENTER',480,357);c.textAlign='left';}c.restore();
 c.fillStyle='#0002';for(let y=0;y<h;y+=4)c.fillRect(0,y,w,1);}
}
