const priorities:Record<string,number>={"flap_down": 10, "flap_up": 10, "run1": 8, "run2": 8, "skid": 40, "skid_end": 40, "thud": 40, "cliff_thud": 40, "egg": 45, "egg_hatch": 40, "die": 80, "ptero_scream": 40, "ptero_intro": 40, "troll": 40, "lava": 40, "transporter_enemy": 40, "transporter_player": 40, "mount": 40, "bounty": 40, "cliff": 40, "extra_man": 100, "game_start": 200, "credit": 255};
const events:Record<string,string|string[]>={"flap": ["flap_down", "flap_up"], "walk": ["run1", "run2"], "thud": "thud", "cthud": "cliff_thud", "skid": "skid", "skidEnd": "skid_end", "eggDrop": "thud", "eggCollect": "egg", "eggHatch": "egg_hatch", "eggLand": "thud", "enemyDie": "die", "playerDie": "die", "ptero": "ptero_intro", "pteroDie": "die", "troll": "troll", "lava": "lava", "spawn": "transporter_enemy", "materialized": "transporter_player", "mount": "mount", "bounty": "bounty", "cliff": "cliff", "extraMan": "extra_man", "bait": "ptero_scream", "bounce": "thud", "waveClear": "game_start", "start": "game_start", "credit": "credit"};
/** PCM rendered from the checksum-verified original VSNDRM4. Single DAC voice. */
export class JoustSound{
 private spatialGain:GainNode;private pan:StereoPannerNode;private lowpass:BiquadFilterNode;
 private master:GainNode;private analyser:AnalyserNode;private buffers=new Map<string,AudioBuffer>();private voice?:{source:AudioBufferSourceNode;until:number;priority:number};private enabled=false;private output=0;private last='';private count=0;private error='';readonly ready:Promise<void>;
 private alternates:Record<string,number>={};
 private context:AudioContext;
 constructor(context:AudioContext){this.context=context;this.master=context.createGain();this.master.gain.value=0;this.analyser=context.createAnalyser();this.analyser.fftSize=256;this.spatialGain=context.createGain();this.pan=context.createStereoPanner();this.lowpass=context.createBiquadFilter();this.lowpass.type='lowpass';this.lowpass.frequency.value=15000;this.master.connect(this.lowpass).connect(this.spatialGain).connect(this.pan).connect(this.analyser).connect(context.destination);this.ready=Promise.all(Object.keys(priorities).map(async key=>{const r=await fetch(`./joust/audio/${key}.ogg`);if(!r.ok)throw Error(`${key}: ${r.status}`);this.buffers.set(key as string,await context.decodeAudioData(await r.arrayBuffer()));})).then(()=>{}).catch(e=>{this.error=String(e);console.error('Joust audio',e);});}
 spatial(mix:{pan:number;gain:number;cutoff:number}){const now=this.context.currentTime;this.pan.pan.setTargetAtTime(mix.pan,now,.08);this.spatialGain.gain.setTargetAtTime(mix.gain,now,.1);this.lowpass.frequency.setTargetAtTime(mix.cutoff,now,.1);}
 state(active:boolean,muted:boolean,volume:number,_thrust=false){this.enabled=active&&!muted;const level=this.enabled?volume*.45:0;if(level!==this.output){this.master.gain.setTargetAtTime(level,this.context.currentTime,.012);this.output=level;}if(!this.enabled&&this.voice){try{this.voice.source.stop()}catch{}this.voice=undefined;}}
 effect(name:string){let event=events[name];if(!event)return;if(Array.isArray(event)){const i=this.alternates[name]=(this.alternates[name]||0)+1;event=event[i%event.length];}const buffer=this.buffers.get(event),now=this.context.currentTime,priority=priorities[event];if(!this.enabled||!buffer||(this.voice&&this.voice.until>now&&this.voice.priority>priority))return;if(this.voice)try{this.voice.source.stop()}catch{}const source=this.context.createBufferSource();source.buffer=buffer;source.connect(this.master);source.start();source.onended=()=>source.disconnect();this.voice={source,until:now+buffer.duration,priority};this.last=event;this.count++;}
 inspect(){const a=new Float32Array(256);this.analyser.getFloatTimeDomainData(a);return {context:this.context.state,level:Math.sqrt(a.reduce((s,x)=>s+x*x,0)/256),output:this.output,pan:this.pan.pan.value,distanceGain:this.spatialGain.gain.value,cutoff:this.lowpass.frequency.value,event:this.last,count:this.count,loaded:this.buffers.size,source:'VSNDRM4 rendered samples',error:this.error};}
}
