import {parts as defenderParts} from './data';
import {joustLayouts} from '../joust-layout.mjs';
import {chipRoles} from './ChipNotes';
const notes:Record<string,Partial<{title:string;code:string;text:string;repair:string;signal:string}>>={
 left_panel:{text:'Joust is a 1982 Williams two-player upright. Brown and black sides, a yellow ostrich-riding knight, flame artwork, and yellow/blue controls distinguish it from Defender. Cabinet construction and recreated artwork are approximate.',repair:'Exterior reference: surviving Joust upright photographs. The exhibit shares a reconstructed Williams chassis; this is not manufacturing CAD.'},
 controls:{text:'Each player has a two-way left/right joystick and a flap button. Yellow controls belong to player one; blue controls belong to player two. The autonomous player pulses the flap button to gain altitude.',repair:'Recreated upright control arrangement. A second pair supports simultaneous two-player Joust; this exhibit watches one autonomous player.',signal:'Horizontal direction and flap contacts feed the input PIA.'},
 logic:{code:'05 / CPU · VIDEO · BLITTER',text:'A 1 MHz Motorola 6809E runs Joust. Twenty-four 4116 RAM chips provide 48 KiB. Two Williams SC1 custom blitter chips accelerate bitmap copying; decoder PROMs 4 and 6 support video addressing.',repair:'Component families follow Joust documentation. This model is a functional reconstruction with approximate placement.'},
 rom:{code:'09 / JOUST PROGRAM',text:'Twelve 4 KiB EPROM positions hold the Joust program and graphics. The 6821 PIA handles peripheral commands. Original bitmap frames are decoded into display assets; the full game program is not shipped.',repair:'All twelve sockets are populated. Chip labels identify function; physical positions remain approximate.'},
 interface:{code:'10 / DIRECTION / FLAP INPUT',text:'The interface reads two horizontal joystick switches and a flap contact per player, plus start and coin inputs.',repair:'Signal animation shows functional data flow, not measured waveforms or a wiring guide.'},
 sound:{text:'The D8224 sound board runs VSNDRM4 with a 6808/6802-family CPU, 6810 RAM and 6821 PIA. An eight-bit DAC feeds the amplifier and speaker.',repair:'Original rendered samples are reused byte-for-byte from this site’s Joust game. The browser plays PCM samples through a single priority voice.'},
 speaker:{repair:'Original Joust VSNDRM4 effects follow flapping, enemy kills, egg collection, spawning and wave changes. The inactive machine is silent.'},
 crt:{repair:'Reconstructed K4600-family CRT assembly. Monitor fitment varied. Original Joust bitmaps use a 292 × 240 display with scanlines, curved glass and phosphor persistence.'},
};
export const joustParts=defenderParts.map(p=>({...p,...notes[p.id]}));
export function joustChipLayout(id:string){return (joustLayouts as Record<string,typeof joustLayouts.cpu>)[id==='logic'?'cpu':id];}
export function joustChipNote(id:string,ref:string){const c=joustChipLayout(id)?.chips.find(c=>c.ref===ref);if(!c)return;return {...c,text:c.family==='SC1 BLITTER'?'One of two Williams custom blitter ICs used to transfer bitmap data quickly. Modeled placement is approximate.':c.family==='6809E'?'The 6809E executes Joust’s game program with externally supplied clocks.':c.family==='VSNDRM4'?'The 4 KiB VSNDRM4 contains the original Joust sound program. Only rendered PCM effects are delivered to the browser.':c.family.startsWith('DECODER')?'Joust uses decoder PROMs 4 and 6 for video addressing.':c.family.startsWith('ROM ')?'One of twelve Joust program EPROM positions. Physical placement is approximate.':chipRoles[c.family]||'Historical component family in a functional reconstruction. Package placement is approximate.'};}
