import {parts as defenderParts} from './data';
import {robotronLayouts} from '../robotron-layout.mjs';
import {chipRoles} from './ChipNotes';
const notes:Record<string,Partial<{title:string;code:string;text:string;repair:string;signal:string}>>={
 left_panel:{text:'Robotron: 2084 is a 1982 Williams twin-stick upright. Pale side panels, red graphic bands, blue panel stripes and a red/yellow marquee distinguish it from Defender. Cabinet construction and recreated artwork are approximate.',repair:'Exterior reference: surviving Robotron upright photographs. The exhibit shares a reconstructed Williams chassis; this is not manufacturing CAD.'},
 controls:{text:'Two independent eight-way leaf-switch joysticks: the left moves the player, the right fires in eight directions. Two blue start buttons sit at the right edge. Both sticks follow the autonomous pilot independently.',repair:'Layout follows the surviving panel photographed by PixelatedArcade. Start buttons select one-player or alternating two-player games.',signal:'Two sets of four switch contacts report movement and firing directions independently.'},
 logic:{code:'05 / CPU · VIDEO · BLITTER',text:'A 1 MHz Motorola 6809E runs Robotron. Twenty-four 4116 RAM chips provide 48 KiB. Two Williams SC1 custom blitter chips accelerate bitmap copying; decoder PROMs 4 and 6 support video addressing.',repair:'Component families follow Robotron documentation. This model is a functional reconstruction with approximate placement.'},
 rom:{code:'09 / ROBOTRON PROGRAM',text:'Twelve 4 KiB EPROM positions hold the Robotron program and graphics. The 6821 PIA handles peripheral commands. Original bitmap frames are decoded into display assets; the full game program is not shipped.',repair:'All twelve sockets are populated. Chip labels identify function; physical positions remain approximate.'},
 interface:{code:'10 / TWIN-STICK INPUT',text:'The interface reads the separate movement and firing switch harnesses, start buttons and coin inputs. Diagonal directions close two switches on the same joystick.',repair:'Signal animation shows functional data flow, not measured waveforms or a wiring guide.'},
 sound:{text:'The D8224 sound board runs Video Sound ROM 3 with a 6808/6802-family CPU, 6810 RAM and 6821 PIA. An eight-bit DAC feeds the amplifier and speaker.',repair:'Audio is rendered from the checksum-verified original sound program, with original game command sequences. The browser plays PCM samples through a single priority voice.'},
 speaker:{repair:'Original Robotron Video Sound ROM 3 effects follow firing, enemy kills, rescues, spawning and wave changes. The inactive machine is silent.'},
 crt:{repair:'Reconstructed K4600-family CRT assembly. Monitor fitment varied. Original Robotron bitmaps use a 292 × 240 display with scanlines, curved glass and phosphor persistence.'},
};
export const robotronParts=defenderParts.map(p=>({...p,...notes[p.id]}));
export function robotronChipLayout(id:string){return (robotronLayouts as Record<string,typeof robotronLayouts.cpu>)[id==='logic'?'cpu':id];}
export function robotronChipNote(id:string,ref:string){const c=robotronChipLayout(id)?.chips.find(c=>c.ref===ref);if(!c)return;return {...c,text:c.family==='SC1 BLITTER'?'One of two Williams custom blitter ICs used to transfer bitmap data quickly. Modeled placement is approximate.':c.family==='6809E'?'The 6809E executes Robotron’s game program with externally supplied clocks.':c.family==='VIDEO SOUND 3'?'The 4 KiB Video Sound ROM 3 contains the original Robotron sound program. Only rendered PCM effects are delivered to the browser.':c.family.startsWith('DECODER')?'Robotron uses decoder PROMs 4 and 6 for video addressing.':c.family.startsWith('ROM ')?'One of twelve Robotron program EPROM positions. Physical placement is approximate.':chipRoles[c.family]||'Historical component family in a functional reconstruction. Package placement is approximate.'};}
