export type RobotronEvent='fire'|'robot'|'step'|'human'|'humanLost'|'start'|'wave'|'death'|'credit'|'extra'|'spawn'|'enforcer'|'brain'|'tank'|'hulk'|'convert';
const priorities:Record<RobotronEvent,number>={fire:208,robot:208,step:192,human:224,humanLost:224,start:240,wave:224,death:238,credit:255,extra:239,spawn:216,enforcer:208,brain:200,tank:200,hulk:208,convert:208};
/** PCM rendered from the checksum-verified original Video Sound ROM 3. Single DAC voice. */
export class RobotronSound{
 private spatialGain:GainNode;private pan:StereoPannerNode;private lowpass:BiquadFilterNode;
 private master:GainNode;private analyser:AnalyserNode;private buffers=new Map<RobotronEvent,AudioBuffer>();private voice?:{source:AudioBufferSourceNode;until:number;priority:number};private enabled=false;private output=0;private last='';private count=0;private error='';readonly ready:Promise<void>;
 private context:AudioContext;
 constructor(context:AudioContext){this.context=context;this.master=context.createGain();this.master.gain.value=0;this.analyser=context.createAnalyser();this.analyser.fftSize=256;this.spatialGain=context.createGain();this.pan=context.createStereoPanner();this.lowpass=context.createBiquadFilter();this.lowpass.type='lowpass';this.lowpass.frequency.value=15000;this.master.connect(this.lowpass).connect(this.spatialGain).connect(this.pan).connect(this.analyser).connect(context.destination);this.ready=Promise.all(Object.keys(priorities).map(async key=>{const r=await fetch(`./robotron/audio/${key}.wav`);if(!r.ok)throw Error(`${key}: ${r.status}`);this.buffers.set(key as RobotronEvent,await context.decodeAudioData(await r.arrayBuffer()));})).then(()=>{}).catch(e=>{this.error=String(e);console.error('Robotron audio',e);});}
 spatial(mix:{pan:number;gain:number;cutoff:number}){const now=this.context.currentTime;this.pan.pan.setTargetAtTime(mix.pan,now,.08);this.spatialGain.gain.setTargetAtTime(mix.gain,now,.1);this.lowpass.frequency.setTargetAtTime(mix.cutoff,now,.1);}
 state(active:boolean,muted:boolean,volume:number,_thrust=false){this.enabled=active&&!muted;const level=this.enabled?volume*.45:0;if(level!==this.output){this.master.gain.setTargetAtTime(level,this.context.currentTime,.012);this.output=level;}if(!this.enabled&&this.voice){try{this.voice.source.stop()}catch{}this.voice=undefined;}}
 effect(event:RobotronEvent){const buffer=this.buffers.get(event),now=this.context.currentTime,priority=priorities[event];if(!this.enabled||!buffer||(this.voice&&this.voice.until>now&&this.voice.priority>priority))return;if(this.voice)try{this.voice.source.stop()}catch{}const source=this.context.createBufferSource();source.buffer=buffer;source.connect(this.master);source.start();source.onended=()=>source.disconnect();this.voice={source,until:now+buffer.duration,priority};this.last=event;this.count++;}
 inspect(){const a=new Float32Array(256);this.analyser.getFloatTimeDomainData(a);return {context:this.context.state,level:Math.sqrt(a.reduce((s,x)=>s+x*x,0)/256),output:this.output,pan:this.pan.pan.value,distanceGain:this.spatialGain.gain.value,cutoff:this.lowpass.frequency.value,event:this.last,count:this.count,loaded:this.buffers.size,source:'Video Sound ROM 3 rendered samples',error:this.error};}
}
