import {joustMarquee,joustSide,joustControls} from './JoustTextures';
import {joustChipLayout} from './JoustNotes';
import {robotronMarquee,robotronSide,robotronControls} from './RobotronTextures';
import {useEffect,useMemo,useRef,useState} from 'react';
import {useFrame,useLoader,useThree,ThreeEvent} from '@react-three/fiber';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ArcadeGame} from './game';
import type {DefenderShow} from './DefenderShow';
import {cabinetRoot} from './model';
import {ArcadeEnvironment,FilmFinish} from './Environment';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {Mode,Signal,offsets} from './data';
import {assemblyOffset,assemblyProgress} from './choreography';
import {boardCenters,boardPoint,hardwareTextures} from './Hardware';
import {crtMaterial,phosphorHistory} from './CRT';
import {cabinetPatina,panelContactRoughness,applyPatina} from './Patina';
import {surfaceTextures} from './SurfaceTextures';
import {coverGlass,marqueeDiffuser,serviceLabel} from './Finish';
import {chipLayout as defenderChipLayout} from './ChipNotes';
import {robotronChipLayout} from './RobotronNotes';
import {mechanismPose,speakerMix,type Panels,type Demonstration} from './Mechanics';
import {ServiceHarness} from './ServiceHarness';
export interface SceneProps{machine?:'defender'|'robotron'|'joust';slot?:number;active?:boolean;roomMode?:Mode;onActivate?:()=>void;panels:Panels;demo:Demonstration;focusTarget:string;onFocus:(name:string)=>void;mode:Mode;speed:number;power:boolean;cabinetLight:boolean;roomLight:boolean;reduced:boolean;quality:string;reset:number;selected:string|null;signal:Signal;game:ArcadeGame;onSelect:(id:string)=>void;onReady:()=>void;onHover:(id:string|null)=>void;}
const anchor:Record<string,[number,number,number]>={left_panel:[-.72,2.45,.03],controls:[.35,2.43,.88],coin:[.25,1.8,1],power:[.5,.9,.1],logic:[.49,2.04,-.2],crt:[.5,3.01,.5],speaker:[.2,3.55,.55],ventilation:[.43,.7,-.55]};
function textTexture(lines:string[],bg:string,fg:string,w=1024,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const a=c.getContext('2d')!;a.fillStyle=bg;a.fillRect(0,0,w,h);a.strokeStyle=fg;a.lineWidth=3;a.strokeRect(12,12,w-24,h-24);a.textAlign='center';lines.forEach((line,i)=>{a.font=`${i===0?'italic bold':'normal'} ${i===0?h*.5:h*.11}px monospace`;a.fillStyle=fg;a.fillText(line,w/2,h*(i===0?.6:.83));});const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function defenderMarquee(logo:CanvasImageSource){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle='#060e1a';c.fillRect(0,0,1024,256);for(let i=0;i<160;i++){const x=(i*137)%1024,y=(i*71)%256;c.fillStyle=i%4?'#adcae0':'#ffe5a0';c.fillRect(x,y,i%7?2:4,i%7?2:4);}c.strokeStyle='#387aa9';c.lineWidth=12;c.beginPath();c.ellipse(530,164,540,85,-.12,0,Math.PI*2);c.stroke();c.fillStyle='#be4626';c.beginPath();c.arc(965,50,85,0,Math.PI*2);c.fill();c.strokeStyle='#e3a447';c.lineWidth=7;c.stroke();c.drawImage(logo,50,49,699,147,60,33,904,190);c.strokeStyle='#c39753';c.lineWidth=3;c.strokeRect(7,7,1010,242);const t=new T.CanvasTexture(canvas);t.colorSpace=T.SRGBColorSpace;return t;}
function controlTexture(){const c=document.createElement('canvas');c.width=1536;c.height=640;const a=c.getContext('2d')!;const W=c.width,H=c.height;const px=(x:number)=>(x+.645)/1.29*W,py=(z:number)=>(z-.3585)/.505*H;a.fillStyle='#121414';a.fillRect(0,0,W,H);
 const box=(x:number,y:number,w:number,h:number,color:string)=>{a.fillStyle=color;a.fillRect(x,y,w,h);a.strokeStyle='#bcbb94';a.lineWidth=3;a.strokeRect(x,y,w,h);};
 // Draw the striped instrument-grid layout in code, with legends aligned to model holes.
 for(let i=0;i<28;i++){const x=30+i*53;box(x,32,43,240,'#171b18');for(const [j,color]of ['#c52221','#dfb62c','#278443'].entries()){a.fillStyle=color;a.fillRect(x+2,90+((i*29+j*39)%140),39,12+j*4);}}
 box(550,28,413,439,'#171a18');box(587,111,335,113,'#205d9b');box(587,239,335,202,'#17191a');
 a.fillStyle='#ba2529';a.beginPath();for(let i=0;i<24;i++){const angle=i*Math.PI/12,rr=i%2?42:174;a.lineTo(750+Math.cos(angle)*rr,338+Math.sin(angle)*rr*.52);}a.closePath();a.fill();
 for(let i=0;i<24;i++){const x=34+i*62;box(x,469,48,115,'#141916');for(const [j,color]of ['#c52b2c','#d6b929','#20824e'].entries()){a.fillStyle=color;a.fillRect(x+2,489+j*23+(i%3)*6,44,13);}}
 box(551,471,412,111,'#2266a2');for(let j=0;j<4;j++){a.strokeStyle='#111c28';a.beginPath();a.moveTo(554,481+j*26);a.lineTo(960,481+j*26);a.stroke();}
 box(56,293,440,153,'#181b19');box(1000,263,227,176,'#191a19');box(1240,298,237,143,'#151b18');a.strokeStyle='#b92d36';a.lineWidth=4;for(let i=0;i<8;i++){a.beginPath();a.moveTo(1254+(i*29)%200,311);a.lineTo(1254+(i*67)%200,426);a.stroke();}
 a.fillStyle='#bc2528';a.fillRect(24,600,W-48,23);a.strokeStyle='#c3bc96';a.lineWidth=4;a.strokeRect(21,21,W-42,H-42);
 a.textAlign='center';a.font='bold 22px monospace';for(const [x,z,label]of [[-.36,.73,'REVERSE'],[.32,.49,'THRUST'],[.46,.49,'FIRE'],[.24,.65,'SMART BOMB'],[0,.80,'HYPERSPACE'],[-.12,.46,'1 PLAYER'],[.12,.46,'2 PLAYERS']] as [number,number,string][]){const xx=px(x),yy=py(z),start=label.includes('PLAYER');a.fillStyle='#c9c5a2';a.fillText(label,xx,start?yy+75:label==='HYPERSPACE'?620:yy-59);}
 a.fillStyle='#c9c5a2';a.font='bold 22px monospace';a.fillText('GAME START',768,67);a.fillStyle='#bcb992';a.fillRect(px(-.48)-22,py(.57)-90,44,181);a.fillStyle='#c9c5a2';a.fillText('UP',px(-.48),py(.57)-107);a.fillText('DOWN',px(-.48),py(.57)+119);
 // Small deterministic scuffs preserve the legibility of the printed legends.
 let seed=1981;for(let i=0;i<900;i++){seed=(seed*1664525+1013904223)>>>0;const x=seed%W;seed=(seed*1664525+1013904223)>>>0;const y=seed%H;a.fillStyle=i%3?'#10110f55':'#d1c39c44';a.fillRect(x,y,1+i%4,1);}
 for(const [x,z]of [[-.36,.73],[.32,.49],[.46,.49],[.24,.65],[0,.8]]){const glow=a.createRadialGradient(px(x),py(z),38,px(x),py(z),102);glow.addColorStop(0,'#d4be8820');glow.addColorStop(.55,'#d4be8810');glow.addColorStop(1,'#0000');a.fillStyle=glow;a.fillRect(px(x)-102,py(z)-102,204,204);}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t;}
function wearTexture(){const c=document.createElement('canvas');c.width=c.height=256;const a=c.getContext('2d')!;a.fillStyle='#8b8b8b';a.fillRect(0,0,256,256);let s=713;const r=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};for(let i=0;i<12000;i++){a.fillStyle=`rgba(${r()>.5?'230,230,215':'15,20,18'},${r()*.24})`;a.fillRect(r()*256,r()*256,r()*2+.2,r()*7+.4);}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,4);return t;}
export function Scene(p:SceneProps){const chipLayout=p.machine==='joust'?joustChipLayout:p.machine==='robotron'?robotronChipLayout:defenderChipLayout;const {camera,gl,size}=useThree();const {scene:loaded}=useLoader(GLTFLoader,p.machine==='defender'?'./cabinet.glb?v=20260911-arcade':`./${p.machine}-cabinet.glb?v=20260911-joust`,loader=>loader.setMeshoptDecoder(MeshoptDecoder));const art=useLoader(T.TextureLoader,'./side-art.webp');const logo=useLoader(T.TextureLoader,p.machine==='joust'?'./joust/marquee.jpg':p.machine==='robotron'?'./robotron/logo.svg':'./defender-logo.svg');const zinc=useLoader(T.TextureLoader,'./galvanized-zinc.webp');const [wood,marqueeArt]=useLoader(T.TextureLoader,['./painted-wood-v2.webp','./marquee.webp']);const scene=useMemo(()=>cabinetRoot(loaded),[loaded]);const group=useRef<T.Group>(null);const initialPosition=useMemo(()=>[(p.slot||0)*2.25,0,p.active===false?-1.9:0] as [number,number,number],[]);const travel=useRef(p.active===false?1:0);const inactiveCut=useMemo(()=>new T.Plane(),[]);const orbit=useRef<OrbitControls|null>(null);const moving=useRef(true);const touched=useRef(false);const explosion=useRef(0);const lightTarget=useMemo(()=>{const o=new T.Object3D();o.position.set(0,1.6,0);return o},[]);const currentMode=useRef(p.mode);const clock=useRef(0);const startup=useRef(0);const credit=useRef(p.game.credits);const coinTime=useRef(4);const [hover,setHover]=useState<string|null>(null);
 const savedView=useRef<{pos:T.Vector3;target:T.Vector3;mode:Mode;selected:string|null}|null>(null),returnView=useRef<{pos:T.Vector3;target:T.Vector3}|null>(null);
 const bases=useMemo(()=>{const map=new Map<string,T.Vector3>();scene.traverse(o=>{if(o.name)map.set(o.name,o.position.clone());});return map;},[scene]);
 const demoTime=useRef(0),demoSerial=useRef(-1);
 const surfaces=useMemo(()=>surfaceTextures(),[]);const robotArt=useMemo(()=>p.machine==='joust'?joustSide():p.machine==='robotron'?robotronSide(logo.image):null,[]);const persistence=useMemo(()=>phosphorHistory(p.game.canvas),[p.game]);
 const hardwareMaps=useMemo(()=>hardwareTextures(scene),[scene]);
 const resources=useMemo(()=>({pins:serviceLabel(['1  2  3  4','PIN ORDER']),crt:new T.CanvasTexture(p.game.canvas),marquee:p.machine==='joust'?joustMarquee(logo.image):p.machine==='robotron'?robotronMarquee(logo.image):defenderMarquee(logo.image),controls:p.machine==='joust'?joustControls():p.machine==='robotron'?robotronControls(logo.image):controlTexture(),coin:textTexture(['25¢','PUSH TO REJECT'],'#4f1308','#ef8b36',256,256),warning:textTexture(['!','HIGH VOLTAGE'],'#d8ac38','#161b19',256,256),tag:textTexture([p.machine==='defender'?'81':'82','RESTORED / JZ'],'#cabca0','#3c3630',256,256),inspection:serviceLabel(['SERVICE RECORD','CABINET / UPRIGHT','INSPECT FASTENERS & GROUND','EXHIBIT RESTORATION']),harness:serviceLabel(['HARNESS / SERVICE','DISCONNECT BEFORE REMOVAL','RETAIN CLIPS & STRAIN RELIEF']),controlService:serviceLabel(['CONTROL PANEL','LEAF SWITCH ASSEMBLY','KEEP CONTACTS CLEAN']),wear:wearTexture(),patina:cabinetPatina(),contact:panelContactRoughness()}),[p.game,logo]);
 useEffect(()=>{zinc.colorSpace=T.SRGBColorSpace;zinc.wrapS=zinc.wrapT=T.RepeatWrapping;zinc.repeat.set(3,3);zinc.anisotropy=8;zinc.needsUpdate=true;wood.colorSpace=T.SRGBColorSpace;marqueeArt.colorSpace=T.SRGBColorSpace;for(const t of [wood]){t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(1,2);t.anisotropy=4;}art.anisotropy=8;art.colorSpace=T.SRGBColorSpace;art.flipY=true;resources.crt.colorSpace=T.SRGBColorSpace;resources.crt.flipY=true;resources.crt.minFilter=T.LinearMipmapLinearFilter;resources.crt.magFilter=T.NearestFilter;resources.crt.generateMipmaps=true;resources.crt.anisotropy=Math.min(8,gl.capabilities.getMaxAnisotropy());for(const t of [wood,marqueeArt,art,resources.crt])t.needsUpdate=true;
 scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const m=(o.material as T.MeshStandardMaterial).clone();o.material=m;
 if(hardwareMaps[m.name]){m.map=hardwareMaps[m.name];m.color.set('#fff');m.roughness=.88;}
 if(['circuit_board','monitor_board'].includes(m.name)){m.map=surfaces.board;m.roughnessMap=surfaces.rough;m.bumpMap=surfaces.rough;m.bumpScale=.0005;}if(['integrated_circuit','speaker_paper','aged_plastic','button_red','button_green','button_amber','button_blue','bezel_face','speaker_face'].includes(m.name)){m.roughnessMap=surfaces.plastic;m.bumpMap=surfaces.plastic;m.bumpScale=.00035;}if(m.name==='aged_label'){m.map=surfaces.paper;}if(m.name==='rubber_trim'){m.metalness=0;m.roughness=.76;m.bumpMap=surfaces.plastic;m.bumpScale=.0005;}if(m.name==='tube_glass'){m.metalness=.08;m.roughness=.28;m.envMapIntensity=.45;}
 if(o.name.endsWith('_print')&&m.name==='side_print'){m.map=robotArt||art;if(robotArt&&o.name==='right_panel_print'){m.map=robotArt.clone();m.map.repeat.x=-1;m.map.offset.x=1;m.map.needsUpdate=true;}m.color.set(p.machine==='robotron'?'#fff':'#c3b59b');m.roughness=.8;applyPatina(m,resources.patina);}
 else if(m.name==='painted_wood'){m.map=wood;m.bumpMap=wood;m.bumpScale=.0014;m.roughnessMap=surfaces.rough;m.roughness=.92;m.color.set('#ded6c0');applyPatina(m,resources.patina,.22);}else if(['aged_steel','zinc_bracket','black_metal','raw_plywood','brass'].includes(m.name)){m.roughnessMap=surfaces.metal;m.bumpMap=surfaces.metal;m.bumpScale=.00065;m.roughness=m.name==='black_metal'?.73:m.name==='brass'?.46:.57;if(m.name==='raw_plywood'){m.map=surfaces.plywood;m.roughness=.94;m.bumpScale=.0012;}}
 if(m.name==='zinc_bracket'){m.map=zinc;m.bumpMap=zinc;m.bumpScale=.00018;m.roughness=.63;m.metalness=.68;m.color.set('#c7ccca');}if(o.name==='crt_screen'){m.map=resources.crt;m.emissiveMap=resources.crt;m.emissive.set('#ffffff');m.emissiveIntensity=1.5;m.color.set('#000000');m.roughness=1;m.metalness=0;m.envMapIntensity=0;m.toneMapped=false;}
 if(o.name==='marquee_print'){marqueeDiffuser(m);m.map=resources.marquee;m.emissiveMap=resources.marquee;m.emissive.set('#fff');m.color.set('#000');m.envMapIntensity=0;m.roughness=1;m.toneMapped=false;}
 if(o.name==='control_print'){m.map=resources.controls;m.color.set(p.machine==='joust'?'#aaa394':p.machine==='robotron'?'#888e94':'#fff');m.metalness=0;m.roughness=.94;m.roughnessMap=resources.contact;m.envMapIntensity=.12;}
 if(o.name==='warning_label'){m.map=resources.warning;m.color.set('#fff');}
 if(m.name.startsWith('coin_lamp')){m.map=resources.coin;m.emissiveMap=resources.coin;m.color.set('#151009');m.toneMapped=false;}if(o.name==='service_tag'){m.map=resources.tag;m.color.set('#fff');}
 const serviceMap=o.name==='inspection_label'?resources.inspection:o.name==='harness_label'?resources.harness:o.name==='controls_service_label'?resources.controlService:null;if(serviceMap){m.map=serviceMap;m.color.set('#fff');}
 if(o.name.endsWith('_pins')){m.map=resources.pins;m.color.set('#fff');}
 if(m.name==='exposed_particleboard'){m.map=surfaces.plywood;m.bumpMap=surfaces.plywood;m.bumpScale=.002;m.roughness=.99;}
 if(m.name==='cover_glass'){o.material=coverGlass();o.castShadow=false;o.receiveShadow=false;o.renderOrder=2;m.dispose();}
 if(m.name==='coin_return_lens'){o.material=new T.MeshPhysicalMaterial({name:m.name,color:'#b82818',roughness:.25,metalness:0,clearcoat:.85,clearcoatRoughness:.18,emissive:'#db2714',emissiveIntensity:.24});m.dispose();}
 if(['bezel_face','speaker_face'].includes(m.name)){o.material=new T.MeshLambertMaterial({name:m.name,color:m.color,bumpMap:surfaces.plastic,bumpScale:.00035});m.dispose();}
 if(['button_red','button_green','button_amber','button_blue','aged_plastic'].includes(m.name)){const plastic=new T.MeshPhysicalMaterial({name:m.name,color:m.color,roughness:m.name==='aged_plastic'?.58:.40,metalness:0,roughnessMap:surfaces.plastic,bumpMap:surfaces.plastic,bumpScale:.0002,clearcoat:.30,clearcoatRoughness:.30,envMapIntensity:.28});plastic.onBeforeCompile=shader=>{shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nvarying float moldedTop;').replace('#include <begin_vertex>','#include <begin_vertex>\nmoldedTop=pow(abs(normal.y),5.0);');shader.fragmentShader=shader.fragmentShader.replace('#include <common>','#include <common>\nvarying float moldedTop;').replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor*=mix(1.25,.58,moldedTop);');};plastic.customProgramCacheKey=()=> 'molded-plastic-contact-v1';o.material=plastic;m.dispose();}m.needsUpdate=true;if(o.name==='crt_screen'){o.material=crtMaterial(resources.crt,persistence.texture);o.frustumCulled=false;o.receiveShadow=false;m.dispose();}}});p.onReady();return()=>{scene.traverse(o=>{if(o instanceof T.Mesh)(o.material as T.Material).dispose()});persistence.texture.dispose();Object.values(resources).forEach(t=>t.dispose());Object.values(hardwareMaps).forEach(t=>t.dispose());Object.values(surfaces).forEach(t=>t.dispose());};},[scene]);
 useEffect(()=>{if(p.active===false)return;const c=new OrbitControls(camera,gl.domElement);c.enableDamping=true;c.dampingFactor=.065;c.minDistance=2.4;c.maxDistance=12;c.maxPolarAngle=Math.PI*.49;c.minPolarAngle=.35;c.target.set(0,1.7,0);c.addEventListener('start',()=>{moving.current=false;touched.current=true});orbit.current=c;return()=>{c.dispose();orbit.current=null;};},[camera,gl,p.active]);
 useEffect(()=>{returnView.current=null;moving.current=true;touched.current=false;currentMode.current=p.mode;},[p.mode,p.reset,p.selected,size.width,p.active]);
 useEffect(()=>{if(p.power)startup.current=0;},[p.power]);
 const targets=useMemo(()=>{
  const mobile=size.width<760;let pos=new T.Vector3(...(mobile?(p.mode==='Exploded'?[2.3,2.9,12.2]:p.mode==='Watch'?[.05,2.55,3.35]:[2.8,2.65,8.1]):p.mode==='Watch'?[.06,2.58,1.95]:p.mode==='Exploded'?[4.3,2.85,7]:p.mode==='X-Ray'?[3.6,2.7,6.5]:[2.8,2.4,5.8]) as [number,number,number]);let target=p.mode==='Watch'?new T.Vector3(0,mobile?2.32:2.45,.39):new T.Vector3(.15,1.72,0);
  if(p.selected&&(anchor[p.selected]||boardCenters[p.selected])){const board=!!boardCenters[p.selected];const point=board?boardPoint(p.selected,p.mode==='Exploded'?1:0,mobile):new T.Vector3(...anchor[p.selected]).add(new T.Vector3(...assemblyOffset(p.selected,p.mode==='Exploded'?1:0,mobile))).multiplyScalar(.84);const distance=p.selected==='left_panel'?5:board?(mobile?({logic:4.1,rom:3,interface:2.4,sound:2.7}[p.selected as 'logic']):p.selected==='logic'?2.15:1.65):3.1;target=point.clone().add(new T.Vector3(mobile?0:.38,mobile?-.35:0,0));pos=point.clone().add(new T.Vector3(board?0:p.selected==='controls'?.15:distance*.34,board?.02:p.selected==='controls'?1.8:.35,p.selected==='controls'?2.2:distance));if(board)target=point.clone().add(new T.Vector3(mobile?0:.20,mobile?-distance*.125:0,0));}
  if(p.selected==='crt'){
   // Look across the tube and its neck, rather than straight into the bezel.
   target=new T.Vector3(.08,2.50,p.mode==='Exploded'?.47:.02);
   pos=target.clone().add(new T.Vector3(mobile?4.1:2.8,mobile?.85:.60,mobile?1.6:.8));
   if(mobile)target.y-=.32;
  }
  if(p.selected==='speaker'){
   target=new T.Vector3(...anchor.speaker).add(new T.Vector3(...assemblyOffset('speaker',p.mode==='Exploded'?1:0,mobile))).multiplyScalar(.84);
   pos=target.clone().add(new T.Vector3(mobile?2.3:1.4,.45,mobile?2.4:1.7));if(mobile)target.y-=.35;
  }
  return {pos,target,mobile};
 },[p.mode,p.selected,size.width]);
 useEffect(()=>{if(p.focusTarget){if(!savedView.current&&orbit.current)savedView.current={pos:camera.position.clone(),target:orbit.current.target.clone(),mode:p.mode,selected:p.selected};returnView.current=null;moving.current=true;touched.current=false;}else if(savedView.current){if(savedView.current.mode===p.mode&&savedView.current.selected===p.selected){returnView.current=savedView.current;moving.current=true;touched.current=true;}savedView.current=null;}},[p.focusTarget]);
 const detailView=()=>{
  if(!p.focusTarget)return null;let node:T.Object3D|undefined,point:T.Vector3,normal:T.Vector3;let distance=.58;
  if(p.focusTarget==='rear_service'){point=scene.localToWorld(new T.Vector3(0,1.9,-.6));normal=new T.Vector3(.28,.10,-1).normalize();distance=3.15;}else if(p.focusTarget.startsWith('chip:')){const [,id,ref]=p.focusTarget.split(':');node=scene.getObjectByName('board_'+(id==='logic'?'cpu':id));const layout=chipLayout(id),chip=layout?.chips.find(c=>c.ref===ref);if(!node||!layout||!chip)return null;point=node.localToWorld(new T.Vector3((chip.u-.5)*layout.width,(.5-chip.v)*layout.height,.02));normal=new T.Vector3(0,0,1).transformDirection(node.matrixWorld);distance=.42;
  }else{node=scene.getObjectByName(p.focusTarget);if(!node)return null;point=node.getWorldPosition(new T.Vector3());const underside=p.focusTarget.startsWith('stick_leaf_')||p.focusTarget.startsWith('leaf_')||p.focusTarget.startsWith('joystick_contact');const top=p.focusTarget.startsWith('joystick')||p.focusTarget.startsWith('button_')||underside;normal=new T.Vector3(top?.28:0,top?(underside?-1:1):0,top?.35:p.focusTarget==='coin_demo_anchor'?-1:1).transformDirection(node.matrixWorld);distance=p.focusTarget==='coin_demo_anchor'?1.0:p.focusTarget==='joystick'?.68:.48;}
  if(size.width<760)distance*=1.45;
  return {target:point,pos:point.clone().addScaledVector(normal,distance)};
 };
 useFrame((_,raw)=>{const dt=Math.min(raw,.05),d=p.reduced?1:1-Math.exp(-dt*4*p.speed);clock.current+=dt*p.speed;startup.current+=dt;if(group.current){if(p.active!==false||explosion.current<.2)travel.current=T.MathUtils.lerp(travel.current,p.active===false?1:0,p.reduced?1:1-Math.exp(-dt*2));const t=travel.current;const slot=p.slot||0;group.current.position.x=T.MathUtils.lerp(group.current.position.x,slot*2.25,p.reduced?1:1-Math.exp(-dt*2));group.current.position.z=-1.9*t+Math.sin(t*Math.PI)*.8;group.current.rotation.y=T.MathUtils.lerp(group.current.rotation.y,-slot*.25,p.reduced?1:1-Math.exp(-dt*2));group.current.userData.machine=p.machine;group.current.userData.active=p.active!==false;}camera.getWorldDirection(inactiveCut.normal);inactiveCut.constant=-inactiveCut.normal.dot(camera.position.clone().addScaledVector(inactiveCut.normal,Math.max(.25,camera.position.distanceTo(new T.Vector3(0,1.7,0))-2.1)));const c=orbit.current;if(c&&p.active!==false){c.enabled=true;c.minDistance=p.focusTarget?.16:p.selected&&boardCenters[p.selected]?.65:p.mode==='Watch'?1.2:2.4;if(moving.current||(p.focusTarget&&!touched.current)){const view=detailView()||returnView.current||targets;const pos=view.pos.clone();camera.position.lerp(pos,d);c.target.lerp(view.target,d);if(camera.position.distanceTo(pos)<.01)moving.current=false;}c.autoRotate=!p.focusTarget&&!Object.values(p.panels).some(Boolean)&&!touched.current&&p.mode==='Hero'&&!p.reduced&&!moving.current&&!p.selected;c.autoRotateSpeed=.08*p.speed;c.update();}
 const cover=scene.getObjectByName('speaker_cover');if(cover)cover.visible=p.mode==='Hero'||p.mode==='Watch';const explode=p.mode==='Exploded';explosion.current=T.MathUtils.lerp(explosion.current,explode?1:0,p.reduced?1:1-Math.exp(-dt*2.4*p.speed));scene.children.forEach(g=>g.position.set(...assemblyOffset(g.name,explosion.current,targets.mobile)));const crtAssembly=scene.getObjectByName('crt');if(crtAssembly)crtAssembly.rotation.y=-.24*assemblyProgress('crt',explosion.current);const bezel=scene.getObjectByName('monitor_bezel');if(bezel){const opening=assemblyProgress('controls',explosion.current);bezel.position.x=-.9*opening;bezel.position.z=.474+.50*opening;bezel.visible=p.selected!=='crt';}const tray=scene.getObjectByName('board_tray');if(tray){const unfold=assemblyProgress('logic',explosion.current);tray.position.set(-.57*(1-unfold),1.90,-.17*(1-unfold));tray.rotation.set(0,(1-unfold)*Math.PI/2,(1-unfold)*Math.PI/2);}const inspecting=p.selected&&boardCenters[p.selected];if(tray)for(const child of tray.children)if(!child.name.startsWith('board_'))child.visible=!inspecting;for(const g of scene.children)g.visible=inspecting?g.name==='logic':!((p.mode==='Hero'||p.mode==='Watch')&&!Object.values(p.panels).some(Boolean)&&['logic','power'].includes(g.name));for(const [id]of Object.entries(boardCenters)){const board=scene.getObjectByName('board_'+(id==='logic'?'cpu':id));if(board)board.visible=!inspecting||p.selected===id;}const hingeCoin=scene.getObjectByName('coin_hinge'),hingeControls=scene.getObjectByName('controls_hinge'),rear=scene.getObjectByName('rear_service');
 if(hingeCoin)hingeCoin.rotation.y=T.MathUtils.lerp(hingeCoin.rotation.y,p.panels.coin?-1.28:0,d);
 if(hingeControls)hingeControls.rotation.x=T.MathUtils.lerp(hingeControls.rotation.x,p.panels.controls?-1.02:0,d);
 for(const rearNode of [rear,scene.getObjectByName('rear_vents')])if(rearNode){const base=bases.get(rearNode.name)!;rearNode.position.z=T.MathUtils.lerp(rearNode.position.z,base.z-(p.panels.rear?.65:0),d);rearNode.position.x=T.MathUtils.lerp(rearNode.position.x,base.x-(p.panels.rear?1.35:0),d);rearNode.rotation.y=T.MathUtils.lerp(rearNode.rotation.y,p.panels.rear?-.35:0,d);}
 scene.updateMatrixWorld(true);
 const speakerNode=scene.getObjectByName('speaker_cone');if(speakerNode){const origin=speakerNode.getWorldPosition(new T.Vector3()),toward=camera.position.clone().sub(origin),distance=toward.length();toward.normalize();const right=new T.Vector3(1,0,0).applyQuaternion(camera.quaternion),normal=new T.Vector3(0,1,0).transformDirection(speakerNode.matrixWorld);(p.game as DefenderShow).sound?.spatial(speakerMix(distance,-toward.dot(right),toward.dot(normal)));}
 if(demoSerial.current!==(p.demo?.serial??-1)){demoSerial.current=p.demo?.serial??-1;demoTime.current=0;if(p.demo?.kind==='coin'&&!p.reduced)coinTime.current=0;}else demoTime.current+=dt;
 const demo=mechanismPose(p.reduced?'':p.demo?.kind||'',demoTime.current);
 scene.traverse(o=>{if(o instanceof T.Mesh){const m=o.material as T.MeshStandardMaterial;let parent:T.Object3D|null=o;while(parent?.parent&&parent.parent!==scene)parent=parent.parent;const id=parent?.name;const clip=p.active===false?[inactiveCut]:null;if(!!m.clippingPlanes!==!!clip){m.clippingPlanes=clip;m.needsUpdate=true;}const shell=['left_panel','right_panel','back_panel','coin','marquee','controls'].includes(id||'');const cover=m.name==='cover_glass';const transparent=cover||(p.mode==='X-Ray'&&shell);const opacity=cover?.018:transparent?.13:1;if(m.transparent!==transparent){m.transparent=transparent;m.depthWrite=!transparent;m.needsUpdate=true;}m.opacity=T.MathUtils.lerp(m.opacity,opacity,d);
 if(o.name==='crt_screen'){m.emissiveIntensity=p.power?1:0;const warm=p.reduced?1:Math.min(1,startup.current/1.3);o.scale.y=p.power?Math.max(.01,warm):.004;}
 else if(o.name==='marquee_print')m.emissiveIntensity=p.power&&p.cabinetLight?(startup.current<1.2&&!p.reduced?Math.sin(startup.current*45)>.1?.95:.1:.9):0;
 else if(m.name==='coin_return_lens'){m.emissive.set('#db2714');m.emissiveIntensity=p.power?.24:0;}
 else if(m.name.startsWith('coin_lamp')){m.emissive.set(p.power?'#fff':'#000');m.emissiveIntensity=.85;}
 else if((id===p.selected||id===hover)&&!['bezel_face','speaker_face','tube_glass'].includes(m.name)){m.emissive.set('#715f44');m.emissiveIntensity=.065;}else {m.emissive.set('#000');}
 }});
 const joy=scene.getObjectByName('joystick');if(joy){joy.rotation.z=p.machine!=='defender'?T.MathUtils.lerp(joy.rotation.z,p.demo?.kind==='joystick'?demo.joystick:p.game.keys.has('ArrowLeft')?.2:p.game.keys.has('ArrowRight')?-.2:0,d):0;joy.rotation.x=T.MathUtils.lerp(joy.rotation.x,p.machine==='joust'?0:p.demo?.kind==='joystick'?demo.joystick:p.game.keys.has('ArrowUp')?-.2:p.game.keys.has('ArrowDown')?.2:0,d);}
 for(let i=0;i<7;i++){const b=scene.getObjectByName('button_'+i);if(b)b.position.y=T.MathUtils.lerp(b.position.y,bases.get(b.name)!.y-.019*(i===2&&p.demo?.kind==='button'?demo.press:p.game.keys.has(['KeyR','KeyT','Space','KeyB','KeyH','Digit1','Digit2'][i])?1:0),d);}
 const fireStick=scene.getObjectByName('joystick_fire');if(fireStick){const aim=(p.game as unknown as {aim:number[]}).aim;fireStick.rotation.x=T.MathUtils.lerp(fireStick.rotation.x,p.machine==='joust'?0:p.demo?.kind==='button'?demo.press*.24:(aim?.[1]||0)*.20,d);fireStick.rotation.z=T.MathUtils.lerp(fireStick.rotation.z,p.machine==='joust'?0:p.demo?.kind==='button'?demo.press*.24:-(aim?.[0]||0)*.20,d);}
 for(const name of ['joystick','joystick_fire']){const stick=scene.getObjectByName(name);if(p.machine!=='defender'&&stick)for(let i=0;i<4;i++){const leaf=scene.getObjectByName('stick_leaf_'+name+'_'+i);if(leaf){const value=p.machine==='joust'?(i===0?stick.rotation.z:-stick.rotation.z):i===0?stick.rotation.x:i===1?stick.rotation.z:i===2?-stick.rotation.x:-stick.rotation.z;leaf.position.y=bases.get(leaf.name)!.y-Math.max(0,value)*.025;}}}
 const fan=scene.getObjectByName('fan_rotor');if(fan&&p.power&&!p.reduced)fan.rotation.z+=dt*p.speed*7;
 const cone=scene.getObjectByName('speaker_cone');if(cone)cone.scale.y=1+(p.power&&performance.now()-p.game.lastAudio<300&&!p.reduced?Math.sin(clock.current*60)*.07:0);
 if(credit.current!==p.game.credits){credit.current=p.game.credits;coinTime.current=0;}const beforeCoin=coinTime.current;coinTime.current+=dt;if(beforeCoin<1.2&&coinTime.current>=1.2&&p.demo?.kind==='coin'&&!p.reduced){p.game.credits++;credit.current=p.game.credits;p.game.tone(510,.14);p.game.onChange();}const creditContact=scene.getObjectByName('coin_credit_contact');if(creditContact)creditContact.rotation.z=coinTime.current>1.12&&coinTime.current<1.48?-.12:0;const coin=scene.getObjectByName('travelling_coin');if(coin){coin.visible=coinTime.current<2.4&&!p.reduced;coin.position.y=bases.get('travelling_coin')!.y-Math.min(.58,coinTime.current*.25);coin.rotation.z=coinTime.current*7;}for(let i=0;i<7;i++){const leaf=scene.getObjectByName('leaf_'+i);if(leaf){const pressed=i===2&&p.demo?.kind==='button'?demo.press:p.game.keys.has(['KeyR','KeyT','Space','KeyB','KeyH','Digit1','Digit2'][i])?1:0;leaf.rotation.z=-.045*pressed;leaf.position.y=T.MathUtils.lerp(leaf.position.y,bases.get(leaf.name)!.y-.005*pressed,d);}}for(let i=0;i<2;i++){const contact=scene.getObjectByName('joystick_contact_'+i);if(contact){const travel=i===0?Math.max(0,demo.joystick):Math.min(0,demo.joystick);contact.rotation.x=travel*.45;contact.position.y=bases.get(contact.name)!.y-Math.abs(travel)/.24*.006;}}
 persistence.update(dt,p.power&&!p.reduced);resources.crt.needsUpdate=true;
 if(location.hostname==='127.0.0.1'&&group.current){const point=new T.Vector3(0,3.84,.72).multiplyScalar(.84);group.current.localToWorld(point);point.project(camera);const debug=window as any;debug.__arcadeMachines??={};debug.__arcadeMachines[p.machine||'defender']={active:p.active!==false,position:group.current.position.toArray(),rotation:group.current.rotation.y,marquee:{x:(point.x*.5+.5)*size.width,y:(-.5*point.y+.5)*size.height},audio:(p.game as any).sound?.inspect(),time:p.game.time};}
 if(p.active===false)return;
 const projected=Object.entries({...anchor,rom:[0,0,0],interface:[0,0,0],sound:[0,0,0]}).map(([id,point])=>{const node=scene.getObjectByName(id)!;const v=boardCenters[id]?boardPoint(id,explosion.current,targets.mobile):new T.Vector3(...point);if(!boardCenters[id])node.localToWorld(v);v.project(camera);return {id,x:(v.x*.5+.5)*size.width,y:(-v.y*.5+.5)*size.height,z:v.z}}).sort((a,b)=>a.y-b.y);
 // Place labels in two lanes and back-propagate collisions inside the safe viewport.
 const top=190,bottom=size.height-205,gap=36;
 for(const left of [true,false]){const lane=projected.filter(item=>['left_panel','controls','coin'].includes(item.id)===left);const ys=lane.map((item,i)=>Math.max(top+i*gap,Math.min(bottom,item.y)));for(let i=1;i<ys.length;i++)ys[i]=Math.max(ys[i],ys[i-1]+gap);if(ys.length&&ys[ys.length-1]>bottom){ys[ys.length-1]=bottom;for(let i=ys.length-2;i>=0;i--)ys[i]=Math.min(ys[i],ys[i+1]-gap);}
 lane.forEach((item,i)=>{const el=document.getElementById('label-'+item.id);if(!el)return;const labelX=left?Math.max(40,item.x-180):Math.min(size.width-210,item.x+48);const dx=targets.mobile?0:labelX-item.x,dy=targets.mobile?0:ys[i]-item.y;el.style.transform=`translate(${item.x}px,${item.y-14}px)`;el.style.setProperty('--label-x',dx+'px');el.style.setProperty('--label-shift',dy+'px');el.style.setProperty('--leader-angle',Math.atan2(dy,dx)+'rad');el.style.setProperty('--leader-length',Math.hypot(dx,dy)+'px');el.style.visibility=(!!p.selected&&!!boardCenters[p.selected])||item.z>1||item.x<12||item.x>size.width-12||(p.selected&&p.selected!==item.id)||(p.mode==='Exploded'&&assemblyProgress(item.id,explosion.current)<.35)?'hidden':'visible';});}
 if(location.hostname==='127.0.0.1'){(window as unknown as {__arcadeDebug:unknown}).__arcadeDebug={machine:p.machine,swapping:travel.current>.02,mode:p.mode,selected:p.selected,progress:explosion.current,positions:Object.fromEntries(scene.children.map(g=>[g.name,g.position.toArray()])),input:[...p.game.keys],credits:p.game.credits,drawCalls:gl.info.render.calls,triangles:gl.info.render.triangles,frameMs:raw*1000,camera:camera.position.toArray(),audio:(p.game as ArcadeGame & {sound?:{inspect:()=>unknown}}).sound?.inspect(),game:{...(p.machine!=='robotron'&&(p.game as unknown as {stage:string}).stage?{stage:(p.game as DefenderShow).stage,wave:p.game.wave,bombs:(p.game as DefenderShow).bombs,carried:(p.game as DefenderShow).carriedHumans.length,rescued:p.game.rescued,falling:(p.game as DefenderShow).looseHumans.length,planet:(p.game as DefenderShow).planet,humans:10-(p.game as DefenderShow).deadHumans.size}:{}),...(p.machine==='joust'?{kills:(p.game as any).kills,effects:(p.game as any).renderer.effects.length,route:(p.game as any).route.length,wave:p.game.wave,rescued:p.game.rescued,phase:(p.game as any).engine.gameOver?'gameOver':'battle',enemies:(p.game as any).engine.enemies.filter((e:any)=>e.alive).length}:{}),...(p.machine==='robotron'?{wave:p.game.wave,rescued:p.game.rescued,phase:(p.game as any).phase,enemies:(p.game as any).actors.length}:{}),time:p.game.time,rescuePhase:(p.game as DefenderShow).pilotAction??'patrol',running:p.game.running,x:p.game.x,y:p.game.y,score:p.game.score,lives:p.game.lives}};}
 });
 const identify=(e:ThreeEvent<PointerEvent|MouseEvent>)=>{let o:T.Object3D|null=e.object;while(o?.parent&&o.parent!==scene){if(o.userData.inspectId){const id=o.userData.inspectId as string,layout=chipLayout(id),point=o.worldToLocal(e.point.clone());if(layout){for(const chip of layout.chips){const x=(chip.u-.5)*layout.width,y=(.5-chip.v)*layout.height,wide=(chip.pins>=22?.031:.017)+.016,long=(chip.pins/2-1)*.0065+.018;const rotated=!!chip.rotation;if(Math.abs(point.x-x)<(rotated?long:wide)/2&&Math.abs(point.y-y)<(rotated?wide:long)/2)return id+'|'+chip.ref;}}return id;}o=o.parent;}return o?.name||null;};
 return <>{p.machine==='defender'&&<><color attach="background" args={['#10100f']}/><fog attach="fog" args={['#151413',10,26]}/><ambientLight intensity={p.roomLight?.65:.1}/><hemisphereLight args={['#9dafa8','#352315',p.roomLight?.9:.26]}/><primitive object={lightTarget}/><spotLight position={[1.4,5,2]} target={lightTarget} color="#ffdcad" intensity={p.roomLight?215:165} angle={.72} penumbra={.75} castShadow shadow-mapSize={[2048,2048]} shadow-bias={-.0002} shadow-normalBias={.016} shadow-radius={2}/><spotLight position={[-3.2,3.7,4]} target={lightTarget} color="#b5c4c8" intensity={p.roomLight?75:30} angle={.6} penumbra={1}/><pointLight position={[-3,2,-1]} color="#a64560" intensity={p.roomLight?18:9}/><spotLight position={[-2,3.9,-2.4]} target={lightTarget} color="#819daa" intensity={44} angle={.62} penumbra={1}/><pointLight position={[3,2.7,-2]} color="#487e92" intensity={p.roomLight?25:12}/><pointLight position={[0,2.3,1]} color="#76bac9" intensity={p.power?.55:0}/>
 </>}<group ref={group} name={'exhibit-'+p.machine} position={initialPosition}><primitive object={scene} onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();if(e.delta>4)return;if(p.active===false){p.onActivate?.();return;}if(travel.current>.02)return;let detail:T.Object3D|null=e.object;while(detail&&detail!==scene){if(/^(button_\d|leaf_\d|stick_leaf_|joystick$|joystick_fire$|joystick_contact|coin_return_|control_harness_plug$|coin_harness_plug$)/.test(detail.name)){p.onFocus(detail.name);return;}detail=detail.parent;}const id=identify(e);if(id)p.onSelect(id==='right_panel'||id==='back_panel'||id==='chassis'?'left_panel':id);}} onPointerOver={(e:ThreeEvent<PointerEvent>)=>{e.stopPropagation();const id=identify(e);setHover(id?.split('|')[0]??null);p.onHover(id?.split('|')[0]??null);}} onPointerOut={()=>{setHover(null);p.onHover(null);}}/></group>{p.active!==false&&<><Wiring {...p} scene={scene}/><ServiceHarness scene={scene} isolated={!!p.selected&&!!boardCenters[p.selected]}/></>}
 {p.machine==='defender'&&<><ArcadeEnvironment wood={wood} marquee={marqueeArt} screen={resources.crt} quality={p.quality} reduced={p.reduced}/>
 <mesh position={[.5,4.15,.2]}><cylinderGeometry args={[.32,.48,.13,40]}/><meshStandardMaterial color="#71604b" metalness={.8} roughness={.35}/></mesh><mesh position={[.5,4.079,.2]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.445,32]}/><meshBasicMaterial color="#ffce83" toneMapped={false}/></mesh>
 <FilmFinish quality={p.quality} mode={p.roomMode||p.mode}/></>}</>;
}
const paths:{from:string;to:string;a:[number,number,number];b:[number,number,number];color:string;kind:Signal}[]=[
 {from:'controls',to:'interface',a:[-.2,2.25,.72],b:[0,.13,.02],color:'#e9b65d',kind:'input'},
 {from:'interface',to:'logic',a:[.21,0,.02],b:[-.50,.08,.02],color:'#e9b65d',kind:'input'},
 {from:'logic',to:'crt',a:[-.50,-.32,.02],b:[.3,2.80,-.20],color:'#66c9da',kind:'video'},
 {from:'rom',to:'sound',a:[-.13,.30,.02],b:[-.06,.22,.02],color:'#b987c7',kind:'audio'},
 {from:'sound',to:'speaker',a:[.08,.22,.02],b:[0,3.45,.35],color:'#b987c7',kind:'audio'},
 {from:'coin',to:'rom',a:[.15,1.8,.86],b:[-.13,.30,.02],color:'#dfa353',kind:'credit'},
 {from:'power',to:'logic',a:[-.15,.65,-.38],b:[-.50,-.32,.02],color:'#e56850',kind:'power'},
 {from:'power',to:'crt',a:[.3,.55,-.05],b:[.2,2.6,-.2],color:'#d8654e',kind:'power'},
 {from:'power',to:'marquee',a:[.25,.50,-.08],b:[.4,3.8,.25],color:'#d8654e',kind:'power'},
 {from:'ventilation',to:'speaker',a:[0,.7,-.75],b:[0,3.44,-.2],color:'#84bfd5',kind:'airflow'}];
function Wiring(p:SceneProps&{scene:T.Group}){const refs=useRef<(T.Mesh|null)[]>([]),dots=useRef<(T.Mesh|null)[]>([]);const progress=useRef(0);const last=useRef('');const creditSerial=useRef(p.game.credits);const lastCredit=useRef(-10);const curves=useRef<T.CatmullRomCurve3[]>([]);
 useFrame((_,dt)=>{progress.current+=Math.min(dt,.05)*p.speed;if(creditSerial.current!==p.game.credits){creditSerial.current=p.game.credits;lastCredit.current=progress.current;}const stamp=(p.scene.parent?.position.toArray().join()||'')+p.scene.children.map(g=>[...g.position.toArray(),...g.rotation.toArray().slice(0,3)].map(v=>Number(v).toFixed(3)).join()).join();if(stamp!==last.current||!curves.current.length){last.current=stamp;paths.forEach((path,i)=>{const endpoint=(id:string,point:[number,number,number])=>{const node=p.scene.getObjectByName(boardCenters[id]?'board_'+(id==='logic'?'cpu':id):id)!;return node.localToWorld(new T.Vector3(...point));};const a=endpoint(path.from,path.a),b=endpoint(path.to,path.b);const curve=new T.CatmullRomCurve3([a,a.clone().add(new T.Vector3(.13,0,-.19)),a.clone().lerp(b,.52).add(new T.Vector3(.10,-Math.min(.35,a.distanceTo(b)*.12),-.28)),b]);curves.current[i]=curve;const m=refs.current[i];if(m){m.geometry.dispose();m.geometry=new T.TubeGeometry(curve,22,path.kind==='airflow'?.003:.004,5,false);}});}
 paths.forEach((path,i)=>{const visible=(path.kind!=='airflow'||p.signal==='airflow')&&(!p.selected||p.signal!=='all')&&(p.mode==='Exploded'||p.mode==='X-Ray')&&(p.signal==='all'||p.signal===path.kind);if(refs.current[i])refs.current[i]!.visible=visible;const dot=dots.current[i];if(dot){const active=path.kind==='input'?p.game.keys.size>0:path.kind==='credit'?progress.current-lastCredit.current<1.8:path.kind==='audio'?performance.now()-p.game.lastAudio<450:true;dot.visible=visible&&p.signal!=='all'&&p.power&&active;if(curves.current[i])dot.position.copy(curves.current[i].getPoint(p.reduced?.5:(progress.current*.35+i*.11)%1));}});
 });return <>{paths.map((path,i)=><group key={i}><mesh ref={el=>{refs.current[i]=el}}><tubeGeometry/><meshStandardMaterial color={p.signal==='all'?'#766851':path.color} emissive={path.color} emissiveIntensity={p.signal==='all'?0:.18} roughness={.55}/></mesh><mesh ref={el=>{dots.current[i]=el}}><sphereGeometry args={[.012,8,6]}/><meshBasicMaterial color={path.color}/></mesh></group>)}</>;
}
