import {useEffect,useMemo,useRef,useState} from 'react';
import {useFrame,useLoader,useThree,ThreeEvent} from '@react-three/fiber';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ArcadeGame} from './game';
import {cabinetRoot} from './model';
import {ArcadeEnvironment,FilmFinish} from './Environment';
import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';
import {Mode,Signal,offsets} from './data';
import {assemblyOffset} from './choreography';
import {boardCenters,boardPoint,hardwareTextures} from './Hardware';
import {crtMaterial} from './CRT';
import {surfaceTextures} from './SurfaceTextures';
import {chipLayout} from './ChipNotes';
export interface SceneProps{mode:Mode;speed:number;power:boolean;cabinetLight:boolean;roomLight:boolean;reduced:boolean;quality:string;reset:number;selected:string|null;signal:Signal;game:ArcadeGame;onSelect:(id:string)=>void;onReady:()=>void;onHover:(id:string|null)=>void;}
const anchor:Record<string,[number,number,number]>={left_panel:[-.72,2.45,.03],controls:[.35,2.43,.88],coin:[.25,1.8,1],power:[.5,.9,.1],logic:[.49,2.04,-.2],crt:[.5,3.01,.5],speaker:[.2,3.55,.55],ventilation:[.43,.7,-.55]};
function textTexture(lines:string[],bg:string,fg:string,w=1024,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const a=c.getContext('2d')!;a.fillStyle=bg;a.fillRect(0,0,w,h);a.strokeStyle=fg;a.lineWidth=3;a.strokeRect(12,12,w-24,h-24);a.textAlign='center';lines.forEach((line,i)=>{a.font=`${i===0?'italic bold':'normal'} ${i===0?h*.5:h*.11}px monospace`;a.fillStyle=fg;a.fillText(line,w/2,h*(i===0?.6:.83));});const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function defenderMarquee(){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=256;const c=canvas.getContext('2d')!;c.fillStyle='#060e1a';c.fillRect(0,0,1024,256);for(let i=0;i<160;i++){const x=(i*137)%1024,y=(i*71)%256;c.fillStyle=i%4?'#adcae0':'#ffe5a0';c.fillRect(x,y,i%7?2:4,i%7?2:4);}c.strokeStyle='#387aa9';c.lineWidth=12;c.beginPath();c.ellipse(530,164,540,85,-.12,0,Math.PI*2);c.stroke();c.fillStyle='#be4626';c.beginPath();c.arc(965,50,85,0,Math.PI*2);c.fill();c.strokeStyle='#e3a447';c.lineWidth=7;c.stroke();c.font='italic 900 159px Impact, sans-serif';c.textAlign='center';c.fillStyle='#b8271b';for(let y=15;y>0;y-=3)c.fillText('DEFENDER',505-y,185+y,935);const ink=c.createLinearGradient(0,65,0,185);ink.addColorStop(0,'#fff99b');ink.addColorStop(.6,'#ffe256');ink.addColorStop(1,'#e9a323');c.fillStyle=ink;c.fillText('DEFENDER',505,185,935);c.strokeStyle='#c39753';c.lineWidth=3;c.strokeRect(7,7,1010,242);const t=new T.CanvasTexture(canvas);t.colorSpace=T.SRGBColorSpace;return t;}
function controlTexture(){const c=document.createElement('canvas');c.width=1536;c.height=640;const a=c.getContext('2d')!;const W=c.width,H=c.height;const px=(x:number)=>(x+.645)/1.29*W,py=(z:number)=>(z-.3585)/.505*H;a.fillStyle='#121414';a.fillRect(0,0,W,H);
 const box=(x:number,y:number,w:number,h:number,color:string)=>{a.fillStyle=color;a.fillRect(x,y,w,h);a.strokeStyle='#bcbb94';a.lineWidth=3;a.strokeRect(x,y,w,h);};
 // Draw the striped instrument-grid layout in code, with legends aligned to model holes.
 for(let i=0;i<28;i++){const x=30+i*53;box(x,32,43,240,'#171b18');for(const [j,color]of ['#c52221','#dfb62c','#278443'].entries()){a.fillStyle=color;a.fillRect(x+2,90+((i*29+j*39)%140),39,12+j*4);}}
 box(550,28,413,439,'#171a18');box(587,111,335,113,'#205d9b');box(587,239,335,202,'#17191a');
 a.fillStyle='#ba2529';a.beginPath();for(let i=0;i<24;i++){const angle=i*Math.PI/12,rr=i%2?42:174;a.lineTo(750+Math.cos(angle)*rr,338+Math.sin(angle)*rr*.52);}a.closePath();a.fill();
 for(let i=0;i<24;i++){const x=34+i*62;box(x,469,48,115,'#141916');for(const [j,color]of ['#c52b2c','#d6b929','#20824e'].entries()){a.fillStyle=color;a.fillRect(x+2,489+j*23+(i%3)*6,44,13);}}
 box(551,471,412,111,'#2266a2');for(let j=0;j<4;j++){a.strokeStyle='#111c28';a.beginPath();a.moveTo(554,481+j*26);a.lineTo(960,481+j*26);a.stroke();}
 box(56,293,440,153,'#181b19');box(1000,263,227,176,'#191a19');box(1240,298,237,143,'#151b18');a.strokeStyle='#b92d36';a.lineWidth=4;for(let i=0;i<8;i++){a.beginPath();a.moveTo(1254+(i*29)%200,311);a.lineTo(1254+(i*67)%200,426);a.stroke();}
 a.fillStyle='#bc2528';a.fillRect(24,600,W-48,23);a.strokeStyle='#c3bc96';a.lineWidth=4;a.strokeRect(21,21,W-42,H-42);
 a.textAlign='center';a.font='bold 22px monospace';for(const [x,z,label]of [[-.36,.73,'REVERSE'],[.32,.49,'THRUST'],[.46,.49,'FIRE'],[.24,.65,'SMART BOMB'],[0,.80,'HYPERSPACE'],[-.12,.46,'1 PLAYER'],[.12,.46,'2 PLAYERS']] as [number,number,string][]){const xx=px(x),yy=py(z),start=label.includes('PLAYER');a.fillStyle='#c9c5a2';a.fillText(label,xx,start?yy+75:label==='HYPERSPACE'?620:yy-59);}
 a.fillStyle='#c9c5a2';a.font='bold 22px monospace';a.fillText('GAME START',768,67);a.fillStyle='#bcb992';a.fillRect(px(-.48)-22,py(.57)-90,44,181);a.fillStyle='#c9c5a2';a.fillText('UP',px(-.48),py(.57)-107);a.fillText('DOWN',px(-.48),py(.57)+119);
 // Small deterministic scuffs preserve the legibility of the printed legends.
 let seed=1981;for(let i=0;i<900;i++){seed=(seed*1664525+1013904223)>>>0;const x=seed%W;seed=(seed*1664525+1013904223)>>>0;const y=seed%H;a.fillStyle=i%3?'#10110f55':'#d1c39c44';a.fillRect(x,y,1+i%4,1);}
 const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.anisotropy=8;return t;}
function wearTexture(){const c=document.createElement('canvas');c.width=c.height=256;const a=c.getContext('2d')!;a.fillStyle='#8b8b8b';a.fillRect(0,0,256,256);let s=713;const r=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};for(let i=0;i<12000;i++){a.fillStyle=`rgba(${r()>.5?'230,230,215':'15,20,18'},${r()*.24})`;a.fillRect(r()*256,r()*256,r()*2+.2,r()*7+.4);}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,4);return t;}
export function Scene(p:SceneProps){const {camera,gl,size}=useThree();const {scene:loaded}=useLoader(GLTFLoader,'./cabinet.glb',loader=>loader.setMeshoptDecoder(MeshoptDecoder));const art=useLoader(T.TextureLoader,'./side-art.webp');const [wood,woodNormal,woodRough,marqueeArt]=useLoader(T.TextureLoader,['./cabinet-albedo.webp','./cabinet-normal.webp','./cabinet-roughness.webp','./marquee.webp']);const scene=useMemo(()=>cabinetRoot(loaded),[loaded]);const group=useRef<T.Group>(null);const orbit=useRef<OrbitControls|null>(null);const moving=useRef(true);const explosion=useRef(0);const lightTarget=useMemo(()=>{const o=new T.Object3D();o.position.set(0,1.6,0);return o},[]);const currentMode=useRef(p.mode);const clock=useRef(0);const startup=useRef(0);const credit=useRef(p.game.credits);const coinTime=useRef(4);const [hover,setHover]=useState<string|null>(null);
 const surfaces=useMemo(()=>surfaceTextures(),[]);
 const hardwareMaps=useMemo(()=>hardwareTextures(scene),[scene]);
 const resources=useMemo(()=>({crt:new T.CanvasTexture(p.game.canvas),marquee:defenderMarquee(),controls:controlTexture(),coin:textTexture(['25¢','PUSH TO REJECT'],'#4f1308','#ef8b36',256,256),warning:textTexture(['!','HIGH VOLTAGE'],'#d8ac38','#161b19',256,256),tag:textTexture(['81','RESTORED / JZ'],'#cabca0','#3c3630',256,256),wear:wearTexture()}),[p.game]);
 useEffect(()=>{wood.colorSpace=T.SRGBColorSpace;marqueeArt.colorSpace=T.SRGBColorSpace;for(const t of [wood,woodNormal,woodRough]){t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(1,2);t.anisotropy=4;}art.anisotropy=8;art.colorSpace=T.SRGBColorSpace;art.flipY=true;resources.crt.colorSpace=T.SRGBColorSpace;resources.crt.flipY=true;resources.crt.minFilter=T.LinearMipmapLinearFilter;resources.crt.magFilter=T.NearestFilter;resources.crt.generateMipmaps=true;resources.crt.anisotropy=Math.min(8,gl.capabilities.getMaxAnisotropy());for(const t of [wood,woodNormal,woodRough,marqueeArt,art,resources.crt])t.needsUpdate=true;
 scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const m=(o.material as T.MeshStandardMaterial).clone();o.material=m;
 if(hardwareMaps[m.name]){m.map=hardwareMaps[m.name];m.color.set('#fff');m.roughness=.88;}
 if(['circuit_board','monitor_board'].includes(m.name)){m.map=surfaces.board;m.roughnessMap=surfaces.rough;m.bumpMap=surfaces.rough;m.bumpScale=.0005;}if(['integrated_circuit','aged_plastic','button_red','button_green','bezel_face','speaker_face'].includes(m.name)){m.roughnessMap=surfaces.plastic;m.bumpMap=surfaces.plastic;m.bumpScale=.00035;}if(m.name==='aged_label'){m.map=surfaces.paper;}
 if(o.name.endsWith('_print')&&m.name==='side_print'){m.map=art;m.color.set('#c3b59b');m.roughness=.8;}
 else if(m.name==='painted_wood'){m.map=wood;m.normalMap=woodNormal;m.normalScale.set(.45,.45);m.roughnessMap=woodRough;m.color.set('#ded6c0');}else if(['aged_steel','zinc_bracket','black_metal','raw_plywood','brass'].includes(m.name)){m.roughnessMap=resources.wear;m.bumpMap=resources.wear;m.bumpScale=.0015;}
 if(o.name==='crt_screen'){m.map=resources.crt;m.emissiveMap=resources.crt;m.emissive.set('#ffffff');m.emissiveIntensity=1.5;m.color.set('#000000');m.roughness=1;m.metalness=0;m.envMapIntensity=0;m.toneMapped=false;}
 if(o.name==='marquee_print'){m.map=resources.marquee;m.emissiveMap=resources.marquee;m.emissive.set('#fff');m.color.set('#000');m.envMapIntensity=0;m.roughness=1;m.toneMapped=false;}
 if(o.name==='control_print'){m.map=resources.controls;m.color.set('#fff');m.metalness=0;m.roughness=.82;}
 if(o.name==='warning_label'){m.map=resources.warning;m.color.set('#fff');}
 if(m.name.startsWith('coin_lamp')){m.map=resources.coin;m.emissiveMap=resources.coin;m.color.set('#151009');m.toneMapped=false;}if(o.name==='service_tag'){m.map=resources.tag;m.color.set('#fff');}
 if(['bezel_face','speaker_face'].includes(m.name)){o.material=new T.MeshLambertMaterial({name:m.name,color:m.color,bumpMap:surfaces.plastic,bumpScale:.00035});m.dispose();}
 m.needsUpdate=true;if(o.name==='crt_screen'){o.material=crtMaterial(resources.crt);o.frustumCulled=false;o.receiveShadow=false;m.dispose();}}});p.onReady();return()=>{scene.traverse(o=>{if(o instanceof T.Mesh)(o.material as T.Material).dispose()});Object.values(resources).forEach(t=>t.dispose());Object.values(hardwareMaps).forEach(t=>t.dispose());Object.values(surfaces).forEach(t=>t.dispose());};},[scene]);
 useEffect(()=>{const c=new OrbitControls(camera,gl.domElement);c.enableDamping=true;c.dampingFactor=.065;c.minDistance=2.4;c.maxDistance=12;c.maxPolarAngle=Math.PI*.49;c.minPolarAngle=.35;c.target.set(0,1.7,0);c.addEventListener('start',()=>{moving.current=false});orbit.current=c;return()=>c.dispose();},[camera,gl]);
 useEffect(()=>{moving.current=true;currentMode.current=p.mode;},[p.mode,p.reset,p.selected,size.width]);
 useEffect(()=>{if(p.power)startup.current=0;},[p.power]);
 const targets=useMemo(()=>{
  const mobile=size.width<760;let pos=new T.Vector3(...(mobile?(p.mode==='Exploded'?[2.3,2.9,12.2]:p.mode==='Watch'?[.05,2.55,3.35]:[2.8,2.65,8.1]):p.mode==='Watch'?[.06,2.58,1.95]:p.mode==='Exploded'?[4.3,2.85,7]:p.mode==='X-Ray'?[3.6,2.7,6.5]:[3.2,2.55,6]) as [number,number,number]);let target=p.mode==='Watch'?new T.Vector3(0,mobile?2.32:2.45,.39):new T.Vector3(.15,1.72,0);
  if(p.selected&&(anchor[p.selected]||boardCenters[p.selected])){const board=!!boardCenters[p.selected];const point=board?boardPoint(p.selected,p.mode==='Exploded'?1:0,mobile):new T.Vector3(...anchor[p.selected]).add(new T.Vector3(...assemblyOffset(p.selected,p.mode==='Exploded'?1:0,mobile))).multiplyScalar(.84);const distance=p.selected==='left_panel'?5:board?(mobile?({logic:4.1,rom:3,interface:2.4,sound:2.7}[p.selected as 'logic']):p.selected==='logic'?2.15:1.65):3.1;target=point.clone().add(new T.Vector3(mobile?0:.38,mobile?-.35:0,0));pos=point.clone().add(new T.Vector3(board?0:p.selected==='controls'?.15:distance*.34,board?.02:p.selected==='controls'?1.8:.35,p.selected==='controls'?2.2:distance));if(board)target=point.clone().add(new T.Vector3(mobile?0:.20,mobile?-distance*.125:0,0));}
  return {pos,target,mobile};
 },[p.mode,p.selected,size.width]);
 useFrame((_,raw)=>{const dt=Math.min(raw,.05),d=p.reduced?1:1-Math.exp(-dt*4*p.speed);clock.current+=dt*p.speed;startup.current+=dt;const c=orbit.current;if(c){c.enabled=true;c.minDistance=p.selected&&boardCenters[p.selected]?.65:p.mode==='Watch'?1.2:2.4;if(moving.current){const pos=targets.pos.clone();camera.position.lerp(pos,d);c.target.lerp(targets.target,d);if(camera.position.distanceTo(pos)<.01)moving.current=false;}c.autoRotate=p.mode==='Hero'&&!p.reduced&&!moving.current&&!p.selected;c.autoRotateSpeed=.08*p.speed;c.update();}
 const cover=scene.getObjectByName('speaker_cover');if(cover)cover.visible=p.mode==='Hero'||p.mode==='Watch';const explode=p.mode==='Exploded';explosion.current=T.MathUtils.lerp(explosion.current,explode?1:0,p.reduced?1:1-Math.exp(-dt*2.4*p.speed));scene.children.forEach(g=>g.position.set(...assemblyOffset(g.name,explosion.current,targets.mobile)));const tray=scene.getObjectByName('board_tray');if(tray){tray.position.set(-.57*(1-explosion.current),1.90,-.17*(1-explosion.current));tray.rotation.set(0,(1-explosion.current)*Math.PI/2,(1-explosion.current)*Math.PI/2);}const inspecting=p.selected&&boardCenters[p.selected];if(tray)for(const child of tray.children)if(!child.name.startsWith('board_'))child.visible=!inspecting;for(const g of scene.children)g.visible=inspecting?g.name==='logic':!((p.mode==='Hero'||p.mode==='Watch')&&['logic','power'].includes(g.name));for(const [id]of Object.entries(boardCenters)){const board=scene.getObjectByName('board_'+(id==='logic'?'cpu':id));if(board)board.visible=!inspecting||p.selected===id;}scene.updateMatrixWorld(true);
 scene.traverse(o=>{if(o instanceof T.Mesh){const m=o.material as T.MeshStandardMaterial;let parent:T.Object3D|null=o;while(parent?.parent&&parent.parent!==scene)parent=parent.parent;const id=parent?.name;const shell=['left_panel','right_panel','back_panel','coin','marquee','controls'].includes(id||'');const transparent=p.mode==='X-Ray'&&shell;const opacity=transparent?.13:1;if(m.transparent!==transparent){m.transparent=transparent;m.depthWrite=!transparent;m.needsUpdate=true;}m.opacity=T.MathUtils.lerp(m.opacity,opacity,d);
 if(o.name==='crt_screen'){m.emissiveIntensity=p.power?1:0;const warm=p.reduced?1:Math.min(1,startup.current/1.3);o.scale.y=p.power?Math.max(.01,warm):.004;}
 else if(o.name==='marquee_print')m.emissiveIntensity=p.power&&p.cabinetLight?(startup.current<1.2&&!p.reduced?Math.sin(startup.current*45)>.1?.95:.1:.9):0;
 else if(m.name.startsWith('coin_lamp')){m.emissive.set(p.power?'#fff':'#000');m.emissiveIntensity=.85;}
 else if((id===p.selected||id===hover)&&!['bezel_face','speaker_face'].includes(m.name)){m.emissive.set('#71512a');m.emissiveIntensity=.2;}else {m.emissive.set('#000');}
 }});
 const joy=scene.getObjectByName('joystick');if(joy){joy.rotation.z=0;joy.rotation.x=T.MathUtils.lerp(joy.rotation.x,p.game.keys.has('ArrowUp')?-.2:p.game.keys.has('ArrowDown')?.2:0,d);}
 for(let i=0;i<7;i++){const b=scene.getObjectByName('button_'+i);if(b)b.position.y=T.MathUtils.lerp(b.position.y,p.game.keys.has(['KeyR','KeyT','Space','KeyB','KeyH','Digit1','Digit2'][i])?1.750:1.769,d);}
 const fan=scene.getObjectByName('fan_rotor');if(fan&&p.power&&!p.reduced)fan.rotation.z+=dt*p.speed*7;
 const cone=scene.getObjectByName('speaker_cone');if(cone)cone.scale.y=1+(p.power&&performance.now()-p.game.lastAudio<300&&!p.reduced?Math.sin(clock.current*60)*.07:0);
 if(credit.current!==p.game.credits){credit.current=p.game.credits;coinTime.current=0;}coinTime.current+=dt;const coin=scene.getObjectByName('travelling_coin');if(coin){coin.visible=coinTime.current<1.4;coin.position.y=1.2-Math.min(.58,coinTime.current*.45);coin.rotation.z=coinTime.current*7;}for(let i=0;i<7;i++){const leaf=scene.getObjectByName('leaf_'+i);if(leaf){const pressed=p.game.keys.has(['KeyR','KeyT','Space','KeyB','KeyH','Digit1','Digit2'][i]);leaf.rotation.z=pressed?-.045:0;leaf.position.y=T.MathUtils.lerp(leaf.position.y,pressed?1.510:1.515,d);}}resources.crt.needsUpdate=true;
 const projected=Object.entries({...anchor,rom:[0,0,0],interface:[0,0,0],sound:[0,0,0]}).map(([id,point])=>{const node=scene.getObjectByName(id)!;const v=boardCenters[id]?boardPoint(id,explosion.current,targets.mobile):new T.Vector3(...point);if(!boardCenters[id])node.localToWorld(v);v.project(camera);return {id,x:(v.x*.5+.5)*size.width,y:(-v.y*.5+.5)*size.height,z:v.z}}).sort((a,b)=>a.y-b.y);
 const placed:{x:number,y:number}[]=[];
 for(const item of projected){const el=document.getElementById('label-'+item.id);if(!el)continue;let labelY=Math.max(180,Math.min(size.height-185,item.y));for(const prev of placed){if(Math.abs(prev.x-item.x)<200&&Math.abs(prev.y-labelY)<34)labelY=prev.y+34;}placed.push({x:item.x,y:labelY});const dy=targets.mobile?0:labelY-item.y;el.style.transform=`translate(${item.x}px,${item.y-14}px)`;el.style.setProperty('--label-shift',dy+'px');el.style.setProperty('--leader-angle',Math.atan2(dy,32)+'rad');el.style.setProperty('--leader-length',Math.sqrt(1024+dy*dy)+'px');el.style.visibility=(!!p.selected&&!!boardCenters[p.selected])||item.z>1||item.x<12||item.x>size.width-12||(p.selected&&p.selected!==item.id)?'hidden':'visible';}
 if(location.hostname==='127.0.0.1'){(window as unknown as {__arcadeDebug:unknown}).__arcadeDebug={mode:p.mode,selected:p.selected,progress:explosion.current,positions:Object.fromEntries(scene.children.map(g=>[g.name,g.position.toArray()])),input:[...p.game.keys],credits:p.game.credits,drawCalls:gl.info.render.calls,triangles:gl.info.render.triangles,frameMs:raw*1000,camera:camera.position.toArray(),audio:(p.game as ArcadeGame & {sound?:{inspect:()=>unknown}}).sound?.inspect(),game:{time:p.game.time,rescuePhase:(p.game as ArcadeGame & {mission?:{phase:string}}).mission?.phase??'patrol',running:p.game.running,x:p.game.x,y:p.game.y,score:p.game.score,lives:p.game.lives}};}
 });
 const identify=(e:ThreeEvent<PointerEvent|MouseEvent>)=>{let o:T.Object3D|null=e.object;while(o?.parent&&o.parent!==scene){if(o.userData.inspectId){const id=o.userData.inspectId as string,layout=chipLayout(id),point=o.worldToLocal(e.point.clone());if(layout){for(const chip of layout.chips){const x=(chip.u-.5)*layout.width,y=(.5-chip.v)*layout.height,wide=(chip.pins>=22?.031:.017)+.016,long=(chip.pins/2-1)*.0065+.018;const rotated=!!chip.rotation;if(Math.abs(point.x-x)<(rotated?long:wide)/2&&Math.abs(point.y-y)<(rotated?wide:long)/2)return id+'|'+chip.ref;}}return id;}o=o.parent;}return o?.name||null;};
 return <><color attach="background" args={['#10100f']}/><fog attach="fog" args={['#151413',10,26]}/><ambientLight intensity={p.roomLight?.65:.1}/><hemisphereLight args={['#9dafa8','#352315',p.roomLight?.9:.26]}/><primitive object={lightTarget}/><spotLight position={[1.4,5,2]} target={lightTarget} color="#ffd29a" intensity={p.roomLight?230:170} angle={.72} penumbra={.75} castShadow shadow-mapSize={[2048,2048]} shadow-bias={-.0002} shadow-normalBias={.012}/><spotLight position={[-3.2,3.7,4]} target={lightTarget} color="#b5c4c8" intensity={p.roomLight?65:36} angle={.6} penumbra={1}/><pointLight position={[-3,2,-1]} color="#a64560" intensity={p.roomLight?18:9}/><pointLight position={[3,2.7,-2]} color="#487e92" intensity={p.roomLight?25:12}/><pointLight position={[0,2.3,1]} color="#76bac9" intensity={p.power?.1:0}/>
 <group ref={group}><primitive object={scene} onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();if(e.delta>4)return;const id=identify(e);if(id)p.onSelect(id==='right_panel'||id==='back_panel'||id==='chassis'?'left_panel':id);}} onPointerOver={(e:ThreeEvent<PointerEvent>)=>{e.stopPropagation();const id=identify(e);setHover(id?.split('|')[0]??null);p.onHover(id?.split('|')[0]??null);}} onPointerOut={()=>{setHover(null);p.onHover(null);}}/><Wiring {...p} scene={scene}/></group>
 <ArcadeEnvironment wood={wood} marquee={marqueeArt} screen={resources.crt} quality={p.quality} reduced={p.reduced}/>
 <mesh position={[.5,4.15,.2]}><cylinderGeometry args={[.32,.48,.13,40]}/><meshStandardMaterial color="#71604b" metalness={.8} roughness={.35}/></mesh><mesh position={[.5,4.079,.2]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.445,32]}/><meshBasicMaterial color="#ffce83" toneMapped={false}/></mesh>
 <FilmFinish quality={p.quality}/></>;
}
const paths:{from:string;to:string;a:[number,number,number];b:[number,number,number];color:string;kind:Signal}[]=[
 {from:'controls',to:'interface',a:[-.2,2.25,.72],b:[0,.13,.02],color:'#e9b65d',kind:'input'},
 {from:'interface',to:'logic',a:[.21,0,.02],b:[-.50,.08,.02],color:'#e9b65d',kind:'input'},
 {from:'logic',to:'crt',a:[-.50,-.32,.02],b:[.3,2.80,-.20],color:'#66c9da',kind:'video'},
 {from:'rom',to:'sound',a:[-.13,.30,.02],b:[-.06,.22,.02],color:'#b987c7',kind:'audio'},
 {from:'sound',to:'speaker',a:[.08,.22,.02],b:[0,3.45,.35],color:'#b987c7',kind:'audio'},
 {from:'coin',to:'rom',a:[.15,1.8,.86],b:[-.13,.30,.02],color:'#dfa353',kind:'credit'},
 {from:'power',to:'logic',a:[-.15,.65,-.38],b:[-.50,-.32,.02],color:'#e56850',kind:'power'},
 {from:'power',to:'crt',a:[.3,.55,-.05],b:[.2,2.6,-.2],color:'#d8654e',kind:'power'},
 {from:'power',to:'marquee',a:[.25,.50,-.08],b:[.4,3.8,.25],color:'#d8654e',kind:'power'},
 {from:'ventilation',to:'speaker',a:[0,.7,-.75],b:[0,3.44,-.2],color:'#84bfd5',kind:'airflow'}];
function Wiring(p:SceneProps&{scene:T.Group}){const refs=useRef<(T.Mesh|null)[]>([]),dots=useRef<(T.Mesh|null)[]>([]);const progress=useRef(0);const last=useRef('');const creditSerial=useRef(p.game.credits);const lastCredit=useRef(-10);const curves=useRef<T.CatmullRomCurve3[]>([]);
 useFrame((_,dt)=>{progress.current+=Math.min(dt,.05)*p.speed;if(creditSerial.current!==p.game.credits){creditSerial.current=p.game.credits;lastCredit.current=progress.current;}const stamp=p.scene.children.map(g=>g.position.toArray().map(v=>v.toFixed(3)).join()).join();if(stamp!==last.current||!curves.current.length){last.current=stamp;paths.forEach((path,i)=>{const endpoint=(id:string,point:[number,number,number])=>{const node=p.scene.getObjectByName(boardCenters[id]?'board_'+(id==='logic'?'cpu':id):id)!;return node.localToWorld(new T.Vector3(...point));};const a=endpoint(path.from,path.a),b=endpoint(path.to,path.b);const curve=new T.CatmullRomCurve3([a,a.clone().add(new T.Vector3(.13,0,-.19)),a.clone().lerp(b,.52).add(new T.Vector3(.15,0,-.25)),b]);curves.current[i]=curve;const m=refs.current[i];if(m){m.geometry.dispose();m.geometry=new T.TubeGeometry(curve,22,path.kind==='airflow'?.003:.004,5,false);}});}
 paths.forEach((path,i)=>{const visible=(!p.selected||p.signal!=='all')&&(p.mode==='Exploded'||p.mode==='X-Ray')&&(p.signal==='all'||p.signal===path.kind);if(refs.current[i])refs.current[i]!.visible=visible;const dot=dots.current[i];if(dot){const active=path.kind==='input'?p.game.keys.size>0:path.kind==='credit'?progress.current-lastCredit.current<1.8:path.kind==='audio'?performance.now()-p.game.lastAudio<450:true;dot.visible=visible&&p.power&&active;if(curves.current[i])dot.position.copy(curves.current[i].getPoint(p.reduced?.5:(progress.current*.35+i*.11)%1));}});
 });return <>{paths.map((path,i)=><group key={i}><mesh ref={el=>{refs.current[i]=el}}><tubeGeometry/><meshStandardMaterial color={path.color} emissive={path.color} emissiveIntensity={.06} roughness={.55}/></mesh><mesh ref={el=>{dots.current[i]=el}}><sphereGeometry args={[.012,8,6]}/><meshBasicMaterial color={path.color}/></mesh></group>)}</>;
}
