import {useEffect,useMemo,useRef,useState} from 'react';
import {useFrame,useLoader,useThree,ThreeEvent} from '@react-three/fiber';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {ArcadeGame} from './game';
import {cabinetRoot} from './model';
import {Mode,Signal,offsets} from './data';
export interface SceneProps{mode:Mode;speed:number;power:boolean;cabinetLight:boolean;roomLight:boolean;reduced:boolean;quality:string;reset:number;selected:string|null;signal:Signal;game:ArcadeGame;onSelect:(id:string)=>void;onReady:()=>void;onHover:(id:string|null)=>void;}
const anchor:Record<string,[number,number,number]>={left_panel:[-.72,2.45,.03],controls:[.55,1.74,.7],coin:[.25,1,.72],power:[.5,.9,.1],logic:[.49,2.04,-.2],crt:[.6,2.45,.5],speaker:[.2,2.92,.55],ventilation:[.43,.7,-.55]};
function textTexture(lines:string[],bg:string,fg:string,w=1024,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const a=c.getContext('2d')!;a.fillStyle=bg;a.fillRect(0,0,w,h);a.strokeStyle=fg;a.lineWidth=3;a.strokeRect(12,12,w-24,h-24);a.textAlign='center';lines.forEach((line,i)=>{a.font=`${i===0?'italic bold':'normal'} ${i===0?h*.5:h*.11}px monospace`;a.fillStyle=fg;a.fillText(line,w/2,h*(i===0?.6:.83));});const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;}
function wearTexture(){const c=document.createElement('canvas');c.width=c.height=256;const a=c.getContext('2d')!;a.fillStyle='#8b8b8b';a.fillRect(0,0,256,256);let s=713;const r=()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296};for(let i=0;i<12000;i++){a.fillStyle=`rgba(${r()>.5?'230,230,215':'15,20,18'},${r()*.24})`;a.fillRect(r()*256,r()*256,r()*2+.2,r()*7+.4);}const t=new T.CanvasTexture(c);t.wrapS=t.wrapT=T.RepeatWrapping;t.repeat.set(2,4);return t;}
export function Scene(p:SceneProps){const {camera,gl,size}=useThree();const {scene:loaded}=useLoader(GLTFLoader,'./cabinet.glb');const art=useLoader(T.TextureLoader,'./side-art.webp');const scene=useMemo(()=>cabinetRoot(loaded),[loaded]);const group=useRef<T.Group>(null);const orbit=useRef<OrbitControls|null>(null);const moving=useRef(true);const currentMode=useRef(p.mode);const clock=useRef(0);const startup=useRef(0);const credit=useRef(p.game.credits);const coinTime=useRef(4);const [hover,setHover]=useState<string|null>(null);
 const resources=useMemo(()=>({crt:new T.CanvasTexture(p.game.canvas),marquee:textTexture(['STARWARD','SPACE RESCUE / 1981'],'#140e09','#ffcc5d'),controls:textTexture(['FLIGHT     FIRE','REVERSE · THRUST · RESCUE'],'#191b1c','#c6a879',1024,256),warning:textTexture(['!','HIGH VOLTAGE'],'#d8ac38','#161b19',256,256),tag:textTexture(['81','RESTORED / JZ'],'#cabca0','#3c3630',256,256),wear:wearTexture()}),[p.game]);
 useEffect(()=>{art.colorSpace=T.SRGBColorSpace;art.flipY=false;resources.crt.colorSpace=T.SRGBColorSpace;resources.crt.flipY=false;resources.crt.minFilter=T.LinearFilter;resources.crt.magFilter=T.LinearFilter;resources.crt.generateMipmaps=false;
 scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const m=(o.material as T.MeshStandardMaterial).clone();o.material=m;
 if(o.name.endsWith('_wood')){m.map=art;m.color.set('#fff');m.roughness=.78;}
 else if(m.name==='painted_wood'||m.name==='aged_steel'){m.roughnessMap=resources.wear;m.bumpMap=resources.wear;m.bumpScale=.008;}
 if(o.name==='crt_screen'){m.map=resources.crt;m.emissiveMap=resources.crt;m.emissive.set('#ffffff');m.emissiveIntensity=1.5;m.color.set('#aaaaaa');m.roughness=.17;}
 if(o.name==='marquee_print'){m.map=resources.marquee;m.emissiveMap=resources.marquee;m.emissive.set('#fff');m.color.set('#fff');}
 if(o.name==='control_print'){m.map=resources.controls;m.color.set('#fff');}
 if(o.name==='warning_label'){m.map=resources.warning;m.color.set('#fff');}
 if(o.name==='service_tag'){m.map=resources.tag;m.color.set('#fff');}
 }});p.onReady();return()=>{scene.traverse(o=>{if(o instanceof T.Mesh)(o.material as T.Material).dispose()});Object.values(resources).forEach(t=>t.dispose());};},[scene]);
 useEffect(()=>{const c=new OrbitControls(camera,gl.domElement);c.enableDamping=true;c.dampingFactor=.065;c.minDistance=2.4;c.maxDistance=12;c.maxPolarAngle=Math.PI*.51;c.minPolarAngle=.35;c.target.set(0,1.7,0);c.addEventListener('start',()=>{moving.current=false});orbit.current=c;return()=>c.dispose();},[camera,gl]);
 useEffect(()=>{moving.current=true;currentMode.current=p.mode;},[p.mode,p.reset,size.width]);
 useEffect(()=>{if(p.power)startup.current=0;},[p.power]);
 const targets=useMemo(()=>{const mobile=size.width<760;return {pos:new T.Vector3(...(p.mode==='Play'?[0,2.38,2.9]:p.mode==='Exploded'?[4.65,3.05,7.5]:p.mode==='X-Ray'?[3.5,2.7,6.5]:[3.7,2.45,5.7]) as [number,number,number]),target:new T.Vector3(p.mode==='Hero'&&!mobile?-.65:.3,1.74,0),mobile}},[p.mode,size.width]);
 useFrame((_,raw)=>{const dt=Math.min(raw,.05),d=p.reduced?1:1-Math.exp(-dt*4*p.speed);clock.current+=dt*p.speed;startup.current+=dt;const c=orbit.current;if(c){c.enabled=p.mode!=='Play';if(moving.current){const pos=targets.pos.clone();if(targets.mobile)pos.multiplyScalar(p.mode==='Exploded'?1.2:1.15);camera.position.lerp(pos,d);c.target.lerp(targets.target,d);if(camera.position.distanceTo(pos)<.01)moving.current=false;}c.autoRotate=p.mode==='Hero'&&!p.reduced&&!moving.current;c.autoRotateSpeed=.22*p.speed;c.update();}
 const explode=p.mode==='Exploded';scene.children.forEach(g=>{const off=offsets[g.name]||[0,0,0];g.position.lerp(new T.Vector3(...off).multiplyScalar(explode?1:0),d);});
 scene.traverse(o=>{if(o instanceof T.Mesh){const m=o.material as T.MeshStandardMaterial;let parent:T.Object3D|null=o;while(parent?.parent&&parent.parent!==scene)parent=parent.parent;const id=parent?.name;const shell=['left_panel','right_panel','back_panel','coin','marquee','controls'].includes(id||'');const transparent=p.mode==='X-Ray'&&shell;const opacity=transparent?.13:1;if(m.transparent!==transparent){m.transparent=transparent;m.depthWrite=!transparent;m.needsUpdate=true;}m.opacity=T.MathUtils.lerp(m.opacity,opacity,d);
 if(o.name==='crt_screen'){m.emissiveIntensity=p.power?1.3:0;const warm=p.reduced?1:Math.min(1,startup.current/1.3);o.scale.y=p.power?Math.max(.01,warm):.004;}
 else if(o.name==='marquee_print')m.emissiveIntensity=p.power&&p.cabinetLight?(startup.current<1.2&&!p.reduced?Math.sin(startup.current*45)>.1?1.3:.1:1.1):0;
 else if(m.name==='coin_lamp'){m.emissive.set(p.power?'#ff5b18':'#000');m.emissiveIntensity=.6;}
 else if(id===p.selected||id===hover){m.emissive.set('#71512a');m.emissiveIntensity=.2;}else {m.emissive.set('#000');}
 }});
 const joy=scene.getObjectByName('joystick');if(joy){joy.rotation.z=T.MathUtils.lerp(joy.rotation.z,p.game.keys.has('ArrowRight')||p.game.keys.has('KeyD')?-.25:p.game.keys.has('ArrowLeft')||p.game.keys.has('KeyA')?.25:0,d);joy.rotation.x=T.MathUtils.lerp(joy.rotation.x,p.game.keys.has('ArrowUp')?-.2:p.game.keys.has('ArrowDown')?.2:0,d);}
 for(let i=0;i<6;i++){const b=scene.getObjectByName('button_'+i);if(b)b.position.y=T.MathUtils.lerp(b.position.y,p.game.keys.has('Space')&&i===2?1.739:1.757,d);}
 const fan=scene.getObjectByName('fan_rotor');if(fan&&p.power&&!p.reduced)fan.rotation.z+=dt*p.speed*7;
 const cone=scene.getObjectByName('speaker_cone');if(cone)cone.scale.y=1+(p.power&&!p.game.muted&&!p.reduced?Math.sin(clock.current*60)*.07:0);
 if(credit.current!==p.game.credits){credit.current=p.game.credits;coinTime.current=0;}coinTime.current+=dt;const coin=scene.getObjectByName('travelling_coin');if(coin){coin.visible=coinTime.current<1.4;coin.position.y=1.2-Math.min(.58,coinTime.current*.45);coin.rotation.z=coinTime.current*7;}for(let i=0;i<6;i++){const leaf=scene.getObjectByName('leaf_'+i);if(leaf)leaf.rotation.z=p.game.keys.has('Space')&&i===2?-.15:0;}resources.crt.needsUpdate=true;
 for(const [id,point]of Object.entries(anchor)){const el=document.getElementById('label-'+id);if(!el)continue;const node=scene.getObjectByName(id);if(!node)continue;const v=new T.Vector3(...point);node.localToWorld(v);v.project(camera);el.style.transform=`translate(${(v.x*.5+.5)*size.width}px,${(-v.y*.5+.5)*size.height}px)`;el.style.visibility=v.z>1?'hidden':'visible';}
 });
 const identify=(e:ThreeEvent<PointerEvent|MouseEvent>)=>{let o:T.Object3D|null=e.object;while(o?.parent&&o.parent!==scene)o=o.parent;return o?.name||null;};
 return <><color attach="background" args={['#10100f']}/><fog attach="fog" args={['#10100f',9,24]}/><ambientLight intensity={p.roomLight?.65:.24}/><hemisphereLight args={['#9dafa8','#352315',p.roomLight?1:.35]}/><spotLight position={[-.4,6.8,2]} target-position={[0,1,0]} color="#ffd49a" intensity={p.roomLight?130:85} angle={.56} penumbra={.8} castShadow shadow-mapSize={[1024,1024]} shadow-bias={-.0005}/><pointLight position={[-3,2,-1]} color="#a64560" intensity={p.roomLight?18:9}/><pointLight position={[3,2.7,-2]} color="#487e92" intensity={p.roomLight?25:12}/><pointLight position={[0,2.3,1]} color="#76bac9" intensity={p.power?1.5:0}/>
 <group ref={group}><primitive object={scene} onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();const id=identify(e);if(id)p.onSelect(id==='right_panel'||id==='back_panel'||id==='chassis'?'left_panel':id);}} onPointerOver={(e:ThreeEvent<PointerEvent>)=>{e.stopPropagation();const id=identify(e);setHover(id);p.onHover(id);}} onPointerOut={()=>{setHover(null);p.onHover(null);}}/><Wiring {...p} scene={scene}/></group>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.025,0]} receiveShadow><planeGeometry args={[100,100]}/><meshStandardMaterial color="#26251f" roughness={.42} metalness={.28} roughnessMap={resources.wear}/></mesh>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.029,0]}><ringGeometry args={[2.42,2.427,100]}/><meshBasicMaterial color="#68614a" transparent opacity={.24}/></mesh>
 <mesh position={[-.4,5.4,.2]}><cylinderGeometry args={[.36,.56,.12,36]}/><meshStandardMaterial color="#4e4231" metalness={.7} roughness={.4}/></mesh><mesh position={[-.4,5.33,.2]} rotation={[Math.PI/2,0,0]}><circleGeometry args={[.49,32]}/><meshBasicMaterial color="#ffdaa0"/></mesh>
 <Room reduced={p.reduced} quality={p.quality}/></>;
}
const paths:{from:string;to:string;a:[number,number,number];b:[number,number,number];color:string;kind:Signal}[]=[
 {from:'controls',to:'logic',a:[.2,1.57,.53],b:[.34,1.7,-.21],color:'#e9b65d',kind:'input'},
 {from:'logic',to:'crt',a:[.16,2.17,-.24],b:[.2,2.27,-.35],color:'#66c9da',kind:'video'},
 {from:'logic',to:'speaker',a:[.34,2.14,-.26],b:[.1,2.77,.38],color:'#b987c7',kind:'audio'},
 {from:'coin',to:'logic',a:[.15,1.14,.54],b:[.35,1.65,-.27],color:'#dfa353',kind:'credit'},
 {from:'power',to:'logic',a:[.4,.96,.04],b:[.43,1.73,-.28],color:'#e56850',kind:'power'},
 {from:'power',to:'crt',a:[.3,1.02,-.02],b:[-.3,2.25,-.27],color:'#d8654e',kind:'power'},
 {from:'power',to:'marquee',a:[.25,1,-.08],b:[.4,3.1,.25],color:'#d8654e',kind:'power'},
 {from:'ventilation',to:'speaker',a:[.3,.7,-.5],b:[.1,2.81,.06],color:'#84bfd5',kind:'airflow'}];
function Wiring(p:SceneProps&{scene:T.Group}){const refs=useRef<(T.Mesh|null)[]>([]),dots=useRef<(T.Mesh|null)[]>([]);const progress=useRef(0);const last=useRef('');const curves=useRef<T.CatmullRomCurve3[]>([]);
 useFrame((_,dt)=>{progress.current+=Math.min(dt,.05)*p.speed;const stamp=p.scene.children.map(g=>g.position.toArray().map(v=>v.toFixed(3)).join()).join();if(stamp!==last.current||!curves.current.length){last.current=stamp;paths.forEach((path,i)=>{const a=new T.Vector3(...path.a).add(p.scene.getObjectByName(path.from)!.position),b=new T.Vector3(...path.b).add(p.scene.getObjectByName(path.to)!.position);const curve=new T.CatmullRomCurve3([a,a.clone().add(new T.Vector3(.13,0,-.19)),a.clone().lerp(b,.52).add(new T.Vector3(.15,0,-.25)),b]);curves.current[i]=curve;const m=refs.current[i];if(m){m.geometry.dispose();m.geometry=new T.TubeGeometry(curve,22,path.kind==='airflow'?.007:.012,5,false);}});}
 paths.forEach((path,i)=>{const visible=(p.mode==='Exploded'||p.mode==='X-Ray')&&(p.signal==='all'||p.signal===path.kind);if(refs.current[i])refs.current[i]!.visible=visible;const dot=dots.current[i];if(dot){dot.visible=visible&&p.power;if(curves.current[i])dot.position.copy(curves.current[i].getPoint(p.reduced?.5:(progress.current*.35+i*.11)%1));}});
 });return <>{paths.map((path,i)=><group key={i}><mesh ref={el=>{refs.current[i]=el}}><tubeGeometry/><meshStandardMaterial color={path.color} emissive={path.color} emissiveIntensity={.35} roughness={.55}/></mesh><mesh ref={el=>{dots.current[i]=el}}><sphereGeometry args={[.025,8,6]}/><meshBasicMaterial color={path.color}/></mesh></group>)}</>;
}
function Room({reduced,quality}:{reduced:boolean;quality:string}){const points=useRef<T.Points>(null);const geometry=useMemo(()=>{const g=new T.BufferGeometry();const n=quality==='low'?35:100;const a=new Float32Array(n*3);for(let i=0;i<n;i++){a[i*3]=Math.sin(i*537)*5;a[i*3+1]=(i*13%50)/10;a[i*3+2]=Math.cos(i*273)*4;}g.setAttribute('position',new T.BufferAttribute(a,3));return g;},[quality]);useFrame((_,dt)=>{if(points.current&&!reduced)points.current.rotation.y+=dt*.008;});return <><points ref={points} geometry={geometry}><pointsMaterial color="#baa789" size={.011} transparent opacity={.4} depthWrite={false}/></points>{[-5,-3,3,5].map((x,i)=><group key={x} position={[x,0,-4.5]} rotation={[0,x<0?.18:-.18,0]}><mesh position={[0,1.4,0]}><boxGeometry args={[1.15,2.8,1.2]}/><meshStandardMaterial color="#10131a" roughness={.9}/></mesh><mesh position={[0,2.4,.61]}><planeGeometry args={[.94,.26]}/><meshBasicMaterial color={i%2?'#643441':'#304a5d'}/></mesh><mesh position={[0,1.9,.62]}><planeGeometry args={[.75,.58]}/><meshBasicMaterial color={i%2?'#24363d':'#452636'}/></mesh></group>)}</>}
