import {addFilterMicroDetail} from './FilterMicroDetail';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
export const filterParts=[
 {name:'Canister & base',role:'A sealed pressure vessel',text:'The outer canister holds the media stack and keeps the water path sealed. The removable base supports the baskets; the open section here is a viewing cutaway.'},
 {name:'Coarse foam',role:'First mechanical stage',text:'Incoming water travels down the side channel and rises through coarse foam. Large debris is trapped before it reaches the finer layers.'},
 {name:'Fine foam',role:'Smaller suspended particles',text:'A finer sponge catches smaller particles. Trapped debris increases resistance, so circulation gradually falls as the filter becomes dirty.'},
 {name:'Ceramic bio-media',role:'Surface area for biofilm',text:'Water and dissolved oxygen pass around porous ceramic rings. Biofilms on wetted surfaces help convert ammonia to nitrite and then nitrate; the rings do not sterilize the water.'},
 {name:'Polishing pad',role:'Final particle capture',text:'The upper pad catches fine particles before the water reaches the pump. Media order varies between filter designs; this exhibit uses a bottom-to-top flow path.'},
 {name:'Head seal & clamps',role:'Keep the canister watertight',text:'An O-ring seals the joint between the head and canister. The perimeter clamps retain the head. The seal must sit cleanly in its groove.'},
 {name:'Impeller & rotor',role:'The moving pump assembly',text:'A magnetic rotor turns the impeller on a stationary shaft. The impeller accelerates water into the outlet chamber. The motor windings sit outside the wet rotor chamber.'},
 {name:'Motor head',role:'Drive and water passages',text:'The head houses the motor, impeller chamber and return passage. Its cutaway exposes the copper-colored windings and wet rotor well. The rotor animation is slowed for inspection.'},
 {name:'Valves & hose block',role:'Inlet and return connections',text:'The inlet feeds the down-channel; the outlet receives water from the pump. Isolation levers close the connections for servicing. Never operate a real filter dry.'},
 {name:'Intake & return hoses',role:'Complete the circuit',text:'The intake strainer draws water from the aquarium. Filtered water returns through the other hose and lily outlet. The arrows show circulation, not a calibrated fluid simulation.'}
];
export class FilterScene{
 readonly renderer:T.WebGLRenderer;private scene=new T.Scene();private camera=new T.PerspectiveCamera(38,1,.1,100);private controls:OrbitControls;private groups:T.Group[]=[];private rotor=new T.Group();private shell:T.Mesh;private topShell:T.Mesh;private materials:T.MeshStandardMaterial[]=[];private flow=new T.Group();private dots:T.Mesh[]=[];private path:T.CatmullRomCurve3;private explosion=0;private target=0;private tick=0;private request=0;private observer:ResizeObserver;private environment:T.WebGLRenderTarget;private pointerStart={x:0,y:0};private dead=false;private isolated=false;private selected=3;private rotation=false;private running=true;
 constructor(private host:HTMLElement,private onPick:(id:number)=>void,private reduced=false){
 this.renderer=new T.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.setClearColor(0x06100f);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.95;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(this.renderer.domElement);this.renderer.domElement.setAttribute('aria-label','3D canister filter. Drag to orbit, scroll or pinch to zoom. Select components with the parts list.');this.renderer.domElement.setAttribute('role','img');
 const pmrem=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room,.04);this.scene.environment=this.environment.texture;room.dispose();pmrem.dispose();
 this.camera.position.set(7,5,10);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.target.set(0,2.2,0);this.controls.enableDamping=!reduced;this.controls.minDistance=1.6;this.controls.maxDistance=22;this.controls.maxPolarAngle=Math.PI*.85;
 this.scene.add(new T.HemisphereLight(0xe5edee,0x090c0d,.6));const key=new T.DirectionalLight(0xffffff,3);key.position.set(4,8,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-6;key.shadow.camera.right=6;key.shadow.camera.top=12;key.shadow.camera.bottom=-3;key.shadow.normalBias=.025;this.scene.add(key);const rim=new T.PointLight(0xffc06c,35);rim.position.set(-4,4,-2);this.scene.add(rim);
 const metal=this.mat(0xb9c1c4,.25,1),dark=this.mat(0x101618,.4,.25),rubber=this.mat(0x101211,.93,0),gold=this.mat(0xa9713c,.26,.95),cyan=this.mat(0x3b4547,.3,.65),ceramic=this.mat(0xa69e88,.96,0);
 const surface=(kind:'steel'|'foam'|'ceramic'|'fiber')=>{const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d')!;let seed=591;const rand=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};ctx.fillStyle=kind==='steel'?'#909090':kind==='foam'?'#454545':'#aaaaaa';ctx.fillRect(0,0,512,512);for(let i=0;i<(kind==='steel'?6500:18000);i++){const x=rand()*512,y=rand()*512,v=Math.floor(30+rand()*170);ctx.strokeStyle=ctx.fillStyle=`rgba(${v},${v},${v},${.1+rand()*.6})`;if(kind==='steel'||kind==='fiber'){ctx.lineWidth=kind==='steel'?.4:.8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+(kind==='steel'?80:12)*rand(),y+(kind==='steel'?0:8));ctx.stroke();}else{ctx.beginPath();ctx.arc(x,y,kind==='foam'?1+rand()*5:.3+rand()*1.8,0,Math.PI*2);ctx.fill();}}const map=new T.CanvasTexture(c);map.wrapS=map.wrapT=T.RepeatWrapping;map.repeat.set(kind==='steel'?3:2,2);map.anisotropy=8;return map;};
 metal.roughnessMap=surface('steel');metal.bumpMap=metal.roughnessMap;metal.bumpScale=.016;ceramic.bumpMap=surface('ceramic');ceramic.bumpScale=.07;
 const hose=this.mat(0x192121,.34,.05);hose.bumpMap=surface('fiber');hose.bumpScale=.008;
 for(let i=0;i<10;i++){const g=new T.Group();g.userData.part=i;this.groups.push(g);this.scene.add(g);}
 const cylinder=(r:number,h:number,material:T.Material,g:T.Object3D,y:number)=>{const m=new T.Mesh(new T.CylinderGeometry(r,r,h,64),material);m.castShadow=true;m.receiveShadow=true;m.position.y=y;g.add(m);return m;};
 const ring=(r:number,t:number,material:T.Material,g:T.Object3D,y:number)=>{const m=new T.Mesh(new T.TorusGeometry(r,t,12,72),material);m.rotation.x=Math.PI/2;m.position.y=y;g.add(m);return m;};
 const tube=(points:number[][],r:number,mat:T.Material,g:T.Object3D)=>{const path=new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p as [number,number,number])));const m=new T.Mesh(new T.TubeGeometry(path,64,r,12,false),mat);g.add(m);return path;};
 cylinder(1.45,.24,metal,this.groups[0],.12);cylinder(1.30,.12,dark,this.groups[0],.3);ring(1.39,.07,metal,this.groups[0],3.66);
 const shellMaterial=metal.clone();shellMaterial.side=T.DoubleSide;this.materials.push(shellMaterial);this.shell=new T.Mesh(new T.CylinderGeometry(1.39,1.39,3.3,80,1,true,.65,Math.PI*1.35),shellMaterial);this.shell.castShadow=true;this.shell.receiveShadow=true;this.shell.position.y=1.98;this.groups[0].add(this.shell);
 // Fine etched horizontal rings and support feet.
 for(const y of [.42,3.45])ring(1.40,.025,metal,this.groups[0],y);
 for(let i=0;i<4;i++){const a=i*Math.PI/2;const foot=cylinder(.18,.18,rubber,this.groups[0],0);foot.position.x=Math.cos(a)*1.08;foot.position.z=Math.sin(a)*1.08;}
 const texture=(color:string,seed:number)=>{const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,128,128);let n=seed;for(let i=0;i<2000;i++){n=(Math.imul(n,1664525)+1013904223)>>>0;const x=n%128;n=(Math.imul(n,1664525)+1013904223)>>>0;ctx.fillStyle=i%2?'#07100f88':'#ffffff22';ctx.beginPath();ctx.arc(x,n%128,seed===4?1:2,0,Math.PI*2);ctx.fill();}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;return t;};
 const heights=[0,.78,1.45,2.19,3.05];
 for(const i of [1,2,3,4]){const g=this.groups[i],y=heights[i];ring(1.13,.045,metal,g,y-.25);ring(1.13,.045,dark,g,y+.25);cylinder(1.1,.06,dark,g,y-.28);
 for(let j=0;j<18;j++){const a=j/18*Math.PI*2,m=new T.Mesh(new T.BoxGeometry(.026,.5,.04),dark);m.position.set(Math.cos(a)*1.13,y,Math.sin(a)*1.13);g.add(m);}
 if(i!==3){const m=this.mat(i===1?0x252b2a:i===2?0x354748:0xa9a593,.97,0);m.bumpMap=surface(i===4?'fiber':'foam');m.bumpScale=i===1?.10:i===2?.055:.028;m.roughnessMap=m.bumpMap;m.map=texture(i===1?'#252b2a':i===2?'#354748':'#a9a593',i);cylinder(1.06,.44,m,g,y);}
 else{for(let layer=0;layer<3;layer++)for(let j=0;j<26;j++){const a=j*2.399,r=.90*Math.sqrt((j+.5)/26),m=new T.Mesh(new T.LatheGeometry([[.067,-.095],[.097,-.095],[.105,-.087],[.105,.087],[.097,.095],[.067,.095],[.061,.087],[.061,-.087],[.067,-.095]].map(([x,y])=>new T.Vector2(x,y)),28),ceramic);m.position.set(Math.cos(a)*r,y-.17+layer*.17,Math.sin(a)*r);m.rotation.set(j*.6,layer*.8,j*.4);g.add(m);}}
 }
 ring(1.30,.065,rubber,this.groups[5],3.75);
 for(let i=0;i<4;i++){const a=i*Math.PI/2+.25;const clamp=new T.Mesh(new T.BoxGeometry(.17,.55,.18),metal);clamp.position.set(Math.cos(a)*1.44,3.75,Math.sin(a)*1.44);clamp.rotation.y=-a;this.groups[5].add(clamp);}
 this.rotor.position.y=4.15;this.groups[6].add(this.rotor);cylinder(.20,.66,dark,this.rotor,0);cylinder(.50,.08,cyan,this.rotor,-.26);
 for(let i=0;i<7;i++){const a=i/7*Math.PI*2;const blade=new T.Mesh(new T.BoxGeometry(.35,.16,.05),cyan);blade.position.set(Math.cos(a)*.3,-.18,Math.sin(a)*.3);blade.rotation.y=-a+.35;this.rotor.add(blade);}cylinder(.04,.93,ceramic,this.groups[6],4.15);
 this.topShell=new T.Mesh(new T.CylinderGeometry(1.43,1.43,.7,64,1,true,.65,Math.PI*1.35),dark);this.topShell.position.y=4.15;this.groups[7].add(this.topShell);ring(1.4,.09,metal,this.groups[7],4.51);
 // Individually wound copper stator coils around laminated iron poles.
 for(let i=0;i<10;i++){const a=i/10*Math.PI*2;const pole=new T.Group();pole.position.set(Math.cos(a)*.72,4.22,Math.sin(a)*.72);pole.rotation.y=-a;const core=new T.Mesh(new T.BoxGeometry(.23,.32,.24),dark);pole.add(core);for(let j=0;j<13;j++){const coil=new T.Mesh(new T.TorusGeometry(.16,.013,6,28),gold);coil.position.z=(j-6)*.020;pole.add(coil);}this.groups[7].add(pole);}

 const cap=cylinder(1.34,.10,metal,this.groups[7],4.6);cap.material=metal;
 for(const [x,mat] of [[-.55,gold],[.55,cyan]] as const){const valve=cylinder(.18,.55,mat,this.groups[8],4.98);valve.position.x=x;const lever=new T.Mesh(new T.BoxGeometry(.55,.09,.17),dark);lever.position.set(x,5.2,0);this.groups[8].add(lever);}
 tube([[-.55,5.25,0],[-.7,5.8,0],[-2.5,5.6,0],[-2.8,3.8,0]],.105,hose,this.groups[9]);tube([[.55,5.25,0],[.7,5.9,0],[2.4,5.7,0],[2.8,4.1,0]],.105,hose,this.groups[9]);
 const strainer=cylinder(.2,.65,dark,this.groups[9],3.65);strainer.position.x=-2.8;for(let i=0;i<6;i++){const rr=ring(.21,.02,gold,this.groups[9],3.4+i*.1);rr.position.x=-2.8;}
 const mouth=new T.Mesh(new T.ConeGeometry(.33,.55,32,1,true),cyan);mouth.rotation.z=Math.PI*.7;mouth.position.set(2.85,3.95,0);this.groups[9].add(mouth);
 // An exposed inlet down-channel feeds the plenum beneath the media stack.
 tube([[-.55,4.8,-.35],[-1.17,3.5,-.35],[-1.17,.42,-.35],[0,.4,0]],.055,gold,this.groups[0]);
 this.path=tube([[-2.8,3.5,.2],[-2.6,5.55,.2],[-.55,5.6,.2],[-1.17,3.6,.2],[-1.17,.40,.2],[0,.4,.2],[0,1.4,.2],[0,3.2,.2],[0,4.1,.2],[.55,5.5,.2],[2.4,5.6,.2],[2.85,4,.2]],.017,new T.MeshBasicMaterial({color:0x65cbe0,transparent:true,opacity:.30}),this.flow);this.scene.add(this.flow);
 const dotGeo=new T.SphereGeometry(.047,8,6);for(let i=0;i<45;i++){const dot=new T.Mesh(dotGeo,new T.MeshBasicMaterial({color:i<20?0xe5b66e:0x76deef}));this.dots.push(dot);this.flow.add(dot);}
 
 const floor=new T.Mesh(new T.CircleGeometry(6,80),new T.ShadowMaterial({opacity:.28}));floor.rotation.x=-Math.PI/2;floor.position.y=-.05;floor.receiveShadow=true;this.scene.add(floor);

 // Machined fasteners, retaining rings, hose barbs and basket perforations.
 const screw=(g:T.Group,x:number,y:number,z:number)=>{const bolt=new T.Mesh(new T.CylinderGeometry(.067,.067,.055,6),metal);bolt.position.set(x,y,z);g.add(bolt);const slot=new T.Mesh(new T.BoxGeometry(.065,.006,.014),rubber);slot.position.set(x,y+.03,z);g.add(slot);};
 for(const [id,y,r] of [[0,.27,1.28],[7,4.68,1.18],[5,3.76,1.23]])for(let i=0;i<10;i++){const a=i/10*Math.PI*2;screw(this.groups[id],Math.cos(a)*r,y,Math.sin(a)*r);}
 for(const x of [-.55,.55]){for(let i=0;i<7;i++){const collar=ring(.19,.018,metal,this.groups[8],4.75+i*.068);collar.position.x=x;}const nut=new T.Mesh(new T.CylinderGeometry(.27,.27,.16,6),metal);nut.position.set(x,4.78,0);this.groups[8].add(nut);for(const yy of [5.18,5.28]){const clamp=ring(.13,.023,metal,this.groups[9],yy);clamp.position.x=x;}screw(this.groups[8],x+.17,5.1,.07);}
 for(let i=0;i<4;i++){const a=i*Math.PI/2+.25;const latch=new T.Group();latch.position.set(Math.cos(a)*1.45,3.75,Math.sin(a)*1.45);latch.rotation.y=-a;for(const yy of [-.18,.15]){const pivot=new T.Mesh(new T.CylinderGeometry(.075,.075,.25,16),metal);pivot.rotation.z=Math.PI/2;pivot.position.y=yy;latch.add(pivot);}const grip=new T.Mesh(new T.BoxGeometry(.13,.32,.09),rubber);grip.position.set(0,.03,.13);latch.add(grip);this.groups[5].add(latch);}
 for(const i of [1,2,3,4]){const g=this.groups[i],y=heights[i];for(let row=0;row<5;row++){ring(1.135,.008,metal,g,y-.22+row*.11);}for(let j=0;j<36;j++){const a=j/36*Math.PI*2;const rib=new T.Mesh(new T.BoxGeometry(.010,.49,.012),metal);rib.position.set(Math.cos(a)*1.137,y,Math.sin(a)*1.137);g.add(rib);}for(let j=0;j<12;j++){const a=j/12*Math.PI*2;const foot=new T.Mesh(new T.CylinderGeometry(.05,.05,.035,12),rubber);foot.position.set(Math.cos(a)*.95,y-.315,Math.sin(a)*.95);g.add(foot);}}
 const plaque=(g:T.Group,text:string,sub:string,x:number,y:number,z:number,w:number)=>{const c=document.createElement('canvas');c.width=768;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle='#121819';ctx.fillRect(0,0,768,256);ctx.strokeStyle='#697574';ctx.lineWidth=5;ctx.strokeRect(8,8,752,240);ctx.fillStyle='#b8c0b7';ctx.font='48px Arial';ctx.fillText(text,36,90);ctx.font='26px monospace';ctx.fillStyle='#7e918d';ctx.fillText(sub,36,153);for(let i=0;i<90;i++){ctx.fillStyle=i%3?'#9aa9a0':'#1c2525';ctx.fillRect(36+i*4,184,2,38);}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,w/3),new T.MeshStandardMaterial({map:t,roughness:.48,metalness:.4}));m.position.set(x,y,z);m.rotation.y=Math.atan2(x,z);g.add(m);};
 plaque(this.groups[0],'AQUASCAPE / CANISTER','CLOSED LOOP FILTRATION',.94,1.76,1.04,.62);
 plaque(this.groups[7],'PUMP HEAD','WET ROTOR ASSEMBLY',.85,4.2,1.07,.48);
 addFilterMicroDetail(this.groups,this.rotor,metal,rubber);
 this.groups.forEach(g=>g.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=!(o instanceof T.InstancedMesh);o.receiveShadow=true;}}));
 this.renderer.domElement.addEventListener('pointerdown',this.down);this.renderer.domElement.addEventListener('pointerup',this.up);this.observer=new ResizeObserver(this.resize);this.observer.observe(host);this.resize();this.select(3);
 let previous=performance.now();const loop=(now:number)=>{if(this.dead)return;const dt=Math.max(0,Math.min(.05,(now-previous)/1000));previous=now;if(this.running&&!this.reduced)this.tick+=dt;this.explosion+=(this.target-this.explosion)*(this.reduced?1:1-Math.exp(-dt*5));this.groups.forEach((g,i)=>{g.position.y=this.explosion*i*.43;});this.rotor.rotation.y=this.tick*4;this.flow.visible=this.running&&!this.isolated&&this.explosion<.08;this.dots.forEach((d,i)=>d.position.copy(this.path.getPointAt((this.tick*.09+i/45)%1)));this.controls.autoRotate=this.rotation&&!this.reduced;this.controls.autoRotateSpeed=.6;this.controls.update();this.renderer.render(this.scene,this.camera);this.request=requestAnimationFrame(loop);};this.request=requestAnimationFrame(loop);
 }
 private mat(color:number,roughness:number,metalness:number){const m=new T.MeshStandardMaterial({color,roughness,metalness});this.materials.push(m);return m;}
 setIsolate(on:boolean){this.isolated=on;this.groups.forEach((g,i)=>g.visible=!on||i===this.selected);}
 focusSelected(){const box=new T.Box3().setFromObject(this.groups[this.selected]),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3());const distance=Math.max(2.4,Math.max(size.x,size.y,size.z)*2.2);this.controls.target.copy(center);this.camera.position.copy(center).add(new T.Vector3(.48,.28,1).normalize().multiplyScalar(distance));this.controls.update();}
 setExplode(value:number){this.target=value;this.controls.target.y=2.2+value*2.5;this.camera.position.set(7,5+value*2,10+value*4);}
 setCutaway(cut:boolean){this.shell.visible=cut;this.topShell.visible=cut; // Cutaway exposes the front; ghost view removes the housing entirely.
 }
 setFlow(on:boolean){this.running=on;}
 setRotate(on:boolean){this.rotation=on;}
 reset(){this.camera.position.set(7,5+this.target*2,10+this.target*4);this.controls.target.set(0,2.2+this.target*2.5,0);this.controls.update();}
 select(id:number){this.selected=id;this.setIsolate(this.isolated);if(this.isolated)this.focusSelected();this.groups.forEach((g,i)=>g.traverse(o=>{if(o instanceof T.Mesh){if(!o.userData.originalMaterial)o.userData.originalMaterial=o.material;if(o.userData.highlight){o.material.dispose();o.userData.highlight=false;}o.material=o.userData.originalMaterial;if(i===id&&o.material instanceof T.MeshStandardMaterial){o.material=o.material.clone();o.material.emissive.set(0x438978);o.material.emissiveIntensity=.07;o.userData.highlight=true;}}}));}
 private resize=()=>{const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.zoom=w/h<.9?.70:1;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);};
 private down=(e:PointerEvent)=>{this.pointerStart={x:e.clientX,y:e.clientY};};
 private up=(e:PointerEvent)=>{if(Math.hypot(e.clientX-this.pointerStart.x,e.clientY-this.pointerStart.y)>5)return;const rect=this.renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),this.camera);const hit=ray.intersectObjects(this.groups,true).find(h=>{let o:T.Object3D|null=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(!hit)return;let object:T.Object3D|null=hit.object;while(object&&object.userData.part===undefined)object=object.parent;if(object)this.onPick(object.userData.part);};
 dispose(){this.dead=true;cancelAnimationFrame(this.request);this.observer.disconnect();this.controls.dispose();this.renderer.domElement.removeEventListener('pointerdown',this.down);this.renderer.domElement.removeEventListener('pointerup',this.up);const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();this.scene.traverse(o=>{if(o instanceof T.Mesh){geometries.add(o.geometry);for(const m of [o.material,o.userData.originalMaterial].flat()){if(m){materials.add(m);for(const key of ['map','bumpMap','roughnessMap'])if(m[key])textures.add(m[key]);}}}});this.materials.forEach(m=>materials.add(m));geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());this.environment.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
