import {chromium} from 'playwright';import fs from 'node:fs';import {createServer} from 'node:http';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../../../..'),out=resolve(import.meta.dirname,'../../.qa-results'),base=process.env.REEF_TEST_BASE??'http://127.0.0.1:5243';
let server;if(!process.env.REEF_TEST_BASE){const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.json':'application/json','.glb':'model/gltf-binary'};server=createServer((req,res)=>{try{let file=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(fs.statSync(file).isDirectory())file+='/index.html';res.setHeader('content-type',mime[extname(file)]??'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(5243,'127.0.0.1',r));}
const browser=await chromium.launch({headless:true,channel:'chrome'}),report={};
try{
const p=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
const prefix=process.env.REEF_TEST_BASE?'':'/prototypes/hidden-reef';await p.goto(base+prefix+'/showroom/reef/?showroom=hidden-reef');await p.waitForFunction(()=>window.reefQA?.snapshot().ready,null,{timeout:120000});
const capture=async name=>p.screenshot({path:resolve(out,'reef-learning-'+(process.env.REEF_TEST_BASE?'live-':'')+name+'.png')});
const tool=mode=>p.locator(`[data-reef-tool="${mode}"]`),panel=p.locator('#reef-learning');
assert.equal(await p.getByRole('link',{name:'Hidden Reef home',exact:true}).count(),1);for(const id of ['learn','explore','chemistry'])assert.ok(await tool(id).isEnabled());await capture('front');
await tool('learn').click();assert.ok(await panel.isVisible());assert.equal(await tool('learn').getAttribute('aria-expanded'),'true');await panel.getByRole('button',{name:'Watch the current',exact:false}).click();await p.waitForTimeout(600);await capture('flow');
await panel.getByRole('button',{name:'Live rock',exact:true}).click();assert.match(await panel.innerText(),/Ammonia/);await panel.getByRole('button',{name:'Inspect the live rock',exact:false}).click();await p.waitForTimeout(300);
await panel.getByRole('button',{name:'Coral & light',exact:true}).click();await panel.getByRole('button',{name:'Blue hour',exact:true}).click();assert.equal(await p.locator('#light').getAttribute('aria-pressed'),'true');await panel.getByRole('button',{name:'Daylight',exact:true}).click();assert.equal(await p.locator('#light').getAttribute('aria-pressed'),'false');
await panel.getByRole('button',{name:'Feeding & care',exact:true}).click();await panel.getByRole('button',{name:'Feed the aquarium',exact:true}).click();assert.ok((await p.evaluate(()=>window.reefQA.snapshot())).food>0);
await tool('explore').click();assert.equal(await tool('learn').getAttribute('aria-expanded'),'false');await p.locator('#reef-subject').selectOption('goby');assert.match(await panel.innerText(),/Synchiropus splendidus/);await p.waitForTimeout(600);await capture('explore');await panel.getByRole('button',{name:'Whole reef',exact:true}).click();await p.waitForTimeout(1600);
await tool('chemistry').click();assert.match(await panel.innerText(),/not live water measurements/);await p.locator('[data-lab="evaporate"]').click();assert.match(await p.locator('[data-metric="salinity"]').innerText(),/35.71/);await p.locator('[data-lab="freshwater"]').click();assert.match(await p.locator('[data-metric="salinity"]').innerText(),/35.00/);assert.ok(await p.locator('[data-lab="freshwater"]').isDisabled());
await p.locator('[data-lab="evaporate"]').click();await p.locator('[data-lab="saltwater"]').click();assert.match(await p.locator('[data-metric="salinity"]').innerText(),/35.70/);await p.locator('[data-reset]').click();await p.locator('[data-lab="uptake"]').click();assert.match(await p.locator('[data-metric="alkalinity"]').innerText(),/8.00/);await p.locator('[data-metric="alkalinity"]').click();assert.match(await p.locator('.reef-chart figcaption').innerText(),/Alkalinity/);await p.locator('[data-lab="nutrients"]').click();await p.locator('[data-lab="change"]').click();assert.match(await p.locator('[data-metric="nitrate"]').innerText(),/5.60/);await panel.evaluate(el=>el.scrollTop=0);await capture('chemistry');
await p.keyboard.press('Escape');assert.ok(await panel.isHidden());assert.equal(await p.evaluate(()=>document.activeElement.dataset.reefTool),'chemistry');
await p.getByRole('button',{name:'Pause',exact:true}).click();const time=(await p.evaluate(()=>window.reefQA.snapshot())).time;await tool('chemistry').click();await p.locator('[data-lab="uptake"]').click();await p.waitForTimeout(400);assert.equal((await p.evaluate(()=>window.reefQA.snapshot())).time,time,'lab does not change simulation time or unpause');await p.keyboard.press('Escape');await p.getByRole('button',{name:'Resume',exact:true}).click();
await p.getByRole('button',{name:'Three-quarter',exact:true}).click();await p.waitForTimeout(1500);await capture('angle');await p.getByRole('button',{name:'Front',exact:true}).click();
for(const width of [390,700,1024]){await p.setViewportSize({width,height:844});await p.waitForTimeout(500);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no overflow at'+width);if(width===390)await capture('mobile');await tool('chemistry').click();await p.waitForTimeout(300);const canvas=await p.locator('#scene').boundingBox(),rail=await panel.boundingBox();assert.ok(canvas.height>=135&&canvas.width>0);assert.ok(rail.x>=0&&rail.x+rail.width<=width+1&&rail.y+rail.height<=845,'panel fits viewport');if(width===390)await capture('mobile-chemistry');await panel.getByRole('button',{name:'Close reef guide',exact:true}).click();assert.ok(await panel.isHidden());}
await p.setViewportSize({width:1440,height:1080});await p.getByRole('button',{name:'Full screen',exact:true}).click();await tool('explore').click();assert.ok(await panel.isVisible());await panel.getByRole('button',{name:'Close reef guide',exact:true}).click();await p.getByRole('button',{name:'Exit full screen',exact:true}).click();
assert.deepEqual(errors,[]);report.checks={lessons:true,closeups:true,lighting:true,feeding:true,chemistry:true,labIndependent:true,keyboardFocus:true,mobile:true,tablet:true,fullscreen:true,navigation:true};report.errors=errors;report.scene=await p.evaluate(()=>{const s=window.reefQA.snapshot();return {fish:s.fish,triangles:s.triangles,fishPassStats:s.fishPassStats};});fs.writeFileSync(resolve(out,'reef-learning-'+(process.env.REEF_TEST_BASE?'live-':'')+'results.json'),JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
