import {chromium} from 'playwright';
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=path.resolve('../..'),out=path.resolve('reef/qa');
const server=createServer(async(req,res)=>{try{
 let file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);
 if(!file.startsWith(root+path.sep))throw Error('Path');
 if((await fs.stat(file)).isDirectory())file=path.join(file,'index.html');
 const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.json':'application/json'};
 res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(await fs.readFile(file));
}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,channel:'chrome'}),report={};
try{
 const page=await browser.newPage({viewport:{width:1440,height:1080},hasTouch:true});
 const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 const origin=process.env.SHOWROOM_ORIGIN||`http://127.0.0.1:${server.address().port}`;
 const base=process.env.SHOWROOM_PATH||'/prototypes/hidden-reef/showroom/';
 await page.goto(origin+base+'?habitat=reef');await page.waitForTimeout(1200);
 assert.equal(await page.locator('#tank-mount iframe').count(),0);
 assert.equal(requests.filter(u=>/\/showroom\/(reef|aquarium)\//.test(u)).length,0,'no renderer download before entry');
 assert.equal(await page.locator('[data-habitat-choice="reef"]').getAttribute('aria-pressed'),'true');
 await page.screenshot({path:path.join(out,'showroom-cover-desktop.png')});
 const entered=Date.now();await page.locator('#launch').click();
 const tank=()=>page.frames().find(f=>/\/showroom\/reef\//.test(f.url()));
 await page.waitForFunction(()=>document.querySelector('#tank-mount iframe')?.contentWindow.reefQA?.snapshot().ready,null,{timeout:120000});
 report.readyMs=Date.now()-entered;const reef=tank();await page.waitForTimeout(800);
 assert.equal((await reef.evaluate(()=>window.reefQA.snapshot())).fish,21);
 await page.locator('#tank-mount').screenshot({path:path.join(out,'showroom-reef-desktop.png')});
 await reef.locator('canvas').screenshot({path:path.resolve('.qa-results/reef-poster.png')});
 await reef.locator('#pause').click();await page.waitForTimeout(2500);
 const idle=await reef.evaluate(()=>window.reefQA.snapshot());await page.waitForTimeout(600);
 const idleEnd=await reef.evaluate(()=>window.reefQA.snapshot());
 assert.equal(idleEnd.renderFrames,idle.renderFrames,'settled pause must not keep rendering');
 assert.deepEqual(idleEnd.positions,idle.positions);report.pausedRedraws=idleEnd.renderFrames-idle.renderFrames;
 await reef.locator('[data-view="angle"]').click();await page.waitForTimeout(2000);
 assert.ok((await reef.evaluate(()=>window.reefQA.snapshot())).renderFrames>idleEnd.renderFrames,'paused camera controls wake rendering');
 await reef.locator('#light').click();await page.waitForTimeout(2800);
 assert.ok((await reef.evaluate(()=>window.reefQA.snapshot())).optics.daylight<.25);
 await reef.locator('#light').click();await reef.locator('#pause').click();
 await page.evaluate(()=>document.body.classList.add('cart-open'));await page.waitForTimeout(300);
 const suspended=await reef.evaluate(()=>window.reefQA.snapshot());assert.equal(suspended.suspended,true);
 await page.waitForTimeout(600);assert.equal((await reef.evaluate(()=>window.reefQA.snapshot())).renderFrames,suspended.renderFrames);
 await page.evaluate(()=>document.body.classList.remove('cart-open'));await page.waitForTimeout(400);
 assert.ok((await reef.evaluate(()=>window.reefQA.snapshot())).time>suspended.time);
 await page.locator('[data-habitat="reef"] [data-value="anemones"]').click();await page.waitForTimeout(700);
 await page.locator('#tank-mount').screenshot({path:path.join(out,'showroom-anemones.png')});
 const canvas=await reef.locator('canvas').boundingBox();await page.mouse.click(canvas.x+canvas.width*.5,canvas.y+canvas.height*.56);
 const title=await reef.locator('#detail h2').innerText();assert.ok(title.length>0);
 assert.equal(await page.locator('#context-title').innerText(),title);
 await reef.locator('#close-detail').click();
 await page.locator('[data-habitat-choice="freshwater"]').click();
 assert.equal(await page.locator('#tank-mount iframe').count(),1);
 assert.match(await page.locator('#tank-mount iframe').getAttribute('src'),/^\.\/aquarium\//);
 await page.waitForFunction(()=>document.querySelector('#tank-status').textContent.startsWith('Drag to rotate'),null,{timeout:120000});
 assert.ok(await page.locator('.showroom-chips[data-habitat="freshwater"]').isVisible());
 await page.locator('#close-tank').click();assert.equal(await page.locator('#tank-mount iframe').count(),0);
 await page.locator('[data-habitat-choice="reef"]').click();assert.equal(await page.locator('#tank-mount iframe').count(),0);
 await page.setViewportSize({width:390,height:844});await page.locator('.habitat-picker').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(out,'showroom-cover-mobile.png')});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#launch').click();
 await page.waitForFunction(()=>document.querySelector('#tank-mount iframe')?.contentWindow.reefQA?.snapshot().ready,null,{timeout:120000});
 await page.waitForTimeout(600);await page.locator('#tank-mount').screenshot({path:path.join(out,'showroom-reef-mobile.png')});
 const mobile=tank();await mobile.locator('#feed').click();await page.waitForTimeout(1200);
 assert.ok((await mobile.evaluate(()=>window.reefQA.snapshot())).food>0);
 await page.locator('#reef-build').scrollIntoViewIfNeeded();await page.waitForTimeout(600);
 assert.equal((await mobile.evaluate(()=>window.reefQA.snapshot())).suspended,true,'offscreen reef must suspend');
 await page.locator('#close-tank').click();assert.equal(await page.locator('#tank-mount iframe').count(),0);
 assert.deepEqual(errors,[]);report.checks={onDemand:true,habitats:true,plantedReady:true,identification:true,closeups:true,pauseIdle:true,pausedCamera:true,pausedLighting:true,modalSuspension:true,offscreenSuspension:true,mobile:true,feeding:true,unmount:true};
 await fs.writeFile(path.join(out,'showroom-results.json'),JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close();await new Promise(r=>server.close(r));}
