import {chromium} from 'playwright';import fs from 'node:fs';import {createServer} from 'node:http';import {resolve,extname} from 'node:path';import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../../../..'),out=resolve(import.meta.dirname,'../../.qa-results'),base=process.env.REEF_TEST_BASE??'http://127.0.0.1:5244';
let server;if(!process.env.REEF_TEST_BASE){const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json','.glb':'model/gltf-binary'};server=createServer((req,res)=>{try{let f=resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(fs.statSync(f).isDirectory())f+='/index.html';res.setHeader('content-type',mime[extname(f)]??'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(5244,'127.0.0.1',r));}
const browser=await chromium.launch({headless:true,channel:'chrome'}),report={samples:[],checks:{}};
try{
 const p=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 const snap=()=>p.evaluate(()=>window.reefQA.snapshot()),shot=name=>p.screenshot({path:resolve(out,'reef-tour-'+(process.env.REEF_TEST_BASE?'live-':'')+name+'.png')}),settle=()=>p.waitForFunction(()=>!window.reefQA.snapshot().tourCamera.moving);
 await p.goto(base+(process.env.REEF_TEST_BASE?'':'/prototypes/hidden-reef')+'/showroom/reef/?showroom=hidden-reef');await p.waitForFunction(()=>window.reefQA?.snapshot().ready,null,{timeout:120000});
 await p.locator('#pause').click();const time=(await snap()).time;await p.locator('[data-reef-tool="explore"]').click();await p.locator('[data-tour="start"]').click();await settle();await shot('stop-1');
 const distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));
 for(let stop=2;stop<=6;stop++){
  const start=(await snap()).tourCamera.position;await p.locator('[data-tour="next"]').click();assert.equal((await snap()).tourCamera.moving,true);const sequence=[];
  for(let i=0;i<7;i++){await p.waitForTimeout(350);sequence.push((await snap()).tourCamera);if(stop===4)await shot('travel-'+i);}
  await settle();const end=(await snap()).tourCamera;assert.ok(distance(start,end.position)>.05);assert.ok(distance(sequence[1].position,start)>.001&&distance(sequence[1].position,end.position)>.001,'intermediate view exists');
  assert.ok(sequence.every(s=>s.position[2]>=4.39),'front corridor');assert.equal((await snap()).time,time,'tour does not unpause animals');assert.match(await p.locator('.reef-tour-count').innerText(),new RegExp('Stop '+stop+' of 6'));report.samples.push({stop,start,sequence,end});await shot('stop-'+stop);
 }
 await p.locator('[data-tour="finish"]').click();await settle();assert.ok(await p.locator('[data-tour="start"]').isVisible());assert.equal((await snap()).paused,true);
 await p.locator('[data-tour="start"]').click();await settle();await p.locator('[data-tour="next"]').click();await p.waitForTimeout(200);
 const box=await p.locator('canvas').boundingBox();await p.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await p.mouse.down();await p.mouse.move(box.x+box.width*.57,box.y+box.height*.53,{steps:8});await p.mouse.up();assert.equal((await snap()).tourCamera.moving,false,'drag cancels travel');assert.ok(await p.locator('#reef-learning').isVisible());
 await p.locator('[data-tour="recenter"]').click();await settle();await p.locator('[data-tour="next"]').click();await p.waitForTimeout(100);await p.locator('[data-tour="back"]').click();await settle();assert.match(await p.locator('.reef-tour-count').innerText(),/Stop 2 of 6/);
 await p.locator('[data-tour="next"]').click();await p.keyboard.press('Escape');assert.equal((await snap()).tourCamera.moving,false);assert.ok(await p.locator('#reef-learning').isHidden());assert.equal(await p.evaluate(()=>document.activeElement.dataset.reefTool),'explore');
 await p.locator('[data-reef-tool="learn"]').click();await p.locator('[data-tour="start"]').click();await settle();await p.locator('[data-tour="next"]').click();await p.locator('[data-reef-tool="chemistry"]').click();assert.equal((await snap()).tourCamera.moving,false);assert.ok(await p.locator('.reef-readings').isVisible());await p.keyboard.press('Escape');
 await p.setViewportSize({width:390,height:844});await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-reef-tool="explore"]').click();await p.locator('[data-tour="start"]').click();assert.equal((await snap()).tourCamera.moving,false);await shot('mobile-start');
 for(let i=0;i<3;i++)await p.locator('[data-tour="next"]').click();await shot('mobile-host');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const next=await p.locator('[data-tour="next"]').boundingBox();assert.ok(next.y>=0&&next.y+next.height<=844,'mobile next remains accessible');
 await p.locator('[data-tour="exit"]').click();assert.ok(await p.locator('[data-tour="start"]').isVisible());await p.keyboard.press('Escape');await p.locator('#pause').click();const before=(await snap()).time;await p.waitForTimeout(400);assert.ok((await snap()).time>before);await p.locator('#feed').click();assert.ok((await snap()).food>0);
 assert.deepEqual(errors,[]);report.checks={sixStops:true,smoothCamera:true,frontCorridor:true,pausePreserved:true,dragInterrupts:true,recenter:true,rapidNavigation:true,escapeFocus:true,switchCancels:true,finish:true,mobile:true,reducedMotion:true,feeding:true};report.errors=errors;
 fs.writeFileSync(resolve(out,'reef-tour-'+(process.env.REEF_TEST_BASE?'live-':'')+'results.json'),JSON.stringify(report,null,2));console.log(report.checks);
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
