# Hand-authored pixel string-art for Glimmer Grotto placeholder sprites.
# Each sprite: palette {char: #hex or #hexAA} + rows of chars ('.' = transparent).
# Rows are padded right with '.' to the widest row; height = len(rows).

SPRITES = {

"miner": {
  "pal": {
    "O":"#241712","H":"#e8a33d","h":"#b5731f","Y":"#ffd87f","y":"#9a5c14",
    "M":"#5d616c","L":"#fff6c4","S":"#edb98b","s":"#cf9367","R":"#e8957a",
    "E":"#2b2330","W":"#ffffff","B":"#8a5a33","b":"#6b4226","D":"#a06a3a",
    "J":"#46897f","j":"#31635c","K":"#65ab9e","T":"#a06a3a","t":"#7e5128",
    "G":"#c9905a","P":"#6e4c33","p":"#523722","F":"#382a20","f":"#5a4433",
    "N":"#7e5128","n":"#5e3c1e",
  },
  "rows": [
    "...........OOOOOOOO..........",
    ".........OOHHHHHHHHOO........",
    "........OHHHHHHHHHYYHO.......",
    ".......OHHHHHHHHHHHYYHO......",
    "......OHHHHHHHHHHHHHYHO......",
    "......OHhHHHHHHHHHHHHOOOO....",
    "......OHhHHHHHHHHHHHOMLLLO...",
    "......OhhHHHHHHHHHHHHOLLLO...",
    ".....OOhhhhhhhhhhhhhhOOOO....",
    ".....OhhhhhhhhhhhhhhhhO......",
    "......OSSSSSSSSSSSSSSO.......",
    "......OSSSSSSSSSSSSSSO.......",
    "......OSsSSSSSSSSSSSsO.......",
    "......OSsEWSSSSSSEWSsO.......",
    "......OSsEESSSSSSEESsO.......",
    "......OSsSSSSsSSSSSRsO.......",
    "......OSBSSSSsSSSSBSsO.......",
    "......OBBBSSSSSSSBBBsO.......",
    "......ODBBBSSSSSBBBBbO.......",
    "......ODBBBBBBBBBBBBbO.......",
    ".......ODBBBBBBBBBBbO........",
    ".......ODBBBBBBBBBbO.........",
    "........ODBBBBBBBbO..........",
    ".........OBBBBBBbO...........",
    ".......OOJJJJJJJJOO..........",
    ".....OOJJKKJJJJJJJJOO........",
    "....ONJJKKJJJJJJJJJJO........",
    "...ONNJJKTJJJJJJJJJJJO.......",
    "...ONnJJJTTJJJJJJJJGGO.......",
    "...ONnJJJJTTJJJJJJOGGO.......",
    "...ONnJjJJJTTJJJJJOOO........",
    "....ONJjJJJJTTJJJJO..........",
    ".....OJjjJJJJTJJJJO..........",
    ".....OJjjjJJJJJJJO...........",
    ".....OTtTTTTTTTtO............",
    ".....OPPPPPOPPPPO............",
    ".....OPpPPO.OPPPO............",
    ".....OPpPO..OPpPO............",
    ".....OPpPO..OPpPO............",
    ".....OPpPO..OPpPO............",
    ".....OFfFO..OFfFO............",
    "....OFFfFO..OFFfFO...........",
    "....OFFFFOO.OFFFFOO..........",
    "....OOOOOO..OOOOOO...........",
  ],
},

"pickaxe": {
  "pal": {"O":"#241712","M":"#b9c2cc","m":"#7e8896","X":"#e8eef4","W":"#8a5a33","w":"#6b4226"},
  "rows": [
    "......OOOOOOO.......",
    "....OOMMMMMMMOO.....",
    "...OMMXXXMMMMMMO....",
    "..OMMXOOWWOOMMMMO...",
    ".OMMXO.OWWO.OOmMO...",
    ".OMXO..OWWO...OmMO..",
    ".OMO...OWWO....OmO..",
    ".OO....OWWO.....OO..",
    "......OWWO..........",
    "......OWWO..........",
    ".....OWWO...........",
    ".....OWWO...........",
    "....OWWO............",
    "....OWWO............",
    "...OWwO.............",
    "...OWwO.............",
    "..OwwO..............",
    "..OwwO..............",
    ".OOO................",
  ],
},

"lantern": {
  "pal": {"O":"#241712","M":"#5d616c","m":"#3c3f47","G":"#ffd87f","g":"#fff6c4","F":"#ffae52"},
  "rows": [
    "....OOOO....",
    "...O....O...",
    "...O....O...",
    "..OOOOOOOO..",
    "..OmMMMMmO..",
    ".OMGGGGGGMO.",
    ".OGGggggGGO.",
    ".OGgggggGGO.",
    ".OGGggggGGO.",
    ".OFGGGGGGFO.",
    "..OmMMMMmO..",
    "...OOOOOO...",
  ],
},

"campfire": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","W":"#8a5a33","w":"#6b4226",
          "F":"#ff9f43","f":"#ffd87f","c":"#fff6c4","E":"#e06036"},
  "rows": [
    "..........cc............",
    ".........cffc...........",
    ".........offfo..........".replace("o","F"),
    "........OFfffFO.........",
    "........OFfffFEO........",
    ".......OFFfcffFO........",
    ".......OEFfccfFEO.......",
    "......OFEFfccffFO.......",
    "......OEFFfffFFEO.......",
    ".....OEEFFFFFFFEEO......",
    "...OWwOEEFFFFEEOwWO.....",
    "..OWWwwOOEEEEOOwwWWO....",
    ".OWWWwwwOOOOOOwwwWWWO...",
    ".OwwWWWWWWwWWWWWWWwwO...",
    "..OOrRROwwwwwwORRrOO....",
    ".ORRrrRRROOOOORRrrRRO...",
    ".ORrRRrRRRRRRRRrRRrRO...",
    "..OOOOOOOOOOOOOOOOOO....",
  ],
},

"minecart": {
  "pal": {"O":"#241712","M":"#5d616c","m":"#3c3f47","W":"#8a5a33","w":"#6b4226",
          "X":"#9aa3ad","G":"#b07ae0","g":"#e8c57a","V":"#7ab362"},
  "rows": [
    "......g..G....V.g.............",
    ".....gGG.GG.VV.Gg.............",
    "..OOgGGGGGGVVVGGgOO...........",
    ".OMMXXXXXXXXXXXXXXMO..........",
    ".OMWWwWWWwWWWwWWWWMO..........",
    ".OMWWwWWWwWWWwWWWWMO..........",
    "..OMWwWWWwWWWwWWWMO...........",
    "..OMWwWWWwWWWwWWWMO...........",
    "...OMwWWWwWWWwWWMO............",
    "...OMMMMMMMMMMMMMO............",
    "....OOOOOOOOOOOO..............",
    "....OmMO....OMmO..............",
    "...OmMMmO..OmMMmO.............",
    "...OMmmMO..OMmmMO.............",
    "....OmMO....OMmO..............",
    ".....OO......OO...............",
  ],
},

"tent": {
  "pal": {"O":"#241712","C":"#c9764a","c":"#a3552f","D":"#874327","P":"#6b4226",
          "L":"#e8945e","I":"#3a2b22"},
  "rows": [
    "..................OO....................",
    ".................OPPO...................",
    ".................OLLO...................",
    "................OLCCLO..................",
    "...............OLCCCCLO................",
    "..............OLCCCCCCLO...............",
    ".............OLCCCCCCCCLO..............",
    "............OLCCCCcCCCCCLO.............",
    "...........OLCCCCccCCCCCCLO............",
    "..........OLCCCCCccCCCCCCCLO...........",
    ".........OLCCCCCcccCCCCCCCCLO..........",
    "........OLCCCCCCcDcCCCCCCCCCLO.........",
    ".......OLCCCCCCcDDDcCCCCCCCCCLO........",
    "......OLCCCCCCcDDIDDcCCCCCCCCCLO.......",
    ".....OLCCCCCCcDDIIIDDcCCCCCCCCCLO......",
    "....OLCCCCCCcDDIIIIIDDcCCCCCCCCCLO.....",
    "...OLCCCCCCcDDIIIIIIIDDcCCCCCCCCCLO....",
    "..OLCCCCCCcDDIIIIIIIIIDDcCCCCCCCCCLO...",
    ".OLCCCCCCcDDIIIIIIIIIIIDDcCCCCCCCCCLO..",
    ".OcccccccDDIIIIIIIIIIIIIDDccccccccccO..",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...",
  ],
},

"crate": {
  "pal": {"O":"#241712","W":"#a06a3a","w":"#7e5128","d":"#5e3c1e","X":"#c9905a"},
  "rows": [
    ".OOOOOOOOOOOOOOOO.",
    "OXWWWWWWWWWWWWWWdO",
    "OWXWWwwwwwwwwWWWdO",
    "OWWXwWWWWWWWWxWWdO".replace("x","w"),
    "OWwWXWWWWWWwXWWWdO",
    "OWwWWXWWWWwXWWWWdO",
    "OWwWWWXWWwXWWWWWdO",
    "OWwWWWWXXWWWWWWWdO",
    "OWwWWWwXXWWWWWWWdO",
    "OWwWWwXWWXWWWWWWdO",
    "OWwWwXWWWWXWWWWWdO",
    "OWwwXWWWWWWXWWWWdO",
    "OWdWWWWWWWWWWWWWdO",
    "OddddddddddddddddO",
    ".OOOOOOOOOOOOOOOO.",
  ],
},

"geode_closed": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","d":"#434a54","X":"#9aa3ad"},
  "rows": [
    "......OOOOOO........",
    "....OORRRRRROO......",
    "...ORRXXRRRRRRO.....",
    "..ORXXRRRRrRRRRO....",
    ".ORXRRRRRRRrRRRRO...",
    ".ORRRRdRRRRRrRRRO...",
    "ORRRRdRRRRRRRrRRRO..",
    "ORRRdRRRRRRRRRrRRO..",
    "ORRrdRRRRRRRRRrrRO..",
    "ORRrRdRRRRRRRrrRRO..",
    ".ORrRRddRRRrrrRRO...",
    ".ORrrRRRdddrrRRRO...",
    "..ORrrrrrrrrrROO....",
    "...OORrrrrrROO......",
    ".....OOOOOOO........",
  ],
},

"geode_open": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","A":"#b07ae0","a":"#8a54c0",
          "W":"#e6d4ff","w":"#cba8f5"},
  "rows": [
    ".....OOOOOOOO.........",
    "...OORRRRRRRROO.......",
    "..ORRaAAaAAaRRRO......",
    ".ORaAWAaAWAaAaRRO.....",
    ".ORAWWAAWWAAWAaRO.....",
    "ORaAWAaAWwAaAWaRRO....",
    "ORAaAAaAwwaAaAAaRO....",
    "ORaAaAaAaAaAaAaARO....",
    ".ORaaAaaAaaAaaARO.....",
    ".ORraaaaaaaaaaRRO.....",
    "..ORrrrrrrrrrROO......",
    "...OORrrrrrROO........",
    ".....OOOOOOO..........",
  ],
},

"fossil_ammonite": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","d":"#52493c","C":"#cdbfa3","c":"#b0a184"},
  "rows": [
    "...OOOOOOOOOOOOO....",
    "..ORRRRRRRRRRRRRO...",
    ".ORRRRccccccRRRRRO..",
    ".ORRRcCCCCCCcRRRRO..",
    "ORRRcCcccccCCcRRRRO.",
    "ORRcCcCCCCcCCcRRRRO.",
    "ORRcCcCccCcCCcRRRrO.",
    "ORRcCcCcCcCCcCRRRrO.",
    "ORRcCcCCCCCcCcRRRrO.",
    "ORRcCcccccccCcRRRrO.",
    "ORRRcCCCCCCCCcRRRrO.",
    "ORRRRccccccccRRRRrO.",
    ".ORRRRRRRRRRRRRrrO..",
    "..ORRRrrrrrrrrrrO...",
    "...OOOOOOOOOOOOO....",
  ],
},

"fossil_fern": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","G":"#a8a182","g":"#8f8868"},
  "rows": [
    "...OOOOOOOOOOOO.....",
    "..ORRRRRRRRRRRRO....",
    ".ORRRRRgGgRRRRRRO...",
    ".ORRRgGgGgGgRRRRO...",
    "ORRRRgGgGgGgGRRRRO..",
    "ORRgGgRgGgRgGgRRRO..",
    "ORRRgGgRGgRGgRRRrO..",
    "ORRgGgRgGgRgGgRRrO..",
    "ORRRgGgRGgRGgRRRrO..",
    "ORRgGgRgGgRgGgRRrO..",
    "ORRRRgGgGgGgRRRRrO..",
    "ORRRRRgGgGgRRRRRrO..",
    ".ORRRRRgGgRRRRRrO...",
    "..ORRRRRRRRRRRrO....",
    "...OOOOOOOOOOOO.....",
  ],
},

"fossil_fish": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","B":"#cdbfa3","b":"#b0a184","E":"#52493c"},
  "rows": [
    "..OOOOOOOOOOOOOOOOOO....",
    ".ORRRRRRRRRRRRRRRRRRO...",
    "ORRRRbBbRRBRRBRRbRRRRO..",
    "ORRBbRRBbRBRRBRBbRRRRO..",
    "ORREBBBBBBBBBBBBBbbRrO..",
    "ORRBbRRBbRBRRBRBbBbRrO..",
    "ORRRRbBbRRBRRBRRbRBrO...",
    ".ORRRRRRRRRRRRRRRRRrO...",
    "..OOOOOOOOOOOOOOOOOO....",
  ],
},

"mushroom_glow_big": {
  "pal": {"O":"#16201f","C":"#3fbfae","c":"#2a8a7e","D":"#1f6159","S":"#e8e2c8",
          "s":"#c4bda0","G":"#aef5ea","g":"#74e0d2"},
  "rows": [
    "......OOOOOOO.......",
    "....OOCCCCCCCOO.....",
    "...OCCGgCCCCCCCO....",
    "..OCGgGCCCCcCCCCO...",
    ".OCCgGCCCCCCcCCCCO..",
    ".OCCCCCCgCCCCcCCCO..",
    "OCCcCCCCCCCCCCcCCCO.",
    "OCcCCCCgGgCCCCCcCCO.",
    "OCcCCCCCgCCCCCCcCCO.",
    "OcCCcCCCCCCCcCCCCcO.",
    ".OccCccCCCCcCCCccO..",
    "..OOcccccccccccOO...",
    "....OOSSsSSOO.......",
    ".....OSSsSSO........",
    ".....OSSsSSO........",
    ".....OSSsSsO........",
    "....OSSSsSSsO.......",
    "....OSsssssSO.......",
    ".....OOOOOOO........",
  ],
},

"mushroom_glow_small": {
  "pal": {"O":"#16201f","C":"#3fbfae","c":"#2a8a7e","S":"#e8e2c8","s":"#c4bda0","G":"#aef5ea"},
  "rows": [
    "...OOOOO....",
    "..OCGCCCO...",
    ".OCGgCCcCO..",
    "OCCGCCCCcCO.",
    "OCcCCGCCcCO.",
    ".OccCCCccO..",
    "..OOcccOO...",
    "...OSsSO....",
    "...OSsSO....",
    "..OSSssSO...",
    "...OOOOO....",
  ],
},

"icon_bag": {
  "pal": {"O":"#241712","B":"#a06a3a","b":"#7e5128","d":"#5e3c1e","S":"#c9905a","G":"#ffd87f"},
  "rows": [
    "....OOOO......",
    "...Od..dO.....",
    "..OdO..OdO....",
    ".OSBBOOBBSO...",
    "OSBBBBBBBBSO..",
    "OBBSGGGGSBBO..",
    "ObBSGGGGSBbO..",
    "ObBBSSSSBBbO..",
    "ObbBBBBBBbbO..",
    ".ObbbBBbbbO...",
    "..OOObbOOO....",
    "....OOOO......",
  ],
},

"icon_energy": {
  "pal": {"O":"#241712","Y":"#ffd87f","y":"#e8a33d","W":"#fff6c4"},
  "rows": [
    "......OOOO....",
    ".....OYYWO....",
    "....OYYWO.....",
    "...OYYWO......",
    "..OYYYYOOO....",
    ".OYWYYYYYO....",
    ".OOOOYYYO.....",
    "....OYYO......",
    "...OYyO.......",
    "..OYyO........",
    "..OyO.........",
    ".OyO..........",
    ".OO...........",
  ],
},

"glowcap_jelly": {
  "pal": {"O":"#1c2a28","K":"#8a5a33","k":"#6b4226","G":"#9fd3df","g":"#6fa8b8",
          "J":"#ffd87f","j":"#e8a33d","W":"#fff6c4"},
  "rows": [
    "....OKKKKO....",
    "....OkKKkO....",
    "...OGGGGGGO...",
    "..OGgWggggGO..",
    "..OGgggggggO..",
    "..OGJJWJJJGO..",
    "..OGJWWJJjGO..",
    "..OGJJJJJjGO..",
    "..OGjJJJjjGO..",
    "...OGgjjgGO...",
    "....OOOOOO....",
  ],
},

"statue_owl": {
  "pal": {"O":"#241712","S":"#948a78","s":"#6f6757","d":"#524a3c","M":"#558a3b","X":"#b5ab97"},
  "rows": [
    "......OOOOOOO.......",
    ".....OSXXSSSSO......",
    "....OSXSSSSSSSO.....",
    "....OSdOSSdOSSO.....",
    "....OSdOSSdOSSO.....",
    "....OSSSddSSSSO.....",
    ".....OSSSdSSSO......",
    "....OSSSSSSSSSO.....",
    "...OSSsSSSSSsSSO....",
    "...OSsSSSSSSSsSO....",
    "...OSsSSSSSSSsSO....",
    "...OSsSSMSSSSsSO....",
    "...OSSsSSSSSsSSO....",
    "....OSSsssssSSO.....",
    "....OssSSSSSssO.....",
    "...OdddddddddddO....",
    "..OdSSSSSSSSSSSdO...",
    "..OdSSsssssMsSSdO...",
    "..OdddddddddddddO...",
    "..OOOOOOOOOOOOOOO...",
  ],
},

"urn": {
  "pal": {"O":"#241712","T":"#c9764a","t":"#a3552f","d":"#874327","X":"#e8945e"},
  "rows": [
    "...OOOOOO.....",
    "..OXTTTTdO....",
    "...OTtttO.....",
    "....OTTO......",
    "...OXTTTdO....",
    "..OXTTTTTdO...",
    ".OXTTTTTTTdO..",
    ".OXTtTTTtTdO..",
    ".OTTtTTTtTdO..",
    ".OTTTTTTTTdO..",
    "..OTTTTTTdO...",
    "..OtTTTTtdO...",
    "...OtttddO....",
    "....OOOOO.....",
  ],
},

"sunken_boat": {
  "pal": {"O":"#101c1e","W":"#7a6448","w":"#5a4a36","d":"#3c322a","X":"#9a8468","A":"#4e8e8a"},
  "rows": [
    "..O.....................O..............",
    "..OO...................OO..............",
    "..OWO........O........OWO...............",
    "..OWWO......OWO......OWWO...............",
    "...OWWOOOOOOWWWOOOOOOWWO................",
    "...OWwWWWWWWwWwWWWWWWwWO................",
    "....OWwWWWWWdWdWWWWWwWO.................",
    "....OwWWXWWWWWWWXWWWwO..................",
    ".....OwWWWWAWWWWWWWwO...................",
    ".....OwwwwwAAwwwwwwO....................",
    "......OddddddddddddO....................",
    ".......OOOOOOOOOOOO.....................",
  ],
},

"cart_wreck": {
  "pal": {"O":"#241712","M":"#5d616c","m":"#3c3f47","W":"#6e5a40","w":"#52432f","R":"#7e4a2a"},
  "rows": [
    "...........OOO..............",
    "..OO......OmMmO.............",
    ".OWWOO....OMmMO.............",
    ".OWWWWOO...OOO..............",
    "..OWwWWWOO..................",
    "..OMWWwWWWOO................",
    "...OMWWWwWWWOO..............",
    "...ORMWWWWwWWWO.............",
    "....OMMWWWWWwWO.............",
    "....OmMMMMMMMO..............",
    ".....OOOmMOOO...............",
    ".......OmMmO................",
    "........OOO.................",
  ],
},

"relic_compass": {
  "pal": {"O":"#241712","G":"#caa958","g":"#94793f","W":"#e8e2c8","R":"#c22746","B":"#2e63b8"},
  "rows": [
    "....OOOO......",
    "..OOGGGGOO....",
    ".OGGgWWgGGO...",
    ".OGWWWRWWGO...",
    "OGgWWRRWWgGO..",
    "OGgWWWRWWgGO..",
    "OGgWWBWWWgGO..",
    ".OGWWBWWWGO...",
    ".OGGgWWgGGO...",
    "..OOGGGGOO....",
    "....OOOO......",
  ],
},

"relic_locket": {
  "pal": {"O":"#241712","G":"#caa958","g":"#94793f","X":"#ffd87f","P":"#e8a8c8"},
  "rows": [
    ".....OO.......",
    "....OggO......",
    "...Og..gO.....",
    "....OggO......",
    "...OGGGGO.....",
    "..OGXGGGGO....",
    ".OGXGPPGGgO...",
    ".OGGPPPPGgO...",
    ".OGGGPPGGgO...",
    "..OGGGGGgO....",
    "...OGggGO.....",
    "....OOOO......",
  ],
},

"relic_coin": {
  "pal": {"O":"#241712","G":"#ffd87f","g":"#caa958","d":"#94793f","X":"#fff6c4"},
  "rows": [
    "...OOOOOO.....",
    "..OGXXGGGO....",
    ".OGXGGGGGgO...",
    ".OGGdddGGgO...",
    "OGXGdGGdGGgO..",
    "OGGGdGGdGGgO..",
    "OGGGdddGGGgO..",
    ".OGGdGGdGgO...",
    ".OGGdGGGGgO...",
    "..OGGGGggO....",
    "...OOOOOO.....",
  ],
},

"relic_idol": {
  "pal": {"O":"#16201f","J":"#2c9c63","j":"#0e5a36","X":"#6fd99c","E":"#ffd87f"},
  "rows": [
    "....OOO.......",
    "...OJXJO......",
    "..OJEJJJO.....",
    "..OJJJJO......",
    "...OJJO.......",
    "..OJXJJO......",
    ".OJJJJJJO.....",
    ".OJjJJjJO.....",
    ".OJJJJJJOO....",
    "..OjJJjJJJO...",
    "..OJJJJOOO....",
    ".OjjOjjO......",
    ".OOO.OOO......",
  ],
},

"relic_bottle": {
  "pal": {"O":"#1c3038","B":"#7ab8c8","b":"#54909e","W":"#e8e2c8","w":"#c4bda0","K":"#6e4c33"},
  "rows": [
    "....OKKO......",
    "....OKKO......",
    "....ObbO......",
    "...ObBBbO.....",
    "..ObBBBBbO....",
    ".ObBWWWBBbO...",
    ".ObBWwWBBbO...",
    ".ObBWWwBBbO...",
    ".ObBBWWBBbO...",
    ".ObbBBBBbbO...",
    "..ObbbbbbO....",
    "...OOOOOO.....",
  ],
},

"moth": {
  "pal": {"O":"#2b2330","W":"#e8dcc0","w":"#c4b89c","d":"#8a7f68","E":"#ffd87f"},
  "rows": [
    "OWWO....OWWO",
    "OWwWO..OWwWO",
    ".OWwWOOWwWO.",
    ".OWdOddOdWO.",
    "..OOdEdOO...",
    "....OdO.....",
  ],
},

"snail": {
  "pal": {"O":"#241712","S":"#a06a3a","s":"#7e5128","d":"#5e3c1e","B":"#e8dcc0","b":"#c4bda0"},
  "rows": [
    ".....OOOO...",
    "B...OSSSSO..",
    "Ob.OSdSSsSO.",
    ".OBOSSdSsSO.",
    ".OBOSsssSO..",
    "OBBBOOOOO...",
    "ObbbbbbbbO..",
    ".OOOOOOOOO..",
  ],
},

"bat": {
  "pal": {"O":"#16121e","B":"#3e3450","b":"#2b2338","E":"#e8a33d"},
  "rows": [
    "O...........O",
    "OBO.OOOOO.OBO",
    "OBBOBBBBBOBBO",
    ".OBBBEBEBBBO.",
    "..OBBBBBBBO..",
    "...OBObOBO...",
    "....O...O....",
  ],
},

"fish": {
  "pal": {"O":"#10262c","T":"#3fa0ae","t":"#2a747e","X":"#8ad8e0","E":"#16242a"},
  "rows": [
    "....OOOOO....O",
    "..OOTXXTTO..OO",
    ".OTXTTTTTTOOtO",
    "OTXTTETTTTTttO",
    ".OTTTTTTTTOOtO",
    "..OOTtttTO..OO",
    "....OOOOO....O",
  ],
},

"bird": {
  "pal": {"O":"#241712","B":"#8a6a4a","b":"#6e5138","R":"#d97a5e","W":"#e8dcc0","E":"#16242a","Y":"#e8a33d"},
  "rows": [
    "...OOO......",
    "..OBBBO.....",
    ".OBBEBBOY...",
    ".ORBBBBOY...",
    "ORRBBbBO....",
    "ORRBBbbO....",
    ".ORRBbO.....",
    "..OObO......",
    "...OYO......",
    "...OYYO.....",
  ],
},

"spore_plant": {
  "pal": {"O":"#16201f","P":"#74e0d2","p":"#3fbfae","d":"#2a8a7e","G":"#3f6b2e","W":"#aef5ea"},
  "rows": [
    "...OPPO.....",
    "..OPWPpO....",
    "..OPppPO....",
    "...OppO.....",
    "OPPO.OG.OPO.",
    "OpWPOOGOPpO.",
    "OPppO.GOppO.",
    ".OOO..G.OO..",
    "...OGGGG....",
    "....OGO.....",
  ],
},

"reeds": {
  "pal": {"O":"#10262c","G":"#3e6e5a","g":"#2c5244","X":"#5a9478","B":"#6e5138"},
  "rows": [
    "..OBO...OBO...",
    "..OBO.X.OBO...",
    ".X.OG.OG.OG...",
    ".OG.OGOXO.OG..",
    "..OGOgO.OGO...",
    ".X.OgO.X.OG...",
    ".OG.OG.OG.....",
    "..OGOgOgO.....",
    "...OgOgO......",
    "...OgOgO......",
    "....OgO.......",
    "....OgO.......",
  ],
},

"spring_lily": {
  "pal": {"O":"#1c3830","G":"#3e8e5a","g":"#2c6a44","X":"#5ab478","P":"#e8a8c8","W":"#fff6c4"},
  "rows": [
    "......OPO.......",
    ".....OPWPO......",
    "......OPO.......",
    "..OOOOXGGOOOO...",
    ".OXGGGGGGGGGgO..",
    "OXGGGGOOGGGGGgO.",
    ".OggggO.Ogggg O".replace(" ",""),
    "..OOOO...OOOO...",
  ],
},

"icon_journal": {
  "pal": {"O":"#241712","B":"#8a4a3a","b":"#6e352a","P":"#e8dcc0","p":"#cdbfa3","G":"#ffd87f"},
  "rows": [
    ".OOOOOOOOOOO..",
    "OBBBBBBBBBBbO.",
    "OBPPPPPPPPpbO.",
    "OBPGGPPPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPppppppPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPppppPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBBBBBBBBBBbO.",
    ".OOOOOOOOOOO..",
  ],
},
}
