# Hand-authored pixel string-art for Glimmer Grotto placeholder sprites.
# Each sprite: palette {char: #hex or #hexAA} + rows of chars ('.' = transparent).
# Rows are padded right with '.' to the widest row; height = len(rows).

SPRITES = {

"miner": {
  "pal": {
    "O":"#241712","H":"#e8a33d","h":"#b5731f","Y":"#ffd87f","l":"#5d616c",
    "L":"#fff6c4","S":"#edb98b","s":"#cf9367","E":"#2b2330","B":"#8a5a33",
    "b":"#6b4226","J":"#46897f","j":"#31635c","K":"#65ab9e","T":"#a06a3a",
    "P":"#6e4c33","p":"#523722","F":"#382a20","f":"#54402f","G":"#cf9367",
    "R":"#e08a6e",
  },
  "rows": [
    "........OOOOOOO.........",
    "......OOHHHHHYYOO.......",
    ".....OHHHHHHHHYYHO......",
    "....OHHHHHHHHHHYHO......",
    "....OHhHHHHHHHHHHOOO....",
    "....OhHHHHHHHHHHHOLLO...",
    "....OhhHHHHHHHHHhOLLO...",
    "...OOhhhhhhhhhhhhOOO....",
    "...OhhhhhhhhhhhhhhO.....",
    "....OSSSSSSSSSSSSO......",
    "....OSSSSSSSSSSSSO......",
    "....OSsSSESSSESSsO......",
    "....OSsSSSSSSSSRsO......",
    "....OBSSSSSSSSSSBO......",
    "....OBBSSSsssSSBBO......",
    ".....OBBBBBBBBBBO.......",
    "......OBBBBBBBBO........",
    "....OOJJJJJJJJJJOO......",
    "...OJKKJJJJJJJJJJJO.....",
    "...OJKTJJJJJJJJJJGGO....",
    "...OJJJTJJJJJJJJOGGO....",
    "...OJjJJTJJJJJJOOOO.....",
    "...OJjJJJTJJJJJO........",
    "...OJjjJJJTJJJJO........",
    "....OjjJJJJJJJO.........",
    "....OTTTTTTTTTO.........",
    "....OPPPPOPPPPO.........",
    "....OPpPO.OPpPO.........",
    "....OPpPO.OPpPO.........",
    "....OFfFO.OFfFO.........",
    "...OFFFFO.OFFFFO........",
    "...OOOOO...OOOOO........",
  ],
},

"pickaxe": {
  "pal": {"O":"#241712","M":"#b9c2cc","m":"#7e8896","X":"#e8eef4","W":"#8a5a33","w":"#6b4226"},
  "rows": [
    "......OOOOOOO.......",
    "....OOMMMMMMMOO.....",
    "...OMMXXXMMMMMMO....",
    "..OMMXOOWWOOMMMMO...",
    ".OMMXO.OWWO.OOmMO...",
    ".OMXO..OWWO...OmMO..",
    ".OMO...OWWO....OmO..",
    ".OO....OWWO.....OO..",
    "......OWWO..........",
    "......OWWO..........",
    ".....OWWO...........",
    ".....OWWO...........",
    "....OWWO............",
    "....OWWO............",
    "...OWwO.............",
    "...OWwO.............",
    "..OwwO..............",
    "..OwwO..............",
    ".OOO................",
  ],
},

"lantern": {
  "pal": {"O":"#241712","M":"#5d616c","m":"#3c3f47","G":"#ffd87f","g":"#fff6c4","F":"#ffae52"},
  "rows": [
    "....OOOO....",
    "...O....O...",
    "...O....O...",
    "..OOOOOOOO..",
    "..OmMMMMmO..",
    ".OMGGGGGGMO.",
    ".OGGggggGGO.",
    ".OGgggggGGO.",
    ".OGGggggGGO.",
    ".OFGGGGGGFO.",
    "..OmMMMMmO..",
    "...OOOOOO...",
  ],
},

"campfire": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","W":"#8a5a33","w":"#6b4226",
          "F":"#ff9f43","f":"#ffd87f","c":"#fff6c4","E":"#e06036"},
  "rows": [
    "..........cc............",
    ".........cffc...........",
    ".........offfo..........".replace("o","F"),
    "........OFfffFO.........",
    "........OFfffFEO........",
    ".......OFFfcffFO........",
    ".......OEFfccfFEO.......",
    "......OFEFfccffFO.......",
    "......OEFFfffFFEO.......",
    ".....OEEFFFFFFFEEO......",
    "...OWwOEEFFFFEEOwWO.....",
    "..OWWwwOOEEEEOOwwWWO....",
    ".OWWWwwwOOOOOOwwwWWWO...",
    ".OwwWWWWWWwWWWWWWWwwO...",
    "..OOrRROwwwwwwORRrOO....",
    ".ORRrrRRROOOOORRrrRRO...",
    ".ORrRRrRRRRRRRRrRRrRO...",
    "..OOOOOOOOOOOOOOOOOO....",
  ],
},

"minecart": {
  "pal": {"O":"#241712","M":"#5d616c","m":"#3c3f47","W":"#8a5a33","w":"#6b4226",
          "X":"#9aa3ad","G":"#b07ae0","g":"#e8c57a","V":"#7ab362"},
  "rows": [
    "......g..G....V.g.............",
    ".....gGG.GG.VV.Gg.............",
    "..OOgGGGGGGVVVGGgOO...........",
    ".OMMXXXXXXXXXXXXXXMO..........",
    ".OMWWwWWWwWWWwWWWWMO..........",
    ".OMWWwWWWwWWWwWWWWMO..........",
    "..OMWwWWWwWWWwWWWMO...........",
    "..OMWwWWWwWWWwWWWMO...........",
    "...OMwWWWwWWWwWWMO............",
    "...OMMMMMMMMMMMMMO............",
    "....OOOOOOOOOOOO..............",
    "....OmMO....OMmO..............",
    "...OmMMmO..OmMMmO.............",
    "...OMmmMO..OMmmMO.............",
    "....OmMO....OMmO..............",
    ".....OO......OO...............",
  ],
},

"tent": {
  "pal": {"O":"#241712","C":"#c9764a","c":"#a3552f","D":"#874327","P":"#6b4226",
          "L":"#e8945e","I":"#3a2b22"},
  "rows": [
    "..................OO....................",
    ".................OPPO...................",
    ".................OLLO...................",
    "................OLCCLO..................",
    "...............OLCCCCLO................",
    "..............OLCCCCCCLO...............",
    ".............OLCCCCCCCCLO..............",
    "............OLCCCCcCCCCCLO.............",
    "...........OLCCCCccCCCCCCLO............",
    "..........OLCCCCCccCCCCCCCLO...........",
    ".........OLCCCCCcccCCCCCCCCLO..........",
    "........OLCCCCCCcDcCCCCCCCCCLO.........",
    ".......OLCCCCCCcDDDcCCCCCCCCCLO........",
    "......OLCCCCCCcDDIDDcCCCCCCCCCLO.......",
    ".....OLCCCCCCcDDIIIDDcCCCCCCCCCLO......",
    "....OLCCCCCCcDDIIIIIDDcCCCCCCCCCLO.....",
    "...OLCCCCCCcDDIIIIIIIDDcCCCCCCCCCLO....",
    "..OLCCCCCCcDDIIIIIIIIIDDcCCCCCCCCCLO...",
    ".OLCCCCCCcDDIIIIIIIIIIIDDcCCCCCCCCCLO..",
    ".OcccccccDDIIIIIIIIIIIIIDDccccccccccO..",
    "..OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...",
  ],
},

"crate": {
  "pal": {"O":"#241712","W":"#a06a3a","w":"#7e5128","d":"#5e3c1e","X":"#c9905a"},
  "rows": [
    ".OOOOOOOOOOOOOOOO.",
    "OXWWWWWWWWWWWWWWdO",
    "OWXWWwwwwwwwwWWWdO",
    "OWWXwWWWWWWWWxWWdO".replace("x","w"),
    "OWwWXWWWWWWwXWWWdO",
    "OWwWWXWWWWwXWWWWdO",
    "OWwWWWXWWwXWWWWWdO",
    "OWwWWWWXXWWWWWWWdO",
    "OWwWWWwXXWWWWWWWdO",
    "OWwWWwXWWXWWWWWWdO",
    "OWwWwXWWWWXWWWWWdO",
    "OWwwXWWWWWWXWWWWdO",
    "OWdWWWWWWWWWWWWWdO",
    "OddddddddddddddddO",
    ".OOOOOOOOOOOOOOOO.",
  ],
},

"geode_closed": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","d":"#434a54","X":"#9aa3ad"},
  "rows": [
    "......OOOOOO........",
    "....OORRRRRROO......",
    "...ORRXXRRRRRRO.....",
    "..ORXXRRRRrRRRRO....",
    ".ORXRRRRRRRrRRRRO...",
    ".ORRRRdRRRRRrRRRO...",
    "ORRRRdRRRRRRRrRRRO..",
    "ORRRdRRRRRRRRRrRRO..",
    "ORRrdRRRRRRRRRrrRO..",
    "ORRrRdRRRRRRRrrRRO..",
    ".ORrRRddRRRrrrRRO...",
    ".ORrrRRRdddrrRRRO...",
    "..ORrrrrrrrrrROO....",
    "...OORrrrrrROO......",
    ".....OOOOOOO........",
  ],
},

"geode_open": {
  "pal": {"O":"#241712","R":"#7e8896","r":"#565d68","A":"#b07ae0","a":"#8a54c0",
          "W":"#e6d4ff","w":"#cba8f5"},
  "rows": [
    ".....OOOOOOOO.........",
    "...OORRRRRRRROO.......",
    "..ORRaAAaAAaRRRO......",
    ".ORaAWAaAWAaAaRRO.....",
    ".ORAWWAAWWAAWAaRO.....",
    "ORaAWAaAWwAaAWaRRO....",
    "ORAaAAaAwwaAaAAaRO....",
    "ORaAaAaAaAaAaAaARO....",
    ".ORaaAaaAaaAaaARO.....",
    ".ORraaaaaaaaaaRRO.....",
    "..ORrrrrrrrrrROO......",
    "...OORrrrrrROO........",
    ".....OOOOOOO..........",
  ],
},

"fossil_ammonite": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","d":"#52493c","C":"#cdbfa3","c":"#b0a184"},
  "rows": [
    "...OOOOOOOOOOOOO....",
    "..ORRRRRRRRRRRRRO...",
    ".ORRRRccccccRRRRRO..",
    ".ORRRcCCCCCCcRRRRO..",
    "ORRRcCcccccCCcRRRRO.",
    "ORRcCcCCCCcCCcRRRRO.",
    "ORRcCcCccCcCCcRRRrO.",
    "ORRcCcCcCcCCcCRRRrO.",
    "ORRcCcCCCCCcCcRRRrO.",
    "ORRcCcccccccCcRRRrO.",
    "ORRRcCCCCCCCCcRRRrO.",
    "ORRRRccccccccRRRRrO.",
    ".ORRRRRRRRRRRRRrrO..",
    "..ORRRrrrrrrrrrrO...",
    "...OOOOOOOOOOOOO....",
  ],
},

"fossil_fern": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","G":"#a8a182","g":"#8f8868"},
  "rows": [
    "...OOOOOOOOOOOO.....",
    "..ORRRRRRRRRRRRO....",
    ".ORRRRRgGgRRRRRRO...",
    ".ORRRgGgGgGgRRRRO...",
    "ORRRRgGgGgGgGRRRRO..",
    "ORRgGgRgGgRgGgRRRO..",
    "ORRRgGgRGgRGgRRRrO..",
    "ORRgGgRgGgRgGgRRrO..",
    "ORRRgGgRGgRGgRRRrO..",
    "ORRgGgRgGgRgGgRRrO..",
    "ORRRRgGgGgGgRRRRrO..",
    "ORRRRRgGgGgRRRRRrO..",
    ".ORRRRRgGgRRRRRrO...",
    "..ORRRRRRRRRRRrO....",
    "...OOOOOOOOOOOO.....",
  ],
},

"fossil_fish": {
  "pal": {"O":"#241712","R":"#8d8273","r":"#6b6253","B":"#cdbfa3","b":"#b0a184","E":"#52493c"},
  "rows": [
    "..OOOOOOOOOOOOOOOOOO....",
    ".ORRRRRRRRRRRRRRRRRRO...",
    "ORRRRbBbRRBRRBRRbRRRRO..",
    "ORRBbRRBbRBRRBRBbRRRRO..",
    "ORREBBBBBBBBBBBBBbbRrO..",
    "ORRBbRRBbRBRRBRBbBbRrO..",
    "ORRRRbBbRRBRRBRRbRBrO...",
    ".ORRRRRRRRRRRRRRRRRrO...",
    "..OOOOOOOOOOOOOOOOOO....",
  ],
},

"mushroom_glow_big": {
  "pal": {"O":"#16201f","C":"#3fbfae","c":"#2a8a7e","D":"#1f6159","S":"#e8e2c8",
          "s":"#c4bda0","G":"#aef5ea","g":"#74e0d2"},
  "rows": [
    "......OOOOOOO.......",
    "....OOCCCCCCCOO.....",
    "...OCCGgCCCCCCCO....",
    "..OCGgGCCCCcCCCCO...",
    ".OCCgGCCCCCCcCCCCO..",
    ".OCCCCCCgCCCCcCCCO..",
    "OCCcCCCCCCCCCCcCCCO.",
    "OCcCCCCgGgCCCCCcCCO.",
    "OCcCCCCCgCCCCCCcCCO.",
    "OcCCcCCCCCCCcCCCCcO.",
    ".OccCccCCCCcCCCccO..",
    "..OOcccccccccccOO...",
    "....OOSSsSSOO.......",
    ".....OSSsSSO........",
    ".....OSSsSSO........",
    ".....OSSsSsO........",
    "....OSSSsSSsO.......",
    "....OSsssssSO.......",
    ".....OOOOOOO........",
  ],
},

"mushroom_glow_small": {
  "pal": {"O":"#16201f","C":"#3fbfae","c":"#2a8a7e","S":"#e8e2c8","s":"#c4bda0","G":"#aef5ea"},
  "rows": [
    "...OOOOO....",
    "..OCGCCCO...",
    ".OCGgCCcCO..",
    "OCCGCCCCcCO.",
    "OCcCCGCCcCO.",
    ".OccCCCccO..",
    "..OOcccOO...",
    "...OSsSO....",
    "...OSsSO....",
    "..OSSssSO...",
    "...OOOOO....",
  ],
},

"icon_bag": {
  "pal": {"O":"#241712","B":"#a06a3a","b":"#7e5128","d":"#5e3c1e","S":"#c9905a","G":"#ffd87f"},
  "rows": [
    "....OOOO......",
    "...Od..dO.....",
    "..OdO..OdO....",
    ".OSBBOOBBSO...",
    "OSBBBBBBBBSO..",
    "OBBSGGGGSBBO..",
    "ObBSGGGGSBbO..",
    "ObBBSSSSBBbO..",
    "ObbBBBBBBbbO..",
    ".ObbbBBbbbO...",
    "..OOObbOOO....",
    "....OOOO......",
  ],
},

"icon_energy": {
  "pal": {"O":"#241712","Y":"#ffd87f","y":"#e8a33d","W":"#fff6c4"},
  "rows": [
    "......OOOO....",
    ".....OYYWO....",
    "....OYYWO.....",
    "...OYYWO......",
    "..OYYYYOOO....",
    ".OYWYYYYYO....",
    ".OOOOYYYO.....",
    "....OYYO......",
    "...OYyO.......",
    "..OYyO........",
    "..OyO.........",
    ".OyO..........",
    ".OO...........",
  ],
},

"icon_journal": {
  "pal": {"O":"#241712","B":"#8a4a3a","b":"#6e352a","P":"#e8dcc0","p":"#cdbfa3","G":"#ffd87f"},
  "rows": [
    ".OOOOOOOOOOO..",
    "OBBBBBBBBBBbO.",
    "OBPPPPPPPPpbO.",
    "OBPGGPPPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPppppppPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPppppPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBPPPPPPPPpbO.",
    "OBBBBBBBBBBbO.",
    ".OOOOOOOOOOO..",
  ],
},
}
