from pathlib import Path
import gzip,hashlib,json
import os
root=Path(__file__).resolve().parent.parent
os.chdir(root)
packed={}
for p in [*Path('assets').glob('*.bin'),Path('assets/scenery/pine.bin')]:
 raw=p.read_bytes(); payload=gzip.compress(raw,compresslevel=9,mtime=0)
 name=p.stem+'-'+hashlib.sha256(raw).hexdigest()[:12]+'.gz.bin'
 dest=Path('assets/packed')/name;dest.parent.mkdir(exist_ok=True);dest.write_bytes(payload)
 packed[p.as_posix()]={'url':dest.as_posix(),'bytes':len(raw),'packedBytes':len(payload)}
Path('packed-assets.js').write_text('// Generated by source/pack-assets.py. Original bytes are retained as a fallback.\nexport const packedAssets='+json.dumps(packed,indent=2)+';\n',encoding='utf-8')
