// Run after npm --prefix scripts/rotatable-aquascape run build.
// Keeps jez237 and both Hidden Reef variants on the same tested aquarium bundle.
import {cpSync,readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {checkAquariumSync} from './check_aquarium_sync.mjs';
const root=resolve(import.meta.dirname,'..');
const site=resolve(root,'prototypes/hidden-reef');
const preview=resolve(root,'prototypes/hidden-reef-header-preview');
const dist=resolve(root,'scripts/rotatable-aquascape/dist');
cpSync(dist,resolve(root,'demos/rotatable-aquascape'),{recursive:true});
// Reuse the store's actual navigation enhancement without running its animated
// full-page background alongside the aquarium. Regenerate rather than fork it.
const backgroundSource=readFileSync(resolve(site,'assets/reef-background.js'),'utf8');
const navigation=backgroundSource.slice(backgroundSource.indexOf('  function enhanceMasthead()'),backgroundSource.indexOf('  function enhancePreviewNotice()'));
if(!navigation.startsWith('  function enhanceMasthead()')||!navigation.includes('updateCompactHeader'))throw Error('Shared store navigation source changed.');
writeFileSync(resolve(site,'assets/showroom-navigation.js'),`// Generated by scripts/sync_hidden_reef_showroom.mjs from reef-background.js.\n(()=>{'use strict';const reefAssetBase=new URL('.',document.currentScript.src);const showroomUrl=new URL('../showroom/',reefAssetBase);\n${navigation.replaceAll('href="/category/','href="../category/')}\nenhanceMasthead();})();\n`);
cpSync(dist,resolve(site,'showroom/aquarium'),{recursive:true});
const entry=resolve(site,'showroom/aquarium/index.html');
writeFileSync(entry,readFileSync(entry,'utf8').replace('href="../living-aquascape/"','href="../"').replace('View the photographic aquarium','Return to the showroom'));
for(const file of ['assets/showroom.js','assets/showroom.css','assets/showroom-navigation.js','assets/site/showroom-preview.jpg','assets/site/favicon.png','assets/link-modal.js','assets/reef-background.js','assets/category.js','assets/header-assets.json','assets/animated-header/header.js','assets/animated-header/header.ts','assets/animated-header/header.css','assets/animated-header/reef-engine.ts','assets/animated-header/index.html','assets/animated-header/README.md','_headers'])cpSync(resolve(site,file),resolve(preview,file));
cpSync(resolve(site,'assets/optimized'),resolve(preview,'assets/optimized'),{recursive:true});
mkdirSync(resolve(preview,'showroom'),{recursive:true});
cpSync(resolve(site,'showroom'),resolve(preview,'showroom'),{recursive:true});
writeFileSync(resolve(preview,'index.html'),readFileSync(resolve(site,'index.html'),'utf8').replace('site-masthead.css?v=20260906-animated"','site-masthead.css?v=20260906-animated-preview"').replace('reef-background.js?v=20260906-performance','reef-background.js?v=20260712-unified-nav'));
checkAquariumSync(root);
console.log('Synchronized the aquarium build across jez237 and both Hidden Reef storefront variants.');
