#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';

const repoRoot = path.resolve(import.meta.dirname, '..');
const outputPath = path.join(repoRoot, 'prototypes/hidden-reef/assets/new-arrivals.js');
const homeUrl = 'https://www.thehiddenreef.com/';
const args = parseArgs(process.argv.slice(2));
const write = Boolean(args.write);
const timestamp = new Date().toISOString();
const reportDir = path.join(repoRoot, 'tmp', `hidden-reef-new-arrivals-${timestamp.replace(/[:.]/g, '-')}`);

function parseArgs(argv) {
  const parsed = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === '--write') {
      parsed.write = true;
    } else if (arg.startsWith('--')) {
      parsed[arg.slice(2)] = argv[index + 1];
      index += 1;
    }
  }
  return parsed;
}

function decodeHtml(value = '') {
  return value
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

function stripTags(value = '') {
  return decodeHtml(value.replace(/<[^>]+>/g, ' '));
}

function absoluteUrl(url, baseUrl) {
  if (!url) return '';
  try {
    return new URL(decodeHtml(url), baseUrl).toString();
  } catch {
    return decodeHtml(url);
  }
}

function bestImageFromSrcset(srcset = '', src = '', baseUrl = '') {
  const candidates = srcset
    .split(',')
    .map(part => {
      const bits = part.trim().split(/\s+/);
      const width = Number((bits[1] || '').replace(/\D/g, '')) || 0;
      return { url: absoluteUrl(bits[0], baseUrl), width };
    })
    .filter(item => item.url);
  if (candidates.length) {
    candidates.sort((a, b) => b.width - a.width);
    return candidates[0].url;
  }
  return absoluteUrl(src, baseUrl);
}

async function fetchHtml(url) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20000);
  try {
    const response = await fetch(url, {
      signal: controller.signal,
      headers: {
        'user-agent': 'Mozilla/5.0 Hidden Reef daily new arrivals refresh',
        accept: 'text/html,application/xhtml+xml'
      }
    });
    if (!response.ok) throw new Error(`${url} returned HTTP ${response.status}`);
    return await response.text();
  } finally {
    clearTimeout(timeout);
  }
}

function parseProductCards(html, pageUrl) {
  const section = html.match(/<h2[^>]*>\s*New arrivals\s*<\/h2>[\s\S]*?<\/section>/i)?.[0] || '';
  const cards = section.match(/<div class="prod-card">[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/g) || [];
  return cards.map((card, index) => {
    const titleMatch = card.match(/<a[^>]+class="product-card__title"[^>]*>([\s\S]*?)<\/a>/);
    const imageLinkMatch = card.match(/<a[^>]+class="prod-card__img-link"[^>]+href="([^"]+)"/);
    const titleLinkMatch = card.match(/<a[^>]+href="([^"]+)"[^>]+class="product-card__title"/);
    const ariaMatch = card.match(/class="prod-card__img-link"[^>]+aria-label="([^"]+)"/);
    const priceMatch = card.match(/<ins[^>]+class="prod-card__price"[^>]*>([\s\S]*?)<\/ins>/);
    const imgTag = card.match(/<img\b[\s\S]*?>/)?.[0] || '';
    const srcMatch = imgTag.match(/\bsrc="([^"]+)"/);
    const srcsetMatch = imgTag.match(/\bsrcset="([\s\S]*?)"/);
    const name = stripTags(titleMatch?.[1] || ariaMatch?.[1] || '');
    const productUrl = absoluteUrl(titleLinkMatch?.[1] || imageLinkMatch?.[1] || '', pageUrl);
    const price = stripTags(priceMatch?.[1] || '');
    const imageUrl = bestImageFromSrcset(srcsetMatch?.[1] || '', srcMatch?.[1] || '', pageUrl);
    if (!name || !productUrl) return null;
    return {
      name,
      price,
      productUrl,
      imageUrl,
      page: 1,
      sourceSection: 'New arrivals',
      newArrivalRank: index + 1
    };
  }).filter(Boolean);
}

function renderNewArrivalsFile(products) {
  const payload = {
    generatedAt: timestamp,
    sourceUrl: homeUrl,
    products
  };
  const json = JSON.stringify(payload, null, 2)
    .replace(/<\/script/gi, '<\\/script')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
  return `// The Hidden Reef new arrivals data\n// Generated by scripts/update_hidden_reef_new_arrivals.mjs\nwindow.THR_NEW_ARRIVALS = ${json};\n`;
}

await fs.mkdir(reportDir, { recursive: true });
const html = await fetchHtml(homeUrl);
const products = parseProductCards(html, homeUrl);
const previous = await fs.readFile(outputPath, 'utf8').catch(() => '');
const next = renderNewArrivalsFile(products);
const changed = previous !== next;
const reportPath = path.join(reportDir, 'report.json');

await fs.writeFile(reportPath, `${JSON.stringify({
  timestamp,
  sourceUrl: homeUrl,
  write,
  changed,
  products: products.length,
  firstProduct: products[0]?.name || ''
}, null, 2)}\n`);

if (write && changed) {
  await fs.writeFile(outputPath, next);
}

console.log(JSON.stringify({
  mode: write ? 'write' : 'dry-run',
  changed,
  products: products.length,
  reportPath
}, null, 2));
