import * as T from 'three';
import {mergeGeometries,mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {edge,bottom,pondShape,seeded} from './PondGeometry.js';
const rand=seeded(281926),pick=(a,b)=>a+(b-a)*rand();
function surfaceMap(kind){const c=document.createElement('canvas');c.width=c.height=512;const cx=c.getContext('2d'),im=cx.createImageData(512,512);for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4,n=rand(),grain=Math.sin(x*.07+Math.sin(y*.03)*3)*Math.cos(y*.09),v=.80+n*.25+grain*.10;const b=kind==='stone'?[125,127,110]:kind==='wood'?[113,81,51]:kind==='bed'?[132,137,100]:[70,91,48];for(let k=0;k<3;k++)im.data[i+k]=b[k]*v;im.data[i+3]=255;}cx.putImageData(im,0,0);if(kind==='wood'){cx.strokeStyle='#352b2240';for(let j=0;j<180;j++){cx.beginPath();cx.moveTo(0,rand()*512);cx.bezierCurveTo(100,rand()*512,300,rand()*512,512,rand()*512);cx.stroke();}}const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;t.repeat.set(kind==='ground'?14:2,kind==='ground'?14:2);return t;}
function merged(parts,mat,name,parent){const g=mergeGeometries(parts,false);for(const part of parts)part.dispose();const m=new T.Mesh(g,mat);m.name=name;m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
function cylinder(a,b,r0,r1,segments=9){const d=new T.Vector3().subVectors(b,a),g=new T.CylinderGeometry(r1,r0,d.length(),segments,1);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),d.normalize()));g.translate((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);return g;}
function rockGeo(x,y,z,sx,sy,sz){const g=mergeVertices(new T.IcosahedronGeometry(1,3)),p=g.getAttribute('position');for(let i=0;i<p.count;i++){const px=p.getX(i),py=p.getY(i),pz=p.getZ(i),f=1+.08*Math.sin(px*13+py*6)*Math.sin(pz*9-px*3);p.setXYZ(i,px*f,py*f,pz*f);}g.computeVertexNormals();g.scale(sx,sy,sz);g.rotateY(rand()*6.28);g.translate(x,y,z);return g;}
function leafGeometry(){const g=new T.BufferGeometry(),p=[],uv=[],indices=[];for(let i=0;i<=10;i++){const t=i/10,w=Math.sin(Math.PI*t)**.85*.041;for(let j=0;j<3;j++){const side=j-1;p.push(side*w,.025*Math.sin(Math.PI*t)-Math.abs(side)*.009,t*.23);uv.push(j/2,t);}if(i)for(let j=0;j<2;j++){const a=(i-1)*3+j;indices.push(a,a+3,a+1,a+1,a+3,a+4);}}g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g;}
function flowerGeometry(){const parts=[];for(let i=0;i<4;i++){const a=i/4*Math.PI*2,g=new T.SphereGeometry(1,8,5);g.scale(.34,.07,.45);g.rotateY(a);g.translate(Math.sin(a)*.29,0,Math.cos(a)*.29);parts.push(g);}const center=new T.SphereGeometry(.14,8,5);center.translate(0,.065,0);parts.push(center);return mergeGeometries(parts,false);}
export function buildPondScene(scene,clock){
 const garden=new T.Group(),underwater=new T.Group();scene.add(garden,underwater);
 const stoneMap=surfaceMap('stone'),woodMap=surfaceMap('wood'),groundMap=surfaceMap('ground'),bedMap=surfaceMap('bed');
 const rockMat=new T.MeshStandardMaterial({map:stoneMap,bumpMap:stoneMap,bumpScale:.018,roughness:.97,color:'#b0ad8f'}),mossMat=new T.MeshStandardMaterial({color:'#617243',roughness:1});
 const outer=new T.Shape();outer.moveTo(-55,-55);outer.lineTo(55,-55);outer.lineTo(55,55);outer.lineTo(-55,55);outer.closePath();const hole=new T.Path(pondShape().getPoints());outer.holes.push(hole);const ground=new T.Mesh(new T.ShapeGeometry(outer,80),new T.MeshStandardMaterial({map:groundMap,roughness:1,color:'#b1b39a'}));ground.rotation.x=-Math.PI/2;ground.position.y=.08;ground.receiveShadow=true;garden.add(ground);
 const shore=[],moss=[];
 for(let i=0;i<108;i++){const a=i/108*Math.PI*2,p=edge(a),s=pick(.17,.32);shore.push(rockGeo(p.x,.04,p.z,s,pick(.14,.28),s*.85));if(i%3===0)moss.push(rockGeo(p.x-.02,.19,p.z-.02,s*.7,.043,s*.65));}
 merged(shore,rockMat,'Weathered stone shoreline',garden);merged(moss,mossMat,'Moss at the water edge',garden);
 // The pond floor is a volumetric bowl with a shallow planted margin.
 const verts=[],uv=[],idx=[];const rings=34,ns=180;
 for(let i=0;i<=rings;i++)for(let j=0;j<=ns;j++){const a=j/ns*Math.PI*2,p=edge(a).multiplyScalar(Math.max(.001,i/rings));verts.push(p.x,bottom(p.x,p.z),p.z);uv.push(p.x/2,p.z/2);}
 for(let i=0;i<rings;i++)for(let j=0;j<ns;j++){const a=i*(ns+1)+j;idx.push(a,a+ns+2,a+ns+1,a,a+1,a+ns+2);}
 const bedGeo=new T.BufferGeometry();bedGeo.setAttribute('position',new T.Float32BufferAttribute(verts,3));bedGeo.setAttribute('uv',new T.Float32BufferAttribute(uv,2));bedGeo.setIndex(idx);bedGeo.computeVertexNormals();
 const bedMat=new T.MeshStandardMaterial({map:bedMap,roughness:1,color:'#74806a',side:T.DoubleSide});
 bedMat.onBeforeCompile=shader=>{shader.uniforms.pondClock=clock;shader.vertexShader='varying vec3 bedWorld;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>','#include <worldpos_vertex>\nbedWorld=(modelMatrix*vec4(transformed,1.)).xyz;');shader.fragmentShader='varying vec3 bedWorld;uniform float pondClock;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <dithering_fragment>',`float a=sin(bedWorld.x*9.+sin(bedWorld.z*7.+pondClock*.55)+pondClock*.32);float b=sin(bedWorld.z*10.+sin(bedWorld.x*6.-pondClock*.41));float c=pow(max(0.,1.-abs(a+b)*1.5),5.);gl_FragColor.rgb*=.78+c*.26;\n#include <dithering_fragment>`);};
 const bed=new T.Mesh(bedGeo,bedMat);bed.receiveShadow=true;underwater.add(bed);
 const pebbles=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),rockMat,1200),d=new T.Object3D();
 for(let i=0;i<1200;i++){const a=rand()*6.28,r=Math.sqrt(rand())*.95,p=edge(a).multiplyScalar(r),s=pick(.015,.065);d.position.set(p.x,bottom(p.x,p.z)+s*.4,p.z);d.scale.set(s,s*.5,s*.7);d.rotation.set(rand()*3,rand()*6,rand()*3);d.updateMatrix();pebbles.setMatrixAt(i,d.matrix);pebbles.setColorAt(i,new T.Color().setHSL(.12,.09,pick(.23,.52)));}pebbles.receiveShadow=true;underwater.add(pebbles);
 // A low timber viewing deck replaces the reference's bridge/pavilion arrangement.
 const planks=[];for(let i=0;i<23;i++){const g=new T.BoxGeometry(.13,.105,1.56);g.translate(-5.0+i*.145,.22,3.22);planks.push(g);}merged(planks,new T.MeshStandardMaterial({map:woodMap,roughness:.76,color:'#a28e74'}),'Timber viewing deck',garden);
 const beams=[];for(const x of [-4.8,-2.2])beams.push(cylinder(new T.Vector3(x,-.25,3.5),new T.Vector3(x,.26,3.5),.09,.09));merged(beams,new T.MeshStandardMaterial({color:'#534334',roughness:1}),'Deck supports',garden);
 const steps=[];for(let i=0;i<9;i++){const x=-2.1+i*.65,z=4.0+Math.sin(i*.48)*.42;steps.push(rockGeo(x,.10,z,.32,.11,.28));}merged(steps,rockMat,'Slate stepping path',garden);
 // Terraced stone cascade occupies the far right corner.
 const cascade=[];for(let tier=0;tier<4;tier++)for(let j=0;j<4;j++){const x=2.62+j*.28+tier*.17,z=-2.36-tier*.40;cascade.push(rockGeo(x,.13+tier*.31,z,.30,.19,.38));}merged(cascade,new T.MeshStandardMaterial({map:stoneMap,roughness:.78,color:'#6c746e'}),'Slate cascade',garden);
 const fallMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time:clock},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time;void main(){float ribbons=.5+.5*sin(v.x*135.+sin(v.y*25.-time*7.));float foam=pow(ribbons,8.)*.35;float edge=smoothstep(0.,.08,v.x)*(1.-smoothstep(.92,1.,v.x));gl_FragColor=vec4(vec3(.66,.83,.82)+foam,edge*(.26+foam));}'});
 for(let tier=0;tier<3;tier++){const a=new T.Vector3(3.03+tier*.17,.24+tier*.31,-2.36-tier*.4),b=new T.Vector3(3.20+tier*.17,.55+tier*.31,-2.76-tier*.4),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([a.x-.4,a.y,a.z,a.x+.4,a.y,a.z,b.x-.4,b.y,b.z,b.x+.4,b.y,b.z],3));g.setAttribute('uv',new T.Float32BufferAttribute([0,0,1,0,0,1,1,1],2));g.setIndex([0,2,1,1,2,3]);g.computeVertexNormals();garden.add(new T.Mesh(g,fallMat));}
 const trunkParts=[],leaves=[];const leafColors=[];
 function tree(x,z,height,hue,seed){const rr=seeded(seed),origin=new T.Vector3(x,.07,z);
  function branch(a,dir,len,radius,level){const b=a.clone().addScaledVector(dir,len);trunkParts.push(cylinder(a,b,radius,radius*.63,8));if(level===0){for(let i=0;i<135;i++){const q=b.clone().add(new T.Vector3((rr()-.5)*1.35,(rr()-.4)*.70,(rr()-.5)*1.35));leaves.push({p:q,s:.5+rr()*.85,r:[rr()*2,rr()*6.28,rr()*2]});leafColors.push(new T.Color().setHSL(hue+(rr()-.5)*.025,.29+rr()*.25,.17+rr()*.13));}return;}for(let j=0;j<3;j++){const az=rr()*6.28,nd=dir.clone().multiplyScalar(.55).add(new T.Vector3(Math.cos(az)*.75,.36+rr()*.25,Math.sin(az)*.75)).normalize();branch(b,nd,len*(.60+rr()*.12),radius*.53,level-1);}}
  branch(origin,new T.Vector3(.08,1,-.02).normalize(),height*.42,height<2?.055:.17,height<2?2:3);
 }
 for(const [x,z,h,hue,seed] of [[-5.8,-3.8,4.8,.25,3],[-4.6,-5.7,5.2,.27,4],[-1.6,-6.5,5.5,.23,5],[1.9,-6.7,5.8,.27,6],[5.4,-5.8,5.3,.24,7],[8.7,-3.4,5,.28,8],[-8,3.4,5.2,.24,9],[-5.8,-.4,3.8,.015,13]])tree(x,z,h,hue,seed);
 // Low, layered evergreen planting frames the pond without hiding its inhabitants.
 for(let i=0;i<24;i++){const a=i/24*Math.PI*2,p=edge(a).multiplyScalar(1.45+rand()*.20);if(p.z>1.5)continue;tree(p.x,p.z,pick(.8,1.55),pick(.23,.30),90+i);}
 merged(trunkParts,new T.MeshStandardMaterial({color:'#584d3d',roughness:1}),'Woodland branches',garden);
 const leafMat=new T.MeshStandardMaterial({color:'#728544',side:T.DoubleSide,roughness:.9});
 leafMat.onBeforeCompile=s=>{s.uniforms.gardenTime=clock;s.vertexShader='uniform float gardenTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x+=sin(gardenTime*1.2+instanceMatrix[3].x*1.3+instanceMatrix[3].z)*.014*uv.y;');};
 const foliage=new T.InstancedMesh(leafGeometry(),leafMat,leaves.length);leaves.forEach((l,i)=>{d.position.copy(l.p);d.scale.setScalar(l.s);d.rotation.set(...l.r);d.updateMatrix();foliage.setMatrixAt(i,d.matrix);foliage.setColorAt(i,leafColors[i]);});foliage.castShadow=foliage.receiveShadow=true;garden.add(foliage);
 // Individual curved blades, fern fronds and low flowering shrubs soften the rim.
 const grasses=[],fern=[];function blade(x,y,z,h,angle,width,bend){const g=new T.BufferGeometry(),p=[],ix=[];for(let j=0;j<=7;j++){const t=j/7,w=width*(1-t)*.5,cx=x+Math.cos(angle)*bend*t*t,cz=z+Math.sin(angle)*bend*t*t;for(const side of [-1,1])p.push(cx+Math.sin(angle)*w*side,y+h*t,cz-Math.cos(angle)*w*side);if(j){const a=(j-1)*2;ix.push(a,a+2,a+1,a+1,a+2,a+3);}}g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setIndex(ix);g.computeVertexNormals();return g;}
 for(let i=0;i<90;i++){const a=i/90*6.28,p=edge(a).multiplyScalar(1.10+rand()*.09);if(p.z>2.1&&p.x<-.8)continue;for(let b=0;b<22;b++)grasses.push(blade(p.x+pick(-.16,.16),.12,p.z+pick(-.16,.16),pick(.18,.65),rand()*6.28,pick(.022,.05),pick(.15,.38)));}
 merged(grasses,new T.MeshStandardMaterial({color:'#355224',roughness:.9,side:T.DoubleSide}),'Sedges and marginal grasses',garden);
 for(let i=0;i<26;i++){const a=i/26*6.28,p=edge(a).multiplyScalar(1.2);if(p.z>1.8&&p.x<-.5)continue;for(let f=0;f<7;f++){const az=f/7*6.28+rand(),len=pick(.35,.72);for(let n=1;n<10;n++){const t=n/10,x=p.x+Math.cos(az)*len*t,z=p.z+Math.sin(az)*len*t,y=.12+Math.sin(t*Math.PI*.75)*len*.7;for(const side of [-1,1])fern.push(blade(x,y,z,.04,az+side*1.1,.045,len*.24*Math.sin(Math.PI*t)));}}}
 merged(fern,new T.MeshStandardMaterial({color:'#315333',roughness:.85,side:T.DoubleSide}),'Fern gardens',garden);
 const flowers=new T.InstancedMesh(flowerGeometry(),new T.MeshStandardMaterial({color:'#bf92b7',roughness:.85}),600);for(let i=0;i<600;i++){const cluster=i%6,a=[.55,1.45,2.95,3.7,4.8,5.65][cluster],p=edge(a).multiplyScalar(1.3),az=rand()*6.28,rad=rand()*.40;d.position.set(p.x+Math.cos(az)*rad,.26+Math.sqrt(.18-rad*rad)*.8+rand()*.09,p.z+Math.sin(az)*rad);d.scale.set(.075,.075,.075);d.rotation.set((rand()-.5)*1.8,rand()*6,(rand()-.5)*1.8);d.updateMatrix();flowers.setMatrixAt(i,d.matrix);flowers.setColorAt(i,new T.Color().setHSL(.82+rand()*.05,.17,.50+rand()*.18));}flowers.castShadow=true;garden.add(flowers);
 // Lily pads stay near one sheltered margin, leaving the open swimming water clear.
 const lilies=new T.Group();for(let i=0;i<11;i++){const a=.1+i*.086,p=edge(a).multiplyScalar(.76+rand()*.12),r=pick(.14,.26);const shape=new T.Shape();shape.moveTo(0,0);for(let j=1;j<=48;j++){const t=.25+j/48*(6.28-.50);shape.lineTo(Math.cos(t)*r,Math.sin(t)*r);}shape.lineTo(0,0);const geo=new T.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);const pad=new T.Mesh(geo,new T.MeshStandardMaterial({color:new T.Color().setHSL(.26,.58,.12+rand()*.06),side:T.DoubleSide,roughness:.72}));pad.position.set(p.x,.017+rand()*.007,p.z);pad.rotation.y=rand()*6.28;pad.castShadow=true;pad.userData.base=pad.position.y;lilies.add(pad);}garden.add(lilies);
 // Veins and a curled perimeter give the floating leaves a close-view surface.
 const leafCanvas=document.createElement('canvas');leafCanvas.width=leafCanvas.height=256;const lc=leafCanvas.getContext('2d');lc.fillStyle='#689048';lc.fillRect(0,0,256,256);for(let n=0;n<42;n++){const a=n/42*Math.PI*2;lc.strokeStyle=n%2?'#9dbb6655':'#264b3b66';lc.lineWidth=n%2?1:2;lc.beginPath();lc.moveTo(128,128);lc.quadraticCurveTo(128+Math.cos(a+.15)*65,128+Math.sin(a+.15)*65,128+Math.cos(a)*126,128+Math.sin(a)*126);lc.stroke();}const padTexture=new T.CanvasTexture(leafCanvas);padTexture.colorSpace=T.SRGBColorSpace;
 for(const pad of lilies.children){const pos=pad.geometry.getAttribute('position'),uv=pad.geometry.getAttribute('uv');pad.geometry.computeBoundingBox();const box=pad.geometry.boundingBox;for(let j=0;j<uv.count;j++)uv.setXY(j,(pos.getX(j)-box.min.x)/(box.max.x-box.min.x),(pos.getZ(j)-box.min.z)/(box.max.z-box.min.z));uv.needsUpdate=true;pad.material.map=padTexture;pad.material.bumpMap=padTexture;pad.material.bumpScale=.008;pad.material.color.set('#738a53');}
 const blooms=new T.Group(),petalMat=new T.MeshStandardMaterial({color:'#f0d9ce',roughness:.47}),goldMat=new T.MeshStandardMaterial({color:'#d8a437',roughness:.68});
 for(const padIndex of [3,8]){const origin=lilies.children[padIndex].position;for(let layer=0;layer<3;layer++)for(let j=0;j<9;j++){const a=j/9*Math.PI*2+layer*.31,r=.07-layer*.02,petal=new T.Mesh(new T.SphereGeometry(1,10,6),petalMat);petal.scale.set(.025,.015,.085-layer*.016);petal.position.set(origin.x+Math.sin(a)*r,.052+layer*.025,origin.z+Math.cos(a)*r);petal.rotation.set(-.20-layer*.22,a,0);blooms.add(petal);}const center=new T.Mesh(new T.SphereGeometry(.025,12,8),goldMat);center.position.copy(origin).add(new T.Vector3(0,.10,0));blooms.add(center);}garden.add(blooms);
 // A hand-built bench and shaded deck establish a distinct viewing garden.
 const benchWood=[],benchMetal=[];for(let j=0;j<4;j++){const g=new T.BoxGeometry(1.8,.055,.10);g.translate(-3.55,.68,3.34+j*.112);benchWood.push(g);}for(let j=0;j<3;j++){const g=new T.BoxGeometry(1.8,.095,.055);g.translate(-3.55,.93+j*.115,3.77);benchWood.push(g);}for(const x of [-4.25,-2.85]){benchMetal.push(cylinder(new T.Vector3(x,.26,3.4),new T.Vector3(x,.70,3.4),.025,.025));benchMetal.push(cylinder(new T.Vector3(x,.26,3.75),new T.Vector3(x,1.25,3.75),.025,.025));}merged(benchWood,new T.MeshStandardMaterial({map:woodMap,color:'#927258',roughness:.75}),'Garden bench',garden);merged(benchMetal,new T.MeshStandardMaterial({color:'#26312b',roughness:.56,metalness:.65}),'Bench ironwork',garden);
 const notes=[{title:'Slate cascade',text:'Moving water increases contact with air. A waterfall supports gas exchange; its appearance alone cannot tell you the pond’s oxygen level.'},{title:'Marginal planting',text:'Plants provide shade, shelter and nutrient uptake. At night plants and animals use oxygen, so circulation and aeration still matter.'}];
 return {garden,underwater,lilies,notes,update(t){for(let i=0;i<lilies.children.length;i++){const p=lilies.children[i];p.position.y=p.userData.base+Math.sin(t*.65+i)*.005;p.rotation.z=Math.sin(t*.6+i)*.009;}}};
}
