import * as T from 'three';
import {mergeGeometries,mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
import {edge,bottom,landHeight,shoreDistance,seeded} from './PondGeometry.js';
import {addCaustics} from './Caustics.js';
const rand=seeded(281926),pick=(a,b)=>a+(b-a)*rand(),TAU=Math.PI*2;
function merged(parts,mat,name,parent){const g=mergeGeometries(parts,false);parts.forEach(p=>p.dispose());const m=new T.Mesh(g,mat);m.name=name;m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
function cylinder(a,b,r0,r1,segments=8){const d=new T.Vector3().subVectors(b,a),g=new T.CylinderGeometry(r1,r0,d.length(),segments,1);g.applyQuaternion(new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),d.normalize()));g.translate((a.x+b.x)/2,(a.y+b.y)/2,(a.z+b.z)/2);return g;}
function stone(x,y,z,sx,sy,sz){const g=mergeVertices(new T.IcosahedronGeometry(1,2)),p=g.attributes.position;for(let i=0;i<p.count;i++){const a=p.getX(i),b=p.getY(i),c=p.getZ(i),f=1+.12*Math.sin(a*9+b*7)*Math.sin(c*8-a*3);p.setXYZ(i,a*f,b*f,c*f);}g.computeVertexNormals();g.scale(sx,sy,sz);g.rotateY(rand()*TAU);g.translate(x,y,z);return g;}
function cardMap(kind){
 const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');
 // Small, overlapping veined leaves remain readable near the camera. All shapes are authored here.
 for(let n=0;n<(kind==='blossom'?120:54);n++){
  const a=rand()*TAU,r=Math.sqrt(rand())*190,x=256+Math.cos(a)*r,y=256+Math.sin(a)*r;
  ctx.save();ctx.translate(x,y);ctx.rotate(rand()*TAU);const s=pick(16,31);ctx.scale(s,s);
  const hue=kind==='maple'?pick(0,14):kind==='blossom'?pick(328,349):pick(78,109),light=kind==='maple'?pick(23,42):kind==='blossom'?pick(64,85):pick(25,52);
  ctx.fillStyle=`hsl(${hue} ${kind==='blossom'?35:pick(38,66)}% ${light}%)`;ctx.beginPath();
  if(kind==='maple'){ctx.moveTo(0,1);for(let j=0;j<10;j++){const an=-Math.PI/2+j/10*TAU,rr=j%2?.42:1;ctx.lineTo(Math.cos(an)*rr,Math.sin(an)*rr);}ctx.closePath();}
  else if(kind==='blossom'){for(let j=0;j<5;j++){const an=j/5*TAU;ctx.ellipse(Math.cos(an)*.45,Math.sin(an)*.45,.47,.32,an,0,TAU);}}
  else{ctx.moveTo(0,1);ctx.bezierCurveTo(-.85,.4,-.68,-.45,0,-1);ctx.bezierCurveTo(.68,-.45,.85,.4,0,1);}
  ctx.fill();ctx.strokeStyle=kind==='blossom'?'#d79575':'#d4db9855';ctx.lineWidth=.055;ctx.beginPath();ctx.moveTo(0,1);ctx.lineTo(0,-.83);ctx.stroke();
  if(kind!=='blossom')for(let j=0;j<4;j++){const q=-.6+j*.35;ctx.beginPath();ctx.moveTo(0,q+.25);ctx.lineTo(.46,q);ctx.moveTo(0,q+.25);ctx.lineTo(-.46,q);ctx.stroke();}ctx.restore();
 }
 const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;tex.anisotropy=8;return tex;
}
function grassBlade(h,w,bend){const p=[],uv=[],ix=[];for(let j=0;j<=6;j++){const t=j/6;for(const side of [-1,1]){p.push(side*w*(1-t)*.5,h*t,bend*t*t);uv.push((side+1)/2,t);}if(j){const a=(j-1)*2;ix.push(a,a+2,a+1,a+1,a+2,a+3);}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();return g;}
function windMaterial(map,clock){const m=new T.MeshStandardMaterial({map,side:T.DoubleSide,alphaTest:.48,alphaToCoverage:true,roughness:.85});m.onBeforeCompile=s=>{s.uniforms.gardenTime=clock;s.vertexShader='uniform float gardenTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed.x+=sin(gardenTime*.8+instanceMatrix[3].x*.5+instanceMatrix[3].z)*.035*uv.y;');};return m;}
export async function buildPondScene(scene,clock){
 const garden=new T.Group(),underwater=new T.Group();scene.add(garden,underwater);const loader=new T.TextureLoader(),base=import.meta.env.BASE_URL+'textures/';
 async function maps(id,normalScale){const list=await Promise.all(['diffuse','nor_gl','rough'].map(k=>loader.loadAsync(base+id+'_'+k+'.jpg')));list.forEach(t=>{t.wrapS=t.wrapT=T.RepeatWrapping;t.anisotropy=8;});list[0].colorSpace=T.SRGBColorSpace;return {map:list[0],normalMap:list[1],roughnessMap:list[2],normalScale:new T.Vector2(normalScale,normalScale)};}
 const [forest,rock,bark,gravel]=await Promise.all([maps('forrest_ground_01',.65),maps('mossy_rock',.8),maps('bark_willow',.75),maps('gravelly_sand',.6)]);
 const groundMat=new T.MeshStandardMaterial({...forest,roughness:1,color:'#a8bb72',vertexColors:true});
 const rockMat=new T.MeshStandardMaterial({...rock,roughness:.91,color:'#b6bbb0'}),wetRock=new T.MeshStandardMaterial({...rock,roughness:.63,color:'#8f9b8a'});
 addCaustics(wetRock,clock,.55);
 // A rolling woodland floor rises out of a deep, irregular bowl.
 function terrain(isLand){const p=[],uv=[],ix=[],colors=[],rings=isLand?52:44,ns=256;for(let i=0;i<=rings;i++)for(let j=0;j<=ns;j++){const a=j/ns*TAU,e=edge(a),r=isLand?1+i/rings*3.2:Math.max(.001,i/rings),x=e.x*r,z=e.z*r,y=isLand?landHeight(x,z):bottom(x,z);p.push(x,y,z);uv.push(x*.48,z*.48);const c=new T.Color().setHSL(.20+Math.sin(x*.5+z*.3)*.014,.16,.72+Math.sin(x*.77)*Math.cos(z*.68)*.12);colors.push(c.r,c.g,c.b);}
 for(let i=0;i<rings;i++)for(let j=0;j<ns;j++){const a=i*(ns+1)+j;ix.push(a,a+1,a+ns+2,a,a+ns+2,a+ns+1);}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.setIndex(ix);g.computeVertexNormals();return g;}
 const ground=new T.Mesh(terrain(true),groundMat);ground.receiveShadow=true;garden.add(ground);
 const bedMat=new T.MeshStandardMaterial({...gravel,roughness:.97,color:'#7d9a89'});addCaustics(bedMat,clock,1.8);const bed=new T.Mesh(terrain(false),bedMat);bed.receiveShadow=true;underwater.add(bed);
 const shore=[],inWater=[],landRocks=[];
 for(let i=0;i<192;i++){const a=i/192*TAU,p=edge(a),s=pick(.22,.57),r=pick(.985,1.025);shore.push(stone(p.x*r,landHeight(p.x,p.z)+pick(-.08,.07),p.z*r,s,pick(.19,.43),s*pick(.68,1.1)));if(i%2===0){const q=p.clone().multiplyScalar(.965);inWater.push(stone(q.x,-.17,q.z,s*.65,.19,s*.6));}}
 for(let i=0;i<80;i++){const a=rand()*TAU,p=edge(a).multiplyScalar(pick(1.12,1.7)),s=pick(.22,.85);landRocks.push(stone(p.x,landHeight(p.x,p.z),p.z,s,s*pick(.45,.85),s*.85));}
 merged(shore,rockMat,'Irregular weathered banks',garden);merged(inWater,wetRock,'Submerged marginal stones',underwater);merged(landRocks,rockMat,'Woodland boulder clusters',garden);
 const d=new T.Object3D(),pebbles=new T.InstancedMesh(new T.IcosahedronGeometry(1,1),bedMat,3800);
 for(let i=0;i<3800;i++){const p=edge(rand()*TAU).multiplyScalar(Math.sqrt(rand())*.96),s=pick(.018,.105);d.position.set(p.x,bottom(p.x,p.z)+s*.45,p.z);d.scale.set(s,s*.48,s*.75);d.rotation.set(rand()*3,rand()*6,rand()*3);d.updateMatrix();pebbles.setMatrixAt(i,d.matrix);pebbles.setColorAt(i,new T.Color().setHSL(.12,.08,pick(.55,.95)));}pebbles.receiveShadow=true;underwater.add(pebbles);
 // Independent layered canopies: red maples, flowering trees, and a green woodland backdrop.
 const trunks=[],leaves={green:[],maple:[],blossom:[]};
 function tree(x,z,h,kind,seed){const rr=seeded(seed),origin=new T.Vector3(x,landHeight(x,z)-.05,z);function branch(a,dir,len,radius,level){const mid=a.clone().addScaledVector(dir,len*.5).add(new T.Vector3((rr()-.5)*.24,.10,(rr()-.5)*.24)),b=a.clone().addScaledVector(dir,len);trunks.push(cylinder(a,mid,radius,radius*.82),cylinder(mid,b,radius*.82,radius*.62));if(!level){for(let j=0;j<28;j++){const az=rr()*TAU,r=Math.sqrt(rr())*h*.23;leaves[kind].push({p:b.clone().add(new T.Vector3(Math.cos(az)*r,(rr()-.5)*h*.23,Math.sin(az)*r)),s:h*(.15+rr()*.10),rx:(rr()-.5)*2.8,ry:rr()*TAU,rz:(rr()-.5)*2.8,light:.72+rr()*.28});}return;}for(let j=0;j<3;j++){const az=j/3*TAU+rr()*2,nd=dir.clone().multiplyScalar(.27).add(new T.Vector3(Math.cos(az)*.78,.40+rr()*.30,Math.sin(az)*.78)).normalize();branch(b,nd,len*(.63+rr()*.12),radius*.54,level-1);}}
 branch(origin,new T.Vector3(pick(-.12,.12),1,pick(-.10,.10)).normalize(),h*.40,h*.036,3);}
 const trees=[[-12,-6,6.7,'maple'],[-8,-10,7.2,'green'],[-3,-11,7.8,'green'],[3,-12,8.2,'green'],[9,-10,6.8,'blossom'],[13,-5,6.5,'green'],[-13,0,6.0,'blossom'],[-12,6,5,'maple'],[14.8,3,5.3,'maple'],[5,-9,4.8,'blossom']];
 trees.forEach(([x,z,h,k],i)=>tree(x,z,h,k,100+i));
 for(let i=0;i<15;i++){const a=Math.PI+i/14*Math.PI,p=edge(a).multiplyScalar(pick(1.85,2.45));tree(p.x,p.z,pick(5.5,8.4),i%7===0?'blossom':'green',300+i);}
 // Low shrubs have full volumes; lower foreground planting preserves views into the water.
 for(let i=0;i<155;i++){const a=rand()*TAU,p=edge(a).multiplyScalar(pick(1.08,1.64)),height=pick(.25,.82),rad=pick(.36,.83),kind=i%15===0?'maple':'green';for(let j=0;j<22;j++){const aa=rand()*TAU,r=Math.sqrt(rand())*rad,x=p.x+Math.cos(aa)*r,z=p.z+Math.sin(aa)*r;leaves[kind].push({p:new T.Vector3(x,landHeight(x,z)+height*Math.sqrt(Math.max(.05,1-r*r/(rad*rad))),z),s:pick(.35,.58),rx:rand()*2,ry:rand()*TAU,rz:rand()*2,light:pick(.8,1.1)});}}
 // Understory spreads across the rolling ground, beyond the ornamental bank.
 for(let i=0;i<410;i++){const a=rand()*TAU,p=edge(a).multiplyScalar(pick(1.43,2.75));if(p.z>7&&Math.abs(p.x)<11)continue;const height=pick(.28,1.08),rad=pick(.42,1.02);for(let j=0;j<24;j++){const aa=rand()*TAU,r=Math.sqrt(rand())*rad,x=p.x+Math.cos(aa)*r,z=p.z+Math.sin(aa)*r;leaves.green.push({p:new T.Vector3(x,landHeight(x,z)+height*Math.sqrt(Math.max(.04,1-r*r/(rad*rad))),z),s:pick(.42,.72),rx:rand()*2.8,ry:rand()*TAU,rz:rand()*2.8,light:pick(.75,1.15)});}}
 merged(trunks,new T.MeshStandardMaterial({...bark,roughness:.98,color:'#c6ad8d',emissive:'#4a3928',emissiveIntensity:.30}),'Branching trees with willow bark',garden);
 for(const [kind,list]of Object.entries(leaves)){const mesh=new T.InstancedMesh(new T.PlaneGeometry(1,1,1,2),windMaterial(cardMap(kind),clock),list.length);list.forEach((l,i)=>{d.position.copy(l.p);d.scale.setScalar(l.s);d.rotation.set(l.rx,l.ry,l.rz);d.updateMatrix();mesh.setMatrixAt(i,d.matrix);mesh.setColorAt(i,new T.Color().setScalar(l.light));});mesh.castShadow=mesh.receiveShadow=true;mesh.name=kind+' leafy canopies';garden.add(mesh);}
 const grassMat=windMaterial(null,clock);grassMat.color.set('#527b2f');grassMat.alphaTest=0;
 const grass=new T.InstancedMesh(grassBlade(1,.05,.4),grassMat,12600);
 for(let i=0;i<12600;i++){const cl=i%420,a=(cl/420)*TAU,base=edge(a).multiplyScalar(1.025+(cl%7)*.045),x=base.x+pick(-.3,.3),z=base.z+pick(-.3,.3),h=pick(.18,.67);d.position.set(x,landHeight(x,z)-.02,z);d.scale.set(pick(.5,1.4),h,pick(.4,1.2));d.rotation.set(0,rand()*TAU,pick(-.12,.12));d.updateMatrix();grass.setMatrixAt(i,d.matrix);grass.setColorAt(i,new T.Color().setHSL(pick(.18,.27),pick(.3,.55),pick(.45,.75)));}grass.receiveShadow=true;garden.add(grass);
 // Compound fern fronds and arching iris leaves grow between the rocks.
 const fernParts=[],irisParts=[];for(let i=0;i<65;i++){const p=edge(rand()*TAU).multiplyScalar(pick(1.08,1.30)),y=landHeight(p.x,p.z);for(let f=0;f<7;f++){const a=f/7*TAU+rand(),len=pick(.45,.95);for(let j=1;j<12;j++){const t=j/12,x=p.x+Math.cos(a)*len*t,z=p.z+Math.sin(a)*len*t,yy=y+Math.sin(t*Math.PI*.85)*len*.6;for(const side of [-1,1]){const g=grassBlade(.025,.065,len*.24*Math.sin(t*Math.PI));g.rotateY(-a+side*.95);g.translate(x,yy,z);fernParts.push(g);}}if(i<24){const g=grassBlade(pick(.6,1.05),.055,pick(.1,.4));g.rotateY(a);g.translate(p.x,y,p.z);irisParts.push(g);}}}
 merged(fernParts,new T.MeshStandardMaterial({color:'#52723d',roughness:.9,side:T.DoubleSide}),'Compound woodland ferns',garden);merged(irisParts,new T.MeshStandardMaterial({color:'#3d653b',roughness:.78,side:T.DoubleSide}),'Iris leaves',garden);
 const flowerGeo=new T.SphereGeometry(1,7,4),flowerParts=[];for(let i=0;i<240;i++){const a=(i%12)/12*TAU+.12,p=edge(a).multiplyScalar(1.17),x=p.x+pick(-.5,.5),z=p.z+pick(-.5,.5),y=landHeight(x,z)+pick(.24,.55);for(let j=0;j<5;j++){const aa=j/5*TAU,g=flowerGeo.clone();g.scale(.045,.018,.075);g.rotateY(aa);g.translate(x+Math.sin(aa)*.04,y,z+Math.cos(aa)*.04);flowerParts.push(g);}}merged(flowerParts,new T.MeshStandardMaterial({color:'#e4b5d6',roughness:.8}),'Soft flowering margins',garden);
 // A cedar sitting terrace and winding stepping stones give this garden its own layout.
 const woodMat=new T.MeshStandardMaterial({...bark,color:'#bd9571',roughness:.75}),planks=[],posts=[],bench=[];const deckX=-8.2,deckZ=5.4,deckY=landHeight(deckX,deckZ)+.12;
 for(let i=0;i<23;i++){const g=new T.BoxGeometry(.135,.12,2);g.translate(deckX+(i-11)*.149,deckY,deckZ);planks.push(g);}for(const x of [deckX-1.4,deckX+1.4])for(const z of [deckZ-.75,deckZ+.75])posts.push(cylinder(new T.Vector3(x,deckY-.7,z),new T.Vector3(x,deckY,z),.08,.08));
 for(let j=0;j<4;j++){const g=new T.BoxGeometry(2.05,.07,.12);g.translate(deckX,deckY+.53,deckZ+.14+j*.13);bench.push(g);}for(let j=0;j<3;j++){const g=new T.BoxGeometry(2.05,.10,.06);g.translate(deckX,deckY+.8+j*.13,deckZ+.63);bench.push(g);}for(const x of [deckX-.85,deckX+.85]){posts.push(cylinder(new T.Vector3(x,deckY,deckZ+.2),new T.Vector3(x,deckY+.55,deckZ+.2),.025,.025),cylinder(new T.Vector3(x,deckY,deckZ+.62),new T.Vector3(x,deckY+1.1,deckZ+.62),.025,.025));}
 merged([...planks,...bench],woodMat,'Cedar viewing terrace and bench',garden);merged(posts,new T.MeshStandardMaterial({color:'#373c31',roughness:.68,metalness:.25}),'Terrace structure',garden);
 const steps=[];for(let i=0;i<35;i++){const a=.65+i/34*2.0,p=edge(a).multiplyScalar(1.20+Math.sin(i*.4)*.015);steps.push(stone(p.x,landHeight(p.x,p.z)+.045,p.z,.37,.07,.28));}merged(steps,rockMat,'Winding stone path',garden);
 // Natural stepped spillway with flowing sheets, falling droplets and surface foam.
 const cp=edge(-.72).multiplyScalar(1.015),cascade=[];for(let tier=0;tier<4;tier++)for(let j=0;j<5;j++){cascade.push(stone(cp.x+(j-2)*.38+tier*.22,.13+tier*.41,cp.z-tier*.58,.45,.28,.48));}merged(cascade,wetRock,'Woodland slate waterfall',garden);
 const fallMat=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time:clock},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time;void main(){float ribbons=.5+.5*sin(v.x*145.+sin(v.y*23.-time*8.));float foam=pow(ribbons,7.)*.46;float edge=smoothstep(0.,.08,v.x)*(1.-smoothstep(.92,1.,v.x));gl_FragColor=vec4(vec3(.66,.82,.77)+foam,edge*(.30+foam));}'});
 for(let tier=0;tier<3;tier++){const a=new T.Vector3(cp.x+tier*.22,.17+tier*.41,cp.z-tier*.58),b=new T.Vector3(cp.x+(tier+1)*.22,.62+tier*.41,cp.z-(tier+1)*.58),g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([a.x-.53,a.y,a.z,a.x+.53,a.y,a.z,b.x-.53,b.y,b.z,b.x+.53,b.y,b.z],3));g.setAttribute('uv',new T.Float32BufferAttribute([0,0,1,0,0,1,1,1],2));g.setIndex([0,2,1,1,2,3]);g.computeVertexNormals();garden.add(new T.Mesh(g,fallMat));}
 const sprayPos=new Float32Array(180*3),spray=new T.Points(new T.BufferGeometry(),new T.PointsMaterial({color:'#deeee1',size:.028,transparent:true,opacity:.6,depthWrite:false}));spray.geometry.setAttribute('position',new T.BufferAttribute(sprayPos,3));garden.add(spray);
 // Sheltered water lilies: cutout leaves, radial veins and layered three-dimensional petals.
 const lc=document.createElement('canvas');lc.width=lc.height=256;const ctx=lc.getContext('2d');ctx.fillStyle='#567d35';ctx.fillRect(0,0,256,256);for(let j=0;j<50;j++){const a=j/50*TAU;ctx.strokeStyle=j%2?'#b9c96666':'#213e2788';ctx.beginPath();ctx.moveTo(128,128);ctx.quadraticCurveTo(128+Math.cos(a+.1)*70,128+Math.sin(a+.1)*70,128+Math.cos(a)*125,128+Math.sin(a)*125);ctx.stroke();}const padTex=new T.CanvasTexture(lc);padTex.colorSpace=T.SRGBColorSpace;const padMat=new T.MeshStandardMaterial({map:padTex,bumpMap:padTex,bumpScale:.014,roughness:.52,side:T.DoubleSide});const lilies=new T.Group(),petals=[],centers=[];
 for(let i=0;i<29;i++){const a=.05+rand()*.55,p=edge(a).multiplyScalar(pick(.82,.94)),r=pick(.16,.34),shape=new T.Shape();shape.moveTo(0,0);for(let j=0;j<=48;j++){const a=.22+j/48*(TAU-.44);shape.lineTo(Math.cos(a)*r,Math.sin(a)*r);}shape.closePath();const g=new T.ShapeGeometry(shape);g.rotateX(-Math.PI/2);const pos=g.attributes.position,uv=g.attributes.uv;for(let j=0;j<uv.count;j++)uv.setXY(j,pos.getX(j)/(r*2)+.5,pos.getZ(j)/(r*2)+.5);const pad=new T.Mesh(g,padMat);pad.position.set(p.x,.022+rand()*.006,p.z);pad.rotation.y=rand()*TAU;pad.userData.base=pad.position.y;lilies.add(pad);if(i%7===0){for(let layer=0;layer<3;layer++)for(let j=0;j<9;j++){const a=j/9*TAU+layer*.3,rr=.09-layer*.023,g=new T.SphereGeometry(1,9,5);g.scale(.036,.014,.11-layer*.023);g.rotateX(-.25-layer*.23);g.rotateY(a);g.translate(p.x+Math.sin(a)*rr,.08+layer*.025,p.z+Math.cos(a)*rr);petals.push(g);}const g=new T.SphereGeometry(.035,10,6);g.translate(p.x,.15,p.z);centers.push(g);}}
 garden.add(lilies);merged(petals,new T.MeshStandardMaterial({color:'#f5c9d7',roughness:.46}),'Water lily petals',garden);merged(centers,new T.MeshStandardMaterial({color:'#eab83e',roughness:.7}),'Lily stamens',garden);
 return {garden,underwater,lilies,cascade:cp,update(t){for(let i=0;i<lilies.children.length;i++){const p=lilies.children[i];p.position.y=p.userData.base+Math.sin(t*.85+i)*.006;p.rotation.z=Math.sin(t*.7+i)*.012;}for(let i=0;i<180;i++){const age=(t*.8+i*.173)%1,tier=i%3;const a=age; sprayPos[i*3]=cp.x+tier*.22+Math.sin(i*34)*.48+a*.12;sprayPos[i*3+1]=.60+tier*.41-a*a*.48;sprayPos[i*3+2]=cp.z-(tier+1)*.58+a*.58;}spray.geometry.attributes.position.needsUpdate=true;}};
}
