export type Lesson='water'|'layers'|'nitrogen'|'day'|'experiments'|'organisms'|'underground'|'challenges';
export const lessonNames:Record<Lesson,string>={water:'Follow a drop',layers:'Inside the layers',nitrogen:'Nitrogen journey',day:'Day & night',experiments:'What happens if…',organisms:'Living close-ups',underground:'Below the gravel',challenges:'Predict & test'};
export type LessonStep={title:string;text:string;detail:string;point:[number,number,number];tag:string};
export const lessons:Record<Lesson,LessonStep[]>={
 underground:[
 {title:'A living substrate cross-section',tag:'Root zone',point:[0,3.3,.9],text:'Explore a representative slice beneath a planted bed. Roots weave between grains, while pores hold water and small organisms.',detail:'This enlarged teaching slice illustrates processes; it is not an X-ray of the displayed aquarium. Its roots, pore sizes and microbes are not to a common scale.'},
 {title:'Debris enters the bed',tag:'Organic debris',point:[1.25,3.5,1.2],text:'Plant fragments and uneaten food can lodge between grains. Microbes break down this organic material.',detail:'Organic matter supplies microbial food. Its breakdown releases dissolved substances and can consume oxygen; the rate depends on local conditions.'},
 {title:'Microbes on wetted surfaces',tag:'Biofilm',point:[-.9,2.4,1.2],text:'Biofilms coat grains and roots. Colored points show enlarged microbial activity, and moving beads illustrate transport through pores.',detail:'Colors identify a teaching overlay, not visible bacterial colors. Oxygen availability varies locally; depth alone cannot tell you which process dominates.'}],
 challenges:[{title:'Make a prediction. Run the comparison.',tag:'Predict & test',point:[0,3,0],text:'Choose an experiment and predict the outcome before seeing the two tanks compared on the same clock.',detail:'These challenges use the existing illustrative ecosystem model. A correct prediction describes that model, not a guaranteed result in a real aquarium.'}],
 water:[
 {title:'Into the intake',tag:'1 · Intake',point:[4.77,1.3,-2.02],text:'The intake draws tank water into an external canister. The moving blue beads trace one illustrative route.',detail:'The flow is driven by the impeller. Intake slots exclude large objects; they do not sterilize the water. Select Next to open the filter cutaway.'},
 {title:'Mechanical filtration',tag:'2 · Foam',point:[0,1.8,0],text:'Water passes through foam that catches suspended particles. Dissolved waste continues with the water.',detail:'This cutaway shows a representative bottom-to-top canister. Real filter layouts vary. Foam holds debris and also hosts microbes; it needs cleaning to keep water moving.'},
 {title:'Biological filtration',tag:'3 · Biofilm',point:[0,2.8,0],text:'Water wets the ceramic media. Microbial biofilms use oxygen while transforming ammonia into nitrite and nitrate.',detail:'The rings provide surface area. The organisms on those surfaces do the work. Biological filtration transforms dissolved nitrogen; it does not make all nitrogen disappear.'},
 {title:'The impeller returns the water',tag:'4 · Impeller',point:[0,4,0],text:'The rotating impeller moves water through the canister and back toward the return pipe.',detail:'Follow the blue beads up through the baskets. A blocked intake or clogged media reduces circulation. An impeller is a pump, not a biological treatment stage.'},
 {title:'Back through the planting',tag:'5 · Return',point:[3.93,4.99,-1.57],text:'The lily pipe spreads the returning water. Surface movement helps gases exchange with the air.',detail:'Circulation transports dissolved substances through the aquarium. These streamlines are a teaching illustration, not a computed flow field.'}],
 layers:[
 {title:'Separate the aquarium',tag:'Plants',point:[0,4.8,0],text:'Use the separation slider to lift the planting and expose the root zone and substrate beneath it.',detail:'The actual planting and substrate separate in this teaching view. Added roots are representative anatomy. The sand path is a surface feature; the model does not pretend this tank has a hidden gravel bed.'},
 {title:'Leaves and growing shoots',tag:'Leaf canopy',point:[1,4.7,0],text:'Leaves intercept light and exchange substances with the water. New growth uses carbon and mineral nutrients.',detail:'Underwater leaves can take up nutrients directly. Roots are another pathway, not the only one. Leaf shape and placement influence which parts receive light.'},
 {title:'Roots and the rhizosphere',tag:'Roots',point:[0,.9,1.6],text:'Roots anchor plants and explore the substrate. The root surface meets a busy microbial environment.',detail:'These branching roots are illustrative. Conditions around roots differ over very short distances, so an aquarium is not a set of perfectly uniform chemical layers.'},
 {title:'Aquasoil and sand',tag:'Substrate',point:[1,-.2,1.8],text:'Aquasoil supports roots and retains nutrients. The pale sand path is a decorative mineral surface.',detail:'Grains create small spaces for water and organisms. A dark substrate is not automatically a dangerous oxygen-free layer. Grain size, depth, flow and biological activity all matter.'}],
 nitrogen:[
 {title:'Start with food',tag:'Food',point:[.7,5,.65],text:'Feed the fish to begin the journey. Some food becomes fish tissue; excretion and leftovers return nitrogen to the water.',detail:'The colored tracer is a conceptual nitrogen pathway. It does not imply that one flake turns instantly into plant growth.'},
 {title:'Waste becomes ammonium / ammonia',tag:'Waste → ammonia',point:[.3,.7,.8],text:'Fish excretion and microbial decomposition supply reduced nitrogen. The proportion present as ammonia depends on water chemistry.',detail:'The experiment model combines this pool and reports it as nitrogen. It does not calculate species-specific toxicity or provide stocking advice.'},
 {title:'The first oxidation',tag:'Ammonia → nitrite',point:[4.77,1.3,-2.02],text:'Ammonia-oxidizing microbes convert reduced nitrogen to nitrite. This process uses dissolved oxygen.',detail:'Biofilms occur on filter media, substrate and other wetted surfaces. The highlighted intake stands for delivery to the external biological filter.'},
 {title:'The second oxidation',tag:'Nitrite → nitrate',point:[4.4,4,-2],text:'Nitrite-oxidizing microbes continue the pathway to nitrate. This step also consumes oxygen.',detail:'This is a simplified teaching pathway. Microbial communities are more diverse than a two-organism diagram.'},
 {title:'Plant uptake and export',tag:'Nitrate → growth',point:[-1,2.7,.5],text:'Plants incorporate available nitrogen into new tissue. Harvesting plant growth and changing water can export nitrogen.',detail:'Plants can use ammonium as well as nitrate. The highlighted route teaches the nitrification sequence, not the only route nitrogen can take.'}],
 day:[
 {title:'Light supplies energy',tag:'Light → leaf',point:[0,5.2,0],text:'In daylight, photosynthesis uses light and carbon dioxide to build organic matter and releases oxygen.',detail:'Plants also respire during the day. Net oxygen change depends on photosynthesis, respiration, gas exchange and other oxygen-consuming processes.'},
 {title:'Life continues after lights out',tag:'Respiration',point:[0,3,.5],text:'At night photosynthesis stops, while plants, fish and microbes continue to consume oxygen through respiration.',detail:'Use Daylight and Night to compare the illustrated directions of gas exchange. Night is dimly lit here so you can still see the aquarium.'},
 {title:'The surface connects water and air',tag:'Air ↔ water',point:[2,5.2,0],text:'Gas exchange at the surface continues day and night. It can add or release oxygen depending on the concentration difference.',detail:'See the experiments for modeled oxygen curves through several light cycles. Bubbles and pearling alone cannot tell you the oxygen concentration.'}],
 experiments:[{title:'Change one condition. Compare two tanks.',tag:'Controlled comparison',point:[0,3,0],text:'Run a balanced tank beside a changed tank on the same simulated clock. Watch gases first, then slower biological changes.',detail:'Illustrative 180 L model, not a calibrated prediction. Gases are mg/L; nitrogen pools are mg N/L. Accelerating this clock does not accelerate fish movement. Reset returns both tanks to identical starting conditions except the selected intervention.'}],
 organisms:[
 {title:'A tetra: breathing while swimming',tag:'Gill region',point:[1,3,0],text:'Water passes across the gills, where oxygen enters the blood and carbon dioxide leaves. Fins help propel, steer and stabilize the fish.',detail:'The enlarged fish uses the aquarium’s animated 3D model. The red gill highlight and blue gas tracer are explanatory overlays, not a scanned anatomical dissection.'},
 {title:'A leaf: a submerged solar collector',tag:'Midrib & blade',point:[0,3,0],text:'A thin blade captures light. Its midrib supports the tissue, while dissolved carbon and nutrients reach the submerged plant.',detail:'This specimen uses the actual sword leaf geometry and tissue texture. Photosynthesis is represented by a light beam and an oxygen tracer; it is not a microscopic image.'},
 {title:'A root: branching into the substrate',tag:'Branching roots',point:[0,2,0],text:'A branching root system anchors the plant and increases its contact with substrate water and nutrients.',detail:'The root model is representative, not species-specific. Plants absorb nutrients through leaves too; the root zone is only one part of the exchange.'}]
};
export const sources=[['USGS · Dissolved oxygen','https://www.usgs.gov/water-science-school/science/dissolved-oxygen-and-water'],['USGS · Photosynthesis and respiration','https://www.usgs.gov/publications/dissolved-oxygen-chapter-6'],['EPA · Nitrification','https://www.epa.gov/sites/default/files/2015-09/documents/nitrification_1.pdf']];
