import {challenges,type ChallengeId} from './LearningChallenges';
import type {Aquarium} from './Aquarium';
import {lessonNames,lessons,sources,type Lesson} from './LearningContent';
import {chemistryDefaults as defaults,oxygenSaturation} from './TankChemistry';
import type {Experiment,Metric} from './LearningModel';
const chartNames:Record<Metric,string>={oxygen:'Dissolved oxygen · mg/L',co2:'Dissolved CO₂ · mg/L',ammonia:'Total ammonia · mg N/L',nitrite:'Nitrite · mg N/L',nitrate:'Nitrate · mg N/L',ph:'Estimated pH',kh:'KH · dKH',nh3:'Un-ionized NH₃-N · mg N/L'};
const labels:Record<Experiment,string>={balanced:'Balanced aquarium',flow:'Restrict filter flow',carbon:'Turn off CO₂',food:'Overfeed once'};
export function installLearning(aquarium:Aquarium){
 const main=document.querySelector('main')!,open=document.querySelector<HTMLButtonElement>('#learn')!;
 const panel=document.createElement('aside');panel.id='learning';panel.hidden=true;panel.setAttribute('aria-label','Aquarium learning guide');main.append(panel);
 const summary=document.createElement('button');summary.className='chemistry-summary';summary.onclick=()=>reveal('experiments',0);main.append(summary);
 let readingsKey='',challenge:ChallengeId='filter',prediction:number|null=null,revealed=false;
 let mode:Lesson='water',step=0,tour=false,nextAt=0,chart:Metric='oxygen';
 const select=(m:Lesson,n=0)=>{if(m==='challenges'&&mode!==m){prediction=null;revealed=false;aquarium.challenge.reset();}n=Math.max(0,Math.min(lessons[m].length-1,n));if(tour)nextAt=performance.now()+9000;document.dispatchEvent(new CustomEvent('aquascape-context',{detail:{lesson:m}}));if(m==='layers'&&mode!=='layers')aquarium.teaching!.separation=1;mode=m;step=n;if(m==='day'&&n<2){aquarium.teaching!.night=n===1;aquarium.learning.setLight(n===1?'night':'day');}aquarium.learn(m,n);document.querySelector<HTMLButtonElement>('#light')!.disabled=m==='day'||m==='experiments'||m==='challenges';render();};
 const close=()=>{tour=false;panel.hidden=true;main.classList.remove('learning-open');open.setAttribute('aria-expanded','false');aquarium.learn(null);document.querySelector<HTMLButtonElement>('#light')!.disabled=false;open.focus();};
 const reveal=(m=mode,n=step)=>{panel.hidden=false;main.classList.add('learning-open');open.setAttribute('aria-expanded','true');select(m,n);};
 open.onclick=()=>panel.hidden?reveal():close();open.disabled=false;
 aquarium.onLessonRequest=m=>reveal(m,0);
 aquarium.teaching!.onSelect=i=>select(mode,i);aquarium.teaching!.onInspect=i=>select('organisms',i);
 const render=()=>{
  readingsKey='';
  const entry=lessons[mode][step],model=mode==='challenges'?aquarium.challenge:aquarium.learning;
  panel.innerHTML=`<div class="learning-top"><span class="eyebrow">HOW THIS WORLD WORKS</span><button id="learn-close" aria-label="Close learning mode">×</button></div>
   <nav class="lesson-tabs" aria-label="Choose a lesson">${Object.entries(lessonNames).map(([id,title])=>`<button data-lesson="${id}" aria-pressed="${id===mode}">${title}</button>`).join('')}</nav>
   <div class="learn-scene-tools"><button id="study-front">Front</button><button id="study-angle">Three-quarter</button><button id="study-pause">${aquarium.paused?'Resume motion':'Pause motion'}</button><button id="study-lens" aria-pressed="${aquarium.magnifierEnabled}">Magnifier</button></div>
   <div class="lesson-body"><div class="lesson-position">${lessonNames[mode]} <span>${step+1} / ${lessons[mode].length}</span></div>
   <h2>${entry.title}</h2><p>${entry.text}</p>
   ${lessons[mode].length>1?`<ol class="lesson-steps" aria-label="Lesson steps">${lessons[mode].map((s,i)=>`<li><button data-step="${i}" aria-label="${i+1}. ${s.title}" ${i===step?'aria-current="step"':''}>${i+1}<span>${s.title}</span></button></li>`).join('')}</ol>`:''}
   ${mode==='organisms'?`<label class="learn-field">Choose a living close-up<select id="living-specimen">${['Cardinal tetra','Leaf','Roots','Cherry shrimp','Dwarf Corydoras'].map((name,i)=>`<option value="${i}" ${step===i?'selected':''}>${name}</option>`).join('')}</select></label>`:''}
   ${mode==='challenges'?`<label class="learn-field">Choose a challenge<select id="challenge">${Object.entries(challenges).map(([id,c])=>`<option value="${id}" ${id===challenge?'selected':''}>${id==='filter'?'Stop the filter':id==='carbon'?'Stop CO₂ supply':'Extra food'}</option>`).join('')}</select></label><p>${challenges[challenge].question}</p><div class="prediction-options">${challenges[challenge].choices.map((label,i)=>`<button data-prediction="${i}" aria-pressed="${prediction===i}" ${revealed?'disabled':''}>${label}</button>`).join('')}</div><button id="run-challenge" class="learn-action" ${prediction===null?'disabled':''}>${revealed?'Run again':'Run six simulated hours'}</button><div id="challenge-result" role="status">${revealed?`<h3>${prediction===challenges[challenge].answer?'Your prediction matches the model.':'The model gives a different result.'}</h3><p>${challenges[challenge].explanation}</p><p>Changed: <strong>${model.state[challenges[challenge].metric].toFixed(3)}</strong> · Control: <strong>${model.baseline[challenges[challenge].metric].toFixed(3)}</strong> ${challenge==='feeding'?'mg N/L':'mg/L'}</p><div id="lab-readings"></div><div id="lab-plot"></div><button id="challenge-reset">Try another prediction</button>`:''}</div>`:''}
   ${mode==='water'?'<div class="teaching-key"><i></i>Blue beads · direction of water travel</div><p class="fine">Filter cutaway is enlarged for teaching. Drag the model to inspect it.</p>':''}
   ${mode==='layers'?`<label class="learn-range">Layer separation <output id="separation-value">${Math.round(aquarium.teaching!.separation*100)}%</output><input id="separation" type="range" min="0" max="100" value="${aquarium.teaching!.separation*100}"/></label><button id="assemble" class="learn-action">Reassemble tank</button><div class="learn-pair"><button id="leaf-closeup">Inspect a leaf</button><button id="root-closeup">Inspect roots</button></div><p class="fine">Expanded view shows representative roots between the lifted planting and the actual substrate.</p>`:''}
   ${mode==='nitrogen'?'<button id="trace-feed" class="learn-action">Feed fish & restart the journey</button><p class="fine">Tracer speed is illustrative. Chemical changes take hours and days; explore their timing in What happens if…</p>':''}
   ${mode==='day'?`<div class="learn-pair"><button id="learn-day" aria-pressed="${!aquarium.teaching!.night}">Daylight</button><button id="learn-night" aria-pressed="${aquarium.teaching!.night}">Night</button></div><div class="gas-key"><span>Blue · oxygen</span><span>Gold · ${aquarium.teaching!.night?'carbon dioxide':'light energy'}</span></div>`:''}
   ${mode==='experiments'?`<div id="lab-event" role="status">${model.event}</div><div id="lab-readings" role="group" aria-label="Simulated readings"></div><label class="learn-field">Reset to scenario<select id="experiment">${Object.entries(labels).map(([id,title])=>`<option value="${id}" ${model.experiment===id?'selected':''}>${title}</option>`).join('')}</select></label>
    <label class="learn-range">Filter flow <output id="flow-value">${model.environment.flow}%</output><input id="learn-flow" type="range" min="0" max="100" value="${model.environment.flow}"></label>
    <label class="learn-range">CO₂ supply · relative setting <output id="carbon-value">${model.environment.co2}</output><input id="learn-carbon" type="range" min="0" max="45" value="${model.environment.co2}"></label>
    <label class="learn-field">Simulated time per second<select id="lab-speed"><option value="0.016666666666666666" ${model.hoursPerSecond===1/60?'selected':''}>1 minute</option><option value=".25" ${model.hoursPerSecond===.25?'selected':''}>15 minutes</option><option value="1" ${model.hoursPerSecond===1?'selected':''}>1 hour</option><option value="4" ${model.hoursPerSecond===4?'selected':''}>4 hours</option></select></label>
    <div class="learn-pair"><button id="lab-play">${model.running?'Pause chemistry':'Run chemistry'}</button><button id="lab-step">+6 hours</button></div>
    <label class="learn-field">Lighting<select id="chem-light"><option value="cycle" ${model.environment.lightMode==='cycle'?'selected':''}>8-hour daily timer</option><option value="day" ${model.environment.lightMode==='day'?'selected':''}>Keep lights on</option><option value="night" ${model.environment.lightMode==='night'?'selected':''}>Lights off</option></select></label>
    <label class="learn-range">Temperature target <output id="temperature-value">${model.environment.temperature}°C</output><input id="chem-temperature" type="range" min="18" max="30" value="${model.environment.temperature}"></label>
    <button id="water-change" class="learn-action">Change 30% of the water</button><p class="fine">Replacement: conditioned water at 24°C, 4 dKH, with zero ammonia, nitrite and nitrate. Uneaten food, animals and attached biofilm remain.</p>

    <label class="learn-field">Chart<select id="lab-chart">${Object.entries(chartNames).map(([key,label])=>`<option value="${key}" ${chart===key?'selected':''}>${label}</option>`).join('')}</select></label><div id="lab-plot"></div>
    <div class="learn-pair"><button id="restore-conditions">Restore flow & CO₂</button><button id="lab-reset">Reset chemistry</button></div><p class="fine">Solid green: changed tank. Dashed gray: balanced control. Both start at noon and share the selected lighting. The control receives no extra feeding, flow changes or water changes. By default, one real second advances one simulated minute. Nitrogen values are mg N/L. Total ammonia combines NH₃ and NH₄⁺. NH₃-N is the estimated un-ionized portion, also expressed as nitrogen. Nitrite/nitrate values as ions are 3.29× / 4.43× their displayed nitrogen values. CO₂ supply is a relative input, not a measured concentration, and switches off with the simulated lights. Tracking continues when this panel closes; Pause motion also holds the chemistry clock. Flow changes circulation and filter delivery; other surfaces still host microbes.</p>`:''}
   <details><summary>Look deeper</summary><p>${entry.detail}</p></details>
   ${lessons[mode].length>1?`<div class="lesson-navigation"><button id="learn-prev" ${step===0?'disabled':''}>← Back</button><button id="tour-play" aria-pressed="${tour}">${tour?'Pause tour':'Play tour'}</button><button id="learn-next" ${step===lessons[mode].length-1?'disabled':''}>Next →</button></div>`:''}
   <p class="learning-limit">Illustrative teaching models · not live water measurements</p><details><summary>Sources & model notes</summary><p>Animated routes, roots and anatomical highlights explain processes. The 180 L simulation tracks food, digestion, detritus, plant uptake and nitrogen export. A normal feed represents up to 0.12 g dry food with 7% nitrogen; visual bites move that nitrogen into digestion and tissue. The pH estimate assumes carbonate buffering at approximately 25°C; humic acids, phosphate and mineral dissolution are not modeled. Rates and biomass are assumed, not calibrated to a real tank. Oxygen exchange assumes freshwater near sea level. Challenges use a separate comparison and cannot reset this tank. These estimates are not toxicity or stocking advice.</p>${sources.map(([title,url])=>`<a href="${url}" target="_blank" rel="noopener">${title} ↗</a>`).join('')}</details></div>`;
  const bind=(id:string,fn:()=>void)=>{const e=panel.querySelector<HTMLButtonElement>('#'+id);if(e)e.onclick=fn;};
  const specimen=panel.querySelector<HTMLSelectElement>('#living-specimen');if(specimen)specimen.onchange=()=>select('organisms',Number(specimen.value));
  const choose=panel.querySelector<HTMLSelectElement>('#challenge');if(choose)choose.onchange=()=>{challenge=choose.value as ChallengeId;prediction=null;revealed=false;model.reset();render();};
  panel.querySelectorAll<HTMLButtonElement>('[data-prediction]').forEach(b=>b.onclick=()=>{prediction=Number(b.dataset.prediction);render();});
  bind('run-challenge',()=>{if(prediction===null)return;model.reset(challenges[challenge].experiment);if(challenge==='filter')model.environment.flow=0;model.step(6);chart=challenges[challenge].metric;revealed=true;render();});
  bind('challenge-reset',()=>{prediction=null;revealed=false;model.reset();render();});
  bind('study-lens',()=>{aquarium.setMagnifier(!aquarium.magnifierEnabled);render();});
  bind('learn-close',close);bind('study-front',()=>aquarium.view('front'));bind('study-angle',()=>aquarium.view('angle'));bind('study-pause',()=>{document.querySelector<HTMLButtonElement>('#pause')!.click();render();});panel.querySelectorAll<HTMLButtonElement>('[data-lesson]').forEach(b=>b.onclick=()=>{tour=false;select(b.dataset.lesson as Lesson);});
  panel.querySelectorAll<HTMLButtonElement>('[data-step]').forEach(b=>b.onclick=()=>select(mode,Number(b.dataset.step)));
  bind('learn-prev',()=>select(mode,step-1));bind('learn-next',()=>select(mode,step+1));
  bind('tour-play',()=>{tour=!tour;nextAt=performance.now()+9000;if(tour&&step===lessons[mode].length-1)select(mode,0);else render();});
  bind('leaf-closeup',()=>select('organisms',1));bind('root-closeup',()=>select('organisms',2));
  bind('assemble',()=>{aquarium.teaching!.separation=0;render();});
  const slider=panel.querySelector<HTMLInputElement>('#separation');if(slider)slider.oninput=()=>{aquarium.teaching!.separation=+slider.value/100;panel.querySelector('#separation-value')!.textContent=slider.value+'%';};
  bind('trace-feed',()=>{aquarium.feed();select('nitrogen',0);});bind('learn-day',()=>select('day',0));bind('learn-night',()=>select('day',1));
  const experiment=panel.querySelector<HTMLSelectElement>('#experiment');if(experiment)experiment.onchange=()=>{aquarium.clearFood();model.reset(experiment.value as Experiment);model.running=true;if(model.experiment==='food')aquarium.feed(false,1200);render();};
  const flow=panel.querySelector<HTMLInputElement>('#learn-flow');if(flow)flow.oninput=()=>{model.environment.flow=+flow.value;panel.querySelector('#flow-value')!.textContent=flow.value+'%';};
  const carbon=panel.querySelector<HTMLInputElement>('#learn-carbon');if(carbon)carbon.oninput=()=>{model.environment.co2=+carbon.value;panel.querySelector('#carbon-value')!.textContent=carbon.value;};
  const speed=panel.querySelector<HTMLSelectElement>('#lab-speed');if(speed)speed.onchange=()=>{model.hoursPerSecond=+speed.value;};
  const graph=panel.querySelector<HTMLSelectElement>('#lab-chart');if(graph)graph.onchange=()=>{chart=graph.value as typeof chart;updateReadings();};
  const light=panel.querySelector<HTMLSelectElement>('#chem-light');if(light)light.onchange=()=>{model.setLight(light.value as typeof model.environment.lightMode);updateReadings();};
  const temperature=panel.querySelector<HTMLInputElement>('#chem-temperature');if(temperature)temperature.oninput=()=>{model.environment.temperature=+temperature.value;panel.querySelector('#temperature-value')!.textContent=temperature.value+'°C';};
  bind('water-change',()=>{model.waterChange();updateReadings();});
  bind('lab-play',()=>{model.running=!model.running;render();});bind('lab-step',()=>{model.step(6);updateReadings();});
  bind('restore-conditions',()=>{model.environment.flow=defaults().flow;model.environment.co2=defaults().co2;render();});bind('lab-reset',()=>{aquarium.clearFood();model.reset(model.experiment);model.running=true;render();});
  updateReadings();
 };
 function updateReadings(){
  const readings=panel.querySelector('#lab-readings');if(!readings)return;
  const m=mode==='challenges'?aquarium.challenge:aquarium.learning,s=m.state,b=m.baseline;
  const key=JSON.stringify([chart,m.event,m.running,aquarium.paused,m.light,s,b,m.history.length,m.history.at(-1)]);
  if(key===readingsKey)return;readingsKey=key;
  const event=panel.querySelector('#lab-event');if(event)event.textContent=m.event;
  readings.innerHTML=`<div class="lab-clock">${s.hours.toFixed(1)} simulated hours · ${m.light>1e-6?'Lights on':'Night'}${mode==='experiments'&&!m.running?' · Chemistry held':''}${aquarium.paused?(mode==='experiments'?' · Motion paused; use +6 hours or resume motion':' · Motion paused; challenge result held'):''}</div><table><thead><tr><th>Reading</th><th>Changed</th><th>Control</th></tr></thead><tbody>${[['O₂ · mg/L',s.oxygen,b.oxygen],['CO₂ · mg/L',s.co2,b.co2],['Total ammonia · mg N/L',s.ammonia,b.ammonia],['Nitrite · mg N/L',s.nitrite,b.nitrite],['Nitrate · mg N/L',s.nitrate,b.nitrate],['NH₃-N · mg N/L',s.nh3,b.nh3],['pH · carbonate estimate',s.ph,b.ph],['KH · dKH',s.kh,b.kh],['Temperature · °C',s.temperature,b.temperature],['O₂ saturation · %',100*s.oxygen/oxygenSaturation(s.temperature),100*b.oxygen/oxygenSaturation(b.temperature)]].map(([label,a,c])=>`<tr><th>${label}</th><td>${Number(a).toFixed(Number(a)<.001?5:Number(a)<1?3:2)}</td><td>${Number(c).toFixed(Number(c)<.001?5:Number(c)<1?3:2)}</td></tr>`).join('')}</tbody></table>`;
  const samples=m.history,values=samples.flatMap(v=>[v.changed[chart],v.control[chart]]),max=Math.max(chart==='oxygen'?10:chart==='ph'?8:chart==='co2'?35:chart==='kh'?5:chart==='nh3'?.0001:.01,...values)*1.08;
  const first=samples[0]?.hour??0,last=Math.max(first+1,samples.at(-1)?.hour??1);
  const path=(control:boolean)=>samples.map((v,i)=>{const n=(control?v.control:v.changed)[chart];return `${i?'L':'M'}${(30+(v.hour-first)/(last-first)*275).toFixed(1)},${(120-n/max*100).toFixed(1)}`;}).join(' ');
  panel.querySelector('#lab-plot')!.innerHTML=`<svg viewBox="0 0 325 150" role="img" aria-label="${chart} comparison from ${first.toFixed(1)} to ${last.toFixed(1)} simulated hours"><path d="M30 15V120H310" stroke="#688079" fill="none"/><text x="1" y="20">${max.toFixed(chart==='nh3'?5:chart==='ammonia'||chart==='nitrite'?3:1)}</text><text x="12" y="123">0</text><text x="30" y="142">${first.toFixed(0)} h</text><text x="275" y="142">${last.toFixed(0)} h</text><path d="${path(true)}" stroke="#a1acae" stroke-dasharray="4 4" fill="none" stroke-width="2"/><path d="${path(false)}" stroke="#bbdda3" fill="none" stroke-width="2"/></svg>`;
 }
 setInterval(()=>{const live=aquarium.learning;summary.textContent=`Water chemistry ↗ · pH ${live.state.ph.toFixed(2)} · O₂ ${live.state.oxygen.toFixed(1)} mg/L`;summary.title=`${live.state.hours.toFixed(1)} simulated hours — ${live.running&&!aquarium.paused?'tracking':'paused'}`;if(panel.hidden)return;const pause=panel.querySelector('#study-pause');if(pause)pause.textContent=aquarium.paused?'Resume motion':'Pause motion';updateReadings();if(tour&&!aquarium.paused&&performance.now()>nextAt){if(step<lessons[mode].length-1){nextAt=performance.now()+9000;select(mode,step+1);}else{tour=false;render();}}},500);
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close();});
}
