import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{runInNewContext}from'node:vm';import ts from'typescript';import{AdaptiveGraphics}from'../src/adaptive-graphics';
const source=ts.createSourceFile('main.ts',readFileSync(new URL('../src/main.ts',import.meta.url),'utf8'),ts.ScriptTarget.ES2022,true),fn=source.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='applyQuality')!.getText(source);
test('production quality application updates render passes and effect budgets while preserving Auto preference',()=>{
 const applied:any[]=[];const receiver={setQuality:(v:string)=>applied.push(v)},renderer={setPixelRatio(){},setSize(){},shadowMap:{enabled:true}},composer={setPixelRatio(){},setSize(){}},adaptiveGraphics=new AdaptiveGraphics();const ctx:any={settings:{quality:'auto'},adaptiveGraphics,renderer,composer,qualityScale:1,devicePixelRatio:1,innerWidth:1280,innerHeight:720,quarry:{sun:{shadow:{mapSize:{setScalar(){}},map:null,needsUpdate:false}},referenceArena:receiver},staticShadows:receiver,vehicleFire:receiver,puddleSplashes:receiver,ao:{enabled:true},reflections:{enabled:true,interval:3}};
 runInNewContext(ts.transpileModule(fn+'\nglobalThis.apply=applyQuality;',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx);ctx.apply();assert.equal(ctx.qualityScale,.85);assert.ok(applied.every(v=>v==='high'));for(let i=0;i<220;i++)adaptiveGraphics.sample(40,true);applied.length=0;ctx.apply();assert.equal(ctx.settings.quality,'auto');assert.equal(ctx.qualityScale,.65);assert.equal(renderer.shadowMap.enabled,false);assert.equal(ctx.ao.enabled,false);assert.equal(ctx.reflections.enabled,false);assert.ok(applied.every(v=>v==='medium'));ctx.settings.quality='ultra';ctx.apply();assert.equal(ctx.qualityScale,1);assert.equal(renderer.shadowMap.enabled,true);assert.equal(ctx.ao.enabled,true);assert.equal(ctx.reflections.enabled,true);
});
test('production frame only adapts during visible active driving and only rebuilds on a level change',()=>{
 const frame=source.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='frame') as ts.FunctionDeclaration;
 const call=frame.body!.statements.find(n=>ts.isIfStatement(n)&&n.expression.getText(source).startsWith('adaptiveGraphics.sample'))!.getText(source);
 const script=ts.transpileModule(call,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
 for(const state of ['playing','menu','countdown','paused','result','loading','wrecked'])for(const hidden of [false,true])for(const preparingEvent of [false,true])for(const studio of [null,{}]){let enabled=false,rebuilds=0;const ctx={state,document:{hidden},preparingEvent,studio,raw:.04,adaptiveGraphics:{sample(ms:number,active:boolean){assert.equal(ms,40);enabled=active;return active;}},applyQuality(){rebuilds++;}};runInNewContext(script,ctx);const expected=state==='playing'&&!hidden&&!preparingEvent&&!studio;assert.equal(enabled,expected);assert.equal(rebuilds,expected?1:0);}
});
