import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import * as T from 'three';
import R from '@dimforge/rapier3d-compat';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {loadCarWithoutImages} from '../tools/car-asset-audit';
import {loadCars} from '../src/assets';
import {Vehicle} from '../src/vehicle';
import {CAR_KINDS,DEFINITIONS,isCarKind,type CarKind} from '../src/rules';
import {stockSetup,readGarage,exportSetup,importSetup} from '../src/garage';
import {ReplayRecorder,replayFile,readReplayFile} from '../src/replay-data';
import {ReplayScene,captureReplayFrame} from '../src/replay-scene';
import {Simulation} from '../multiplayer/simulation';
import {type Snapshot} from '../multiplayer/protocol';
import {OnlineView} from '../src/online-view';
import {freshComponents} from '../src/component-damage';
import {encodeSnapshotWire,decodeSnapshotWire} from '../src/snapshot-wire';
import {effectiveOnlineSetup,stockOnlineSetup} from '../src/online-setup';

await R.init();
const originalLoad=GLTFLoader.prototype.loadAsync;
try{
  GLTFLoader.prototype.loadAsync=async url=>{
    const name=/\/([^/]+)\.glb$/.exec(String(url))?.[1];assert.ok(name&&(name==='wheel-machining'||isCarKind(name)),String(url));return loadCarWithoutImages(name);
  };
  await loadCars(()=>{});
}finally{GLTFLoader.prototype.loadAsync=originalLoad;}
const fx={emit(){},mark(){},detach(m:T.Mesh){m.visible=false;},reset(){}} as any;
const zero={x:0,y:0,z:0},near=(a:number,b:number,epsilon=1e-6)=>assert.ok(Math.abs(a-b)<epsilon,`${a} != ${b}`);
const panels=(car:Vehicle)=>car.panels.filter(p=>p.name.startsWith('panel_Reinforcement_'));
const arrayHash=(a:ArrayBufferView)=>createHash('sha256').update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength)).digest('hex');
function stockSignature(car:Vehicle){
  const h=createHash('sha256');
  car.model.traverse(o=>{
    h.update(JSON.stringify([o.name,o.position.toArray(),o.quaternion.toArray(),o.scale.toArray()]));
    if(o instanceof T.Mesh){
      for(const key of Object.keys(o.geometry.attributes).sort()){const a=o.geometry.attributes[key].array;h.update(key);h.update(new Uint8Array(a.buffer,a.byteOffset,a.byteLength));}
      for(const m of (Array.isArray(o.material)?o.material:[o.material]) as T.MeshPhysicalMaterial[])h.update(JSON.stringify([m.name,m.color?.toArray(),m.roughness,m.metalness,m.clearcoat,m.clearcoatRoughness,m.emissive?.toArray(),m.emissiveIntensity,m.opacity]));
    }
  });return h.digest('hex');
}
// Captured using the published 69a9673 sources in an isolated checkout before
// armor integration. These are independent stock render baselines, not outputs
// regenerated by the implementation under test. The buggy entry now describes
// rigid shock batching, validated against the unchanged published GLB by
// buggy-batching.test.ts; its prior signature remains in the demo-quality layer.
// The van entry includes the formed roof and rear portal, independently checked
// against its preceding GLB in van-coachwork.test.ts; the old hash is frozen there.
// The Ravine wheel-only refinement now has independent non-wheel byte and
// physical-envelope proof in buggy-wheel-quality.test.ts. Its preceding
// signature remains immutable in the buggy-wheel revision layer.
// Tern/Marten now use the reviewed road wheels and four arch-cleared sills.
// classic-wheel-quality.test.ts checks every other body byte and reproduces
// the preceding stock signatures from independently frozen published GLBs.
const publishedStock:Record<CarKind,string>={
  coupe:'b2ee8118b23e343e7934b04a85992d9f2a38f8c6b4577bc6d0f70eb09af59175',sedan:'322d0fc9ee6a098f60fbc3886d2886faca426295c34e6effbc72d38891077be8',hatch:'dea844bd8751c9decfccab0584808e4e10cfb1cc6ab4fddfda5de53a6b813ef9',
  muscle:'4bf4637244629f3ab1dbbd085725c9c0a54a53fcdc851f5d7a632ca4468a19b5',wagon:'1bb157c02ac02e372eab78e20deaf06a586267a4d1b6a462204f310b18f50418',utility:'dd7fcf76b50f90e05402512998e144506b5fa88a275bab88ef05df92ce9f05e2',
  compact:'9f1bdaa56a8fcced6283aee8ca0fdc53166781caec3fbca00efa5da54ac1943e',van:'1d91a2bbd759f9ef530b6062bce2d8b78bae3452dace25037666f8984afaac1d',tern:'392d0fc407b8d688ff22cc4626f2f621481d10a90754f326971998d0de8f21ba',
  marten:'5f23b5499e4dfe4cc2f37b18ae10f7ad6b1bfac72c050c998e3f2f41712ab9eb',buggy:'c3fd14b9a430932b3a54f040cd7c9e1a79e8a77ffd857af488cc3313ed4054c3',
};
const shape=(car:Vehicle)=>panels(car).map(p=>({name:p.name,visible:p.visible,position:arrayHash(p.geometry.attributes.position.array),normal:arrayHash(p.geometry.attributes.normal.array),wear:arrayHash(p.geometry.attributes.impactWear.array),transfer:arrayHash(p.geometry.attributes.transferPaint.array)}));
function pose(car:Vehicle,x=2,y=3,z=4,yaw=.6){
  const p=new T.Vector3(x,y,z),q=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),yaw);car.body.setTranslation(p,true);car.body.setRotation(q,true);car.body.setLinvel(zero,true);car.body.setAngvel(zero,true);
  car.previous.copy(p);car.current.copy(p);car.previousQ.copy(q);car.currentQ.copy(q);car.root.position.copy(p);car.root.quaternion.copy(q);car.root.updateMatrixWorld(true);
}
function contact(car:Vehicle,region='front'){
  const mesh=panels(car).find(p=>p.name===`panel_Reinforcement_${region}_steel`);assert.ok(mesh,region+' reinforcement');
  const point=new T.Box3().setFromBufferAttribute(mesh.userData.wreckRest).getCenter(new T.Vector3());car.root.updateMatrixWorld(true);
  return point.applyMatrix4(car.model.matrixWorld);
}
function hit(car:Vehicle,damage=32,time=.5,region='front'){
  car.hit(contact(car,region),new T.Vector3(region==='left'?1:0,0,region==='front'?-1:region==='rear'?1:0).applyQuaternion(car.root.quaternion),damage,time,true,new T.Color(0x984e36));
}

test('armor zero preserves the published geometry and material state of every vehicle',()=>{
  for(const kind of CAR_KINDS)for(const explicit of [false,true]){
    const world=new R.World(zero),car=new Vehicle(0,kind,DEFINITIONS[kind].color,new T.Scene(),world,fx,explicit?stockSetup(kind):undefined);
    try{assert.equal(panels(car).length,0);assert.equal(stockSignature(car),publishedStock[kind],kind+' '+(explicit?'explicit stock':'legacy constructor'));}
    finally{car.dispose();world.free();}
  }
});

test('all eleven cars fit distinct armor tiers with prepared wear attributes, genuine dents and exact repair',()=>{
  for(const kind of CAR_KINDS){
    const signatures:string[]=[],counts:number[]=[];
    for(const level of [1,2,3]){
      const world=new R.World(zero),setup=stockSetup(kind);setup.armor=level;const car=new Vehicle(0,kind,setup.paint,new T.Scene(),world,fx,setup);
      try{
        pose(car);const armor=panels(car);assert.ok(armor.length>0&&armor.length<=8,kind+' batched armor budget');counts.push(armor.length);
        for(const region of level===1?['front','rear']:['front','rear','left','right'])assert.ok(armor.some(p=>p.name===`panel_Reinforcement_${region}_steel`));
        for(const p of armor){
          assert.equal(p.userData.constructionRole,'rail');assert.equal(p.userData.detachAssembly,null,'Chassis reinforcement must not join a stock plastic bumper hinge');
          assert.equal(p.castShadow,p.name.endsWith('_steel'),'Steel supplies the reinforcement silhouette; small fasteners do not add shadow draws');
          for(const name of ['position','normal','impactWear','wreckPosition','restPosition','impactAxis','transferPaint'])assert.ok(p.geometry.getAttribute(name),p.name+' '+name);
          assert.ok(Array.from(p.geometry.attributes.position.array).every(Number.isFinite));
        }
        near(car.body.mass(),DEFINITIONS[kind].mass+95*level,.01);
        const intact=shape(car);signatures.push(createHash('sha256').update(JSON.stringify(intact)).digest('hex'));
        hit(car);near(car.health,100-32*car.specification.damageScale);
        assert.notDeepEqual(shape(car),intact,kind+' fitted armor receives actual Vehicle.hit damage');
        assert.ok(shape(car).some((p,i)=>p.position!==intact[i].position),kind+' reinforcement vertices actually deform');
        assert.ok(armor.some(p=>Array.from(p.geometry.attributes.impactWear.array).some(x=>x>0)),kind+' damaged steel has wear');
        assert.ok(armor.every(p=>p.visible),'Reinforcement stays attached to the chassis');
        car.repair();assert.deepEqual(shape(car),intact,kind+' repair restores all armor buffers');assert.equal(car.setup.armor,level);
      }finally{car.dispose();world.free();}
    }
    assert.equal(new Set(signatures).size,3,kind+' tiers change fitted geometry');assert.ok(counts[1]>counts[0]&&counts[2]>=counts[1]);
  }
});

test('armor presets and setup exchange preserve all tiers while legacy saves remain stock',()=>{
  for(const kind of CAR_KINDS){
    const presets=[0,1,2,3].map(armor=>({name:'Reinforcement '+armor,setup:{...stockSetup(kind),armor}}));
    const garage=readGarage(JSON.stringify({version:1,cars:{[kind]:{setup:presets[2].setup,presets}}}));assert.equal(garage.cars[kind].setup.armor,2);
    for(const [level,preset] of garage.cars[kind].presets.entries()){
      assert.equal(preset.setup.armor,level);assert.deepEqual(importSetup(exportSetup(kind,preset.setup),kind),presets[level].setup);
    }
    const old={...stockSetup(kind)} as Partial<ReturnType<typeof stockSetup>>;delete old.armor;
    assert.equal(readGarage(JSON.stringify({version:1,cars:{[kind]:{setup:old}}})).cars[kind].setup.armor,0);
  }
  const kind='marten',setup=stockSetup(kind);setup.armor=3;setup.paint=0x6d8356;const restored=importSetup(exportSetup(kind,setup),kind),world=new R.World(zero),a=new Vehicle(0,kind,setup.paint,new T.Scene(),world,fx,setup),b=new Vehicle(1,kind,restored.paint,new T.Scene(),world,fx,restored);
  try{assert.deepEqual(shape(a),shape(b));assert.ok(panels(b).some(p=>p.name==='panel_Reinforcement_left_steel'));}
  finally{a.dispose();b.dispose();world.free();}
});

test('damage and disposal of one armor kit leave another vehicle and later stock clones intact',()=>{
  const world=new R.World(zero),scene=new T.Scene(),setup=stockSetup('buggy');setup.armor=3;
  const a=new Vehicle(0,'buggy',setup.paint,scene,world,fx,setup),b=new Vehicle(1,'buggy',setup.paint,scene,world,fx,setup);let aAlive=true;
  try{
    pose(a);pose(b,12);const untouched=shape(b),otherMaterials=new Set(panels(b).map(p=>p.material));
    for(const p of panels(a)){assert.equal(otherMaterials.has(p.material),false);assert.notEqual(p.geometry,panels(b).find(q=>q.name===p.name)!.geometry);}
    hit(a,48);assert.notDeepEqual(shape(a),untouched);assert.deepEqual(shape(b),untouched);
    a.dispose();aAlive=false;assert.deepEqual(shape(b),untouched);b.repair();assert.deepEqual(shape(b),untouched);
    const fresh=new Vehicle(2,'buggy',setup.paint,scene,world,fx,setup);try{assert.deepEqual(shape(fresh),untouched,'A later fitted clone still starts with the pristine cached armor');}finally{fresh.dispose();}
    const stock=new Vehicle(0,'buggy',DEFINITIONS.buggy.color,scene,world,fx);try{assert.equal(stockSignature(stock),publishedStock.buggy);}finally{stock.dispose();}
  }finally{if(aAlive)a.dispose();b.dispose();world.free();}
});

test('fitted armor, transferred paint and repair survive compressed replay with repeated backwards seeks',async()=>{
  for(const [kind,level] of [['coupe',1],['marten',2],['buggy',3]] as const){
    const world=new R.World(zero),scene=new T.Scene(),setup=stockSetup(kind);setup.armor=level;const car=new Vehicle(0,kind,setup.paint,scene,world,fx,setup);pose(car);car.render(1);
    const recorder=new ReplayRecorder({version:1,mode:'derby',reverse:false,cars:[{id:0,kind,setup}],props:0,created:'2026-10-02T20:00:00Z'});let time=0;car.onVisualEvent=event=>recorder.event(0,time,event);
    const frames:ReturnType<typeof shape>[]=[];const capture=(at:number)=>{car.wreckParts.poseAt(at,0);recorder.capture(at,()=>captureReplayFrame([car],[],[0]),true);frames.push(shape(car));};
    try{
      capture(0);time=.5;hit(car,30,time);capture(1);time=1.5;hit(car,24,time,level>1?'left':'rear');capture(2);time=2.5;car.repair();capture(3);
      assert.notDeepEqual(frames[1],frames[0]);assert.notDeepEqual(frames[2],frames[1]);assert.deepEqual(frames[3],frames[0]);
      const doc=await readReplayFile(new File([await replayFile(recorder.document())],`armor-${kind}.qir`));assert.equal(doc.meta.cars[0].setup.armor,level);
      const replay=new ReplayScene(doc,scene,world,[]);
      try{for(const at of [0,1,2,3,0,2,1,3,0]){replay.seek(at);assert.deepEqual(shape(replay.cars[0]),frames[at],kind+' armor replay at '+at);}}
      finally{replay.dispose();}
      assert.deepEqual(shape(car),frames[3],'Replay seeking leaves the live car unchanged');
    }finally{car.dispose();world.free();}
  }
});

test('confirmed authority setup fits the right armor, preserves collision scaling and restores stock without stale kit',()=>{
  const setup={...stockOnlineSetup('coupe'),armor:2,paint:0x598367},authority=new Simulation(R,'playground',[],8,[setup]),cold=new Simulation(R,'playground'),world=new R.World(zero),scene=new T.Scene();let cars:Vehicle[]=[];
  const view=new OnlineView(scene,world,fx,{clearCars(){},attach(){},shot(){}} as any,()=>cars,next=>cars=next);
  try{
    const saved:Snapshot={...authority.snapshot(true),members:[],ack:{}},wire=decodeSnapshotWire(encodeSnapshotWire(saved)) as Snapshot;cold.restore(wire);
    assert.equal(cold.cars[0].state.setup!.armor,2);near(cold.cars[0].body.mass(),authority.cars[0].body.mass(),.001);
    view.receive(wire);let rendered=cars.find(c=>c.id===0)!;assert.ok(panels(rendered).some(p=>p.name==='panel_Reinforcement_left_steel'));near(rendered.body.mass(),cold.cars[0].body.mass(),.001);
    const point=rendered.root.worldToLocal(contact(rendered).clone()),hitSnapshot=structuredClone(wire);hitSnapshot.tick++;hitSnapshot.cars[0].health=80;
    hitSnapshot.cars[0].dents=[{id:1,localPoint:{x:point.x,y:point.y,z:point.z},localDirection:{x:0,y:0,z:-1},damage:20,repair:0}];
    const before=shape(rendered);view.receive(hitSnapshot);rendered=cars.find(c=>c.id===0)!;assert.notDeepEqual(shape(rendered),before);near(rendered.lastDamage,20);assert.equal(rendered.health,80);
    const reused=structuredClone(hitSnapshot);reused.tick++;reused.cars.forEach(c=>delete c.dents);view.receive(reused);assert.equal(cars.find(c=>c.id===0),rendered,'Identical armor setup does not rebuild every network update');
    const stock=structuredClone(reused);stock.tick++;stock.cars[0].setup=effectiveOnlineSetup('coupe',setup,'stock');stock.cars[0].repair++;stock.cars[0].health=100;stock.cars[0].components=freshComponents();
    view.receive(stock);const replacement=cars.find(c=>c.id===0)!;assert.notEqual(replacement,rendered);assert.equal(rendered.root.parent,null);assert.equal(panels(replacement).length,0);assert.equal(replacement.paintColor.getHex(),setup.paint);
    const legacy=structuredClone(stock);legacy.tick++;legacy.cars.forEach(c=>delete c.setup);view.receive(legacy);assert.ok(cars.every(c=>panels(c).length===0),'Missing legacy authority setup cannot invent local garage armor');
  }finally{cars.forEach(c=>c.dispose());world.free();authority.dispose();cold.dispose();}
});
