import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import * as T from 'three';import R from '@dimforge/rapier3d-compat';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {buildCompactAsset} from '../src/compact-asset';import {encodeVehicleGlb} from '../tools/vehicle-glb';import {loadCarWithoutImages} from '../tools/car-asset-audit';import {loadCars,templates} from '../src/assets';import {Vehicle} from '../src/vehicle';import {DEFINITIONS,CAR_KINDS,isCarKind} from '../src/rules';import {classicWheelAnchors,vehicleWheelRadius,classicEngineVoice} from '../src/classic-vehicle-specs';import {stockSetup,readGarage,exportSetup,importSetup} from '../src/garage';import {demoCarKind} from '../src/demo-session';import {createVehiclePhysics,stepVehiclePhysics,vehicleSpecification} from '../src/vehicle-physics';import {ReplayRecorder,replayFile,readReplayFile} from '../src/replay-data';import {ReplayScene,captureReplayFrame} from '../src/replay-scene';import {verifyEstateRearJointRevision} from './estate-rear-joint-invariants';
import {drivingObstacleClearance} from '../src/driving-probe';import {derbyTrafficClearance} from '../src/derby-driving';
await R.init();const original=GLTFLoader.prototype.loadAsync;GLTFLoader.prototype.loadAsync=async url=>loadCarWithoutImages(/\/(coupe|sedan|hatch|muscle|wagon|utility|compact|van|wheel-machining)\.glb$/.exec(String(url))![1]);try{await loadCars(()=>{});}finally{GLTFLoader.prototype.loadAsync=original;}
const fx={emit(){},mark(){},detach(m:T.Mesh){m.visible=false;}}as any;
const vectorKey=(p:T.Vector3)=>p.toArray().map(x=>x.toFixed(6)).join(',');
test('the original compact exports deterministically with closed shaped pressings and finite geometry under the fleet budget',()=>{
 const root=buildCompactAsset(),bytes=encodeVehicleGlb(root,()=>{throw Error('No textures');},{generator:'Quarry Impact original Rook 1100 pressing authoring',copyright:'Original Quarry Impact vehicle artwork, 2026'});assert.deepEqual(bytes,readFileSync(new URL('../public/models/compact.glb',import.meta.url)));let vertices=0;
 root.traverse(o=>{if(!(o instanceof T.Mesh))return;const p=o.geometry.attributes.position;vertices+=p.count;for(const a of Object.values(o.geometry.attributes))assert.ok([...a.array].every(Number.isFinite),o.name);for(let i=0;i<p.count;i+=3){const a=new T.Vector3().fromBufferAttribute(p,i),b=new T.Vector3().fromBufferAttribute(p,i+1),c=new T.Vector3().fromBufferAttribute(p,i+2);assert.ok(b.sub(a).cross(c.sub(a)).lengthSq()>1e-18,o.name+' degenerate triangle');}});assert.ok(vertices<65000,`Vertices ${vertices}`);
 for(const name of ['panel_hood','panel_Boot','panel_Roof','panel_BodyDoorL','panel_BodyDoorR','panel_FrontWingL','panel_RearWingR','panel_FrontValance','panel_RearValance']){const p=(root.getObjectByName(name)as T.Mesh).geometry.attributes.position,edges=new Map<string,number>();for(let i=0;i<p.count;i+=3)for(let j=0;j<3;j++){const key=[vectorKey(new T.Vector3().fromBufferAttribute(p,i+j)),vectorKey(new T.Vector3().fromBufferAttribute(p,i+(j+1)%3))].sort().join('|');edges.set(key,(edges.get(key)??0)+1);}assert.ok([...edges.values()].every(n=>n===2),name+' must have an inner skin and closed perimeter');}
 for(const side of [-1,1])for(const z of [-1.09,1.09]){const hits=new T.Raycaster(new T.Vector3(side*1.2,.60,z),new T.Vector3(-side,0,0)).intersectObject(root,true);assert.ok(hits.length);assert.ok(hits[0].object.name.startsWith('Tire_'),'Arch opening must expose the tyre');}
});
test('the compact roster entry persists tuning and old garage saves, and participates in selected and mixed demos',()=>{
 assert.equal(CAR_KINDS.length,8);assert.ok(isCarKind('compact'));assert.ok(templates.has('compact'));const old=stockSetup('wagon');old.engine=3;const saved=readGarage(JSON.stringify({version:1,cars:{wagon:{setup:old}}}));assert.deepEqual(saved.cars.wagon.setup,old);assert.deepEqual(saved.cars.compact.setup,stockSetup('compact'));const setup=stockSetup('compact');setup.armor=2;setup.tune.suspension=.5;assert.deepEqual(importSetup(exportSetup('compact',setup),'compact'),setup);assert.throws(()=>importSetup(exportSetup('compact',setup),'hatch'));assert.equal(demoCarKind(23,'compact','selected'),'compact');assert.deepEqual(new Set(Array.from({length:16},(_,i)=>demoCarKind(i,'compact','mixed'))),new Set(CAR_KINDS));assert.deepEqual(classicEngineVoice('compact'),{bank:'hatch',pitch:1.12});
});
test('visible compact tyres align with suspension and impact anchors, including after wheel damage and repair',()=>{
 const world=new R.World({x:0,y:-9.81,z:0}),car=new Vehicle(0,'compact',DEFINITIONS.compact.color,new T.Scene(),world,fx);try{const a=classicWheelAnchors('compact');assert.equal(-car.model.position.y,a.modelOffset);for(let i=0;i<4;i++){assert.deepEqual({...car.wheels[i].position},a.wheels[i]);const p=car.controller.wheelChassisConnectionPointCs(i)!;assert.ok(Math.abs(p.x-a.wheels[i].x)<1e-6&&Math.abs(p.z-a.wheels[i].z)<1e-6);assert.ok(Math.abs(car.controller.wheelRadius(i)!-.32)<1e-6);}assert.ok(car.roof.halfExtents().x<.61&&car.roof.halfExtents().z>.70);for(const name of ['hood','front-bumper','rear-bumper','door-left','door-right'])assert.ok(car.wreckParts.assemblies.some(a=>a.name===name));assert.equal(car.glass.length,6);assert.ok(car.brakeLights.size>0);assert.ok(car.model.getObjectByName('panel_inner_engine_Structure Rook Steel'));
 car.place(0,0,0);car.root.updateMatrixWorld(true);const point=new T.Vector3(-.655,.3400195,1.09).applyMatrix4(car.model.matrixWorld);car.hit(point,new T.Vector3(1,0,0),25,.5,true);assert.ok(car.wreckParts.wheelDamage[0]>0);car.preStep(1/60);assert.ok(car.controller.wheelRadius(0)!<.32);car.repair();for(let i=0;i<4;i++)assert.ok(Math.abs(car.controller.wheelRadius(i)!-vehicleWheelRadius('compact'))<1e-6);
 }finally{car.dispose();world.free();}
});
test('the compact accelerates, turns, brakes and reverses with smaller tyres and a distinct lightweight specification',()=>{
 const world=new R.World({x:0,y:-9.81,z:0});world.timestep=1/60;world.createCollider(R.ColliderDesc.cuboid(500,.5,500).setTranslation(0,-.5,0));const spec=vehicleSpecification('compact'),rig=createVehiclePhysics(R,world,'compact',spec.mass),s={health:100,damageLeft:0,damageRight:0,steering:0,speed:0,slip:0,surface:'asphalt' as const,gear:1,rpm:850,input:{throttle:1,steer:0,brake:0,handbrake:false}};rig.body.setTranslation({x:0,y:.9,z:0},true);
 try{for(let i=0;i<600;i++){stepVehiclePhysics(rig.body,rig.controller,'compact',spec,s,1/60);world.step();}assert.ok(s.speed>20&&s.speed<39);assert.equal(rig.controller.wheelEngineForce(0),0);assert.ok(rig.controller.wheelEngineForce(2)!>0);assert.ok(spec.mass<vehicleSpecification('hatch').mass&&spec.speedLimit<vehicleSpecification('wagon').speedLimit);assert.ok(rig.body.translation().y>.5&&rig.body.translation().y<1);
 s.input.steer=.18;for(let i=0;i<60;i++){stepVehiclePhysics(rig.body,rig.controller,'compact',spec,s,1/60);world.step();}assert.ok(Math.abs(rig.body.rotation().y)>.05);s.input.steer=0;s.input.throttle=0;s.input.brake=1;for(let i=0;i<600;i++){stepVehiclePhysics(rig.body,rig.controller,'compact',spec,s,1/60);world.step();}assert.ok(Math.abs(s.speed)<1);s.input.throttle=-.7;s.input.brake=0;for(let i=0;i<120;i++){stepVehiclePhysics(rig.body,rig.controller,'compact',spec,s,1/60);world.step();}assert.ok(s.speed< -3);assert.equal(s.gear,0);
 }finally{world.removeVehicleController(rig.controller);world.free();}
});
test('compact paint, geometry, hinges and damaged wheels survive compressed replay and backwards seeks',async()=>{
 const scene=new T.Scene(),world=new R.World({x:0,y:-9.81,z:0}),setup=stockSetup('compact'),car=new Vehicle(0,'compact',setup.paint,scene,world,fx,setup);car.place(2,4,.2);car.render(1);car.root.updateMatrixWorld(true);const recorder=new ReplayRecorder({version:1,mode:'derby',reverse:false,cars:[{id:0,kind:'compact',setup}],props:0,created:'2026-10-01T20:00:00Z'});car.onVisualEvent=e=>recorder.event(0,.5,e);
 const shape=(c:Vehicle)=>({health:c.health,wheels:[...c.wreckParts.wheelDamage],panels:c.panels.map(p=>({name:p.name,visible:p.visible,positions:[...p.geometry.attributes.position.array]})),hinges:c.wreckParts.assemblies.flatMap(a=>a.members.map(m=>m.mesh.matrix.toArray()))});
 try{recorder.capture(0,()=>captureReplayFrame([car],[],[0]),true);const intact=shape(car);car.hit(new T.Vector3(-.70,.77,.32).applyMatrix4(car.model.matrixWorld),new T.Vector3(1,0,0).applyQuaternion(car.root.quaternion),24,.5,true);car.wreckParts.poseAt(1,0);recorder.capture(1,()=>captureReplayFrame([car],[],[0]),true);const damaged=shape(car);assert.notDeepEqual(damaged,intact);const doc=await readReplayFile(new File([await replayFile(recorder.document())],'rook.qir'));const replay=new ReplayScene(doc,scene,world,[]);try{replay.seek(1);assert.deepEqual(shape(replay.cars[0]),damaged);replay.seek(0);assert.deepEqual(shape(replay.cars[0]),intact);replay.seek(1);assert.deepEqual(shape(replay.cars[0]),damaged);}finally{replay.dispose();}car.repair();assert.deepEqual(shape(car),intact);
 }finally{car.dispose();world.free();}
});
test('compact integration retains the preceding source bytes and all historic revision layers',verifyEstateRearJointRevision);
test('compact obstacle sensing sees a touching barrier and recovery clearance respects both vehicle footprints',()=>{
 const world=new R.World({x:0,y:0,z:0});world.createCollider(R.ColliderDesc.cuboid(3,.6,.15).setTranslation(0,.6,2.14));world.step();
 try{const hit=world.castRay(new R.Ray({x:0,y:.8,z:0},{x:0,y:0,z:1}),24,true)!;assert.ok(hit);assert.ok(drivingObstacleClearance({kind:'compact'},0,hit.timeOfImpact)<.02);assert.equal(world.castRay(new R.Ray({x:0,y:.8,z:2.5},{x:0,y:0,z:1}),24,true),null,'The old origin skips this barrier');
 const car={id:0,kind:'compact' as const,current:{x:0,y:.8,z:0},forward:{x:0,y:0,z:1},right:{x:1,y:0,z:0}}as any,other={...car,id:1,kind:'sedan',current:{x:0,y:.8,z:-7}};const clear=derbyTrafficClearance(car,[car,other],0,-1);assert.ok(Math.abs(clear-(7-(1.86+.15)-(2.475+.15)))<1e-6);other.current.x=5;assert.equal(derbyTrafficClearance(car,[car,other],0,-1),30);
 }finally{world.free();}
});
