import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {drawQuarryMap} from '../src/quarry-minimap';
import {IRONFIELD} from '../src/ironfield-course';

type Command=unknown[];
type Paint={operation:string;path:Command[];style:Record<string,unknown>};
function canvasRecorder(size:number){
 const calls:Command[]=[],paints:Paint[]=[],stack:Record<string,unknown>[]=[],gradients=new WeakMap<object,string>();let style:Record<string,unknown>={},path:Command[]=[],gradientId=0;
 const context=new Proxy({}as Record<string,unknown>,{
  set(_target,key,value){style[String(key)]=value;calls.push(['set',String(key),typeof value==='object'&&value?gradients.get(value):value]);return true;},
  get(_target,key){if(Object.hasOwn(style,key))return style[String(key)];return(...args:unknown[])=>{
   const name=String(key);calls.push([name,...args]);
   if(name==='createRadialGradient'){const id='gradient'+gradientId++,gradient={addColorStop(...stops:unknown[]){calls.push(['addColorStop',id,...stops]);}};gradients.set(gradient,id);return gradient;}
   if(name==='save')stack.push({...style});else if(name==='restore')style=stack.pop()!;
   else if(name==='beginPath')path=[];else if(['moveTo','lineTo','arc','ellipse','closePath'].includes(name))path.push([name,...args]);
   else if(name==='fill'||name==='stroke')paints.push({operation:name,path:path.map(c=>c.slice()),style:{...style}});
  };},
 });
 const canvas={width:size,getContext(type:string){calls.push(['getContext',type]);return context;}}as unknown as HTMLCanvasElement;
 return{canvas,calls,paints};
}
const quaternion=(yaw:number)=>({x:0,y:Math.sin(yaw/2),z:0,w:Math.cos(yaw/2)});
const cars=[{id:0,health:100,current:{x:0,z:0},currentQ:quaternion(.3)},{id:1,health:0,current:{x:77,z:64},currentQ:quaternion(0)},{id:5,health:49,current:{x:-95,z:-42},currentQ:quaternion(-1.1)}];
const waypoints=[{x:58,z:-22,label:'3'},{x:-34,z:44,label:'FINISH'}];
const fixtures=[
 {name:'race400',size:400,mode:'race',arena:{x:18,z:14,radius:64},followed:5,points:waypoints,hash:'e2417b80070116686be6d7eb98bd2c935bf2d813d804432361c27e3c81fda911'},
 {name:'derby400',size:400,mode:'derby',arena:{x:18,z:14,radius:64},followed:0,points:undefined,hash:'aa429ff94f5ef7daef137b44b8ada08dca6006aa0bc6418b3cc0f5b1ee15c847'},
 {name:'playground240',size:240,mode:'playground',arena:{x:0,z:0,radius:46},followed:1,points:waypoints,hash:'3b40e70c56f63d838659515a925c73e3c161239365036fe43053bf06c0d3c183'},
 {name:'legacyDerby320',size:320,mode:'derby',arena:{x:0,z:0,radius:46},followed:5,points:undefined,hash:'8930cc42297e6811551efcc42279303cf641ebaf2271244003d952d667b5d100'},
];

test('omitted course preserves every Quarry canvas call from frozen 7f62f79',()=>{
 // Golden command hashes were generated by the unmodified 7f62f79 source,
 // including style assignments, gradient stops, path order and car headings.
 for(const f of fixtures){const recorded=canvasRecorder(f.size);drawQuarryMap(recorded.canvas,cars,f.arena,f.mode,f.followed,f.points);assert.equal(createHash('sha256').update(JSON.stringify(recorded.calls)).digest('hex'),f.hash,f.name);}
});

test('Ironfield draws an open asphalt figure-eight at physical width without painting its infields',()=>{
 const r=canvasRecorder(400),extent=145,scale=180/extent;
 drawQuarryMap(r.canvas,[],{x:18,z:14,radius:64},'race',0,[],{point:IRONFIELD.point,extent,halfWidth:IRONFIELD.halfWidth});
 const route=r.paints.find(p=>p.path.filter(c=>c[0]==='lineTo').length>100)!;assert.ok(route,'course must have a visible route');assert.equal(route.operation,'stroke');assert.equal(route.style.lineWidth,17*scale);assert.equal(route.style.lineJoin,'round');
 assert.equal(r.paints.filter(p=>p.operation==='fill').length,0,'road lobes must never be filled');
 const points=route.path.map(p=>({x:((p[1] as number)-200)/scale,z:(200-(p[2]as number))/scale}));
 assert.ok(Math.min(...points.map(p=>p.x))< -109&&Math.max(...points.map(p=>p.x))>109,'both lobes visible');
 assert.ok(Math.min(...points.map(p=>p.z))< -63&&Math.max(...points.map(p=>p.z))>63,'north/south road extent visible');
 assert.deepEqual(points[0],points.at(-1),'course closes without a filled polygon');
 let crossings=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dz=b.z-a.z,t=Math.max(0,Math.min(1,-(a.x*dx+a.z*dz)/(dx*dx+dz*dz)));if(Math.hypot(a.x+dx*t,a.z+dz*t)<.03)crossings++;}
 assert.ok(crossings>=2,'both at-grade branches pass through centre');
 for(const p of points){assert.ok(IRONFIELD.distance(p.x,p.z)<.02);assert.ok(Math.hypot(p.x,p.z)+IRONFIELD.halfWidth<extent,'full route width fits circular clipping');}
});

test('course extent scales road, waypoint and car positions together while derby ignores course',()=>{
 const arena={x:18,z:14,radius:64};
 for(const [size,extent]of [[240,145],[400,180]]){
  const r=canvasRecorder(size),scale=size*.45/extent,car=cars[2];drawQuarryMap(r.canvas,[car],arena,'race',car.id,[waypoints[0]],{point:IRONFIELD.point,extent});
  assert.deepEqual(r.calls.find(c=>c[0]==='translate'),['translate',size/2+car.current.x*scale,size/2-car.current.z*scale]);
  assert.ok(r.calls.some(c=>c[0]==='arc'&&c[1]===size/2+58*scale&&c[2]===size/2+22*scale&&c[3]===10));
  const route=r.paints.find(p=>p.path.filter(c=>c[0]==='lineTo').length>100)!;assert.equal(route.style.lineWidth,12*scale,'optional halfWidth defaults to 6m');
 }
 const stock=canvasRecorder(400),extra=canvasRecorder(400);drawQuarryMap(stock.canvas,cars,arena,'derby',0);drawQuarryMap(extra.canvas,cars,arena,'derby',0,[],{point(){throw Error('derby must not sample course');},extent:145});assert.deepEqual(extra.calls,stock.calls);
});


test('open airfield map shows all crossing runways at their driving widths',async()=>{
 const {MEREFIELD}=await import('../src/merefield-course'),r=canvasRecorder(400),scale=180/MEREFIELD.mapExtent;
 drawQuarryMap(r.canvas,[],{x:0,z:0,radius:64},'race',0,[],{point:MEREFIELD.point,extent:MEREFIELD.mapExtent,halfWidth:MEREFIELD.halfWidth,lines:MEREFIELD.mapLines});
 for(const line of MEREFIELD.mapLines){const [a,b]=line.points;assert.ok(r.paints.some(p=>p.operation==='stroke'&&p.style.lineWidth===line.width*scale&&JSON.stringify(p.path)===JSON.stringify([['moveTo',200+a.x*scale,200-a.z*scale],['lineTo',200+b.x*scale,200-b.z*scale]])));}
});
