import{ReplayLibrary}from'../src/replay-library';import{stockSetup}from'../src/garage';import{REPLAY_STRIDE,replayFile,type ReplayDocument}from'../src/replay-data';
import{showReplayLibrary}from'../src/replay-library-ui';
const output=document.querySelector('#results')!,prefix='quarry-library-test-'+crypto.randomUUID();let passed=0,failed=0;const databases:string[]=[];
const assert=(v:unknown,message:string)=>{if(!v)throw Error(message);};
const doc=(id=0):ReplayDocument=>{const frame=(x:number)=>{const v=new Float32Array(REPLAY_STRIDE);v[0]=x;v[6]=1;v[14]=100;for(let i=0;i<4;i++)v[21+i*8]=1;return v;};return{meta:{version:1,mode:'race',reverse:false,cars:[{id:0,kind:'coupe',setup:stockSetup('coupe')}],props:0,created:'2026-10-01T17:00:00Z'},frames:[{time:0,values:frame(id)},{time:10,values:frame(id+10)}],events:[],limited:false};};
const library=(suffix:string,limit=50,bytes=256*1024*1024)=>{const name=prefix+suffix;databases.push(name);return new ReplayLibrary(indexedDB,name,limit,bytes);};
async function check(name:string,fn:()=>Promise<void>){try{await fn();passed++;output.textContent+=`PASS ${name}\n`;}catch(e){failed++;output.textContent+=`FAIL ${name}: ${e}\n`;}document.querySelector('#summary')!.textContent=`${passed} passed · ${failed} failed`;}
await check('save survives a fresh database connection and preserves poses/setup',async()=>{const a=library('-reopen'),saved=await a.save(doc(),'First race'),b=library('-reopen');const rows=await b.list(),loaded=await b.load(saved.id);assert(rows.length===1&&rows[0].name==='First race','metadata lost');assert(loaded.frames[1].values[0]===10&&loaded.meta.cars[0].setup.paint===doc().meta.cars[0].setup.paint,'content differs');});
await check('repeated save deduplicates and rename persists',async()=>{const a=library('-duplicate');const x=await a.save(doc(),'First'),y=await a.save(doc(),'Second');assert(x.id===y.id&&(await a.list()).length===1,'duplicate consumed storage');await a.rename(x.id,'Renamed race');assert((await a.list())[0].name==='Renamed race','rename lost');});
await check('concurrent writers respect the shared count limit without eviction',async()=>{const a=library('-parallel',2),b=library('-parallel',2);const results=await Promise.allSettled([a.save(doc(1)),b.save(doc(2)),a.save(doc(3))]);assert(results.filter(r=>r.status==='fulfilled').length===2,'wrong committed count');const rows=await b.list();assert(rows.length===2,'quota race');for(const row of rows)await b.load(row.id);});
await check('byte limit aborts without partial metadata or payload',async()=>{const a=library('-bytes',50,1);await a.save(doc()).then(()=>{throw Error('oversized accepted');},()=>{});assert((await a.list()).length===0,'partial commit');});
await check('invalid imports cannot overwrite an existing recording',async()=>{const a=library('-invalid');const saved=await a.save(doc(),'Keep me');await a.import(new File(['broken'],'bad.qir')).then(()=>{throw Error('corrupt accepted');},()=>{});assert((await a.list()).length===1&&(await a.load(saved.id)).frames.length===2,'existing data changed');});
await check('export/import round-trip and deletion release count and payload',async()=>{const a=library('-delete',1),first=await a.save(doc(1)),file=await a.file(first.id);await a.remove(first.id);assert((await a.list()).length===0,'row remains');await a.file(first.id).then(()=>{throw Error('payload remains');},()=>{});const next=await a.import(new File([file],'Shared race.qir'));assert(next.name==='Shared race'&&(await a.load(next.id)).frames[0].values[0]===1,'import changed recording');});
await check('a missing rename fails without creating a phantom entry',async()=>{const a=library('-missing');await a.rename('absent','Name').then(()=>{throw Error('missing accepted');},()=>{});assert((await a.list()).length===0,'phantom metadata');});
await check('failed second write rolls back the first metadata write',async()=>{const a=library('-abort'),original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){const request=original.apply(this,args as any);if(this.name==='recordings')this.transaction.abort();return request;};try{await a.save(doc()).then(()=>{throw Error('aborted save accepted');},()=>{});}finally{IDBObjectStore.prototype.put=original;}assert((await a.list()).length===0,'metadata survived abort');});
// Keep a separate fixture library available for visible UI and reload checks.
const fixture=new ReplayLibrary(indexedDB,'quarry-library-ui-fixture');
document.querySelector<HTMLButtonElement>('#seed')!.onclick=async()=>{await fixture.save(doc(40),'Quarry sprint');await fixture.save({...doc(80),meta:{...doc(80).meta,mode:'derby'}},'Last car standing');document.querySelector('#ui-status')!.textContent='Fixture recordings saved';};
document.querySelector<HTMLButtonElement>('#open')!.onclick=()=>showReplayLibrary(document.querySelector('#ui')!,doc=>{document.querySelector('#ui-status')!.textContent=`Loaded ${doc.meta.mode}: ${doc.frames.length} frames · x=${doc.frames[0].values[0]}`;},()=>{},fixture);
for(const name of new Set(databases))indexedDB.deleteDatabase(name);
