import {musicNotes,NOTE_INTERVAL,midiFrequency,stereoWidth} from './coastal-music.js';
export class Soundscape{
 constructor(){this.ctx=null;this.enabled=true;this.mode='stereo';this.music=false;this.volume=.8;this.previewUntil=0;this.nextNote=0;this.musicStep=0;this.pans=[];this.musicPans=new Set();this.voices=[];}
 setOptions(options={}){if(['stereo','mono','headphones'].includes(options.mode))this.mode=options.mode;if(typeof options.music==='boolean')this.music=options.music;if(Number.isFinite(options.volume))this.volume=Math.max(0,Math.min(1,options.volume));if(typeof options.enabled==='boolean')this.enabled=options.enabled;for(const p of [...this.pans,...this.musicPans])p.node.pan.setTargetAtTime(p.base*stereoWidth(this.mode),this.ctx.currentTime,.05);}
 pan(destination,base=0){const node=this.ctx.createStereoPanner();node.pan.value=base*stereoWidth(this.mode);node.connect(destination);this.pans.push({node,base});return node;}
 start(){if(this.ctx){this.ctx.resume();return;}const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;const ctx=this.ctx=new C();this.master=ctx.createGain();this.master.gain.value=0;const limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-10;limiter.knee.value=12;limiter.ratio.value=6;this.master.connect(limiter).connect(ctx.destination);this.effects=ctx.createGain();this.effects.connect(this.master);this.musicGain=ctx.createGain();this.musicGain.gain.value=0;this.musicGain.connect(this.master);
  for(let i=0;i<2;i++){const engine=ctx.createOscillator(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),pan=this.pan(this.effects,0);engine.type='sawtooth';engine.frequency.value=58;filter.type='lowpass';filter.frequency.value=320;gain.gain.value=0;engine.connect(filter).connect(gain).connect(pan);engine.start();this.voices.push({engine,gain,pan});}
  this.engine=this.voices[0].engine;this.engineGain=this.voices[0].gain;
  const buffer=ctx.createBuffer(1,ctx.sampleRate*4,ctx.sampleRate),data=buffer.getChannelData(0);let b=0;for(let i=0;i<data.length;i++){b=(b+Math.random()*.14-.07)/1.02;data[i]=b*3;}const source=ctx.createBufferSource();source.buffer=buffer;this.noiseBuffer=buffer;source.loop=true;
  this.wind=ctx.createBiquadFilter();this.wind.type='lowpass';this.wind.frequency.value=500;this.windGain=ctx.createGain();source.connect(this.wind).connect(this.windGain).connect(this.pan(this.effects,.22));this.windGain.gain.value=.14;source.start();
  this.water=ctx.createBiquadFilter();this.water.type='bandpass';this.water.frequency.value=1100;this.water.Q.value=.5;this.waterGain=ctx.createGain();source.connect(this.water).connect(this.waterGain).connect(this.pan(this.effects,-.28));this.waterGain.gain.value=.12;
 }
 preview(){if(!this.enabled)return false;this.start();if(!this.ctx)return false;this.previewUntil=this.ctx.currentTime+10;this.nextNote=this.ctx.currentTime;this.musicStep=0;return true;}
 stopPreview(){this.previewUntil=0;}
 scheduleMusic(active){const ctx=this.ctx,c=ctx.currentTime;this.musicGain.gain.setTargetAtTime(active?.8:0,c,.2);if(!active){this.nextNote=c;return;}if(this.nextNote<c-.2)this.nextNote=c;
  while(this.nextNote<c+.15){for(const note of musicNotes(this.musicStep)){const o=ctx.createOscillator(),g=ctx.createGain(),pan=ctx.createStereoPanner();o.type=note.type;o.frequency.value=midiFrequency(note.midi);pan.pan.value=note.pan*stereoWidth(this.mode);const entry={node:pan,base:note.pan};this.musicPans.add(entry);g.gain.setValueAtTime(0,this.nextNote);g.gain.linearRampToValueAtTime(note.gain,this.nextNote+.035);g.gain.exponentialRampToValueAtTime(.0001,this.nextNote+note.duration);o.connect(g).connect(pan).connect(this.musicGain);o.start(this.nextNote);o.stop(this.nextNote+note.duration+.04);o.onended=()=>{o.disconnect();g.disconnect();pan.disconnect();this.musicPans.delete(entry);};}this.nextNote+=NOTE_INTERVAL;this.musicStep++;}
 }
 update(speed,storm,recovery,paused,t,wet=1,companion=null){if(!this.ctx)return;const c=this.ctx.currentTime,preview=c<this.previewUntil;this.master.gain.setTargetAtTime(this.enabled&&(!paused||preview)?.38*this.volume:0,c,.15);this.effects.gain.setTargetAtTime(paused?0:1,c,.12);
  for(let i=0;i<2;i++){const v=this.voices[i],s=i?(companion?.speed||0):speed,w=i?(companion?.wet??1):wet;v.engine.frequency.setTargetAtTime(58+Math.abs(s)*(20+(1-w)*5)+Math.sin(t*13+i)*1.2,c,.12);v.gain.gain.setTargetAtTime(i&&!companion?0:(.022+Math.abs(s)*.011+(recovery?.03:0))*(companion?.65:1),c,.12);v.pan.pan.setTargetAtTime(companion?(i?.4:-.4)*stereoWidth(this.mode):0,c,.08);}
  this.wind.frequency.setTargetAtTime(350+storm*1800,c,.6);this.windGain.gain.setTargetAtTime(.10+storm*.45,c,.5);this.waterGain.gain.setTargetAtTime(.08+Math.abs(speed)*.025*wet+storm*.15+Math.sin(t*.7)*.02,c,.3);this.scheduleMusic(this.enabled&&(preview||this.music&&!paused));
 }
 splash(impact=3,side=0){if(!this.ctx||!this.enabled||!this.noiseBuffer)return;const t=this.ctx.currentTime,source=this.ctx.createBufferSource(),filter=this.ctx.createBiquadFilter(),gain=this.ctx.createGain(),pan=this.ctx.createStereoPanner();pan.pan.value=side*stereoWidth(this.mode);source.buffer=this.noiseBuffer;filter.type='bandpass';filter.frequency.setValueAtTime(1600,t);filter.frequency.exponentialRampToValueAtTime(280,t+.55);filter.Q.value=.45;gain.gain.setValueAtTime(Math.min(.65,impact*.09),t);gain.gain.exponentialRampToValueAtTime(.001,t+.7);source.connect(filter).connect(gain).connect(pan).connect(this.effects);source.start(t);source.stop(t+.75);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();pan.disconnect();};}
 chime(kind='cargo'){if(!this.ctx||!this.enabled)return;const c=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=kind==='hit'?'triangle':'sine';o.frequency.setValueAtTime(kind==='hit'?70:520,c);o.frequency.exponentialRampToValueAtTime(kind==='hit'?28:780,c+.18);g.gain.setValueAtTime(.2,c);g.gain.exponentialRampToValueAtTime(.001,c+.65);o.connect(g).connect(this.effects);o.start(c);o.stop(c+.7);o.onended=()=>{o.disconnect();g.disconnect();};}
}
