import * as T from './vendor/three.module.js';
import {createState,step,context,loadWeight,stormLevel,wave,ground,DOCK,ROCKS,DURATION,craftField} from './simulation.js';
import {makeSky,makeTerrain,makeOcean,shared} from './ocean.js';
import {makeWorld} from './world.js';
import {makeJetSki} from './jetski.js';
import {Soundscape} from './audio.js';
import {advanceSpray} from './spray-physics.js';
import {pilot,voyage} from './verification.js';
const $=id=>document.getElementById(id),canvas=$('sea');
const verifying=new URLSearchParams(location.search).has('verify');let autoVoyage=false,routeIndex=0,qaResult=null;
let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('error').textContent='WebGL 2 is needed to sail this cove. Try a current desktop browser with hardware acceleration enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.fog=new T.FogExp2(0xa3b7b6,.0018);const camera=new T.PerspectiveCamera(53,innerWidth/innerHeight,.15,1800);camera.position.set(30,13,161);
const sun=new T.DirectionalLight(0xffe1aa,3.0);sun.position.set(-90,64,-230);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:450});sun.shadow.bias=-.0003;sun.shadow.normalBias=.15;scene.add(sun);scene.add(sun.target);const ambient=new T.HemisphereLight(0xbad6e0,0x565039,1.25);scene.add(ambient);
const sky=makeSky(scene);const envScene=new T.Scene();envScene.add(sky.clone());const pmrem=new T.PMREMGenerator(renderer);const environment=pmrem.fromScene(envScene,.04,.1,2000);scene.environment=environment.texture;scene.environmentIntensity=.62;pmrem.dispose();makeTerrain(scene);const world=makeWorld(scene),vessel=makeJetSki(scene),ocean=makeOcean(renderer,scene,camera),audio=new Soundscape();
let state=createState(),keys={},orbit=0,pitch=.18,distance=12.5,drag=false,lastX=0,lastY=0,lastTime=performance.now(),simTime=0,eventId=0,toastUntil=0,uiTime=0,wakeClock=0,wakeIndex=0,quality='high',frameSum=0,frameCount=0,adaptClock=0,lastMode='intro';
const target=new T.Vector3(),camGoal=new T.Vector3(),look=new T.Vector3(0,0,110);const cameraLook=new T.Vector3(0,0,110);
// A fixed-size particle pool: emissions depend on speed, wave impacts and collisions.
const poolSize=2400,positions=new Float32Array(poolSize*3),sizes=new Float32Array(poolSize),alphas=new Float32Array(poolSize),velocities=new Float32Array(poolSize*3);const particles=Array.from({length:poolSize},()=>({life:0,max:1,vx:0,vy:0,vz:0,size:1}));let particleIndex=0,sprayBudget=0,lastHeave=0,verticalSpeed=0,impactCooldown=0;
const pg=new T.BufferGeometry();pg.setAttribute('position',new T.BufferAttribute(positions,3));pg.setAttribute('size',new T.BufferAttribute(sizes,1));pg.setAttribute('alpha',new T.BufferAttribute(alphas,1));pg.setAttribute('velocity',new T.BufferAttribute(velocities,3));const pm=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{pixelRatio:{value:renderer.getPixelRatio()}},vertexShader:`attribute float size;attribute float alpha;attribute vec3 velocity;varying float a;varying vec2 streak;uniform float pixelRatio;void main(){a=alpha;vec3 sv=mat3(modelViewMatrix)*velocity;streak=vec2(atan(sv.y,sv.x),clamp(length(sv)*.06,0.,.65));vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=min(38.,size*pixelRatio*220./max(1.,-p.z));}`,fragmentShader:`varying float a;varying vec2 streak;void main(){vec2 uv=gl_PointCoord-.5;uv=mat2(cos(streak.x),-sin(streak.x),sin(streak.x),cos(streak.x))*uv;uv.y*=1.+streak.y*3.;float d=dot(uv,uv)*4.;if(d>1.)discard;gl_FragColor=vec4(.84,.91,.88,a*exp(-d*3.)*(1.-smoothstep(.7,1.,d)));}`});const spray=new T.Points(pg,pm);spray.frustumCulled=false;scene.add(spray);spray.userData.skipRefraction=true;
function emitParticle(x,y,z,vx,vy,vz,size=.25,life=1){const i=particleIndex++%poolSize,p=particles[i];p.life=p.max=life;p.vx=vx;p.vy=vy;p.vz=vz;p.size=size;positions[i*3]=x;positions[i*3+1]=y;positions[i*3+2]=z;}
function splash(n=24){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,r=Math.random()*1.5;emitParticle(state.x+Math.sin(a)*1.5,vessel.boat.position.y,state.z+Math.cos(a)*2,Math.sin(a)*r,1+Math.random()*2.5,Math.cos(a)*r,.14+Math.random()*.18,1.0);}}
// Rain streaks live around the camera rather than filling the entire map.
const rainCount=1500,rainPos=new Float32Array(rainCount*6);for(let i=0;i<rainCount;i++){const x=(Math.random()-.5)*75,y=Math.random()*45,z=(Math.random()-.5)*75;rainPos.set([x,y,z,x-.35,y+1.3,z+.2],i*6);}const rainGeo=new T.BufferGeometry();rainGeo.setAttribute('position',new T.BufferAttribute(rainPos,3));const rainMat=new T.LineBasicMaterial({color:0xb6ced6,transparent:true,opacity:0,depthWrite:false});const rain=new T.LineSegments(rainGeo,rainMat);rain.frustumCulled=false;scene.add(rain);rain.userData.skipRefraction=true;
const cableGeo=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]);const cable=new T.Line(cableGeo,new T.LineBasicMaterial({color:0xc0ad82}));cable.visible=false;scene.add(cable);
const markerRoot=document.createElement('div');markerRoot.style.cssText='position:fixed;inset:0;pointer-events:none';document.body.insertBefore(markerRoot,$('overlay'));const markers=state.jobs.map((j,i)=>{const d=document.createElement('div');d.style.cssText='position:absolute;color:#efd099;text-align:center;font-size:10px;text-shadow:0 2px 4px #082d38;transform:translate(-50%,-100%);letter-spacing:.04em';markerRoot.appendChild(d);return d;});
function applyQuality(q){quality=q;ocean.quality=q;const ratio=q==='high'?Math.min(devicePixelRatio,1.5):q==='medium'?1:.75;renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);ocean.resize();ocean.reflect.setSize(q==='high'?1024:q==='medium'?640:384,q==='high'?1024:q==='medium'?640:384);renderer.shadowMap.enabled=q!=='low';pm.uniforms.pixelRatio.value=ratio;}
$('quality').addEventListener('change',()=>{applyQuality($('quality').value==='auto'?'high':$('quality').value);adaptClock=0;});$('sound').addEventListener('change',()=>audio.enabled=$('sound').checked);
function clearInput(){keys={};drag=false;canvas.style.cursor='grab';}
function start(){if(state.mode==='paused'){state.mode='playing';}else{state=createState();state.mode='playing';simTime=0;eventId=0;orbit=0;distance=12.5;pitch=.18;lastMode='intro';for(const p of particles)p.life=0;for(const w of ocean.mat.uniforms.wake.value)w.set(10000,10000,0,0);for(const j of world.jobs){j.g.visible=true;j.cargo.position.y=-state.jobs[world.jobs.indexOf(j)].depth;}vessel.boat.position.set(0,0,139);camera.position.set(0,4.5,152);cameraLook.set(0,1,135);toastUntil=0;$('toast').textContent='';}$('overlay').classList.add('hidden');$('hud').classList.remove('hidden');clearInput();audio.start();$('sea').focus();}
function pause(){if(state.mode==='playing'){state.mode='paused';clearInput();$('overlay').classList.remove('hidden');$('eyebrow').textContent='AT ANCHOR';$('title').innerHTML='Take a breath';$('description').textContent='The weather waits while you are paused.';$('brief').classList.add('hidden');$('start').textContent='Resume voyage';$('start').disabled=false;}else if(state.mode==='paused')start();}
$('start').onclick=start;$('pause').onclick=pause;
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyE','KeyF','KeyC','Escape'].includes(e.code)&&e.target.tagName!=='SELECT'){e.preventDefault();if(e.code==='Escape'&&!e.repeat)pause();if(e.code==='KeyC')orbit=0;keys[e.code]=true;}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{clearInput();if(state.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')pause();});canvas.tabIndex=0;canvas.style.cursor='grab';canvas.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';});canvas.addEventListener('pointerup',()=>{drag=false;canvas.style.cursor='grab';});canvas.addEventListener('pointermove',e=>{if(drag){orbit-=(e.clientX-lastX)*.005;pitch=T.MathUtils.clamp(pitch+(e.clientY-lastY)*.003,.11,.9);lastX=e.clientX;lastY=e.clientY;}});canvas.addEventListener('wheel',e=>{e.preventDefault();distance=T.MathUtils.clamp(distance+e.deltaY*.012,7,26);},{passive:false});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);ocean.resize();});
const map=$('map'),mc=map.getContext('2d'),base=document.createElement('canvas');base.width=base.height=240;const bc=base.getContext('2d');function mapXY(x,z){return [120+x*.49,110+z*.49];}const id=bc.createImageData(240,240);for(let y=0;y<240;y++)for(let x=0;x<240;x++){const g=ground((x-120)/.49,(y-110)/.49),k=(y*240+x)*4;const c=g>0?[82,101,91]:g>-2?[52,91,94]:[24,60,71];id.data.set([...c,255],k);}bc.putImageData(id,0,0);bc.strokeStyle='#b7d6d014';bc.lineWidth=1;for(let v=0;v<240;v+=30){bc.beginPath();bc.moveTo(v,0);bc.lineTo(v,240);bc.moveTo(0,v);bc.lineTo(240,v);bc.stroke();}
function drawMap(){mc.clearRect(0,0,240,240);mc.save();mc.beginPath();mc.arc(120,120,114,0,Math.PI*2);mc.clip();mc.drawImage(base,0,0);for(const r of ROCKS){const[x,y]=mapXY(r.x,r.z);mc.fillStyle='#bbba9366';mc.beginPath();mc.arc(x,y,r.r*.49+1,0,7);mc.fill();}const[dx,dy]=mapXY(DOCK.x,DOCK.z);mc.fillStyle='#9cddcc';mc.fillRect(dx-4,dy-4,8,8);for(let i=0;i<state.jobs.length;i++){const j=state.jobs[i];if(j.status!=='waiting')continue;const[x,y]=mapXY(j.x,j.z);mc.strokeStyle='#e7bf74';mc.beginPath();mc.arc(x,y,5,0,7);mc.stroke();mc.fillStyle='#efcd88';mc.font='12px Arial';mc.fillText(String(i+1),x+8,y+4);}const[x,y]=mapXY(state.x,state.z);mc.translate(x,y);mc.rotate(-state.heading);mc.fillStyle='#f5f4df';mc.beginPath();mc.moveTo(0,7);mc.lineTo(-4,-5);mc.lineTo(4,-5);mc.closePath();mc.fill();mc.restore();}
function updateUI(){vessel.updateDash(state.speed,state.hull);const weight=loadWeight(state),storm=stormLevel(state),ctx=context(state);$('hull').innerHTML=Math.ceil(state.hull)+'<span>%</span>';$('hullbar').style.width=state.hull+'%';$('hullbar').style.background=state.hull<35?'#e78a70':'#a9d6bb';$('load').textContent=weight+' / 3';const remaining=Math.ceil(DURATION-state.time);$('clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');$('wind').textContent='wind '+Math.round(6+storm*31)+' knots';$('weather').textContent=storm<.23?'A break in the weather':storm<.55?'Wind rising · watch the shallows':storm<.8?'Rain offshore · consider heading home':'Storm warning · return to the dock';$('speed').innerHTML=(Math.abs(state.speed)*1.944).toFixed(1)+' <small>KNOTS</small>';$('objectives').innerHTML=state.jobs.map((j,i)=>'<div class="job '+(j.status==='delivered'?'done':'')+'"><span>'+(j.status==='delivered'?'✓':j.status==='aboard'?'▣':i+1)+'</span> '+j.name+' <span style="width:auto;opacity:.6">'+(j.status==='waiting'?j.weight+'u · $'+j.value:j.status)+'</span></div>').join('');$('prompt').textContent=ctx.text;let p=state.recovery!==null?state.jobs[state.recovery].progress/state.jobs[state.recovery].seconds:state.dockProgress/3;$('progress').style.width=Math.min(100,p*100)+'%';$('interaction').style.opacity=ctx.text?1:0;
 if(state.eventId!==eventId){eventId=state.eventId;$('toast').textContent=state.event;toastUntil=performance.now()+5000;audio.chime(state.event.includes('strike')?'hit':'cargo');if(state.event.includes('strike'))splash(48);}$('toast').style.opacity=performance.now()<toastUntil?1:0;drawMap();
 if((state.mode==='success'||state.mode==='failure')&&lastMode!==state.mode){const success=state.mode==='success',value=state.delivered.reduce((a,i)=>a+state.jobs[i].value,0);$('overlay').classList.remove('hidden');$('eyebrow').textContent=success?'VOYAGE COMPLETE':'VOYAGE LOST';$('title').innerHTML=success?(state.delivered.length===3?'Everything<br>came home.':'A safe<br>return.'):'The sea<br>had other plans.';$('description').textContent=(success?'You made it back. ':state.event+'. ')+state.delivered.length+' of 3 cargoes delivered · $'+value+' secured. '+(success&&state.delivered.length<3?'A partial haul is better than a lost craft.':'');$('brief').classList.add('hidden');$('start').textContent='Sail again';clearInput();}lastMode=state.mode;
}
function visual(dt){const storm=stormLevel(state),weight=loadWeight(state);Object.assign(craftField,{x:state.x,z:state.z,heading:state.heading,power:Math.min(1,Math.abs(state.speed)/8.2)});shared.time.value=simTime;shared.storm.value=storm;const b=vessel.boat;b.position.set(state.x,wave(state.x,state.z,simTime,storm)+.015-weight*.055+Math.min(1,Math.abs(state.speed)/6)*.10,state.z);b.rotation.y=state.heading;const fX=Math.sin(state.heading),fZ=Math.cos(state.heading),rX=Math.cos(state.heading),rZ=-Math.sin(state.heading);const fore=wave(state.x+fX*1.35,state.z+fZ*1.35,simTime,storm),aft=wave(state.x-fX*1.35,state.z-fZ*1.35,simTime,storm),left=wave(state.x-rX,state.z-rZ,simTime,storm),right=wave(state.x+rX,state.z+rZ,simTime,storm);vessel.body.rotation.x=T.MathUtils.damp(vessel.body.rotation.x,-Math.atan2(fore-aft,2.7)*.65-Math.min(.09,Math.abs(state.speed)*.015)-Math.max(0,state.acceleration)*.012,4,dt);vessel.body.rotation.z=T.MathUtils.damp(vessel.body.rotation.z,Math.atan2(right-left,2)*.60+state.turn*Math.min(1,Math.abs(state.speed)/5)*.40,4,dt);vessel.updateRider?.({time:simTime,speed:Math.abs(state.speed),turn:state.turn,steering:state.turn*.24});vessel.prop.rotation.y=-state.turn*.38;vessel.handlebars.rotation.y=state.turn*.24;vessel.rider.rotation.z=T.MathUtils.damp(vessel.rider.rotation.z,state.turn*Math.min(1,Math.abs(state.speed)/5)*.08,4,dt);vessel.winch.rotation.x=state.recovery!==null?simTime*5:0;vessel.cargo.children.forEach((c,i)=>c.visible=i<weight);
world.update(simTime,storm);if(state.mode==='playing'){for(const debris of world.debris){const dx=debris.position.x-state.x,dz=debris.position.z-state.z,d=Math.hypot(dx,dz);if(d<3.4&&d>.01){debris.userData.x+=dx/d*(3.4-d)*dt*.8;debris.userData.z+=dz/d*(3.4-d)*dt*.8;debris.rotation.y+=dt*state.speed*.18;}}}world.jobs.forEach((j,i)=>{j.g.visible=state.jobs[i].status==='waiting';j.cargo.position.y=-state.jobs[i].depth+state.jobs[i].progress/state.jobs[i].seconds*state.jobs[i].depth;});
 cable.visible=state.recovery!==null;if(cable.visible){const a=vessel.body.localToWorld(new T.Vector3(.44,.90,-1.81)),j=world.jobs[state.recovery],bb=j.cargo.getWorldPosition(new T.Vector3());cableGeo.attributes.position.setXYZ(0,a.x,a.y,a.z);cableGeo.attributes.position.setXYZ(1,bb.x,bb.y+.5,bb.z);cableGeo.attributes.position.needsUpdate=true;}
 // Momentum-driven jet stream, side sheets, churned microbubbles and wake crest spray.
 const speed=Math.abs(state.speed),power=Math.min(1,speed/8.2),sternX=state.x-fX*1.9,sternZ=state.z-fZ*1.9;
 const wakeU=ocean.mat.uniforms;wakeU.craft.value.set(state.x,state.z,state.heading,power);wakeU.craftTurn.value=state.turn;
 if(state.mode==='playing'&&speed>.25){wakeClock+=dt;sprayBudget+=dt*(50+power*420);if(wakeClock>.25){wakeClock%=.25;const n=wakeIndex++%48;wakeU.wake.value[n].set(sternX,sternZ,simTime,power);wakeU.wakeHeading.value[n]=state.heading;}
 const count=Math.min(50,Math.floor(sprayBudget));sprayBudget-=count;for(let k=0;k<count;k++){
 const side=Math.random()<.5?-1:1,jitter=(Math.random()-.5),jetX=-fX+rX*state.turn*.25,jetZ=-fZ+rZ*state.turn*.25;
 // Compact nozzle exhaust: high speed droplets exit down and aft, with an angled telltale plume.
 if(k%3===0){const rooster=power*(4.2+Math.random()*.65);emitParticle(sternX+rX*jitter*.18,b.position.y-.03,sternZ+rZ*jitter*.18,jetX*(2.7+power*4)+rX*jitter,rooster+Math.random()*.35,jetZ*(2.7+power*4)+rZ*jitter,.055+Math.random()*.055,.5+power*.8);}
 // The loaded outside chine throws a higher, broader fan while carving.
 const carve=1+Math.max(0,side*state.turn)*1.4;
 if(k%3===1){const longitudinal=.2+Math.random()*.9;emitParticle(state.x+fX*longitudinal+rX*side*.58,b.position.y-.01,state.z+fZ*longitudinal+rZ*side*.58,rX*side*(.8+power*2)*carve-fX*power*.8,(.25+power*.8)*carve,rZ*side*(.8+power*2)*carve-fZ*power*.8,.048+Math.random()*.06,.5+power*.45);}
 if(k%3===2)emitParticle(sternX+rX*jitter*.6,b.position.y-.03,sternZ+rZ*jitter*.6,-fX*.45+rX*jitter,.0,-fZ*.45+rZ*jitter,.15+power*.10,1.6+Math.random()*1.3);
 }
 // Re-entry into a wave produces a short impact fan rather than constant spray.
 const vv=(b.position.y-lastHeave)/Math.max(.005,dt);impactCooldown-=dt;if(verticalSpeed<-.28&&vv>.02&&speed>4&&impactCooldown<0){splash(Math.round(18+power*18));impactCooldown=.8;}verticalSpeed=vv;
 }lastHeave=b.position.y;
 const particleSurface=(x,z)=>wave(x,z,simTime,storm)+.025;
 for(let i=0;i<poolSize;i++){const p=particles[i];if(p.life>0){p.life-=dt;advanceSpray(p,positions,i*3,dt,storm,particleSurface);velocities[i*3]=p.vx;velocities[i*3+1]=p.vy;velocities[i*3+2]=p.vz;alphas[i]=Math.max(0,p.life/p.max)*.70;sizes[i]=p.size;}else{alphas[i]=0;sizes[i]=0;}}pg.attributes.position.needsUpdate=true;pg.attributes.size.needsUpdate=true;pg.attributes.alpha.needsUpdate=true;pg.attributes.velocity.needsUpdate=true;
 const rainAmount=Math.max(0,(storm-.32)/.68);rainMat.opacity=rainAmount*.34;rainGeo.setDrawRange(0,Math.floor(rainCount*rainAmount*(quality==='low'?.35:1))*2);rain.position.set(camera.position.x,0,camera.position.z);for(let i=0;i<rainCount;i++){let k=i*6;rainPos[k]-=dt*(4+storm*8);rainPos[k+1]-=dt*26;rainPos[k+2]+=dt*3;if(rainPos[k+1]<0){rainPos[k]=(Math.random()-.5)*75;rainPos[k+1]=40;rainPos[k+2]=(Math.random()-.5)*75;}rainPos[k+3]=rainPos[k]-.5;rainPos[k+4]=rainPos[k+1]+1.5;rainPos[k+5]=rainPos[k+2]+.2;}rainGeo.attributes.position.needsUpdate=true;
 sun.intensity=3.0-storm*2.35;sun.color.setRGB(1,.86+storm*.1,.66+storm*.26);ambient.intensity=1.25-storm*.24;scene.environmentIntensity=.62-storm*.34;scene.fog.color.setRGB(.64-storm*.44,.72-storm*.44,.71-storm*.39);scene.fog.density=.0018+storm*.0048;sun.position.set(state.x-90,64,state.z-230);sun.target.position.set(state.x,0,state.z);sky.position.copy(camera.position);
 if(state.mode==='intro'){const t=simTime*.012;camGoal.set(state.x+29+Math.sin(t)*6,12,state.z+21);target.set(-22,0,67);}else{const angle=state.heading+Math.PI+orbit;camGoal.set(state.x+Math.sin(angle)*distance,Math.max(b.position.y+1.65+Math.sin(pitch)*distance,ground(state.x+Math.sin(angle)*distance,state.z+Math.cos(angle)*distance)+3),state.z+Math.cos(angle)*distance);target.set(state.x+fX*2.7,b.position.y+.95,state.z+fZ*2.7);}camera.position.lerp(camGoal,1-Math.exp(-dt*2.8));cameraLook.lerp(target,1-Math.exp(-dt*3.5));camera.lookAt(cameraLook);
 markers.forEach((el,i)=>{const j=state.jobs[i],d=Math.hypot(j.x-state.x,j.z-state.z),v=new T.Vector3(j.x,4.5,j.z).project(camera);const visible=state.mode==='playing'&&j.status==='waiting'&&v.z<1&&v.z>0&&Math.abs(v.x)<.91&&Math.abs(v.y)<.78;el.style.display=visible?'block':'none';if(visible){el.style.left=(v.x*.5+.5)*innerWidth+'px';el.style.top=(-v.y*.5+.5)*innerHeight+'px';el.innerHTML='<span style="font-size:17px">◇</span><br>'+String(i+1).padStart(2,'0')+' · '+Math.round(d)+' m';}});
 audio.update(state.speed,storm,state.recovery!==null,state.mode!=='playing',simTime);
}
function frame(now){requestAnimationFrame(frame);const raw=Math.max(.001,(now-lastTime)/1000);lastTime=now;const dt=Math.min(raw,.05),verifyRate=autoVoyage?Number($('verifyRate')?.value||12):1;if(state.mode!=='paused'&&state.mode!=='success'&&state.mode!=='failure')simTime+=dt;if(state.mode==='playing'){const input={throttle:(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0),steer:(keys.KeyA||keys.ArrowLeft?1:0)-(keys.KeyD||keys.ArrowRight?1:0),brake:keys.Space,interact:keys.KeyE,finish:keys.KeyF};if(autoVoyage){for(let n=0;n<verifyRate&&state.mode==='playing';n++){const ctl=pilot(state,voyage,routeIndex);routeIndex=ctl.index;step(state,ctl.input,dt);if(n>0)simTime+=dt;}if(state.mode!=='playing'){autoVoyage=false;qaResult={mode:state.mode,time:state.time,hull:state.hull,delivered:state.delivered.length};if($('verifyStatus'))$('verifyStatus').textContent=JSON.stringify(qaResult);}}else step(state,input,dt);}if(state.mode!=='paused')visual(dt*verifyRate);else audio.update(0,0,false,true,simTime);uiTime+=dt;if(uiTime>.10){uiTime=0;updateUI();}ocean.updateFoam(state.mode==='paused'?0:dt,state.x,state.z);ocean.render();frameSum+=raw;frameCount++;adaptClock+=raw;if(adaptClock>8&&$('quality').value==='auto'){const fps=frameCount/frameSum;if(fps<36&&quality==='high')applyQuality('medium');else if(fps<27&&quality==='medium')applyQuality('low');frameSum=0;frameCount=0;adaptClock=0;}}
if(verifying){
 const panel=document.createElement('div');panel.style.cssText='position:fixed;right:12px;top:68px;z-index:20;background:#112b35e8;padding:12px;font:12px monospace;max-width:370px';panel.innerHTML='<b>DEVELOPMENT VERIFICATION</b><label> Clock <select id="verifyRate"><option value="1">1x</option><option value="4">4x</option><option value="12" selected>12x</option></select></label><div style="display:flex;gap:6px;margin:10px 0"><button id="verifyVoyage">Run full voyage</button><button id="verifyCollision">Hull failure</button><button id="verifyStorm">Storm failure</button></div><div id="verifyStatus">Ready</div>';document.body.appendChild(panel);
 $('verifyVoyage').onclick=()=>{state.mode='intro';start();autoVoyage=true;routeIndex=0;$('verifyStatus').textContent='Sailing with ordinary helm inputs';};
 $('verifyCollision').onclick=()=>{autoVoyage=false;state.mode='intro';start();state.x=-72;state.z=28;state.heading=-Math.PI/2;state.speed=4;state.hull=8;keys.KeyW=true;$('verifyStatus').textContent='Heading into the reef';};
 $('verifyStorm').onclick=()=>{autoVoyage=false;state.mode='intro';start();state.z=30;state.time=476;simTime=476;$('verifyStatus').textContent='Harbour deadline test';};
 }
 // Read-only state snapshots support reproducible browser verification.
window.afterTheStorm={snapshot:()=>JSON.parse(JSON.stringify({...state,quality,depth:-ground(state.x,state.z),fps:frameCount/Math.max(.01,frameSum)}))};
try{renderer.compile(scene,camera);visual(.016);ocean.render();$('start').disabled=false;$('start').textContent='Cast off';requestAnimationFrame(frame);}catch(e){$('error').textContent='The cove could not load: '+e.message;console.error(e);}
