// Generated by source/pack-assets.py. Original bytes are retained as a fallback.
export const packedAssets={
  "assets/coastal-rider-lod.bin": {
    "url": "assets/packed/coastal-rider-lod-eda6af63b060.gz.bin",
    "bytes": 2881728,
    "packedBytes": 614839
  },
  "assets/coastal-rider.bin": {
    "url": "assets/packed/coastal-rider-49238031c8d1.gz.bin",
    "bytes": 8336160,
    "packedBytes": 1808358
  },
  "assets/tideline-r01-lod.bin": {
    "url": "assets/packed/tideline-r01-lod-22e5a6c44074.gz.bin",
    "bytes": 2020968,
    "packedBytes": 369843
  },
  "assets/tideline-r01.bin": {
    "url": "assets/packed/tideline-r01-5bc2e56a9b8a.gz.bin",
    "bytes": 5918976,
    "packedBytes": 1050174
  },
  "assets/scenery/pine.bin": {
    "url": "assets/packed/pine-4037458b1621.gz.bin",
    "bytes": 251136,
    "packedBytes": 131316
  }
};
