import {COURSES} from './courses.js';
import {RIDERS} from './race-core.js';
import {cleanName,exportSave,importSave,replaceSave,eraseRecords,restoreRecords,initialSave,recordKey,writeSave} from './race-records.js';

export function mountOptions({saved,storage,audio,onChange}){
 const dialog=document.createElement('dialog');dialog.id='optionsPanel';dialog.setAttribute('aria-labelledby','optionsTitle');
 dialog.innerHTML=`<div class="options-heading"><h2 id="optionsTitle">Rider options</h2><button id="closeOptions">Close options</button></div>
 <section><h3>Rider names</h3><form id="namesForm"><div id="nameFields"></div><button>Save rider names</button><button type="button" id="defaultNames">Restore default names</button></form></section>
 <section><h3>Sound</h3><div class="sound-options"><label>Output <select id="audioMode"><option value="stereo">Stereo</option><option value="mono">Mono</option><option value="headphones">Headphones</option></select></label><label>Volume <input id="audioVolume" type="range" min="0" max="1" step=".05"></label><label><input id="musicEnabled" type="checkbox"> Background music</label></div><p>ElevenLabs engine, water, wind and impact recordings; no announcer. The instrumental is optional. Headphones use a narrower stereo image.</p><button id="previewMusic">Preview music</button><span id="audioStatus" role="status"></span><p id="sampleStatus" role="status"></p></section>
 <section><h3>Course records</h3><div class="record-filters"><label>Record venue <select id="recordCourse"></select></label><label>Record class <select id="recordClass"><option value="0">Normal</option><option value="1">Hard</option><option value="2">Expert</option><option value="3">Reverse</option></select></label><label>Record type <select id="recordType"><option value="time">Race times</option><option value="score">Stunt scores</option></select></label><label id="recordLapLabel">Record laps <select id="recordLaps"><option>3</option><option>4</option><option>5</option><option>6</option><option>9</option></select></label></div><p id="recordSummary"></p><ol id="managedRecords"></ol><button id="eraseCourse">Erase displayed records</button><span id="eraseConfirm" hidden>Erase this course/class table? <button id="confirmErase">Confirm erase</button><button id="cancelErase">Cancel</button></span><button id="undoErase" hidden>Undo record erase</button></section>
 <section><h3>Riding techniques</h3><p>Rocket start: press throttle as GO appears to start at maximum power. Quick turn: hold E (rearward trim) while steering; gamepad users pull the stick diagonally back. Shift gives a looser surface slide.</p><p>After a wipeout, tap throttle to remount faster. Hold B to absorb wave impacts. Stunt keys: 1 flip, 2/3 rolls, 4 stand, 5 handstand, 6 backwards, 4 then 7 somersault. F dives while descending.</p></section><section><h3>Controller guide</h3><p>Gamepad: left stick steering and fore/aft trim, right trigger throttle, left trigger brake, right shoulder slide, bottom face button absorb, top face button camera, Start pause.</p><p>Stunts: hold the left shoulder plus top face button for a flip, left/right face buttons for rolls, D-pad up/right/down for rider poses, bottom face button for a somersault, or left trigger to dive during descent.</p></section><section><h3>Portable save</h3><p>Includes rider settings, names, records, course unlocks, sound and graphics preferences. Export a copy, or import one from another browser.</p><button id="exportSave">Show save data</button><button id="downloadSave">Download save file</button><label class="save-field">Exported save data<textarea id="exportText" readonly rows="5"></textarea></label><label class="save-field">Import save file<input id="importFile" type="file" accept=".json,application/json"></label><label class="save-field">Paste save data<textarea id="importText" rows="5" placeholder="Paste an After the Storm export"></textarea></label><button id="checkImport">Check import</button><p id="importSummary" role="status"></p><button id="applyImport" hidden>Replace progress with this save</button><button id="undoImport" hidden>Undo save replacement</button></section>
 <section><h3>Reset progress</h3><p>Clear saved records, names, tuning and course unlocks. A session undo remains available.</p><button id="resetSave">Reset saved progress</button><span id="resetConfirm" hidden><button id="confirmReset">Confirm reset all progress</button><button id="cancelReset">Cancel reset</button></span></section><p id="optionsStatus" role="status"></p>`;
 document.body.append(dialog);const $=id=>dialog.querySelector('#'+id);let candidate=null,undo=null,replaced=null;
 const status=text=>$('optionsStatus').textContent=text;
 const persist=message=>{const ok=writeSave(storage,saved);onChange();status(ok?message:'Storage unavailable; this change lasts for this session.');return ok;};
 const name=id=>saved.names[id]||RIDERS[id].name;
 RIDERS.forEach((r,i)=>{const label=document.createElement('label');label.textContent=r.name;const input=document.createElement('input');input.id='riderName'+i;input.maxLength=20;input.setAttribute('aria-label','Name for '+r.name);label.append(input);$('nameFields').append(label);});
 for(const c of COURSES){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;$('recordCourse').append(o);}
 function refreshNames(){RIDERS.forEach((r,i)=>$('riderName'+i).value=name(i));}
 function scope(){return {course:$('recordCourse').value,difficulty:Number($('recordClass').value),laps:Number($('recordLaps').value),kind:$('recordType').value};}
 const time=t=>Math.floor(t/60)+':'+(t%60).toFixed(3).padStart(6,'0');
 function records(){const s=scope(),scores=s.kind==='score',table=scores?saved.scores[s.course+'/'+s.difficulty]:saved.records[recordKey(s)],rows=scores?table:table?.times;$('recordLapLabel').hidden=scores;$('managedRecords').replaceChildren();$('recordSummary').textContent=rows?.length?(scores?'Highest scores':'Best lap '+time(table.lap.bestLap)+' · '+table.lap.initials+' / N standard, C custom'):'No records for this selection.';$('eraseCourse').disabled=!rows?.length;$('eraseConfirm').hidden=true;for(const row of rows||[]){const li=document.createElement('li');li.textContent=row.initials+' · '+name(row.rider)+' · '+(scores?row.score.toLocaleString()+' points':time(row.time)+' · '+(row.custom?'C':'N'));$('managedRecords').append(li);}}
 function refresh(){refreshNames();$('sampleStatus').textContent=audio.samples?.ready?'ElevenLabs audio loaded · '+Object.keys(audio.samples.buffers).length+'/8 clips · no narration':audio.ctx?'Audio clips are loading; synthesized fallback is available.':'Audio loads after your first ride or preview.';$('audioMode').value=saved.audio.mode;$('audioVolume').value=saved.audio.volume;$('musicEnabled').checked=saved.audio.music;records();}
 $('namesForm').onsubmit=e=>{e.preventDefault();saved.names=RIDERS.map((r,i)=>cleanName($('riderName'+i).value)||r.name);refreshNames();persist('Rider names saved.');records();};
 $('defaultNames').onclick=()=>{saved.names=[];refreshNames();persist('Default names restored.');records();};
 function sound(){saved.audio={...saved.audio,mode:$('audioMode').value,volume:Number($('audioVolume').value),music:$('musicEnabled').checked};audio.setOptions(saved.audio);persist('Sound settings saved.');}
 for(const id of ['audioMode','audioVolume','musicEnabled'])$(id).onchange=sound;
 let previewTimer=null;$('previewMusic').onclick=()=>{clearTimeout(previewTimer);const ok=audio.preview();$('audioStatus').textContent=ok?'Playing the coastal theme · 10 seconds':'Enable Sound in the main menu to preview.';if(ok)previewTimer=setTimeout(()=>{$('audioStatus').textContent='Preview finished.';},10000);};
 for(const id of ['recordCourse','recordClass','recordType','recordLaps'])$(id).onchange=records;
 $('eraseCourse').onclick=()=>$('eraseConfirm').hidden=false;$('cancelErase').onclick=()=>$('eraseConfirm').hidden=true;
 $('confirmErase').onclick=()=>{undo=eraseRecords(saved,scope());persist('Displayed records erased.');$('undoErase').hidden=false;records();};
 $('undoErase').onclick=()=>{restoreRecords(saved,undo);undo=null;$('undoErase').hidden=true;persist('Erased records restored.');records();};
 function exportText(){try{const text=exportSave(saved);$('exportText').value=text;return text;}catch(e){status(e.message);return null;}}
 $('exportSave').onclick=exportText;$('downloadSave').onclick=()=>{const text=exportText();if(!text)return;const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='after-the-storm-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Save download requested. You can also copy the exported data.');};
 function check(){candidate=null;$('applyImport').hidden=true;try{candidate=importSave($('importText').value);const times=Object.values(candidate.records).reduce((n,r)=>n+r.times.length,0),scores=Object.values(candidate.scores).reduce((n,r)=>n+r.length,0);$('importSummary').textContent='Valid save: '+candidate.reached.length+' venues reached, '+times+' times, '+scores+' stunt scores. Replacing progress also replaces names and preferences.';$('applyImport').hidden=false;}catch(e){$('importSummary').textContent=e.message;}}
 $('checkImport').onclick=check;$('importText').oninput=()=>{candidate=null;$('applyImport').hidden=true;$('importSummary').textContent='';};
 $('importFile').onchange=async()=>{candidate=null;$('applyImport').hidden=true;const file=$('importFile').files[0];if(!file)return;if(file.size>300000){$('importSummary').textContent='Save file is too large.';return;}try{$('importText').value=await file.text();check();}catch{$('importSummary').textContent='The selected file could not be read.';}};
 function replace(value,message){const previous=exportSave(saved);replaceSave(saved,value,storage);replaced=previous;$('undoImport').hidden=false;candidate=null;$('applyImport').hidden=true;undo=null;$('undoErase').hidden=true;refresh();onChange();status(message);}
 $('applyImport').onclick=()=>{if(!candidate)return;try{replace(candidate,'Imported save applied.');$('importSummary').textContent='Import complete.';}catch(e){status(e.message);}};
 $('undoImport').onclick=()=>{try{replaceSave(saved,importSave(replaced),storage);replaced=null;$('undoImport').hidden=true;refresh();onChange();status('Previous save restored.');}catch(e){status(e.message);}};
 $('resetSave').onclick=()=>$('resetConfirm').hidden=false;$('cancelReset').onclick=()=>$('resetConfirm').hidden=true;
 $('confirmReset').onclick=()=>{try{replace(initialSave(),'Saved progress reset. Use Undo save replacement to restore it.');$('resetConfirm').hidden=true;}catch(e){status(e.message);}};
 $('closeOptions').onclick=()=>dialog.close();dialog.onclose=()=>{audio.stopPreview();clearTimeout(previewTimer);$('audioStatus').textContent='';};
 dialog.addEventListener('keydown',e=>e.stopPropagation());
 return {open(){refresh();status('');dialog.showModal();},get opened(){return dialog.open;}};
}
