import * as T from './vendor/three.module.js';
import {waterLevel} from './simulation.js';
export function waterlineMaterial(mat){const before=mat.onBeforeCompile;mat.onBeforeCompile=s=>{before.call(mat,s);s.uniforms.tideLevel=waterLevel;s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 tideP;').replace('#include <project_vertex>','#include <project_vertex>\ntideP=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 tideP;uniform float tideLevel;').replace('#include <color_fragment>',`#include <color_fragment>
 float grain=fract(sin(dot(floor(tideP.xz*18.+tideP.y*7.),vec2(12.9898,78.233)))*43758.5453);float tide=tideP.y;
 float algae=(1.-smoothstep(-.15,.24,tide+grain*.13))*smoothstep(-1.8,-.7,tide);diffuseColor.rgb=mix(diffuseColor.rgb,diffuseColor.rgb*vec3(.38,.61,.28),algae*.72);
 float salt=exp(-pow((tide-.46+(grain-.5)*.10)/.095,2.));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.53,.55,.43),salt*.32);
 `).replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor=mix(roughnessFactor,.30,1.-smoothstep(-.10,.16,tideP.y-tideLevel));');};mat.customProgramCacheKey=()=>before.toString()+'-tidal-bands-1';mat.needsUpdate=true;}
export function makeWaterlineScenery(root,course,piles){
 const owned=[],dummy=new T.Object3D(),shellMat=new T.MeshStandardMaterial({color:0xb6b299,roughness:.88}),shellGeo=new T.ConeGeometry(.035,.07,6,1,true),shells=new T.InstancedMesh(shellGeo,shellMat,1800);shells.receiveShadow=true;let count=0;
 for(const p of (course.theme==='lake'?[]:piles)){p.o.updateWorldMatrix(true,false);const center=p.o.getWorldPosition(new T.Vector3());for(let j=0;j<45&&count<1800;j++){const a=j*2.399963+center.x,y=waterLevel.value-.65+(j%13)/13*.95;if(y<center.y-p.h/2||y>center.y+p.h/2)continue;dummy.position.set(center.x+Math.cos(a)*(p.r+.016),y,center.z+Math.sin(a)*(p.r+.016));dummy.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),new T.Vector3(Math.cos(a),.1,Math.sin(a)).normalize());dummy.scale.setScalar(.55+(j%7)/7);dummy.updateMatrix();shells.setMatrixAt(count++,dummy.matrix);}}
 shells.count=count;shells.instanceMatrix.needsUpdate=true;shells.computeBoundingSphere();root.add(shells);owned.push(shells);
 const rocks=(course.rocks||[]).filter(r=>!r.type||r.type==='rock');const floorAt=course.renderGround||course.ground;for(let z=-192;z<=192&&rocks.length<72;z+=12)for(let x=-192;x<=192&&rocks.length<72;x+=12){const y=floorAt(x,z),slope=Math.hypot(floorAt(x+2,z)-floorAt(x-2,z),floorAt(x,z+2)-floorAt(x,z-2));if(y<waterLevel.value-1.5&&y>waterLevel.value-4&&slope>.08&&Math.sin(x*3.1+z*.7)>.1)rocks.push({x,z,r:1.8+(Math.sin(x+z)+1)*1.1});}const shelfGeo=new T.IcosahedronGeometry(1,2),shelfMat=new T.MeshStandardMaterial({color:0x707967,roughness:.85}),shelves=new T.InstancedMesh(shelfGeo,shelfMat,Math.max(1,rocks.length));let k=0;
 for(const r of rocks){const floor=(course.renderGround||course.ground)(r.x,r.z);if(floor>waterLevel.value-.65)continue;dummy.position.set(r.x,floor+.08,r.z);dummy.rotation.set(0,r.x*.1,.04);dummy.scale.set(r.r*1.8,.28+r.r*.08,r.r*1.3);dummy.updateMatrix();shelves.setMatrixAt(k++,dummy.matrix);}shelves.count=k;shelves.instanceMatrix.needsUpdate=true;shelves.computeBoundingSphere();shelves.receiveShadow=true;root.add(shelves);owned.push(shelves);
 root.userData.waterlineDetail={barnacles:count,shelves:k};return {dispose(){for(const m of owned){m.removeFromParent();m.geometry.dispose();m.material.dispose();}}};
}
