import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';
const base=process.env.STUDIO_URL||'http://127.0.0.1:8768/demos/model-s-studio/',shots=process.env.STUDIO_SHOTS||path.join(tmpdir(),'model-s-cockpit-validation');await mkdir(shots,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&r.url().startsWith(new URL(base).origin))errors.push(`${r.status()} ${r.url()}`)});
const state=()=>page.evaluate(()=>modelSCockpit.getState()),press=label=>page.locator('.screen-hotspots').getByRole('button',{name:label,exact:true}).click();
try{
 await page.goto(new URL('cockpit.html',base).href);await page.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:60000});assert.equal((await state()).view,'driver');await page.screenshot({path:path.join(shots,'driver.png')});
 const before=await state();await page.locator('#cockpit-viewport').focus();await page.keyboard.press('ArrowLeft');const after=await state();assert.deepEqual(after.camera,before.camera);assert.notDeepEqual(after.look,before.look);
 for(const view of ['passenger','yoke','display']){await page.locator(`[data-camera="${view}"]`).click();await page.waitForTimeout(800);assert.equal((await state()).view,view);await page.screenshot({path:path.join(shots,`${view}.png`)});}
 // Click through UV coordinates on the physical 3D display, without opening the dialog.
 const target=await page.evaluate(()=>modelSCockpit.getScreenTargets().find(t=>t.label==='Climate'));await page.mouse.click(target.x,target.y);assert.equal((await state()).software.tab,'climate');assert.equal((await state()).screenOpen,false);
 await page.locator('#open-screen').click();assert.equal((await state()).screenOpen,true);
 await press('+ Warmer');assert.equal((await state()).software.temperature,73);await press('− Cooler');assert.equal((await state()).software.temperature,72);
 await press('+ Fan');assert.equal((await state()).software.fan,4);assert.equal((await state()).software.auto,false);await press('Auto: off');assert.equal((await state()).software.auto,true);
 await press('Seat heat: 0');assert.equal((await state()).software.seatHeat,1);await press('A/C: on');assert.equal((await state()).software.ac,false);await page.screenshot({path:path.join(shots,'climate.png')});
 await press('Charging');await press('+ Limit');assert.equal((await state()).software.limit,90);await press('Start charging demo');const battery=(await state()).software.battery;await page.waitForFunction(v=>modelSCockpit.getState().software.battery>v,battery);await press('Stop charging demo');assert.equal((await state()).software.charging,false);await press('Reset sample to 78%');assert.equal((await state()).software.battery,78);await page.screenshot({path:path.join(shots,'charging.png')});
 await press('Controls');await press('Doors: locked');assert.equal((await state()).software.locked,false);await press('Headlights: Auto');assert.equal((await state()).software.lights,'On');await press('Appearance: day');assert.equal((await state()).software.night,true);await press('− Dimmer');assert.equal((await state()).software.brightness,75);await page.screenshot({path:path.join(shots,'controls-night.png')});
 await press('Navigate');await press('Harbor charger');assert.equal((await state()).software.route,'Harbor charger');await page.screenshot({path:path.join(shots,'navigation.png')});await page.keyboard.press('Escape');assert.equal((await state()).screenOpen,false);
 await page.locator('[data-camera="driver"]').click();await page.waitForTimeout(800);await page.screenshot({path:path.join(shots,'night-driver.png')});
 await page.setViewportSize({width:390,height:844});await page.locator('#day-night').click();await page.locator('[data-camera="display"]').click();await page.waitForTimeout(800);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(shots,'phone.png'),fullPage:true});
 await page.locator('[data-app="climate"]').click();await press('+ Warmer');assert.equal((await state()).software.temperature,73);await page.screenshot({path:path.join(shots,'phone-software.png')});await page.locator('#close-screen').click();assert.equal((await state()).screenOpen,false);
 await page.goto(new URL('cockpit.html?app=charging',base).href);await page.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:60000});assert.equal((await state()).software.tab,'charging');assert.equal((await state()).screenOpen,true);
 const reduced=await browser.newPage({viewport:{width:1000,height:800},reducedMotion:'reduce'});await reduced.goto(new URL('cockpit.html',base).href);await reduced.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:60000});await reduced.locator('[data-camera="yoke"]').click();assert.deepEqual(await reduced.evaluate(()=>modelSCockpit.getState().camera),[.41,1.07,-.12]);await reduced.close();
 await page.goto(base);await page.locator('a.cockpit-entry[href="cockpit.html"]').click();await page.waitForURL(/\/cockpit(?:\.html)?$/);await page.goto(new URL('manual.html#cockpit',base).href);assert.equal(await page.locator('#cockpit').count(),1);assert.deepEqual(errors,[]);
 console.log('PASS: cockpit cameras, seated look controls, physical-screen UV clicks, climate/charging/vehicle/navigation interactions, shared state, day/night, phone UI, dialog/deep links, reduced motion, studio/manual links. '+base+' Screenshots: '+shots);
}finally{await browser.close();}
