export type System='system'|'roller'|'skimmer'|'biology'|'return';
export const systems:Record<System,{name:string;title:string;text:string;experiment:string;lessons:[string,string][]}>={
 system:{name:'The complete sump',title:'One continuous circuit.',text:'A transparent sump brings the hidden equipment into view. Gravity delivers water from the reef; the return pump sends it back. Select an assembly above to open its internal layers.',experiment:'Play the water-circuit guide →',lessons:[
 ['Down by gravity','The overflow takes surface water from the display. A drain carries it into the mechanical filter; a separate emergency drain provides a backup route. The return pump drives the overall circulation.'],
 ['A place for each job','The roller intercepts debris. The skimmer processes water within its chamber, drawing air into its own pump. Not every drop goes through the skimmer on every trip through the sump.'],
 ['Over, under, over','The first and third baffles rise from the bottom; the middle one leaves a gap below. This arrangement stabilizes the upstream water level and gives bubbles a chance to separate before the return chamber.'],
 ['Back to the living reef','The return lifts water to the aquarium. Live rock in the display supports microbial filtration. Evaporation changes the return chamber level; a real system needs suitable top-off and spare sump capacity for water draining back when power stops.']]},
 roller:{name:'Fleece roller / mechanical filtration',title:'Catch it. Lift it out.',text:'A porous strip catches particles while water passes through. Fresh fleece feeds from one roll, travels around a support cradle, and winds onto the waste roll.',experiment:'Simulate clogged fleece',lessons:[
 ['The fleece is the barrier','Water enters the space inside the fleece cradle. The support grid holds the strip while water passes through its fibers. The enlarged amber specks represent trapped debris.'],
 ['A rising level asks for fresh fleece','As debris restricts the strip, the upstream level rises. A sensor requests a brief movement from the drive motor. The experiment briefly makes the cloth translucent so you can see the rising and falling water.'],
 ['A short, measured advance','The take-up roll pulls dirty fleece above the water and draws in a fresh section. The motor stops again once the demonstration clears. Real control logic and advance length vary by product.'],
 ['The roll is a consumable','The used strip and the material it traps are removed together. Fleece does not remove every dissolved compound. The timer here is accelerated to make one cycle visible; it is not a replacement interval.']]},
 skimmer:{name:'Protein skimmer / foam fractionation',title:'Tiny bubbles. A useful boundary.',text:'A pump mixes air into seawater. Some organic compounds gather at bubble surfaces, then leave the water as foam rises into the collection cup.',experiment:'Play the bubble-to-cup guide →',lessons:[
 ['Air meets moving water','The venturi admits air at the pump inlet. The needle-wheel rotor breaks the mixture into fine bubbles. The air silencer sits above the waterline.'],
 ['Spread the bubbles','A perforated diffuser spreads the bubbly water into the reaction body. The clear shell lets you see the cloud; the enlarged white particles make its upward movement legible.'],
 ['Foam climbs; water leaves below','The body narrows toward the neck. Foam rises into the cup while processed water returns through a lower outlet. The sump’s main flow continues past this local circuit.'],
 ['Export requires an empty cup','Collected skimmate is discarded and the cup and neck are cleaned. The model shows this separation without calculating removal rates. It is not a direct nitrate or phosphate remover.']]},
 biology:{name:'Live rock / living surfaces',title:'The filter is alive.',text:'The rock is a home for the microbes that process dissolved waste. Look at the magnified surface below the model, then play the three-step explanation. Separate the rock to explore its pores.',experiment:'Play the microscopic story →',lessons:[
 ['A home, not a cartridge','The rock represents biological filtration in the display aquarium. Rough external surfaces and connected pores offer places for biofilms. The surface inset enlarges a microscopic film of attached microbes; they are not loose particles floating beside the rock.'],
 ['Ammonia becomes nitrite','Animal waste and decomposing material add ammonia. In oxygenated regions, communities of ammonia oxidizers convert it toward nitrite. A mature biofilter takes time to establish.'],
 ['Nitrite becomes nitrate','Other microorganisms oxidize nitrite to nitrate. This transformation is different from physically taking nutrients out of the aquarium. The arrows are conceptual, not a measured chemical simulation.'],
 ['Transformation is not export','Nitrate still needs management through uptake and export appropriate to the system. Flow supplies oxygen to exposed surfaces. Keep established biological media wet and avoid treating every surface as something to sterilize.']]},
 return:{name:'Return pump / wet-rotor circulation',title:'Energy in. Water back up.',text:'A sealed stator turns the magnetic wet rotor. Swept impeller vanes accelerate water into an expanding volute, then through the discharge. Open the cutaway, separate the parts, or follow the animated guide.',experiment:'Play the impeller guide →',lessons:[
 ['In through the eye','The slotted guard admits water to the center of the impeller. Large debris is discouraged at the inlet; fine mechanical filtration still happens elsewhere. The inlet needs clearance and an adequate water supply.'],
 ['A wet rotor inside a sealed motor','The motor winding stays encapsulated around a hollow rotor well. The magnetic sleeve turns with the impeller around this model’s ceramic shaft. The pale bearing seats align the rotating assembly.'],
 ['Vanes give the water energy','Swept vanes move water outward from the eye. The collecting channel expands around the wheel and leads to a tangential outlet. The cutaway removes a side of the housing; it is a teaching section, not another removable service cover.'],
 ['Read the curve at the real head','Vertical lift and plumbing losses reduce delivered flow. The example below compares three routes at one pump setting. Manufacturer flow ratings at zero head and maximum head are different ends of a curve, not a simultaneous operating point.'],
 ['Quiet depends on the whole installation','Rubber feet soften vibration into the sump floor. Rigid contact with glass or plumbing can transmit noise. Air ingestion, trapped debris and worn bearing surfaces can also cause poor or noisy operation.'],
 ['Plan for a stop and restart','Leave sump capacity for drain-back. Keep the wet side supplied with water, and restore stable levels before equipment that depends on them. Isolate power before maintenance and use the actual pump manual.']]}
};
export type Description={title:string;kind:string;description:string;care:string};
export const descriptions:Record<string,Description>={};
export function describe(id:string,title:string,kind:string,description:string,care:string){descriptions[id]={title,kind,description,care};}
