export type System='system'|'roller'|'skimmer'|'biology'|'return';
export const systems:Record<System,{name:string;title:string;text:string;experiment:string;lessons:[string,string][]}>={
 system:{name:'The complete sump',title:'One continuous circuit.',text:'A transparent sump brings the hidden equipment into view. Gravity delivers water from the reef; the return pump sends it back. Select an assembly above to open its internal layers.',experiment:'Follow the water →',lessons:[
 ['Down by gravity','The overflow takes surface water from the display. A drain carries it into the mechanical filter; a separate emergency drain provides a backup route. The return pump drives the overall circulation.'],
 ['A place for each job','The roller intercepts debris. The skimmer processes water within its chamber, drawing air into its own pump. Not every drop goes through the skimmer on every trip through the sump.'],
 ['Over, under, over','The first and third baffles rise from the bottom; the middle one leaves a gap below. This arrangement stabilizes the upstream water level and gives bubbles a chance to separate before the return chamber.'],
 ['Back to the living reef','The return lifts water to the aquarium. Live rock in the display supports microbial filtration. Evaporation changes the return chamber level; a real system needs suitable top-off and spare sump capacity for water draining back when power stops.']]},
 roller:{name:'Fleece roller / mechanical filtration',title:'Catch it. Lift it out.',text:'A porous strip catches particles while water passes through. Fresh fleece feeds from one roll, travels around a support cradle, and winds onto the waste roll.',experiment:'Simulate clogged fleece',lessons:[
 ['The fleece is the barrier','Water enters the space inside the fleece cradle. The support grid holds the strip while water passes through its fibers. The enlarged amber specks represent trapped debris.'],
 ['A rising level asks for fresh fleece','As debris restricts the strip, the upstream level rises. A sensor requests a brief movement from the drive motor. The experiment briefly makes the cloth translucent so you can see the rising and falling water.'],
 ['A short, measured advance','The take-up roll pulls dirty fleece above the water and draws in a fresh section. The motor stops again once the demonstration clears. Real control logic and advance length vary by product.'],
 ['The roll is a consumable','The used strip and the material it traps are removed together. Fleece does not remove every dissolved compound. The timer here is accelerated to make one cycle visible; it is not a replacement interval.']]},
 skimmer:{name:'Protein skimmer / foam fractionation',title:'Tiny bubbles. A useful boundary.',text:'A pump mixes air into seawater. Some organic compounds gather at bubble surfaces, then leave the water as foam rises into the collection cup.',experiment:'Trace air into the skimmer',lessons:[
 ['Air meets moving water','The venturi admits air at the pump inlet. The needle-wheel rotor breaks the mixture into fine bubbles. The air silencer sits above the waterline.'],
 ['Spread the bubbles','A perforated diffuser spreads the bubbly water into the reaction body. The clear shell lets you see the cloud; the enlarged white particles make its upward movement legible.'],
 ['Foam climbs; water leaves below','The body narrows toward the neck. Foam rises into the cup while processed water returns through a lower outlet. The sump’s main flow continues past this local circuit.'],
 ['Export requires an empty cup','Collected skimmate is discarded and the cup and neck are cleaned. The model shows this separation without calculating removal rates. It is not a direct nitrate or phosphate remover.']]},
 biology:{name:'Live rock / enlarged habitat',title:'The filter is alive.',text:'Rock is more than scenery. Its wet surfaces support microbial communities. Separate this enlarged teaching section to look inside a porous habitat.',experiment:'Follow the nitrogen pathway',lessons:[
 ['A home, not a cartridge','The rock represents biological filtration in the display aquarium. Rough external surfaces and connected pores offer places for biofilms. The colored colonies shown here are magnified symbols, not visible-sized bacteria.'],
 ['Ammonia becomes nitrite','Animal waste and decomposing material add ammonia. In oxygenated regions, communities of ammonia oxidizers convert it toward nitrite. A mature biofilter takes time to establish.'],
 ['Nitrite becomes nitrate','Other microorganisms oxidize nitrite to nitrate. This transformation is different from physically taking nutrients out of the aquarium. The arrows are conceptual, not a measured chemical simulation.'],
 ['Transformation is not export','Nitrate still needs management through uptake and export appropriate to the system. Flow supplies oxygen to exposed surfaces. Keep established biological media wet and avoid treating every surface as something to sterilize.']]},
 return:{name:'Return pump / circulation',title:'The way back up.',text:'A wet rotor turns an impeller inside a sealed motor housing. The impeller transfers energy to the water; the outlet connects to the return pipe.',experiment:'Trace water through the pump',lessons:[
 ['Enter at the center','Water enters the front intake near the impeller axis. The protective strainer keeps larger objects away while allowing flow. It is not a substitute for the fleece roller.'],
 ['Follow the curved blades','The rotating impeller sends water outward into the surrounding chamber. Explode the pump to see the rotor, shaft, bearing supports and sealing ring individually. Motion is slowed for inspection.'],
 ['Collect the flow','The volute guides moving water toward the outlet. The display return points into the tank. Actual delivered flow depends on pipework, height and the pump curve.'],
 ['Keep the wet side wet','The motor stator stays encapsulated; the rotor cavity contains water. Debris and mineral buildup can impair the moving parts. Real disassembly and cleaning follow the manufacturer’s instructions with power isolated.']]}
};
export type Description={title:string;kind:string;description:string;care:string};
export const descriptions:Record<string,Description>={};
export function describe(id:string,title:string,kind:string,description:string,care:string){descriptions[id]={title,kind,description,care};}
