import * as T from 'three';
import {materials,roundedBox,vessel,enrich,rockMaterial,bubbleMap,fibers} from './Realism.ts';
import {loadRock} from './LoadRock.ts';
import {growRock} from './SurfaceDetail.ts';
import {describe,type System} from './content.ts';
export type Part={id:string;system:System;group:T.Group;base:T.Vector3;offset:T.Vector3;label:T.Vector3};
type XYZ=[number,number,number];
const V=(p:XYZ)=>new T.Vector3(...p);
export function makeFiltration(){
 const root=new T.Group(),groups:Record<string,T.Group>={},parts:Part[]=[],animators:((time:number,dt:number,clog:number)=>void)[]=[],paths:{system:System;curve:T.Curve<T.Vector3>;color:number;speed:number;points:T.Points;count:number}[]=[];
 const mat=(color:number,roughness=.4,metalness=0)=>new T.MeshStandardMaterial({color,roughness,metalness});
 const palette=materials(),{white,dark,teal,metal,rubber,gold,cream,glass,shell}=palette;
 const water=new T.MeshBasicMaterial({color:0x2aadc9,transparent:true,opacity:.025,depthWrite:false,side:T.DoubleSide});
 const sphereG=new T.SphereGeometry(1,16,12);
 function mesh(g:T.BufferGeometry,m:T.Material,parent:T.Object3D,pos:XYZ=[0,0,0],scale?:XYZ){const o=new T.Mesh(g,m);o.position.set(...pos);if(scale)o.scale.set(...scale);parent.add(o);return o;}
 const box=(p:T.Object3D,pos:XYZ,size:XYZ,m:T.Material=white)=>mesh(roundedBox(...size),m,p,pos);
 const cylinder=(p:T.Object3D,pos:XYZ,r:number,h:number,m:T.Material=white,r2=r,open=false)=>mesh(open&&m===shell?vessel(r,r2,h):new T.CylinderGeometry(r2,r,h,64,1,open),m,p,pos);
 const sphere=(p:T.Object3D,pos:XYZ,size:XYZ,m:T.Material)=>mesh(sphereG,m,p,pos,size);
 function pipe(p:T.Object3D,ps:XYZ[],r=.09,m:T.Material=teal){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(ps.map(V),false,'centripetal'),Math.max(20,ps.length*10),r,16,false),m,p);}
 function ring(p:T.Object3D,pos:XYZ,r:number,t=.04,m:T.Material=teal){const a=mesh(new T.TorusGeometry(r,t,10,48),m,p,pos);a.rotation.x=Math.PI/2;return a;}
 function annulus(p:T.Object3D,y:number,outer:number,inner:number,thickness:number,m:T.Material){const shape=new T.Shape();shape.absarc(0,0,outer,0,Math.PI*2,false);const hole=new T.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);shape.holes.push(hole);const g=new T.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:false,curveSegments:48}),a=mesh(g,m,p,[0,y,0]);a.rotation.x=-Math.PI/2;return a;}
 function assembly(system:System,pos:XYZ){const g=new T.Group();g.position.set(...pos);root.add(g);groups[system]=g;return g;}
 function part(system:System,id:string,title:string,kind:string,description:string,care:string,pos:XYZ,offset:XYZ,label:XYZ=[0,.3,0]){const g=new T.Group();g.position.set(...pos);g.userData.part=id;groups[system].add(g);parts.push({id,system,group:g,base:V(pos),offset:V(offset),label:V(label)});describe(id,title,kind,description,care);return g;}
 function bolts(p:T.Object3D,r:number,y:number,count=8){for(let i=0;i<count;i++){const a=i/count*Math.PI*2;const b=cylinder(p,[Math.cos(a)*r,y,Math.sin(a)*r],.055,.075,metal);b.geometry.dispose();b.geometry=new T.CylinderGeometry(.055,.055,.075,6);}}
 function grille(p:T.Object3D,w:number,h:number,z:number){for(let x=-w/2;x<=w/2;x+=.14)box(p,[x,0,z],[.025,h,.04],dark);for(let y=-h/2;y<=h/2;y+=.18)box(p,[0,y,z],[w,.025,.04],dark);}
 function flow(system:System,ps:XYZ[],color=0x65dfff,count=36,speed=.12){const curve=new T.CatmullRomCurve3(ps.map(V),false,'centripetal');const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(new Float32Array(count*3),3));const points=new T.Points(geo,new T.PointsMaterial({color,size:color===0xeeb47a?.085:.075,transparent:true,opacity:.96,sizeAttenuation:true,depthWrite:false}));const trace=new T.Line(new T.BufferGeometry().setFromPoints(curve.getPoints(100)),new T.LineBasicMaterial({color,transparent:true,opacity:.3,depthWrite:false}));points.add(trace);groups[system].add(points);paths.push({system,curve,color,speed,points,count});}
 // Clear sump: each pane and each baffle remains selectable after separation.
 assembly('system',[0,0,0]);
 const sump=part('system','sump','Sump base & frame','SYSTEM','The cabinet reservoir holds the filtration equipment and connects the water circuit. The pale outline above the water indicates unused capacity.','Leave capacity for drain-back when the return pump stops; actual sizing depends on the installation.',[0,0,0],[0,-.3,0]);
 box(sump,[0,-.05,0],[12,.17,3.8],dark);box(sump,[0,.065,0],[11.8,.07,3.6],glass);
 for(const z of [-1.8,1.8])box(sump,[0,.06,z],[12,.12,.08],teal);
 for(const [id,pos,size,off,title] of [
 ['front',[0,1.05,1.82],[12,2,.055],[0,0,2],'Front viewing pane'],['back',[0,1.05,-1.82],[12,2,.055],[0,0,-1.4],'Rear sump pane'],['left',[-5.97,1.05,0],[.055,2,3.64],[-1.5,0,0],'Inlet-end pane'],['right',[5.97,1.05,0],[.055,2,3.64],[1.5,0,0],'Return-end pane']
 ] as [string,XYZ,XYZ,XYZ,string][]){const p=part('system','sump-'+id,title,'SUMP ENCLOSURE','A transparent wall contains the water while keeping the chambers visible in this exhibit.','The panels separate for explanation, not as a real maintenance procedure.',pos,off);box(p,[0,0,0],size,glass);}
 for(let i=0;i<3;i++){const p=part('system','baffle-'+i,['First baffle · over','Middle baffle · under','Final baffle · over'][i],'BUBBLE TRAP','Alternating high and low passages guide water toward the return chamber. The middle panel leaves a lower passage.','The trap discourages entrained bubbles; it is not a debris filter.',[2.35+i*.45,i===1?1.08:.64,0],[i*.5,1.8+i*.3,0]);box(p,[0,0,0],[.055,i===1?1.55:1.16,3.55],shell);box(p,[0,i===1?.77:.58,0],[.07,.035,3.55],teal);}
 const overflow=part('system','overflow','Surface overflow & drain','GRAVITY INLET','Surface water crosses the weir and travels down to the fleece filter. The nearby emergency drain bypasses the filter in this schematic.','Drain design, capacity and fail-safe plumbing must be engineered for the real aquarium.',[-4.5,0,-.7],[-.8,.8,-.8]);
 box(overflow,[0,3.45,0],[1.25,.7,.7],dark);for(let x=-.57;x<.62;x+=.13)box(overflow,[x,3.88,.34],[.07,.24,.075],teal);
 pipe(overflow,[[0,3.3,0],[0,3,0],[-.25,2.85,0],[-.25,2.15,0]],.12);for(const y of [2.6,2.95])cylinder(overflow,[-.25,y,0],.18,.13,white);
 const emergency=part('system','emergency','Emergency drain','BACKUP ROUTE','A second drain is an independent route to the sump. It is shown dry during normal circulation.','Never block a safety drain or rely on this illustration for plumbing dimensions.',[-5.5,0,-1.25],[-1,1,-.5]);pipe(emergency,[[0,3.95,0],[.05,3.6,0],[.05,.8,0],[.3,.5,0]],.08,white);
 const returnPipe=part('system','return-pipe','Return riser & outlet','PRESSURIZED RETURN','Water from the return pump rises to an outlet in the display. The loop completes the circuit above the sump.','The return does not replace circulation pumps within the reef.', [4.65,0,-.1],[1.2,.5,-.7]);pipe(returnPipe,[[0,.82,0],[.35,1.1,0],[.35,3.9,0],[-.15,4.12,0],[-.8,4.12,0]],.1);for(const y of [1.65,2.5])cylinder(returnPipe,[.35,y,0],.17,.15,white);
 const waterLevel=box(groups.system,[-1.82,.67,0],[8.2,1.08,3.5],water),returnWaterLevel=box(groups.system,[4.5,.53,0],[2.75,.81,3.5],water);
 flow('system',[[-4.75,3.5,-.7],[-4.75,2.3,-.7],[-4.2,1.5,0],[-4.1,.5,0],[-2.5,.7,1.22],[1.8,.8,1.22],[2.3,1.33,1.22],[2.6,.3,1.22],[2.97,.28,1.22],[3.28,1.3,1.22],[3.85,.65,.9],[4.5,.55,.3],[5,.9,-.1],[5,3.9,-.1],[4.25,4.12,-.1]],0x65dfff,90,.055);
 // Mechanical roller: rolls transverse to the incoming stream, continuous U-shaped strip.
 assembly('roller',[-3.95,0,0]);
 const rb=part('roller','roller-frame','Roller chassis','STRUCTURE','The open frame supports the two rolls and the lower fleece cradle. It stands above the water so used fleece can leave the wet path.','Keep the waste roll accessible for removal.',[0,.25,0],[0,-.25,0]);
 box(rb,[0,0,0],[2.1,.16,2.1],dark);for(const x of [-.95,.95]){box(rb,[x,1.1,0],[.1,2.2,1.7],white);for(const z of [-.65,.65])cylinder(rb,[x,0,z],.1,.24,rubber);}
 const cradle=part('roller','cradle','Perforated filter cradle','WATER SUPPORT','A grid supports the fleece against water pressure while leaving openings for filtered water. It lifts clear of the chassis in the exploded view.','The grid supports the strip; its openings alone are too large for fine filtration.',[0,.87,0],[0,.1,2.15]);
 for(const z of [-.64,.64]){const g=new T.Group();g.position.set(0,.07,z);cradle.add(g);grille(g,1.7,.95,0);}for(let x=-.8;x<=.82;x+=.15)box(cradle,[x,-.42,0],[.03,.035,1.3],dark);
 const texCanvas=document.createElement('canvas');texCanvas.width=256;texCanvas.height=256;const ctx=texCanvas.getContext('2d')!;ctx.fillStyle='#e0d9bb';ctx.fillRect(0,0,256,256);let seed=4;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<3600;i++){ctx.fillStyle=`rgba(95,76,42,${.04+random()*.12})`;ctx.fillRect(random()*256,random()*256,.5+random()*1.4,1+random()*7);}const fleeceTexture=new T.CanvasTexture(texCanvas);fleeceTexture.wrapS=fleeceTexture.wrapT=T.RepeatWrapping;fleeceTexture.colorSpace=T.SRGBColorSpace;fleeceTexture.image=fibers.image;fleeceTexture.needsUpdate=true;
 const fleeceMat=new T.MeshStandardMaterial({map:fleeceTexture,bumpMap:fibers,bumpScale:.015,color:0xffffee,roughness:1,side:T.DoubleSide});
 const fleece=part('roller','fleece','Continuous fleece strip','MECHANICAL BARRIER','The cloth follows a U around the cradle. Water passes through it; particles remain on the fibers until the motor pulls that section onto the waste roll.','This demonstration enlarges the texture and debris to show the separation.',[0,0,0],[0,0,-2.3]);
 const stripPoints=[new T.Vector3(0,2.42,-.78),new T.Vector3(0,.64,-.69),new T.Vector3(0,.42,0),new T.Vector3(0,.64,.69),new T.Vector3(0,2.42,.78)];const stripCurve=new T.CatmullRomCurve3(stripPoints);const stripG=new T.BufferGeometry(),sp:number[]=[],uv:number[]=[],si:number[]=[];
 for(let i=0;i<=80;i++){const v=stripCurve.getPoint(i/80);for(const x of [-.82,.82]){sp.push(x,v.y,v.z);uv.push(x<0?0:1,i/80*2);}if(i<80){const a=i*2;si.push(a,a+1,a+2,a+1,a+3,a+2);}}stripG.setAttribute('position',new T.Float32BufferAttribute(sp,3));stripG.setAttribute('uv',new T.Float32BufferAttribute(uv,2));stripG.setIndex(si);stripG.computeVertexNormals();mesh(stripG,fleeceMat,fleece);
 const rollers:T.Object3D[]=[];
 for(const [id,z,col,off,title] of [['clean-roll',-.78,cream,[0,1,-.8],'Clean fleece roll'],['waste-roll',.78,gold,[0,1,.8],'Used fleece roll']] as [string,number,T.Material,XYZ,string][]){const p=part('roller',id,title,'FLEECE SUPPLY',id==='clean-roll'?'Fresh porous material unwinds from this spool. The roll turns only during an advance.':'The take-up spool lifts the dirty strip out of the water. The brown surface represents captured material.','Roll diameter and capacity here are illustrative.',[0,2.42,z],off);const rotor=new T.Group();p.add(rotor);const c=cylinder(rotor,[0,0,0],.31,1.7,col);c.rotation.z=Math.PI/2;for(const x of [-.9,.9]){const disk=cylinder(rotor,[x,0,0],.34,.05,teal);disk.rotation.z=Math.PI/2;}const axle=cylinder(rotor,[0,0,0],.065,2.15,metal);axle.rotation.z=Math.PI/2;for(let a=0;a<8;a++){const t=a*Math.PI/4;box(rotor,[.937,Math.cos(t)*.18,Math.sin(t)*.18],[.01,.045,.045],white);}rollers.push(rotor);}
 const motor=part('roller','roller-motor','Take-up drive motor','INTERMITTENT DRIVE','The motor turns the waste spool for a short advance, then stops. Its controller responds to the level sensor.','The “clogged fleece” experiment speeds up one request-and-clear cycle.',[1.18,2.42,.78],[1.3,.7,.8]);box(motor,[0,0,0],[.44,.52,.52],dark);cylinder(motor,[0,.3,0],.05,.09,teal);
 const sensor=part('roller','sensor','Upstream level sensor','LEVEL CONTROL','Water rises on the dirty side as the fleece restricts flow. The illuminated sensor marks the request to advance fresh material.','Sensor type and control safeguards differ between products.',[-.92,1.65,-.12],[-1.05,.45,0]);box(sensor,[0,0,0],[.16,.4,.22],dark);const led=sphere(sensor,[-.09,.12,.12],[.045,.045,.045],mat(0x7cf1a5));pipe(sensor,[[0,.22,0],[-.06,.65,0],[.3,.9,-.3]],.025,rubber);
 const intake=part('roller','roller-inlet','Inlet chute','DIRTY-WATER ENTRY','The drain delivers water to the inside of the fleece cradle. Water leaves through the supported strip into the sump.','The chute is opened out here so its direction is easy to inspect.',[0,1.9,-.3],[0,.9,-1.6]);pipe(intake,[[-.8,.15,-.5],[-.6,0,-.1],[0,-.1,0]],.14,white);
 const dirtyWater=box(groups.roller,[0,.91,0],[1.6,.35,1.12],new T.MeshBasicMaterial({color:0x6ebbbb,transparent:true,opacity:.15,depthWrite:false}));
 flow('roller',[[-.8,2.05,-.8],[-.1,1.6,-.1],[0,.88,0],[0,.42,.3],[0,.36,.9],[.2,.32,1.3]],0x65dfff,30,.18);
 flow('roller',[[.6,1.8,0],[.3,1.05,.35],[.5,.8,.65]],0xeeb47a,12,.16);
 animators.push((time,dt,clog)=>{const advance=clog>4&&clog<6;if(advance){for(const r of rollers)r.rotation.x-=dt*1.6;fleeceTexture.offset.y-=dt*.3;}const height=.6+(clog<0||clog>6?0:clog<4?clog*.18:(6-clog)*.36);dirtyWater.scale.y=height/.35;dirtyWater.position.y=.5+height/2;led.scale.setScalar((clog>3&&clog<6?1.5:1)*.045);const cutaway=clog>=0&&clog<8;if(fleeceMat.transparent!==cutaway){fleeceMat.transparent=cutaway;fleeceMat.depthWrite=!cutaway;fleeceMat.needsUpdate=true;}fleeceMat.opacity=cutaway?.28:1;});
 // Skimmer: hollow reaction shell and foam cup, removable diffuser and wet-side needle wheel.
 assembly('skimmer',[-.65,0,0]);
 const base=part('skimmer','skimmer-base','Skimmer base & dampers','SUPPORT','The circular base supports the reaction chamber. Soft feet decouple vibration from the sump.','The base separates downward in this teaching model.',[0,.3,0],[0,-.35,0]);cylinder(base,[0,0,0],1.05,.14,white);bolts(base,.94,.11);for(let i=0;i<4;i++){const a=i*Math.PI/2+.7;cylinder(base,[Math.cos(a)*.7,-.13,Math.sin(a)*.7],.12,.18,rubber);}
 const pump=part('skimmer','skimmer-pump','Skimmer pump motor','ENCAPSULATED MOTOR','The motor drives the needle-wheel rotor in the wet cavity. This is a separate pump from the sump return.','Disconnect power before servicing real equipment.',[0,.56,.04],[-1.6,0,.5]);box(pump,[0,0,0],[.85,.4,.55],dark);for(let x=-.35;x<.4;x+=.12)box(pump,[x,.22,0],[.04,.045,.57],metal);
 const needle=part('skimmer','needle-wheel','Needle-wheel rotor','AIR–WATER MIXING','Rows of pins on the rotating wheel break the incoming air–water mixture into many smaller bubbles. The animation is slowed for inspection.','A needle wheel is shown here, distinct from the broad blades in the return pump.',[0,.59,.48],[0,0,1.9]);const wheel=new T.Group();needle.add(wheel);const nw=cylinder(wheel,[0,0,0],.31,.06,teal);nw.rotation.x=Math.PI/2;for(let r=.09;r<=.27;r+=.075)for(let i=0;i<16;i++){const a=i*Math.PI/8;const pin=cylinder(wheel,[Math.cos(a)*r,Math.sin(a)*r,.1],.013,.13,white);pin.rotation.x=Math.PI/2;}const shaft=cylinder(wheel,[0,0,-.14],.04,.4,metal);shaft.rotation.x=Math.PI/2;animators.push((time)=>{wheel.rotation.z=-time*2;});
 const venturi=part('skimmer','venturi','Venturi & water inlet','AIR INJECTION','A narrowed inlet creates suction for the air line as water enters the pump. Air travels down the thin hose from the silencer.','This is the air entry; the broad outlet pipe is a different path.',[0,.57,.85],[0,.1,2.55]);pipe(venturi,[[0,0,-.15],[0,0,.1],[0,0,.4]],.14,white);pipe(venturi,[[0,0,.13],[0,.3,.13]],.045,teal);
 const diffuser=part('skimmer','diffuser','Perforated diffuser plate','BUBBLE DISTRIBUTION','The pump discharges beneath this plate. Its many openings spread the bubbles over the chamber cross-section.','The disc lifts out to reveal the mixing pump below.',[0,.95,0],[-1.8,.9,0]);
 const discShape=new T.Shape();discShape.absarc(0,0,.79,0,Math.PI*2,false);for(let x=-.65;x<=.66;x+=.15)for(let y=-.65;y<=.66;y+=.15)if(x*x+y*y<.46){const hole=new T.Path();hole.absarc(x,y,.04,0,Math.PI*2,true);discShape.holes.push(hole);}const disc=mesh(new T.ExtrudeGeometry(discShape,{depth:.055,bevelEnabled:false,curveSegments:8}),white,diffuser);disc.rotation.x=-Math.PI/2;cylinder(diffuser,[0,-.11,0],.76,.2,shell,.76,true);
 const body=part('skimmer','reaction-body','Tapered reaction chamber','CONTACT VOLUME','The tapered clear shell contains bubbly water and guides the rising foam toward the neck. Water can leave through the lower outlet.','A stable surrounding water depth helps the skimmer operate consistently.',[0,1.7,0],[0,1.6,-.9]);cylinder(body,[0,0,0],.91,1.65,shell,.38,true);ring(body,[0,-.82,0],.91,.055,white);ring(body,[0,.83,0],.38,.05,white);
 const neck=part('skimmer','neck','Foam riser neck','FOAM CONCENTRATION','The narrow riser continues into the center of the cup. Foam reaches its lip and spills into the surrounding collection space.','Organic deposits on the neck affect the foam boundary.',[0,2.83,0],[0,2.1,0]);cylinder(neck,[0,0,0],.34,.68,shell,.34,true);ring(neck,[0,-.31,0],.36,.04,rubber);
 const cup=part('skimmer','cup','Collection cup','WASTE EXPORT','The annular space catches foam spilling over the central neck. Collapsed foam becomes dark liquid, separate from the aquarium water.','Empty and clean the cup as required for the actual aquarium.',[0,2.98,0],[0,2.95,0]);cylinder(cup,[0,0,0],.78,.62,shell,.78,true);annulus(cup,-.31,.78,.34,.055,white);ring(cup,[0,.31,0],.78,.035,teal);annulus(cup,-.24,.75,.35,.085,mat(0x67472a,.75));
 const lid=part('skimmer','cup-lid','Vented cup lid','REMOVABLE COVER','The lid covers the waste cup while vents let air escape. The center knob gives access for cup cleaning.','This is an explanatory assembly order, not a service sequence.',[0,3.35,0],[0,3.7,0]);cylinder(lid,[0,0,0],.82,.09,teal);cylinder(lid,[0,.11,0],.11,.18,dark);for(let i=0;i<12;i++){const a=i*Math.PI/6;cylinder(lid,[Math.cos(a)*.56,.055,Math.sin(a)*.56],.024,.015,dark);}
 const silencer=part('skimmer','silencer','Air silencer & hose','AIR SUPPLY','The upper chamber quiets the air intake. A narrow flexible hose connects it to the venturi below.','Air intake must remain clear; this illustrated chamber is above the sump waterline.',[1.13,2.36,0],[1.55,1.1,0]);cylinder(silencer,[0,0,0],.15,.48,white);cylinder(silencer,[0,.25,0],.18,.06,teal);pipe(silencer,[[0,-.2,0],[.05,-.6,.1],[.05,-1.4,.4],[-1.13,-1.52,.98]],.025,rubber);cylinder(silencer,[0,.34,0],.04,.16,white);
 const outlet=part('skimmer','skimmer-outlet','Water outlet & adjustment','PROCESSED-WATER RETURN','Water exits the lower body back into the sump. The adjustment represents control of the internal water and foam level.','Water exits here; concentrated waste leaves in the cup above.',[1,.58,-.2],[1.5,.1,-1.2]);pipe(outlet,[[-.25,0,0],[.15,0,0],[.32,.15,0],[.32,.45,0]],.14,white);cylinder(outlet,[.32,.7,0],.16,.38,teal);ring(outlet,[.32,.92,0],.17,.055,dark);
 flow('skimmer',[[1.13,2.72,0],[1.14,2.08,0],[1.17,1,.38],[0,.85,.98],[0,.57,.98],[0,.57,.45]],0xf3ffff,28,.15);
 flow('skimmer',[[0,.6,1.2],[0,.58,.75],[0,.65,0],[0,1,0],[.65,1.2,0],[.9,.65,-.2],[1.5,.58,-.2]],0x65dfff,34,.12);
 flow('skimmer',[[0,2.45,0],[0,2.8,0],[0,3.2,0],[.27,3.22,0],[.43,2.91,0],[.6,2.86,0]],0xeeb47a,28,.13);
 const bubbles=new T.BufferGeometry(),bubbleCount=22000,bb=new Float32Array(bubbleCount*3);bubbles.setAttribute('position',new T.BufferAttribute(bb,3));const bubbleCloud=new T.Points(bubbles,new T.PointsMaterial({color:0xecffff,map:bubbleMap,size:.058,transparent:true,opacity:.85,depthWrite:false,alphaTest:.02}));bubbleCloud.renderOrder=8;groups.skimmer.add(bubbleCloud);
 animators.push(time=>{for(let i=0;i<bubbleCount;i++){const f=(i/bubbleCount+time*(.1+(i%7)*.004))%1,y=1+f*2.2,r=(.76*(1-f)+.06)*Math.sqrt(((i*37)%22003)/22003),a=i*2.4+time*.4;bb[i*3]=Math.cos(a)*r;bb[i*3+1]=y;bb[i*3+2]=Math.sin(a)*r;}bubbles.attributes.position.needsUpdate=true;});
 // Return pump with independently separated rotor/shaft/seal/volute/strainer.
 assembly('return',[4.48,.08,.1]);
 const feet=part('return','pump-base','Pump cradle & rubber feet','VIBRATION CONTROL','The cradle holds the pump horizontally. Four rubber pads soften contact with the sump floor.','Keeping the intake clear matters more than the illustrative orientation shown here.',[0,.12,0],[0,-.5,0]);box(feet,[0,0,0],[1.25,.12,1.65],teal);for(const x of [-.45,.45])for(const z of [-.6,.6])cylinder(feet,[x,-.08,z],.1,.12,rubber);
 const motorBody=part('return','pump-motor','Encapsulated motor housing','DRIVE','The stationary motor surrounds the rotor cavity. Molded ribs strengthen the exterior housing.','Electrical parts stay sealed; this is a visual explanation of the wet-side parts.',[0,.56,-.3],[0,0,-1.35]);box(motorBody,[0,0,0],[1,.87,.8],dark);for(let z=-.3;z<.38;z+=.1)box(motorBody,[0,.44,z],[.85,.045,.038],metal);pipe(motorBody,[[-.38,0,-.4],[-.58,.12,-.75],[-.55,.55,-.95]],.045,rubber);
 const rotor=part('return','pump-rotor','Magnetic rotor & impeller','MOVING ASSEMBLY','The magnetic rotor and impeller turn together. Curved vanes send water from the inlet toward the volute.','Shown at a slow inspection speed; actual speed is not represented.',[0,.58,.25],[0,0,1.45]);const imp=new T.Group();rotor.add(imp);const magnet=cylinder(imp,[0,0,-.21],.14,.5,dark);magnet.rotation.x=Math.PI/2;const back=cylinder(imp,[0,0,.11],.4,.07,teal);back.rotation.x=Math.PI/2;for(let i=0;i<7;i++){const a=i*Math.PI*2/7;pipe(imp,[[Math.cos(a)*.12,Math.sin(a)*.12,.18],[Math.cos(a+.24)*.24,Math.sin(a+.24)*.24,.18],[Math.cos(a+.5)*.38,Math.sin(a+.5)*.38,.18]],.045,white);}animators.push(t=>{imp.rotation.z=-t*1.7;});
 const bearing=part('return','shaft','Shaft & bearing supports','ROTOR ALIGNMENT','The central shaft aligns the rotor. Small bearing supports seat it at the ends of the wet cavity.','Shaft material and bearing design vary by pump; the slender shaft is shown separately here.',[0,.58,.1],[1.25,0,1.45]);const sh=cylinder(bearing,[0,0,0],.026,.9,cream);sh.rotation.x=Math.PI/2;for(const z of [-.47,.47]){const b=cylinder(bearing,[0,0,z],.08,.11,rubber);b.rotation.x=Math.PI/2;}
 const volute=part('return','volute','Volute & discharge port','FLOW COLLECTION','The housing around the impeller collects outward-moving water and directs it into the upper discharge.','Separate the opaque cover to reveal the impeller and its collecting chamber.',[0,.58,.52],[0,.3,2.5]);const vol=cylinder(volute,[0,0,0],.52,.36,shell);vol.rotation.x=Math.PI/2;pipe(volute,[[.25,.32,0],[.25,.59,0],[.25,.72,-.3]],.12,teal);ring(volute,[0,0,0],.52,.045,white).rotation.x=0;
 const seal=part('return','seal','Volute sealing ring','WET JOINT','An elastomer ring seals the removable wet-side cover to its housing. It separates as one ring here.','Inspect seals when servicing according to the manufacturer.',[0,.58,.32],[0,0,3.25]);const sr=ring(seal,[0,0,0],.45,.035,rubber);sr.rotation.x=0;
 const screen=part('return','strainer','Intake guard','FRONT INLET','Slots admit water while helping keep larger objects away from the impeller. Water enters near the center of the rotor.','A blocked intake reduces circulation. The guard is not fine mechanical filtration.',[0,.58,.85],[0,0,4]);const guard=cylinder(screen,[0,0,0],.47,.22,dark,.47,true);guard.rotation.x=Math.PI/2;for(let x=-.4;x<.41;x+=.09){const height=Math.sqrt(.45*.45-x*x)*2;box(screen,[x,0,.12],[.033,height,.04],white);}
 flow('return',[[0,.55,1.25],[0,.58,.8],[0,.58,.42],[.31,.76,.52],[.25,1.15,.4],[.25,1.4,-.1]],0x65dfff,36,.16);
 // Enlarged rock section: porous cross-section slabs with colonies and colored microbial symbols.
 assembly('biology',[0,0,0]);groups.biology.visible=false;
 const rockMat=rockMaterial();
 for(let layer=0;layer<3;layer++){
  const p=part('biology','rock-'+layer,['Outer living surface','Porous rock interior','Connected pore habitat'][layer],'BIOLOGICAL HABITAT',layer===0?'Coralline-like crusts grow over a rugged carbonate skeleton. Small cavities and exposed surfaces provide habitat for biofilms.':'This cutaway reveals irregular connected cavities inside a continuous piece of live rock. The cut planes are added for teaching; real rock is not a stack of cartridges.','Rock shape and surface growth are illustrative. Colored microbial markers remain deliberately enlarged.',[0,1.65,(layer-1)*.64],[0,layer*.2,(layer-1)*2]);

 }
 let biologyReady=false,rockPromise:Promise<void>|null=null;const loadBiology=()=>rockPromise??(rockPromise=loadRock().then(geometries=>{for(let i=0;i<3;i++){const p=parts.find(p=>p.id==='rock-'+i)!;const o=mesh(geometries[i],rockMat,p.group);o.castShadow=o.receiveShadow=true;growRock(p.group,geometries[i],i);}biologyReady=true;}));
 for(const [id,title,x,col,explanation] of [['ammonia','Ammonia oxidizers',-1,0xeba654,'Symbolic amber colonies represent microorganisms involved in ammonia oxidation. Their size is enormously exaggerated so the habitat can be inspected.'],['nitrite','Nitrite oxidizers',1,0x79ccbd,'Symbolic teal colonies represent microorganisms that oxidize nitrite toward nitrate. Many organisms share the wet rock habitat.']] as [string,string,number,number,string][]){const p=part('biology',id,title,'ENLARGED MICROBIAL SYMBOLS',explanation,'Colors identify the teaching groups; they are not diagnostic colors of real bacteria.',[x,1.7,1.1],[x*.45,.4,2]);const m=mat(col,.6);for(let i=0;i<18;i++){const a=i*2.4,r=.12+random()*.35;const cell=sphere(p,[Math.cos(a)*r,Math.sin(a)*r*.8,random()*.12],[.035,.085,.035],m);cell.rotation.z=random()*Math.PI;}}
 flow('biology',[[-2.3,1.7,1.6],[-1,1.7,1.6],[0,1.9,1.6],[1,1.7,1.6],[2.3,1.7,1.6]],0xeeb47a,20,.13);
 const realism=enrich(parts,groups,palette);
 const connectorMaterial=new T.LineDashedMaterial({color:0x6c9da7,dashSize:.07,gapSize:.07,transparent:true,opacity:.35});
 const lines=parts.map(p=>{const g=new T.BufferGeometry().setFromPoints([p.base,p.base]);const l=new T.Line(g,connectorMaterial);l.computeLineDistances();groups[p.system].add(l);return l;});
 let current:System='system',explode=0,isolated:string|null=null,showFlow=true;
 function setView(v:System){current=v;isolated=null;for(const [key,g] of Object.entries(groups))g.visible=v==='system'?key!=='biology':key===v;setExplosion(explode);}
 function setExplosion(t:number){explode=t;for(let i=0;i<parts.length;i++){const p=parts[i];p.group.position.copy(p.base).addScaledVector(p.offset,t);const positions=lines[i].geometry.attributes.position as T.BufferAttribute;positions.setXYZ(0,p.base.x,p.base.y,p.base.z);positions.setXYZ(1,p.group.position.x,p.group.position.y,p.group.position.z);positions.needsUpdate=true;lines[i].computeLineDistances();lines[i].visible=t>.01&&!isolated;}waterLevel.visible=t<.04;dirtyWater.visible=t<.04;updateVisibility();}
 function updateVisibility(){for(const p of parts)p.group.visible=!isolated||p.id===isolated;for(const path of paths)path.points.visible=showFlow&&!isolated&&explode<.04;bubbleCloud.visible=showFlow&&!isolated&&explode<.04;waterLevel.visible=returnWaterLevel.visible=explode<.04&&!isolated;realism.visibility(explode<.04&&!isolated);dirtyWater.visible=explode<.04&&!isolated;}
 return {root,parts,groups,paths,loadBiology,isReady:()=>current!=='biology'||biologyReady,setView,setExplosion,setFlow:(v:boolean)=>{showFlow=v;updateVisibility();},isolate:(id:string|null)=>{isolated=id;setExplosion(explode);},update:(time:number,dt:number,clog:number)=>{for(const f of animators)f(time,dt,clog);realism.update(time);for(const p of paths){if(!p.points.visible||!groups[p.system].visible)continue;const a=p.points.geometry.attributes.position as T.BufferAttribute;for(let i=0;i<p.count;i++){const v=p.curve.getPoint((i/p.count+time*p.speed)%1);a.setXYZ(i,v.x,v.y,v.z);}a.needsUpdate=true;}},snapshot:()=>({current,explode,isolated,flow:showFlow,parts:parts.length,rollerAngle:rollers[0].rotation.x,rotorAngle:imp.rotation.z,bubble:bb.slice(0,3)})};
}
