import * as T from 'three';
import {mergeVertices} from 'three/addons/utils/BufferGeometryUtils.js';
// An implicit solid cut into three inspectable sections: through-cavities, no bead-covered slabs.
export function rockLayer(layer:number){
 const lo=-1+layer*2/3,hi=lo+2/3,center=(layer-1)*.64;
 const noise=(x:number,y:number,z:number)=>Math.sin(x*3.7+Math.sin(z*2.3))*Math.cos(y*4.5+z*1.8)+.38*Math.sin(x*10.2+y*8.3)*Math.cos(z*11.4-x*2.3);
 function field(x:number,y:number,z:number){let f=Math.sqrt((x/1.62)**2+(y/1.21)**2+(z/.98)**2)-1+.11*noise(x,y,z);for(const [cx,cy,r] of [[-.73,.29,.29],[.49,.22,.3],[-.12,-.56,.23],[.78,-.52,.18],[-.43,.85,.16]]){const dx=x-cx+.09*Math.sin(z*5+cy),dy=y-cy+.07*Math.cos(z*6+cx);f=Math.max(f,r-Math.sqrt(dx*dx+dy*dy));}const pore=Math.sin(x*17+Math.sin(z*9))*Math.sin(y*18+Math.cos(x*7))*Math.cos(z*19+y*5);f=Math.max(f,(pore-.64)*.24);return Math.max(f,lo-z,z-hi);}
 const nx=86,ny=66,nz=24,bounds=[-1.85,1.85,-1.45,1.45,lo-.06,hi+.06],vertices:number[]=[];
 const corner=[[0,0,0],[1,0,0],[1,1,0],[0,1,0],[0,0,1],[1,0,1],[1,1,1],[0,1,1]],tet=[[0,5,1,6],[0,1,2,6],[0,2,3,6],[0,3,7,6],[0,7,4,6],[0,4,5,6]],points:T.Vector3[]=[],values:number[]=[];
 for(let x=0;x<=nx;x++)for(let y=0;y<=ny;y++)for(let z=0;z<=nz;z++){const p=new T.Vector3(bounds[0]+x/nx*(bounds[1]-bounds[0]),bounds[2]+y/ny*(bounds[3]-bounds[2]),bounds[4]+z/nz*(bounds[5]-bounds[4]));points.push(p);values.push(field(p.x,p.y,p.z));}
 const index=(x:number,y:number,z:number)=>(x*(ny+1)+y)*(nz+1)+z;
 function triangle(a:T.Vector3,b:T.Vector3,c:T.Vector3){const n=new T.Vector3().subVectors(b,a).cross(new T.Vector3().subVectors(c,a)),mid=a.clone().add(b).add(c).multiplyScalar(1/3),e=.008,grad=new T.Vector3(field(mid.x+e,mid.y,mid.z)-field(mid.x-e,mid.y,mid.z),field(mid.x,mid.y+e,mid.z)-field(mid.x,mid.y-e,mid.z),field(mid.x,mid.y,mid.z+e)-field(mid.x,mid.y,mid.z-e));if(n.dot(grad)<0)[b,c]=[c,b];for(const p of [a,b,c])vertices.push(p.x,p.y,p.z-center);}
 for(let x=0;x<nx;x++)for(let y=0;y<ny;y++)for(let z=0;z<nz;z++){const ids=corner.map(c=>index(x+c[0],y+c[1],z+c[2]));for(const t of tet){const inside=t.filter(i=>values[ids[i]]<0),outside=t.filter(i=>values[ids[i]]>=0);if(!inside.length||!outside.length)continue;const cross=(a:number,b:number)=>points[ids[a]].clone().lerp(points[ids[b]],values[ids[a]]/(values[ids[a]]-values[ids[b]]));if(inside.length===1)triangle(...outside.map(b=>cross(inside[0],b)) as [T.Vector3,T.Vector3,T.Vector3]);else if(inside.length===3)triangle(...inside.map(a=>cross(a,outside[0])) as [T.Vector3,T.Vector3,T.Vector3]);else{const a=cross(inside[0],outside[0]),b=cross(inside[0],outside[1]),c=cross(inside[1],outside[0]),d=cross(inside[1],outside[1]);triangle(a,b,c);triangle(b,d,c);}}}
 const raw=new T.BufferGeometry();raw.setAttribute('position',new T.Float32BufferAttribute(vertices,3));const geo=mergeVertices(raw,.002);raw.dispose();geo.computeVertexNormals();const pos=geo.attributes.position,col=new Float32Array(pos.count*3),uv=new Float32Array(pos.count*2),base=new T.Color(0x9d8d70),purple=new T.Color(0x693d54),ochre=new T.Color(0x876d39),green=new T.Color(0x42583b),temp=new T.Color();for(let i=0;i<pos.count;i++){const x=pos.getX(i),y=pos.getY(i),z=pos.getZ(i)+center,n=noise(x*1.1+4,y*1.1,z*1.1),fine=.73+.2*Math.sin(x*63+y*47)*Math.cos(z*59);temp.copy(base);if(n>.01)temp.lerp(purple,T.MathUtils.smoothstep(n,.01,.54)*.95);else if(n<-.45)temp.lerp(ochre,.7);else if(n<-.25)temp.lerp(green,.35);temp.multiplyScalar(fine);col.set([temp.r,temp.g,temp.b],i*3);uv.set([(x+z*.38)*1.7,y*1.7],i*2);}geo.setAttribute('color',new T.BufferAttribute(col,3));geo.setAttribute('uv',new T.BufferAttribute(uv,2));return geo;
}
